#!/usr/bin/env python3
"""Generate a self-contained Python package directory for a distribution.

The bindings/python source tree carries BOTH modules — `n4m` (the full surface)
and `pls4all` (the slim PLS-only subset). PyPI ships them as two packages. This
emits a self-contained `bindings/python_<pkg>/` that ships exactly ONE module,
with a baked package name (a static `[project].name` cannot be overridden at
build time). `release-wheels.yml` builds each via cibuildwheel; libn4m is staged
into `<module>/lib/` by `build_libn4m_in_wheel.sh`.

    make_python_package.py --all
    make_python_package.py --name nirs4all-methods   # -> bindings/python_nirs4all_methods/
    make_python_package.py --name pls4all            # -> bindings/python_pls4all/
"""

from __future__ import annotations

import argparse
import re
import shutil
from pathlib import Path

REPO = Path(__file__).resolve().parents[3]
SRC_PKG = REPO / "bindings" / "python"

PACKAGES = {
    "nirs4all-methods": {
        "module": "n4m",
        "dir": "python_nirs4all_methods",
        "description": "nirs4all-methods — portable PLS / NIRS engine (full surface) over the libn4m C ABI.",
        "readme": """# nirs4all-methods

nirs4all-methods is the full numerical/method engine distribution. The Python
distribution name is `nirs4all-methods`; the import package is `n4m`, matching
the stable `libn4m` C ABI and `n4m_*` exported symbols.

The wheel bundles the `libn4m` shared library, so `pip install nirs4all-methods`
is self-contained — no separate native build is required. The slim `pls4all`
distribution remains available for PLS-focused users; both distributions load
the same ABI family.

```python
import n4m
from n4m.estimators.regression.latent import PLS

print(n4m.version())      # project version + ABI, e.g. "{version}+abi.{abi_version}"
print(n4m.abi_version())  # ABI triple, e.g. ({abi_tuple})

model = PLS(n_components=2).fit(X, y)
pred = model.predict(X)
```

`n4m` loads `libn4m` via `ctypes.CDLL` and exposes version/ABI helpers,
`Context`, and role-based packages such as `n4m.estimators`, `n4m.transform`,
`n4m.feature_selection`, `n4m.model_selection`, and `n4m.augmentation`.
Estimator-style wrappers live under those role packages; there is no flat
`n4m.sklearn` package in the ABI 2 surface.

Native hyperparameter studies can be checkpointed without Python pickles:
`checkpoint = optimizer.save()` returns portable N4MOPT bytes and
`Optimizer.load(checkpoint)` resumes the exact sequential ask/tell trajectory.

Set `N4M_LIB_PATH` to point at a development `libn4m` build when overriding the
bundled wheel library.

See <https://github.com/GBeurier/nirs4all-methods> for documentation.
""",
    },
    "pls4all": {
        "module": "pls4all",
        "dir": "python_pls4all",
        "description": "pls4all — slim PLS-only subset of nirs4all-methods over the libn4m C ABI.",
        "readme": """# pls4all

pls4all is the slim, PLS-focused subset distribution of nirs4all-methods. The
Python distribution and import package are both `pls4all`, while the native
library underneath is still `libn4m`.

The wheel bundles the `libn4m` shared library, so `pip install pls4all` is
self-contained — no separate native build is required. Install
`nirs4all-methods` when you need the full preprocessing, augmentation, feature
selection, diagnostics, and model-selection surface.

```python
import pls4all
from pls4all.sklearn import PLSRegression

print(pls4all.version())      # project version + ABI, e.g. "{version}+abi.{abi_version}"
print(pls4all.abi_version())  # ABI triple, e.g. ({abi_tuple})

model = PLSRegression(n_components=2).fit(X, y)
pred = model.predict(X)
```

`pls4all` loads `libn4m` via `ctypes.CDLL` and exposes a Pythonic `Context` /
`Config`, the PLS method fit/predict surface, and the optional
`pls4all.sklearn` estimator layer. `scikit-learn` is optional; the core
`import pls4all` works with NumPy alone.

Set `PLS4ALL_LIB_PATH` or `N4M_LIB_PATH` to point at a development `libn4m`
build when overriding the bundled wheel library.

See <https://github.com/GBeurier/nirs4all-methods> for documentation.
""",
    },
}

_PYPROJECT = """# GENERATED by bindings/python/scripts/make_python_package.py — do not edit.
[build-system]
requires = ["setuptools>=77", "wheel", "packaging>=24.2"]
build-backend = "setuptools.build_meta"

[project]
name = "{name}"
version = "{version}"
description = "{description}"
authors = [{{ name = "Grégory Beurier and contributors" }}]
license = "CECILL-2.1"
license-files = ["LICENSE"]
readme = "README.md"
requires-python = ">=3.10"
dependencies = ["numpy>=1.21"]

[project.urls]
Homepage = "https://github.com/GBeurier/nirs4all-methods"
Repository = "https://github.com/GBeurier/nirs4all-methods"
Issues = "https://github.com/GBeurier/nirs4all-methods/issues"
Documentation = "https://methods.nirs4all.org/"

[tool.setuptools.packages.find]
where = ["src"]
include = ["{module}", "{module}.*"]

# libn4m is staged into {module}/lib/ by scripts/build_libn4m_in_wheel.sh.
[tool.setuptools.package-data]
{module} = ["lib/libn4m*", "lib/*.so", "lib/*.so.*", "lib/*.dylib", "lib/*.dll"]
"""

_SETUP_CFG = """# GENERATED by bindings/python/scripts/make_python_package.py — do not edit.
[metadata]
name = {name}
version = {version}
description = {description}
author = Grégory Beurier and contributors
license = CECILL-2.1
license_files = LICENSE
long_description = file: README.md
long_description_content_type = text/markdown
url = https://github.com/GBeurier/nirs4all-methods
project_urls =
    Homepage = https://github.com/GBeurier/nirs4all-methods
    Repository = https://github.com/GBeurier/nirs4all-methods
    Issues = https://github.com/GBeurier/nirs4all-methods/issues
    Documentation = https://methods.nirs4all.org/

[options]
package_dir =
    = src
packages = find:
python_requires = >=3.10
install_requires =
    numpy>=1.21
include_package_data = True

[options.packages.find]
where = src
include =
    {module}
    {module}.*

[options.package_data]
{module} =
    lib/libn4m*
    lib/*.so
    lib/*.so.*
    lib/*.dylib
    lib/*.dll
"""


def _version() -> str:
    m = re.search(
        r'^version\s*=\s*"([^"]+)"',
        (SRC_PKG / "pyproject.toml").read_text(encoding="utf-8"),
        re.M,
    )
    return m.group(1) if m else "0.0.0"


def _abi_version() -> tuple[str, str]:
    # SRC_PKG always identifies the source checkout; REPO may be redirected by
    # release tests or tooling to choose an output root.
    source_repo = SRC_PKG.parents[1]
    header = (source_repo / "cpp" / "include" / "n4m" / "n4m_version.h").read_text(
        encoding="utf-8"
    )
    values = []
    for field in ("MAJOR", "MINOR", "PATCH"):
        match = re.search(rf"^#define N4M_ABI_VERSION_{field}\s+(\d+)$", header, re.M)
        if match is None:
            raise RuntimeError(
                f"cannot read N4M_ABI_VERSION_{field} from n4m_version.h"
            )
        values.append(match.group(1))
    return ".".join(values), ", ".join(values)


def generate(name: str) -> Path:
    spec = PACKAGES[name]
    module = spec["module"]
    out = REPO / "bindings" / spec["dir"]
    if out.exists():
        shutil.rmtree(out)
    (out / "src").mkdir(parents=True)
    ignore = shutil.ignore_patterns(
        "__pycache__", "*.pyc", "lib"
    )  # lib/ staged at build
    shutil.copytree(SRC_PKG / "src" / module, out / "src" / module, ignore=ignore)
    for asset in ("setup.py", "LICENSE"):
        shutil.copy2(SRC_PKG / asset, out / asset)
    # Generate a per-package README — do NOT copy bindings/python/README.md,
    # which documents the slim `pls4all` surface and would mislabel the full
    # `nirs4all-methods` (module `n4m`) package on PyPI.
    # encoding="utf-8" is mandatory: the templates carry non-ASCII (em-dashes,
    # "Grégory"), and on Windows runners the default text encoding is cp1252 —
    # writing the generated pyproject.toml as cp1252 makes cibuildwheel's UTF-8
    # `tomllib.load` crash with UnicodeDecodeError (byte 0x97).
    version = _version()
    abi_version, abi_tuple = _abi_version()
    (out / "README.md").write_text(
        spec["readme"].format(
            version=version,
            abi_version=abi_version,
            abi_tuple=abi_tuple,
        ),
        encoding="utf-8",
    )
    (out / "pyproject.toml").write_text(
        _PYPROJECT.format(
            name=name, version=version, module=module, description=spec["description"]
        ),
        encoding="utf-8",
    )
    (out / "setup.cfg").write_text(
        _SETUP_CFG.format(
            name=name, version=version, module=module, description=spec["description"]
        ),
        encoding="utf-8",
    )
    # Per-module smoke test (cibuildwheel CIBW_TEST_COMMAND target).
    (out / "tests").mkdir()
    # abi_version() forces the embedded libn4m to load and respond, and is
    # exposed by both modules (the slim pls4all subset has no `python`
    # submodule, so importing it directly would fail there).
    if module == "n4m":
        test_text = '''def test_import_and_load():
    import numpy as np

    import n4m
    from n4m._impl import aom_facade as aom
    from n4m._impl import moment_facade as moment
    from n4m._impl import native
    from n4m.estimators.regression.regularized import Ridge
    from n4m.model_selection.aom_campaign import AOMMomentScreenRefitRegressor
    from n4m.model_selection.aom_search import aom_screen_refit_candidate_pool

    assert n4m.__version__
    assert n4m.abi_version()  # loads + queries the embedded libn4m
    assert callable(native.moments)
    assert aom.aom_screen_refit_candidate_pool is native.aom_screen_refit_candidate_pool
    assert moment.moments is native.moments
    assert moment.ridge is native.ridge
    aom_inventory = {row["name"]: row for row in aom.available_methods()}
    moment_inventory = {row["name"]: row for row in moment.available_methods()}
    # Every advertised inventory entry must resolve as a facade attribute, so the
    # generated wheel can never ship a facade that names a wrapper it does not
    # actually export (regression guard for the aom pop_pls wrapper gap).
    for facade in (aom, moment):
        for row in facade.available_methods():
            assert hasattr(facade, row["entry"]), (facade.__name__, row["name"], row["entry"])
    assert {"preprocess", "moment_mixed_screen_refit", "fixed_candidate"}.issubset(
        aom_inventory
    )
    assert {"moments", "moment_sweep", "ridge", "ridge_regressor"}.issubset(
        moment_inventory
    )
    assert "cuda_pls_min_device_features" in aom_inventory[
        "moment_mixed_screen_refit"
    ]["config_options"]
    assert "cuda_pls_min_device_features" in moment_inventory["sweep_run"][
        "config_options"
    ]

    rng = np.random.default_rng(731)
    X = rng.standard_normal((48, 6))
    y = X[:, 0] - 0.25 * X[:, 2] + 0.03 * rng.standard_normal(48)
    folds = np.arange(48, dtype=np.int32) % 4
    chains = [[("identity", ())], [("savgol_smooth", (5, 2))]]

    stats = moment.moments(X, y)
    assert stats["xtx"].shape == (X.shape[1], X.shape[1])
    pre = aom.aom_preprocess(X, y, operators=["identity"], gating_mode="soft")
    np.testing.assert_allclose(pre["transformed"], X)
    assert pre["operator_kinds"].tolist() == [0]
    ridge = moment.ridge(X, y, alpha=0.1, scale_x=False)
    assert ridge["predictions"].shape[0] == X.shape[0]
    ridge_model = Ridge(alpha=0.1, scale_x=False).fit(X, y)
    np.testing.assert_allclose(
        ridge_model.predict(X), ridge["predictions"].ravel(), rtol=1e-10, atol=1e-10
    )

    model = AOMMomentScreenRefitRegressor(
        chains=chains,
        cv=4,
        fold_ids=folds,
        ridge_lambdas=(0.01,),
        pls_components=(1,),
        top_k=1,
        refit_top_k=1,
        refit_per_head_top_k=1,
        chain_chunk_size=2,
        scale_x=False,
    ).fit(X, y)
    diag = model.get_diagnostics()
    assert diag["preset"] == "moment_mixed_gcv_proxy_screen_refit"
    assert diag["split_head_scoring"] == "auto"
    assert diag["n_split_head_chunks"] >= 1
    assert diag["n_refit_candidates"] >= 2
    assert {row["head"] for row in model.refit_report_["rows"]} == {"ridge", "pls"}
    pool = aom_screen_refit_candidate_pool(
        model.screen_report_,
        refit_top_k=1,
        refit_per_head_top_k=1,
    )
    assert pool["n_candidates"] == diag["n_refit_candidates"]


def test_core_import_without_sklearn():
    # The wheel declares only numpy as a runtime dependency and advertises
    # scikit-learn (and scipy) as optional. Prove the SHIPPED package honors that:
    # importing n4m + the role packages + the direct function surface must work in
    # a child interpreter where sklearn and scipy are blocked, falling back to
    # n4m._impl.compat for the estimator base classes. The cibuildwheel test stage
    # installs scikit-learn for the sklearn-wrapper smoke above, so only this
    # explicit block exercises the optional-dependency contract.
    import os
    import subprocess
    import sys

    child = """
import sys
_BLOCK = {"sklearn", "scipy"}
class _Block:
    def find_spec(self, name, path=None, target=None):
        if name.split(".")[0] in _BLOCK:
            raise ModuleNotFoundError("blocked for test: " + name)
        return None
sys.meta_path.insert(0, _Block())

import numpy as np
import n4m
from n4m._impl import aom_facade as aom
from n4m._impl import moment_facade as moment

assert "sklearn" not in sys.modules
assert "scipy" not in sys.modules
from n4m._impl.compat import BaseEstimator
assert BaseEstimator.__module__ == "n4m._impl.compat"
assert n4m.abi_version()

rng = np.random.default_rng(0)
X = rng.standard_normal((32, 5))
y = X[:, 0] - 0.2 * X[:, 1] + 0.01 * rng.standard_normal(32)
assert moment.moments(X, y)["xtx"].shape == (5, 5)
pre = aom.aom_preprocess(X, y, operators=["identity"])
np.testing.assert_allclose(pre["transformed"], X)
r = moment.ridge(X, y, alpha=0.1, scale_x=False)
assert r["predictions"].shape[0] == 32
assert aom.available_methods() and moment.available_methods()

from n4m.estimators.regression.regularized import Ridge
m = Ridge(alpha=0.1, scale_x=False).fit(X, y)
np.testing.assert_allclose(m.predict(X), r["predictions"].ravel(), rtol=1e-10, atol=1e-10)
print("SKLEARN_OPTIONAL_OK")
"""
    env = dict(os.environ)
    env["PYTHONPATH"] = os.pathsep.join(p for p in sys.path if p)
    proc = subprocess.run(
        [sys.executable, "-c", child], capture_output=True, text=True, env=env
    )
    assert proc.returncode == 0, proc.stdout + proc.stderr
    assert "SKLEARN_OPTIONAL_OK" in proc.stdout
'''
    else:
        test_text = (
            f"def test_import_and_load():\n"
            f"    import {module}\n"
            f"    assert {module}.__version__\n"
            f"    assert {module}.abi_version()  # loads + queries the embedded libn4m\n"
        )
    (out / "tests" / "test_import.py").write_text(test_text, encoding="utf-8")
    print(f"generated {out.relative_to(REPO)}  (name={name}, module={module})")
    return out


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    g = ap.add_mutually_exclusive_group(required=True)
    g.add_argument("--name", choices=sorted(PACKAGES))
    g.add_argument("--all", action="store_true")
    args = ap.parse_args(argv)
    for name in sorted(PACKAGES) if args.all else [args.name]:
        generate(name)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
