// SPDX-License-Identifier: CECILL-2.1
//
// Model-fixture parity tests for the core regression-solver PLS families that
// are reachable through the public `n4m_model_fit` / `n4m_model_predict` /
// `n4m_model_get_array` C ABI.
//
// Each family's expected coefficients / preprocessing stats / latent matrices /
// training predictions are read from the mechanically generated fixture headers
// under cpp/tests/fixtures/ (regenerated by
// parity/python_generator/src/pls4all_parity/cpp_header.py). Every generated
// family header shares the same record layout (id, n_components, X, Y,
// coefficients, intercept, x_mean, x_scale, y_mean, y_scale, weights_w,
// loadings_p, y_loadings_q, rotations_r, scores_t, predict_train) so a single
// templated checker drives all of them — only the (algorithm, solver,
// deflation) config triple changes between families.
//
// Tolerance: the solver/algorithm rows in parity/tolerances.md gate these at
// abs/rel 1e-9 (`pls4all-numpy-{simpls,svd,power,randomized-svd}`,
// `sklearn/PLSCanonical/*`, `sklearn/PLSSVD`, `sklearn/PLSDA-dummy`,
// `pls4all-numpy-{opls,opls-da-*,kernelpls,wide-kernelpls,pcr}`,
// `pls-r-oscorespls`). Latent matrices (weights/loadings/scores/rotations) are
// only determined up to a per-column sign, so the generator marks them
// sign_invariant and the checker compares magnitudes for those.

#include "n4m/n4m.h"

#include <algorithm>
#include <cmath>
#include <cstddef>
#include <cstdint>
#include <string>
#include <vector>

#include "fixtures/canonical_fixtures.hpp"
#include "fixtures/canonical_svd_fixtures.hpp"
#include "fixtures/kernel_fixtures.hpp"
#include "fixtures/opls_da_fixtures.hpp"
#include "fixtures/opls_fixtures.hpp"
#include "fixtures/orthogonal_scores_fixtures.hpp"
#include "fixtures/pcr_fixtures.hpp"
#include "fixtures/pls_da_fixtures.hpp"
#include "fixtures/pls_svd_fixtures.hpp"
#include "fixtures/power_fixtures.hpp"
#include "fixtures/randomized_svd_fixtures.hpp"
#include "fixtures/simpls_fixtures.hpp"
#include "fixtures/svd_fixtures.hpp"
#include "fixtures/wide_kernel_fixtures.hpp"
#include "harness.hpp"

namespace {

using ::n4m::test::fixtures::MatrixRef;

constexpr double kAbsTol = 1e-9;
constexpr double kRelTol = 1e-9;

// The randomized-SVD fixture was generated with a fixed PCG64 seed; the C
// engine must be seeded identically to reproduce the projection sketch.
constexpr std::uint64_t kRandomizedSvdFixtureSeed = 123456789ULL;

// One config recipe per family: how to drive the generic n4m_model_fit path.
struct FitRecipe {
    n4m_algorithm_t algorithm;
    n4m_solver_t    solver;
    n4m_deflation_t deflation;
    bool            set_deflation;   // some families leave deflation at default
    bool            seed;            // randomized-svd needs a deterministic seed
};

n4m_matrix_view_t make_view(const MatrixRef& ref) {
    n4m_matrix_view_t v{};
    const n4m_status_t st = n4m_matrix_view_init_rowmajor(
        &v, const_cast<double*>(ref.values), ref.rows, ref.cols, N4M_DTYPE_F64);
    N4M_TEST_REQUIRE(st == N4M_OK);
    return v;
}

void check_close(const char* tag, const double* actual, const MatrixRef& expected) {
    for (std::size_t i = 0; i < expected.size; ++i) {
        const double a = expected.sign_invariant ? std::fabs(actual[i]) : actual[i];
        const double b = expected.sign_invariant ? std::fabs(expected.values[i])
                                                  : expected.values[i];
        const double diff  = std::fabs(a - b);
        const double scale = std::max(std::max(std::fabs(a), std::fabs(b)), 1.0);
        if (diff > kAbsTol && diff > kRelTol * scale) {
            throw std::runtime_error(std::string(tag) + " mismatch at i=" +
                std::to_string(i) + " got=" + std::to_string(actual[i]) +
                " want=" + std::to_string(expected.values[i]) +
                " diff=" + std::to_string(diff));
        }
    }
}

// Pull a tagged fitted-model array and compare it to the expected MatrixRef.
void check_model_array(n4m_context_t* ctx, n4m_model_t* model,
                       n4m_model_array_t which, const char* tag,
                       const MatrixRef& expected) {
    n4m_array_t* arr = nullptr;
    N4M_TEST_REQUIRE(n4m_model_get_array(ctx, model, which, &arr) == N4M_OK);
    N4M_TEST_REQUIRE(arr != nullptr);
    std::int64_t rows = 0, cols = 0;
    N4M_TEST_REQUIRE(n4m_array_shape(arr, &rows, &cols) == N4M_OK);
    N4M_TEST_REQUIRE(rows == expected.rows);
    N4M_TEST_REQUIRE(cols == expected.cols);
    n4m_dtype_t dtype = N4M_DTYPE_UNKNOWN;
    N4M_TEST_REQUIRE(n4m_array_dtype(arr, &dtype) == N4M_OK);
    N4M_TEST_REQUIRE(dtype == N4M_DTYPE_F64);
    n4m_matrix_view_t view{};
    N4M_TEST_REQUIRE(n4m_array_view(arr, &view) == N4M_OK);
    check_close(tag, static_cast<const double*>(view.data), expected);
    n4m_array_free(arr);
}

std::vector<double> array_values(const n4m_array_t* arr) {
    std::int64_t rows = 0, cols = 0;
    n4m_array_shape(arr, &rows, &cols);
    n4m_matrix_view_t view{};
    n4m_array_view(arr, &view);
    const auto* p = static_cast<const double*>(view.data);
    return std::vector<double>(p, p + rows * cols);
}

// Generic per-fixture check. Fixture must expose the shared generated layout.
template <typename Fixture>
void check_fixture(const Fixture& fx, const FitRecipe& recipe) {
    n4m_context_t* ctx = nullptr;
    n4m_config_t*  cfg = nullptr;
    n4m_model_t*   model = nullptr;
    N4M_TEST_REQUIRE(n4m_context_create(&ctx) == N4M_OK);
    if (recipe.seed) {
        N4M_TEST_REQUIRE(n4m_context_set_seed(ctx, kRandomizedSvdFixtureSeed) == N4M_OK);
    }
    N4M_TEST_REQUIRE(n4m_config_create(&cfg) == N4M_OK);
    N4M_TEST_REQUIRE(n4m_config_set_n_components(cfg, fx.n_components) == N4M_OK);
    N4M_TEST_REQUIRE(n4m_config_set_algorithm(cfg, recipe.algorithm) == N4M_OK);
    N4M_TEST_REQUIRE(n4m_config_set_solver(cfg, recipe.solver) == N4M_OK);
    if (recipe.set_deflation) {
        N4M_TEST_REQUIRE(n4m_config_set_deflation(cfg, recipe.deflation) == N4M_OK);
    }

    n4m_matrix_view_t X = make_view(fx.X);
    n4m_matrix_view_t Y = make_view(fx.Y);
    N4M_TEST_REQUIRE(n4m_model_fit(ctx, cfg, &X, &Y, &model) == N4M_OK);
    N4M_TEST_REQUIRE(model != nullptr);

    std::int32_t n_components = 0, n_features = 0, n_targets = 0;
    N4M_TEST_REQUIRE(n4m_model_get_n_components(model, &n_components) == N4M_OK);
    N4M_TEST_REQUIRE(n4m_model_get_n_features(model, &n_features) == N4M_OK);
    N4M_TEST_REQUIRE(n4m_model_get_n_targets(model, &n_targets) == N4M_OK);
    N4M_TEST_REQUIRE(n_components == fx.n_components);
    N4M_TEST_REQUIRE(n_features == static_cast<std::int32_t>(fx.X.cols));
    N4M_TEST_REQUIRE(n_targets == static_cast<std::int32_t>(fx.Y.cols));

    // Core-allocated predictions.
    n4m_array_t* pred = nullptr;
    N4M_TEST_REQUIRE(n4m_model_predict_alloc(ctx, model, &X, &pred) == N4M_OK);
    N4M_TEST_REQUIRE(pred != nullptr);
    std::int64_t prows = 0, pcols = 0;
    N4M_TEST_REQUIRE(n4m_array_shape(pred, &prows, &pcols) == N4M_OK);
    N4M_TEST_REQUIRE(prows == fx.predict_train.rows);
    N4M_TEST_REQUIRE(pcols == fx.predict_train.cols);
    std::vector<double> pred_values = array_values(pred);
    check_close(fx.id, pred_values.data(), fx.predict_train);
    n4m_array_free(pred);

    // Caller-allocated predictions must match the core-allocated path.
    std::vector<double> caller(fx.predict_train.size, 0.0);
    n4m_matrix_view_t out{};
    N4M_TEST_REQUIRE(n4m_matrix_view_init_rowmajor(
        &out, caller.data(), fx.predict_train.rows, fx.predict_train.cols,
        N4M_DTYPE_F64) == N4M_OK);
    N4M_TEST_REQUIRE(n4m_model_predict(ctx, model, &X, &out) == N4M_OK);
    check_close(fx.id, caller.data(), fx.predict_train);

    check_model_array(ctx, model, N4M_MODEL_COEFFICIENTS, "coefficients", fx.coefficients);
    check_model_array(ctx, model, N4M_MODEL_INTERCEPT,    "intercept",    fx.intercept);
    check_model_array(ctx, model, N4M_MODEL_X_MEAN,       "x_mean",       fx.x_mean);
    check_model_array(ctx, model, N4M_MODEL_X_SCALE,      "x_scale",      fx.x_scale);
    check_model_array(ctx, model, N4M_MODEL_Y_MEAN,       "y_mean",       fx.y_mean);
    check_model_array(ctx, model, N4M_MODEL_Y_SCALE,      "y_scale",      fx.y_scale);
    check_model_array(ctx, model, N4M_MODEL_WEIGHTS_W,    "weights_w",    fx.weights_w);
    check_model_array(ctx, model, N4M_MODEL_LOADINGS_P,   "loadings_p",   fx.loadings_p);
    check_model_array(ctx, model, N4M_MODEL_Y_LOADINGS_Q, "y_loadings_q", fx.y_loadings_q);
    check_model_array(ctx, model, N4M_MODEL_ROTATIONS_R,  "rotations_r",  fx.rotations_r);

    n4m_model_destroy(model);
    n4m_config_destroy(cfg);
    n4m_context_destroy(ctx);
}

template <typename Fixture, std::size_t N>
void check_family(const Fixture (&fixtures)[N], const FitRecipe& recipe) {
    for (const auto& fx : fixtures) {
        check_fixture(fx, recipe);
    }
}

// ---- Per-family entry points (one test per family for readable reporting) ---

void test_simpls() {
    check_family(::n4m::test::fixtures::kSimplsFixtures,
                 {N4M_ALGO_PLS_REGRESSION, N4M_SOLVER_SIMPLS, N4M_DEFLATION_REGRESSION, false, false});
}
void test_svd() {
    check_family(::n4m::test::fixtures::kSvdFixtures,
                 {N4M_ALGO_PLS_REGRESSION, N4M_SOLVER_SVD, N4M_DEFLATION_REGRESSION, false, false});
}
void test_power() {
    check_family(::n4m::test::fixtures::kPowerFixtures,
                 {N4M_ALGO_PLS_REGRESSION, N4M_SOLVER_POWER, N4M_DEFLATION_REGRESSION, false, false});
}
void test_randomized_svd() {
    check_family(::n4m::test::fixtures::kRandomizedSvdFixtures,
                 {N4M_ALGO_PLS_REGRESSION, N4M_SOLVER_RANDOMIZED_SVD, N4M_DEFLATION_REGRESSION, false, true});
}
void test_pcr() {
    check_family(::n4m::test::fixtures::kPcrFixtures,
                 {N4M_ALGO_PCR, N4M_SOLVER_SVD, N4M_DEFLATION_REGRESSION, false, false});
}
void test_kernel() {
    check_family(::n4m::test::fixtures::kKernelFixtures,
                 {N4M_ALGO_PLS_REGRESSION, N4M_SOLVER_KERNEL_ALGORITHM, N4M_DEFLATION_REGRESSION, false, false});
}
void test_wide_kernel() {
    check_family(::n4m::test::fixtures::kWideKernelFixtures,
                 {N4M_ALGO_PLS_REGRESSION, N4M_SOLVER_WIDE_KERNEL, N4M_DEFLATION_REGRESSION, false, false});
}
void test_orthogonal_scores() {
    check_family(::n4m::test::fixtures::kOrthogonalScoresFixtures,
                 {N4M_ALGO_PLS_REGRESSION, N4M_SOLVER_ORTHOGONAL_SCORES, N4M_DEFLATION_REGRESSION, false, false});
}
void test_pls_svd() {
    check_family(::n4m::test::fixtures::kPlsSvdFixtures,
                 {N4M_ALGO_PLS_SVD, N4M_SOLVER_SVD, N4M_DEFLATION_CANONICAL, true, false});
}
void test_canonical() {
    check_family(::n4m::test::fixtures::kCanonicalFixtures,
                 {N4M_ALGO_PLS_CANONICAL, N4M_SOLVER_NIPALS, N4M_DEFLATION_CANONICAL, true, false});
}
void test_canonical_svd() {
    check_family(::n4m::test::fixtures::kCanonicalSvdFixtures,
                 {N4M_ALGO_PLS_CANONICAL, N4M_SOLVER_SVD, N4M_DEFLATION_CANONICAL, true, false});
}
void test_pls_da() {
    check_family(::n4m::test::fixtures::kPlsDaFixtures,
                 {N4M_ALGO_PLS_DA, N4M_SOLVER_NIPALS, N4M_DEFLATION_REGRESSION, true, false});
}
void test_opls() {
    check_family(::n4m::test::fixtures::kOplsFixtures,
                 {N4M_ALGO_OPLS, N4M_SOLVER_NIPALS, N4M_DEFLATION_ORTHOGONAL, true, false});
}
void test_opls_da() {
    check_family(::n4m::test::fixtures::kOplsDaFixtures,
                 {N4M_ALGO_OPLS_DA, N4M_SOLVER_NIPALS, N4M_DEFLATION_ORTHOGONAL, true, false});
}

}  // namespace

void register_models_pls_tests(n4m_testing::Runner& r) {
    r.run("models_pls/simpls",             test_simpls);
    r.run("models_pls/svd",                test_svd);
    r.run("models_pls/power",              test_power);
    r.run("models_pls/randomized_svd",     test_randomized_svd);
    r.run("models_pls/pcr",                test_pcr);
    r.run("models_pls/kernel",             test_kernel);
    r.run("models_pls/wide_kernel",        test_wide_kernel);
    r.run("models_pls/orthogonal_scores",  test_orthogonal_scores);
    r.run("models_pls/pls_svd",            test_pls_svd);
    r.run("models_pls/canonical",          test_canonical);
    r.run("models_pls/canonical_svd",      test_canonical_svd);
    r.run("models_pls/pls_da",             test_pls_da);
    r.run("models_pls/opls",               test_opls);
    r.run("models_pls/opls_da",            test_opls_da);
}
