// Generated by catalog/scripts/generate_estimator_manifest.py. Do not edit.
// Adapter factories named by catalog `estimator.adapter` entries.

#pragma once

#include <memory>

#include "core/estimator/spec.hpp"

namespace n4m::estimator {

std::unique_ptr<Adapter> make_affine_bagging_pls(const MethodSpec& spec);
std::unique_ptr<Adapter> make_affine_boosting_pls(const MethodSpec& spec);
std::unique_ptr<Adapter> make_affine_continuum_regression(const MethodSpec& spec);
std::unique_ptr<Adapter> make_affine_cppls(const MethodSpec& spec);
std::unique_ptr<Adapter> make_affine_di_pls(const MethodSpec& spec);
std::unique_ptr<Adapter> make_affine_ecr(const MethodSpec& spec);
std::unique_ptr<Adapter> make_affine_fused_sparse_pls(const MethodSpec& spec);
std::unique_ptr<Adapter> make_affine_group_sparse_pls(const MethodSpec& spec);
std::unique_ptr<Adapter> make_affine_mb_pls(const MethodSpec& spec);
std::unique_ptr<Adapter> make_affine_mir_pls(const MethodSpec& spec);
std::unique_ptr<Adapter> make_affine_n_pls(const MethodSpec& spec);
std::unique_ptr<Adapter> make_affine_random_subspace_pls(const MethodSpec& spec);
std::unique_ptr<Adapter> make_affine_ridge(const MethodSpec& spec);
std::unique_ptr<Adapter> make_affine_ridge_pls(const MethodSpec& spec);
std::unique_ptr<Adapter> make_affine_robust_pls(const MethodSpec& spec);
std::unique_ptr<Adapter> make_affine_sparse_simpls(const MethodSpec& spec);
std::unique_ptr<Adapter> make_pcr(const MethodSpec& spec);
std::unique_ptr<Adapter> make_pls_fit_simple(const MethodSpec& spec);
std::unique_ptr<Adapter> make_pls_regression(const MethodSpec& spec);

}  // namespace n4m::estimator
