// Generated by catalog/scripts/generate_estimator_manifest.py. Do not edit.
// Adapter factories named by catalog `estimator.adapter` entries.

#pragma once

#include <memory>

#include "core/estimator/spec.hpp"

namespace n4m::estimator {

std::unique_ptr<Adapter> make_affine_bagging_pls(const MethodSpec& spec);
std::unique_ptr<Adapter> make_affine_boosting_pls(const MethodSpec& spec);
std::unique_ptr<Adapter> make_affine_continuum_regression(const MethodSpec& spec);
std::unique_ptr<Adapter> make_affine_cppls(const MethodSpec& spec);
std::unique_ptr<Adapter> make_affine_di_pls(const MethodSpec& spec);
std::unique_ptr<Adapter> make_affine_ecr(const MethodSpec& spec);
std::unique_ptr<Adapter> make_affine_fused_sparse_pls(const MethodSpec& spec);
std::unique_ptr<Adapter> make_affine_group_sparse_pls(const MethodSpec& spec);
std::unique_ptr<Adapter> make_affine_mb_pls(const MethodSpec& spec);
std::unique_ptr<Adapter> make_affine_mir_pls(const MethodSpec& spec);
std::unique_ptr<Adapter> make_affine_n_pls(const MethodSpec& spec);
std::unique_ptr<Adapter> make_affine_o2pls(const MethodSpec& spec);
std::unique_ptr<Adapter> make_affine_random_subspace_pls(const MethodSpec& spec);
std::unique_ptr<Adapter> make_affine_ridge(const MethodSpec& spec);
std::unique_ptr<Adapter> make_affine_ridge_pls(const MethodSpec& spec);
std::unique_ptr<Adapter> make_affine_robust_pls(const MethodSpec& spec);
std::unique_ptr<Adapter> make_affine_sparse_simpls(const MethodSpec& spec);
std::unique_ptr<Adapter> make_affine_weighted_pls(const MethodSpec& spec);
std::unique_ptr<Adapter> make_pcr(const MethodSpec& spec);
std::unique_ptr<Adapter> make_pls_fit_simple(const MethodSpec& spec);
std::unique_ptr<Adapter> make_pls_regression(const MethodSpec& spec);
std::unique_ptr<Adapter> make_select_bipls(const MethodSpec& spec);
std::unique_ptr<Adapter> make_select_bve(const MethodSpec& spec);
std::unique_ptr<Adapter> make_select_cars(const MethodSpec& spec);
std::unique_ptr<Adapter> make_select_emcuve(const MethodSpec& spec);
std::unique_ptr<Adapter> make_select_ga(const MethodSpec& spec);
std::unique_ptr<Adapter> make_select_ipw(const MethodSpec& spec);
std::unique_ptr<Adapter> make_select_irf(const MethodSpec& spec);
std::unique_ptr<Adapter> make_select_iriv(const MethodSpec& spec);
std::unique_ptr<Adapter> make_select_pso(const MethodSpec& spec);
std::unique_ptr<Adapter> make_select_random_frog(const MethodSpec& spec);
std::unique_ptr<Adapter> make_select_randomization(const MethodSpec& spec);
std::unique_ptr<Adapter> make_select_rep(const MethodSpec& spec);
std::unique_ptr<Adapter> make_select_scars(const MethodSpec& spec);
std::unique_ptr<Adapter> make_select_shaving(const MethodSpec& spec);
std::unique_ptr<Adapter> make_select_sipls(const MethodSpec& spec);
std::unique_ptr<Adapter> make_select_spa(const MethodSpec& spec);
std::unique_ptr<Adapter> make_select_st(const MethodSpec& spec);
std::unique_ptr<Adapter> make_select_stability(const MethodSpec& spec);
std::unique_ptr<Adapter> make_select_t2(const MethodSpec& spec);
std::unique_ptr<Adapter> make_select_uve(const MethodSpec& spec);
std::unique_ptr<Adapter> make_select_variable_rank(const MethodSpec& spec);
std::unique_ptr<Adapter> make_select_vip_spa(const MethodSpec& spec);
std::unique_ptr<Adapter> make_select_vissa(const MethodSpec& spec);
std::unique_ptr<Adapter> make_select_wvc(const MethodSpec& spec);
std::unique_ptr<Adapter> make_select_wvc_threshold(const MethodSpec& spec);
std::unique_ptr<Adapter> make_tr_airpls(const MethodSpec& spec);
std::unique_ptr<Adapter> make_tr_area_normalization(const MethodSpec& spec);
std::unique_ptr<Adapter> make_tr_arpls(const MethodSpec& spec);
std::unique_ptr<Adapter> make_tr_asls(const MethodSpec& spec);
std::unique_ptr<Adapter> make_tr_beads(const MethodSpec& spec);
std::unique_ptr<Adapter> make_tr_crop(const MethodSpec& spec);
std::unique_ptr<Adapter> make_tr_detrend(const MethodSpec& spec);
std::unique_ptr<Adapter> make_tr_first_derivative(const MethodSpec& spec);
std::unique_ptr<Adapter> make_tr_fraction_to_percent(const MethodSpec& spec);
std::unique_ptr<Adapter> make_tr_from_absorbance(const MethodSpec& spec);
std::unique_ptr<Adapter> make_tr_gaussian(const MethodSpec& spec);
std::unique_ptr<Adapter> make_tr_haar(const MethodSpec& spec);
std::unique_ptr<Adapter> make_tr_iasls(const MethodSpec& spec);
std::unique_ptr<Adapter> make_tr_imodpoly(const MethodSpec& spec);
std::unique_ptr<Adapter> make_tr_kubelka_munk(const MethodSpec& spec);
std::unique_ptr<Adapter> make_tr_local_snv(const MethodSpec& spec);
std::unique_ptr<Adapter> make_tr_modpoly(const MethodSpec& spec);
std::unique_ptr<Adapter> make_tr_norris_williams(const MethodSpec& spec);
std::unique_ptr<Adapter> make_tr_percent_to_fraction(const MethodSpec& spec);
std::unique_ptr<Adapter> make_tr_resample(const MethodSpec& spec);
std::unique_ptr<Adapter> make_tr_robust_snv(const MethodSpec& spec);
std::unique_ptr<Adapter> make_tr_rolling_ball(const MethodSpec& spec);
std::unique_ptr<Adapter> make_tr_savitzky_golay(const MethodSpec& spec);
std::unique_ptr<Adapter> make_tr_second_derivative(const MethodSpec& spec);
std::unique_ptr<Adapter> make_tr_snip(const MethodSpec& spec);
std::unique_ptr<Adapter> make_tr_snv(const MethodSpec& spec);
std::unique_ptr<Adapter> make_tr_to_absorbance(const MethodSpec& spec);
std::unique_ptr<Adapter> make_tr_wavelet(const MethodSpec& spec);
std::unique_ptr<Adapter> make_tr_wavelet_denoise(const MethodSpec& spec);
std::unique_ptr<Adapter> make_tr_wavelet_features(const MethodSpec& spec);

}  // namespace n4m::estimator
