// SPDX-License-Identifier: CECILL-2.1
// Generated by scripts/generate_js_roles.py from `n4m_cli --manifest-json`. Do not edit.
// Native ABI 2.13.0.

import { NativeEstimator, type Regressor, type Selector, type Transformer } from "./estimatorRoles.js";
import type { Matrix } from "./types.js";

/** Parameters of BaggingPLS; unset values take the native defaults. */
export interface BaggingPLSParams {
    /** Default 2. */
    n_components?: number;
    /** Default 50. */
    n_estimators?: number;
    /** Default 0. */
    seed?: number;
}

/** Native `models.ensembles.bagging_pls` (regressor). */
export class BaggingPLS extends NativeEstimator implements Regressor {
    readonly methodId = "models.ensembles.bagging_pls";
    protected readonly paramTypes = {
        n_components: "int",
        n_estimators: "int",
        seed: "int",
    } as const;

    constructor(params: BaggingPLSParams = {}) {
        super();
        this.params = { ...params };
    }

    predict(X: Matrix): Matrix {
        return this.predictMatrix(X);
    }
}
NativeEstimator.register("models.ensembles.bagging_pls", BaggingPLS);

/** Parameters of BoostingPLS; unset values take the native defaults. */
export interface BoostingPLSParams {
    /** Default 2. */
    n_components?: number;
    /** Default 50. */
    n_estimators?: number;
    /** Default 0.1. */
    learning_rate?: number;
}

/** Native `models.ensembles.boosting_pls` (regressor). */
export class BoostingPLS extends NativeEstimator implements Regressor {
    readonly methodId = "models.ensembles.boosting_pls";
    protected readonly paramTypes = {
        n_components: "int",
        n_estimators: "int",
        learning_rate: "double",
    } as const;

    constructor(params: BoostingPLSParams = {}) {
        super();
        this.params = { ...params };
    }

    predict(X: Matrix): Matrix {
        return this.predictMatrix(X);
    }
}
NativeEstimator.register("models.ensembles.boosting_pls", BoostingPLS);

/** Parameters of RandomSubspacePLS; unset values take the native defaults. */
export interface RandomSubspacePLSParams {
    /** Default 2. */
    n_components?: number;
    /** Default 50. */
    n_estimators?: number;
    /** Default 10. */
    features_per_subspace?: number;
    /** Default 0. */
    seed?: number;
}

/** Native `models.ensembles.random_subspace_pls` (regressor). */
export class RandomSubspacePLS extends NativeEstimator implements Regressor {
    readonly methodId = "models.ensembles.random_subspace_pls";
    protected readonly paramTypes = {
        n_components: "int",
        n_estimators: "int",
        features_per_subspace: "int",
        seed: "int",
    } as const;

    constructor(params: RandomSubspacePLSParams = {}) {
        super();
        this.params = { ...params };
    }

    predict(X: Matrix): Matrix {
        return this.predictMatrix(X);
    }
}
NativeEstimator.register("models.ensembles.random_subspace_pls", RandomSubspacePLS);

/** Parameters of MBPLS; unset values take the native defaults. */
export interface MBPLSParams {
    /** Default 2. */
    n_components?: number;
}

/** Native `models.multiblock.mb_pls` (regressor). Required fit inputs: blocks. */
export class MBPLS extends NativeEstimator implements Regressor {
    readonly methodId = "models.multiblock.mb_pls";
    protected readonly paramTypes = {
        n_components: "int",
    } as const;

    constructor(params: MBPLSParams = {}) {
        super();
        this.params = { ...params };
    }

    predict(X: Matrix): Matrix {
        return this.predictMatrix(X);
    }
}
NativeEstimator.register("models.multiblock.mb_pls", MBPLS);

/** Parameters of MIRPLS; unset values take the native defaults. */
export interface MIRPLSParams {
    /** Default 2. */
    n_components?: number;
}

/** Native `models.multiblock.mir_pls` (regressor). */
export class MIRPLS extends NativeEstimator implements Regressor {
    readonly methodId = "models.multiblock.mir_pls";
    protected readonly paramTypes = {
        n_components: "int",
    } as const;

    constructor(params: MIRPLSParams = {}) {
        super();
        this.params = { ...params };
    }

    predict(X: Matrix): Matrix {
        return this.predictMatrix(X);
    }
}
NativeEstimator.register("models.multiblock.mir_pls", MIRPLS);

/** Parameters of O2PLS; unset values take the native defaults. */
export interface O2PLSParams {
    /** Default 2. */
    n_predictive?: number;
    /** Default 1. */
    n_x_orthogonal?: number;
    /** Default 1. */
    n_y_orthogonal?: number;
}

/** Native `models.multiblock.o2pls` (regressor). */
export class O2PLS extends NativeEstimator implements Regressor {
    readonly methodId = "models.multiblock.o2pls";
    protected readonly paramTypes = {
        n_predictive: "int",
        n_x_orthogonal: "int",
        n_y_orthogonal: "int",
    } as const;

    constructor(params: O2PLSParams = {}) {
        super();
        this.params = { ...params };
    }

    predict(X: Matrix): Matrix {
        return this.predictMatrix(X);
    }
}
NativeEstimator.register("models.multiblock.o2pls", O2PLS);

/** Parameters of CPPLS; unset values take the native defaults. */
export interface CPPLSParams {
    /** Default 2. */
    n_components?: number;
    /** Default 0.5. */
    gamma?: number;
}

/** Native `models.pls.cppls` (regressor). */
export class CPPLS extends NativeEstimator implements Regressor {
    readonly methodId = "models.pls.cppls";
    protected readonly paramTypes = {
        n_components: "int",
        gamma: "double",
    } as const;

    constructor(params: CPPLSParams = {}) {
        super();
        this.params = { ...params };
    }

    predict(X: Matrix): Matrix {
        return this.predictMatrix(X);
    }
}
NativeEstimator.register("models.pls.cppls", CPPLS);

/** Parameters of PCR; unset values take the native defaults. */
export interface PCRParams {
    /** Default 2. */
    n_components?: number;
    /** Default true. */
    center_x?: boolean;
    /** Default true. */
    scale_x?: boolean;
    /** Default true. */
    center_y?: boolean;
    /** Default false. */
    scale_y?: boolean;
}

/** Native `models.pls.pcr` (transformer, regressor). */
export class PCR extends NativeEstimator implements Regressor, Transformer {
    readonly methodId = "models.pls.pcr";
    protected readonly paramTypes = {
        n_components: "int",
        center_x: "bool",
        scale_x: "bool",
        center_y: "bool",
        scale_y: "bool",
    } as const;

    constructor(params: PCRParams = {}) {
        super();
        this.params = { ...params };
    }

    predict(X: Matrix): Matrix {
        return this.predictMatrix(X);
    }

    transform(X: Matrix): Matrix {
        return this.transformMatrix(X);
    }
}
NativeEstimator.register("models.pls.pcr", PCR);

/** Parameters of SimplePLS; unset values take the native defaults. */
export interface SimplePLSParams {
    /** Default 2. */
    n_components?: number;
}

/** Native `models.pls.pls_fit_simple` (transformer, regressor). */
export class SimplePLS extends NativeEstimator implements Regressor, Transformer {
    readonly methodId = "models.pls.pls_fit_simple";
    protected readonly paramTypes = {
        n_components: "int",
    } as const;

    constructor(params: SimplePLSParams = {}) {
        super();
        this.params = { ...params };
    }

    predict(X: Matrix): Matrix {
        return this.predictMatrix(X);
    }

    transform(X: Matrix): Matrix {
        return this.transformMatrix(X);
    }
}
NativeEstimator.register("models.pls.pls_fit_simple", SimplePLS);

/** Parameters of PLSRegression; unset values take the native defaults. */
export interface PLSRegressionParams {
    /** Default 2. */
    n_components?: number;
    /** Default "nipals". */
    solver?: "nipals" | "simpls" | "orthogonal_scores" | "kernel_algorithm" | "wide_kernel" | "svd" | "power" | "randomized_svd";
    /** Default true. */
    center_x?: boolean;
    /** Default true. */
    scale_x?: boolean;
    /** Default true. */
    center_y?: boolean;
    /** Default true. */
    scale_y?: boolean;
}

/** Native `models.pls.pls_regression` (transformer, regressor). */
export class PLSRegression extends NativeEstimator implements Regressor, Transformer {
    readonly methodId = "models.pls.pls_regression";
    protected readonly paramTypes = {
        n_components: "int",
        solver: "enum",
        center_x: "bool",
        scale_x: "bool",
        center_y: "bool",
        scale_y: "bool",
    } as const;

    constructor(params: PLSRegressionParams = {}) {
        super();
        this.params = { ...params };
    }

    predict(X: Matrix): Matrix {
        return this.predictMatrix(X);
    }

    transform(X: Matrix): Matrix {
        return this.transformMatrix(X);
    }
}
NativeEstimator.register("models.pls.pls_regression", PLSRegression);

/** Parameters of ContinuumRegression; unset values take the native defaults. */
export interface ContinuumRegressionParams {
    /** Default 2. */
    n_components?: number;
    /** Default 0.5. */
    tau?: number;
}

/** Native `models.regularized.continuum_regression` (regressor). */
export class ContinuumRegression extends NativeEstimator implements Regressor {
    readonly methodId = "models.regularized.continuum_regression";
    protected readonly paramTypes = {
        n_components: "int",
        tau: "double",
    } as const;

    constructor(params: ContinuumRegressionParams = {}) {
        super();
        this.params = { ...params };
    }

    predict(X: Matrix): Matrix {
        return this.predictMatrix(X);
    }
}
NativeEstimator.register("models.regularized.continuum_regression", ContinuumRegression);

/** Parameters of Ridge; unset values take the native defaults. */
export interface RidgeParams {
    /** Default 1. */
    alpha?: number;
    /** Default true. */
    center_x?: boolean;
    /** Default true. */
    scale_x?: boolean;
    /** Default true. */
    center_y?: boolean;
}

/** Native `models.regularized.ridge` (regressor). */
export class Ridge extends NativeEstimator implements Regressor {
    readonly methodId = "models.regularized.ridge";
    protected readonly paramTypes = {
        alpha: "double",
        center_x: "bool",
        scale_x: "bool",
        center_y: "bool",
    } as const;

    constructor(params: RidgeParams = {}) {
        super();
        this.params = { ...params };
    }

    predict(X: Matrix): Matrix {
        return this.predictMatrix(X);
    }
}
NativeEstimator.register("models.regularized.ridge", Ridge);

/** Parameters of RidgePLS; unset values take the native defaults. */
export interface RidgePLSParams {
    /** Default 2. */
    n_components?: number;
    /** Default 0.1. */
    ridge_lambda?: number;
    /** Default true. */
    center_x?: boolean;
    /** Default true. */
    scale_x?: boolean;
    /** Default true. */
    center_y?: boolean;
    /** Default true. */
    scale_y?: boolean;
}

/** Native `models.regularized.ridge_pls` (regressor). */
export class RidgePLS extends NativeEstimator implements Regressor {
    readonly methodId = "models.regularized.ridge_pls";
    protected readonly paramTypes = {
        n_components: "int",
        ridge_lambda: "double",
        center_x: "bool",
        scale_x: "bool",
        center_y: "bool",
        scale_y: "bool",
    } as const;

    constructor(params: RidgePLSParams = {}) {
        super();
        this.params = { ...params };
    }

    predict(X: Matrix): Matrix {
        return this.predictMatrix(X);
    }
}
NativeEstimator.register("models.regularized.ridge_pls", RidgePLS);

/** Parameters of RobustPLS; unset values take the native defaults. */
export interface RobustPLSParams {
    /** Default 2. */
    n_components?: number;
    /** Default 1.345. */
    huber_k?: number;
    /** Default 5. */
    max_irls_iter?: number;
    /** Default true. */
    center_x?: boolean;
    /** Default true. */
    scale_x?: boolean;
    /** Default true. */
    center_y?: boolean;
    /** Default true. */
    scale_y?: boolean;
}

/** Native `models.regularized.robust_pls` (regressor). */
export class RobustPLS extends NativeEstimator implements Regressor {
    readonly methodId = "models.regularized.robust_pls";
    protected readonly paramTypes = {
        n_components: "int",
        huber_k: "double",
        max_irls_iter: "int",
        center_x: "bool",
        scale_x: "bool",
        center_y: "bool",
        scale_y: "bool",
    } as const;

    constructor(params: RobustPLSParams = {}) {
        super();
        this.params = { ...params };
    }

    predict(X: Matrix): Matrix {
        return this.predictMatrix(X);
    }
}
NativeEstimator.register("models.regularized.robust_pls", RobustPLS);

/** Parameters of WeightedPLS; unset values take the native defaults. */
export interface WeightedPLSParams {
    /** Default 2. */
    n_components?: number;
    /** Default true. */
    center_x?: boolean;
    /** Default true. */
    scale_x?: boolean;
    /** Default true. */
    center_y?: boolean;
    /** Default true. */
    scale_y?: boolean;
}

/** Native `models.regularized.weighted_pls` (regressor). */
export class WeightedPLS extends NativeEstimator implements Regressor {
    readonly methodId = "models.regularized.weighted_pls";
    protected readonly paramTypes = {
        n_components: "int",
        center_x: "bool",
        scale_x: "bool",
        center_y: "bool",
        scale_y: "bool",
    } as const;

    constructor(params: WeightedPLSParams = {}) {
        super();
        this.params = { ...params };
    }

    predict(X: Matrix): Matrix {
        return this.predictMatrix(X);
    }
}
NativeEstimator.register("models.regularized.weighted_pls", WeightedPLS);

/** Parameters of FusedSparsePLS; unset values take the native defaults. */
export interface FusedSparsePLSParams {
    /** Default 2. */
    n_components?: number;
    /** Default 0.05. */
    l1_lambda?: number;
    /** Default 0.05. */
    fusion_lambda?: number;
}

/** Native `models.sparse.fused_sparse_pls` (regressor). */
export class FusedSparsePLS extends NativeEstimator implements Regressor {
    readonly methodId = "models.sparse.fused_sparse_pls";
    protected readonly paramTypes = {
        n_components: "int",
        l1_lambda: "double",
        fusion_lambda: "double",
    } as const;

    constructor(params: FusedSparsePLSParams = {}) {
        super();
        this.params = { ...params };
    }

    predict(X: Matrix): Matrix {
        return this.predictMatrix(X);
    }
}
NativeEstimator.register("models.sparse.fused_sparse_pls", FusedSparsePLS);

/** Parameters of GroupSparsePLS; unset values take the native defaults. */
export interface GroupSparsePLSParams {
    /** Default 2. */
    n_components?: number;
    /** Default 0.05. */
    group_lambda?: number;
}

/** Native `models.sparse.group_sparse_pls` (regressor). Required fit inputs: feature_groups. */
export class GroupSparsePLS extends NativeEstimator implements Regressor {
    readonly methodId = "models.sparse.group_sparse_pls";
    protected readonly paramTypes = {
        n_components: "int",
        group_lambda: "double",
    } as const;

    constructor(params: GroupSparsePLSParams = {}) {
        super();
        this.params = { ...params };
    }

    predict(X: Matrix): Matrix {
        return this.predictMatrix(X);
    }
}
NativeEstimator.register("models.sparse.group_sparse_pls", GroupSparsePLS);

/** Parameters of SparseSIMPLS; unset values take the native defaults. */
export interface SparseSIMPLSParams {
    /** Default 2. */
    n_components?: number;
    /** Default 0.05. */
    sparsity_lambda?: number;
}

/** Native `models.sparse.sparse_simpls` (regressor). */
export class SparseSIMPLS extends NativeEstimator implements Regressor {
    readonly methodId = "models.sparse.sparse_simpls";
    protected readonly paramTypes = {
        n_components: "int",
        sparsity_lambda: "double",
    } as const;

    constructor(params: SparseSIMPLSParams = {}) {
        super();
        this.params = { ...params };
    }

    predict(X: Matrix): Matrix {
        return this.predictMatrix(X);
    }
}
NativeEstimator.register("models.sparse.sparse_simpls", SparseSIMPLS);

/** Parameters of ECR; unset values take the native defaults. */
export interface ECRParams {
    /** Default 2. */
    n_components?: number;
    /** Default 0.5. */
    alpha?: number;
}

/** Native `models.specialized.ecr` (regressor). */
export class ECR extends NativeEstimator implements Regressor {
    readonly methodId = "models.specialized.ecr";
    protected readonly paramTypes = {
        n_components: "int",
        alpha: "double",
    } as const;

    constructor(params: ECRParams = {}) {
        super();
        this.params = { ...params };
    }

    predict(X: Matrix): Matrix {
        return this.predictMatrix(X);
    }
}
NativeEstimator.register("models.specialized.ecr", ECR);

/** Parameters of NPLS; unset values take the native defaults. */
export interface NPLSParams {
    /** Default 2. */
    n_components?: number;
    /** Required. */
    mode_j?: number;
    /** Required. */
    mode_k?: number;
}

/** Native `models.specialized.tensor_pls` (regressor). */
export class NPLS extends NativeEstimator implements Regressor {
    readonly methodId = "models.specialized.tensor_pls";
    protected readonly paramTypes = {
        n_components: "int",
        mode_j: "int",
        mode_k: "int",
    } as const;

    constructor(params: NPLSParams = {}) {
        super();
        this.params = { ...params };
    }

    predict(X: Matrix): Matrix {
        return this.predictMatrix(X);
    }
}
NativeEstimator.register("models.specialized.tensor_pls", NPLS);

/** Parameters of DIPLS; unset values take the native defaults. */
export interface DIPLSParams {
    /** Default 2. */
    n_components?: number;
    /** Default 1. */
    di_lambda?: number;
}

/** Native `models.transfer.di_pls` (regressor). Required fit inputs: target_domain. */
export class DIPLS extends NativeEstimator implements Regressor {
    readonly methodId = "models.transfer.di_pls";
    protected readonly paramTypes = {
        n_components: "int",
        di_lambda: "double",
    } as const;

    constructor(params: DIPLSParams = {}) {
        super();
        this.params = { ...params };
    }

    predict(X: Matrix): Matrix {
        return this.predictMatrix(X);
    }
}
NativeEstimator.register("models.transfer.di_pls", DIPLS);

/** Parameters of BiPLS; unset values take the native defaults. */
export interface BiPLSParams {
    /** Default 2. */
    n_components?: number;
    /** Default 10. */
    interval_width?: number;
    /** Default 2. */
    min_intervals?: number;
    /** Default 3. */
    cv?: number;
}

/** Native `selection.bipls` (selector). */
export class BiPLS extends NativeEstimator implements Selector {
    readonly methodId = "selection.bipls";
    protected readonly paramTypes = {
        n_components: "int",
        interval_width: "int",
        min_intervals: "int",
        cv: "int",
    } as const;

    constructor(params: BiPLSParams = {}) {
        super();
        this.params = { ...params };
    }

    transform(X: Matrix): Matrix {
        return this.transformMatrix(X);
    }

    selectedIndices(): number[] {
        return this.selectedIndexArray();
    }
}
NativeEstimator.register("selection.bipls", BiPLS);

/** Parameters of BVE; unset values take the native defaults. */
export interface BVEParams {
    /** Default 2. */
    n_components?: number;
    /** Default 10. */
    n_steps?: number;
    /** Default 0. */
    min_features?: number;
    /** Default 3. */
    cv?: number;
}

/** Native `selection.bve` (selector). */
export class BVE extends NativeEstimator implements Selector {
    readonly methodId = "selection.bve";
    protected readonly paramTypes = {
        n_components: "int",
        n_steps: "int",
        min_features: "int",
        cv: "int",
    } as const;

    constructor(params: BVEParams = {}) {
        super();
        this.params = { ...params };
    }

    transform(X: Matrix): Matrix {
        return this.transformMatrix(X);
    }

    selectedIndices(): number[] {
        return this.selectedIndexArray();
    }
}
NativeEstimator.register("selection.bve", BVE);

/** Parameters of CARS; unset values take the native defaults. */
export interface CARSParams {
    /** Default 2. */
    n_components?: number;
    /** Default 50. */
    n_iterations?: number;
    /** Default 0. */
    min_features?: number;
    /** Default 3. */
    cv?: number;
}

/** Native `selection.cars` (selector). */
export class CARS extends NativeEstimator implements Selector {
    readonly methodId = "selection.cars";
    protected readonly paramTypes = {
        n_components: "int",
        n_iterations: "int",
        min_features: "int",
        cv: "int",
    } as const;

    constructor(params: CARSParams = {}) {
        super();
        this.params = { ...params };
    }

    transform(X: Matrix): Matrix {
        return this.transformMatrix(X);
    }

    selectedIndices(): number[] {
        return this.selectedIndexArray();
    }
}
NativeEstimator.register("selection.cars", CARS);

/** Parameters of EMCUVE; unset values take the native defaults. */
export interface EMCUVEParams {
    /** Default 2. */
    n_components?: number;
    /** Default 50. */
    noise_features?: number;
    /** Default 0. */
    noise_seed?: number;
    /** Default 10. */
    n_ensembles?: number;
    /** Default 0.5. */
    vote_threshold?: number;
    /** Default 3. */
    cv?: number;
}

/** Native `selection.emcuve` (selector). */
export class EMCUVE extends NativeEstimator implements Selector {
    readonly methodId = "selection.emcuve";
    protected readonly paramTypes = {
        n_components: "int",
        noise_features: "int",
        noise_seed: "int",
        n_ensembles: "int",
        vote_threshold: "double",
        cv: "int",
    } as const;

    constructor(params: EMCUVEParams = {}) {
        super();
        this.params = { ...params };
    }

    transform(X: Matrix): Matrix {
        return this.transformMatrix(X);
    }

    selectedIndices(): number[] {
        return this.selectedIndexArray();
    }
}
NativeEstimator.register("selection.emcuve", EMCUVE);

/** Parameters of GA; unset values take the native defaults. */
export interface GAParams {
    /** Default 2. */
    n_components?: number;
    /** Default 30. */
    n_generations?: number;
    /** Default 40. */
    population_size?: number;
    /** Default 0. */
    min_features?: number;
    /** Default 0. */
    max_features?: number;
    /** Default 0.05. */
    mutation_rate?: number;
    /** Default 3. */
    cv?: number;
    /** Default 0. */
    seed?: number;
}

/** Native `selection.ga` (selector). */
export class GA extends NativeEstimator implements Selector {
    readonly methodId = "selection.ga";
    protected readonly paramTypes = {
        n_components: "int",
        n_generations: "int",
        population_size: "int",
        min_features: "int",
        max_features: "int",
        mutation_rate: "double",
        cv: "int",
        seed: "int",
    } as const;

    constructor(params: GAParams = {}) {
        super();
        this.params = { ...params };
    }

    transform(X: Matrix): Matrix {
        return this.transformMatrix(X);
    }

    selectedIndices(): number[] {
        return this.selectedIndexArray();
    }
}
NativeEstimator.register("selection.ga", GA);

/** Parameters of IPW; unset values take the native defaults. */
export interface IPWParams {
    /** Required. */
    top_k?: number;
    /** Default 2. */
    n_components?: number;
    /** Default 20. */
    n_iterations?: number;
    /** Default 0.5. */
    damping?: number;
    /** Default 1e-06. */
    weight_floor?: number;
    /** Default 3. */
    cv?: number;
}

/** Native `selection.ipw` (selector). */
export class IPW extends NativeEstimator implements Selector {
    readonly methodId = "selection.ipw";
    protected readonly paramTypes = {
        top_k: "int",
        n_components: "int",
        n_iterations: "int",
        damping: "double",
        weight_floor: "double",
        cv: "int",
    } as const;

    constructor(params: IPWParams = {}) {
        super();
        this.params = { ...params };
    }

    transform(X: Matrix): Matrix {
        return this.transformMatrix(X);
    }

    selectedIndices(): number[] {
        return this.selectedIndexArray();
    }
}
NativeEstimator.register("selection.ipw", IPW);

/** Parameters of IRF; unset values take the native defaults. */
export interface IRFParams {
    /** Required. */
    top_k?: number;
    /** Default 2. */
    n_components?: number;
    /** Default 100. */
    n_iterations?: number;
    /** Default 5. */
    window_size?: number;
    /** Default 5. */
    initial_intervals?: number;
    /** Default 3. */
    cv?: number;
    /** Default 0. */
    seed?: number;
}

/** Native `selection.irf` (selector). */
export class IRF extends NativeEstimator implements Selector {
    readonly methodId = "selection.irf";
    protected readonly paramTypes = {
        top_k: "int",
        n_components: "int",
        n_iterations: "int",
        window_size: "int",
        initial_intervals: "int",
        cv: "int",
        seed: "int",
    } as const;

    constructor(params: IRFParams = {}) {
        super();
        this.params = { ...params };
    }

    transform(X: Matrix): Matrix {
        return this.transformMatrix(X);
    }

    selectedIndices(): number[] {
        return this.selectedIndexArray();
    }
}
NativeEstimator.register("selection.irf", IRF);

/** Parameters of IRIV; unset values take the native defaults. */
export interface IRIVParams {
    /** Default 2. */
    n_components?: number;
    /** Default 5. */
    max_rounds?: number;
    /** Default 5. */
    cv?: number;
    /** Default 0. */
    seed?: number;
}

/** Native `selection.iriv` (selector). */
export class IRIV extends NativeEstimator implements Selector {
    readonly methodId = "selection.iriv";
    protected readonly paramTypes = {
        n_components: "int",
        max_rounds: "int",
        cv: "int",
        seed: "int",
    } as const;

    constructor(params: IRIVParams = {}) {
        super();
        this.params = { ...params };
    }

    transform(X: Matrix): Matrix {
        return this.transformMatrix(X);
    }

    selectedIndices(): number[] {
        return this.selectedIndexArray();
    }
}
NativeEstimator.register("selection.iriv", IRIV);

/** Parameters of PSO; unset values take the native defaults. */
export interface PSOParams {
    /** Default 2. */
    n_components?: number;
    /** Default 30. */
    n_swarm?: number;
    /** Default 50. */
    n_iterations?: number;
    /** Default 0.729. */
    w?: number;
    /** Default 1.494. */
    c1?: number;
    /** Default 1.494. */
    c2?: number;
    /** Default 4. */
    v_max?: number;
    /** Default 3. */
    cv?: number;
    /** Default 0. */
    seed?: number;
}

/** Native `selection.pso` (selector). */
export class PSO extends NativeEstimator implements Selector {
    readonly methodId = "selection.pso";
    protected readonly paramTypes = {
        n_components: "int",
        n_swarm: "int",
        n_iterations: "int",
        w: "double",
        c1: "double",
        c2: "double",
        v_max: "double",
        cv: "int",
        seed: "int",
    } as const;

    constructor(params: PSOParams = {}) {
        super();
        this.params = { ...params };
    }

    transform(X: Matrix): Matrix {
        return this.transformMatrix(X);
    }

    selectedIndices(): number[] {
        return this.selectedIndexArray();
    }
}
NativeEstimator.register("selection.pso", PSO);

/** Parameters of RandomFrog; unset values take the native defaults. */
export interface RandomFrogParams {
    /** Required. */
    top_k?: number;
    /** Default 2. */
    n_components?: number;
    /** Default 100. */
    n_iterations?: number;
    /** Default 20. */
    initial_size?: number;
    /** Default 0. */
    min_size?: number;
    /** Default 0. */
    max_size?: number;
    /** Default 3. */
    cv?: number;
    /** Default 0. */
    seed?: number;
}

/** Native `selection.random_frog` (selector). */
export class RandomFrog extends NativeEstimator implements Selector {
    readonly methodId = "selection.random_frog";
    protected readonly paramTypes = {
        top_k: "int",
        n_components: "int",
        n_iterations: "int",
        initial_size: "int",
        min_size: "int",
        max_size: "int",
        cv: "int",
        seed: "int",
    } as const;

    constructor(params: RandomFrogParams = {}) {
        super();
        this.params = { ...params };
    }

    transform(X: Matrix): Matrix {
        return this.transformMatrix(X);
    }

    selectedIndices(): number[] {
        return this.selectedIndexArray();
    }
}
NativeEstimator.register("selection.random_frog", RandomFrog);

/** Parameters of Randomization; unset values take the native defaults. */
export interface RandomizationParams {
    /** Default 2. */
    n_components?: number;
    /** Default 200. */
    n_permutations?: number;
    /** Default 0. */
    randomization_seed?: number;
    /** Default 0.05. */
    alpha?: number;
}

/** Native `selection.randomization` (selector). */
export class Randomization extends NativeEstimator implements Selector {
    readonly methodId = "selection.randomization";
    protected readonly paramTypes = {
        n_components: "int",
        n_permutations: "int",
        randomization_seed: "int",
        alpha: "double",
    } as const;

    constructor(params: RandomizationParams = {}) {
        super();
        this.params = { ...params };
    }

    transform(X: Matrix): Matrix {
        return this.transformMatrix(X);
    }

    selectedIndices(): number[] {
        return this.selectedIndexArray();
    }
}
NativeEstimator.register("selection.randomization", Randomization);

/** Parameters of REP; unset values take the native defaults. */
export interface REPParams {
    /** Default 2. */
    n_components?: number;
    /** Default 10. */
    n_steps?: number;
    /** Default 0. */
    min_features?: number;
    /** Default 1. */
    remove_count?: number;
    /** Default 3. */
    cv?: number;
}

/** Native `selection.rep` (selector). */
export class REP extends NativeEstimator implements Selector {
    readonly methodId = "selection.rep";
    protected readonly paramTypes = {
        n_components: "int",
        n_steps: "int",
        min_features: "int",
        remove_count: "int",
        cv: "int",
    } as const;

    constructor(params: REPParams = {}) {
        super();
        this.params = { ...params };
    }

    transform(X: Matrix): Matrix {
        return this.transformMatrix(X);
    }

    selectedIndices(): number[] {
        return this.selectedIndexArray();
    }
}
NativeEstimator.register("selection.rep", REP);

/** Parameters of SCARS; unset values take the native defaults. */
export interface SCARSParams {
    /** Default 2. */
    n_components?: number;
    /** Default 50. */
    n_iterations?: number;
    /** Default 0. */
    min_features?: number;
    /** Default 0.8. */
    sample_fraction?: number;
    /** Default 3. */
    cv?: number;
    /** Default 0. */
    seed?: number;
}

/** Native `selection.scars` (selector). */
export class SCARS extends NativeEstimator implements Selector {
    readonly methodId = "selection.scars";
    protected readonly paramTypes = {
        n_components: "int",
        n_iterations: "int",
        min_features: "int",
        sample_fraction: "double",
        cv: "int",
        seed: "int",
    } as const;

    constructor(params: SCARSParams = {}) {
        super();
        this.params = { ...params };
    }

    transform(X: Matrix): Matrix {
        return this.transformMatrix(X);
    }

    selectedIndices(): number[] {
        return this.selectedIndexArray();
    }
}
NativeEstimator.register("selection.scars", SCARS);

/** Parameters of Shaving; unset values take the native defaults. */
export interface ShavingParams {
    /** Default 2. */
    n_components?: number;
    /** Default 10. */
    n_steps?: number;
    /** Default 0. */
    min_features?: number;
    /** Default 0.2. */
    shave_fraction?: number;
    /** Default 3. */
    cv?: number;
}

/** Native `selection.shaving` (selector). */
export class Shaving extends NativeEstimator implements Selector {
    readonly methodId = "selection.shaving";
    protected readonly paramTypes = {
        n_components: "int",
        n_steps: "int",
        min_features: "int",
        shave_fraction: "double",
        cv: "int",
    } as const;

    constructor(params: ShavingParams = {}) {
        super();
        this.params = { ...params };
    }

    transform(X: Matrix): Matrix {
        return this.transformMatrix(X);
    }

    selectedIndices(): number[] {
        return this.selectedIndexArray();
    }
}
NativeEstimator.register("selection.shaving", Shaving);

/** Parameters of SiPLS; unset values take the native defaults. */
export interface SiPLSParams {
    /** Default 2. */
    n_components?: number;
    /** Default 10. */
    interval_width?: number;
    /** Default 2. */
    combination_size?: number;
    /** Default 3. */
    cv?: number;
}

/** Native `selection.sipls` (selector). */
export class SiPLS extends NativeEstimator implements Selector {
    readonly methodId = "selection.sipls";
    protected readonly paramTypes = {
        n_components: "int",
        interval_width: "int",
        combination_size: "int",
        cv: "int",
    } as const;

    constructor(params: SiPLSParams = {}) {
        super();
        this.params = { ...params };
    }

    transform(X: Matrix): Matrix {
        return this.transformMatrix(X);
    }

    selectedIndices(): number[] {
        return this.selectedIndexArray();
    }
}
NativeEstimator.register("selection.sipls", SiPLS);

/** Parameters of SPA; unset values take the native defaults. */
export interface SPAParams {
    /** Required. */
    top_k?: number;
    /** Default 2. */
    n_components?: number;
}

/** Native `selection.spa` (selector). */
export class SPA extends NativeEstimator implements Selector {
    readonly methodId = "selection.spa";
    protected readonly paramTypes = {
        top_k: "int",
        n_components: "int",
    } as const;

    constructor(params: SPAParams = {}) {
        super();
        this.params = { ...params };
    }

    transform(X: Matrix): Matrix {
        return this.transformMatrix(X);
    }

    selectedIndices(): number[] {
        return this.selectedIndexArray();
    }
}
NativeEstimator.register("selection.spa", SPA);

/** Parameters of ST; unset values take the native defaults. */
export interface STParams {
    /** Required. */
    thresholds?: number[];
    /** Default 2. */
    n_components?: number;
    /** Default 0. */
    min_selected?: number;
    /** Default 3. */
    cv?: number;
}

/** Native `selection.st` (selector). */
export class ST extends NativeEstimator implements Selector {
    readonly methodId = "selection.st";
    protected readonly paramTypes = {
        thresholds: "double_array",
        n_components: "int",
        min_selected: "int",
        cv: "int",
    } as const;

    constructor(params: STParams = {}) {
        super();
        this.params = { ...params };
    }

    transform(X: Matrix): Matrix {
        return this.transformMatrix(X);
    }

    selectedIndices(): number[] {
        return this.selectedIndexArray();
    }
}
NativeEstimator.register("selection.st", ST);

/** Parameters of Stability; unset values take the native defaults. */
export interface StabilityParams {
    /** Required. */
    top_k?: number;
    /** Default 2. */
    n_components?: number;
    /** Default 3. */
    cv?: number;
}

/** Native `selection.stability` (selector). */
export class Stability extends NativeEstimator implements Selector {
    readonly methodId = "selection.stability";
    protected readonly paramTypes = {
        top_k: "int",
        n_components: "int",
        cv: "int",
    } as const;

    constructor(params: StabilityParams = {}) {
        super();
        this.params = { ...params };
    }

    transform(X: Matrix): Matrix {
        return this.transformMatrix(X);
    }

    selectedIndices(): number[] {
        return this.selectedIndexArray();
    }
}
NativeEstimator.register("selection.stability", Stability);

/** Parameters of T2; unset values take the native defaults. */
export interface T2Params {
    /** Required. */
    alpha_thresholds?: number[];
    /** Default 2. */
    n_components?: number;
    /** Default 0. */
    min_selected?: number;
    /** Default 3. */
    cv?: number;
}

/** Native `selection.t2` (selector). */
export class T2 extends NativeEstimator implements Selector {
    readonly methodId = "selection.t2";
    protected readonly paramTypes = {
        alpha_thresholds: "double_array",
        n_components: "int",
        min_selected: "int",
        cv: "int",
    } as const;

    constructor(params: T2Params = {}) {
        super();
        this.params = { ...params };
    }

    transform(X: Matrix): Matrix {
        return this.transformMatrix(X);
    }

    selectedIndices(): number[] {
        return this.selectedIndexArray();
    }
}
NativeEstimator.register("selection.t2", T2);

/** Parameters of UVE; unset values take the native defaults. */
export interface UVEParams {
    /** Default 2. */
    n_components?: number;
    /** Default 50. */
    noise_features?: number;
    /** Default 0. */
    noise_seed?: number;
    /** Default -1. */
    min_features?: number;
    /** Default 3. */
    cv?: number;
}

/** Native `selection.uve` (selector). */
export class UVE extends NativeEstimator implements Selector {
    readonly methodId = "selection.uve";
    protected readonly paramTypes = {
        n_components: "int",
        noise_features: "int",
        noise_seed: "int",
        min_features: "int",
        cv: "int",
    } as const;

    constructor(params: UVEParams = {}) {
        super();
        this.params = { ...params };
    }

    transform(X: Matrix): Matrix {
        return this.transformMatrix(X);
    }

    selectedIndices(): number[] {
        return this.selectedIndexArray();
    }
}
NativeEstimator.register("selection.uve", UVE);

/** Parameters of VariableSelect; unset values take the native defaults. */
export interface VariableSelectParams {
    /** Required. */
    top_k?: number;
    /** Default 2. */
    n_components?: number;
    /** Default "vip". */
    rank_method?: "vip" | "coefficient" | "selectivity_ratio";
}

/** Native `selection.variable_select` (selector). */
export class VariableSelect extends NativeEstimator implements Selector {
    readonly methodId = "selection.variable_select";
    protected readonly paramTypes = {
        top_k: "int",
        n_components: "int",
        rank_method: "enum",
    } as const;

    constructor(params: VariableSelectParams = {}) {
        super();
        this.params = { ...params };
    }

    transform(X: Matrix): Matrix {
        return this.transformMatrix(X);
    }

    selectedIndices(): number[] {
        return this.selectedIndexArray();
    }
}
NativeEstimator.register("selection.variable_select", VariableSelect);

/** Parameters of VIPSPA; unset values take the native defaults. */
export interface VIPSPAParams {
    /** Required. */
    top_k?: number;
    /** Default 2. */
    n_components?: number;
    /** Default 0.3. */
    vip_threshold?: number;
}

/** Native `selection.vip_spa` (selector). */
export class VIPSPA extends NativeEstimator implements Selector {
    readonly methodId = "selection.vip_spa";
    protected readonly paramTypes = {
        top_k: "int",
        n_components: "int",
        vip_threshold: "double",
    } as const;

    constructor(params: VIPSPAParams = {}) {
        super();
        this.params = { ...params };
    }

    transform(X: Matrix): Matrix {
        return this.transformMatrix(X);
    }

    selectedIndices(): number[] {
        return this.selectedIndexArray();
    }
}
NativeEstimator.register("selection.vip_spa", VIPSPA);

/** Parameters of VISSA; unset values take the native defaults. */
export interface VISSAParams {
    /** Default 2. */
    n_components?: number;
    /** Default 10. */
    n_iterations?: number;
    /** Default 60. */
    n_submodels?: number;
    /** Default 0.1. */
    ratio_kept?: number;
    /** Default 0.5. */
    threshold?: number;
    /** Default 0.05. */
    floor_probability?: number;
    /** Default 3. */
    cv?: number;
    /** Default 0. */
    seed?: number;
}

/** Native `selection.vissa` (selector). */
export class VISSA extends NativeEstimator implements Selector {
    readonly methodId = "selection.vissa";
    protected readonly paramTypes = {
        n_components: "int",
        n_iterations: "int",
        n_submodels: "int",
        ratio_kept: "double",
        threshold: "double",
        floor_probability: "double",
        cv: "int",
        seed: "int",
    } as const;

    constructor(params: VISSAParams = {}) {
        super();
        this.params = { ...params };
    }

    transform(X: Matrix): Matrix {
        return this.transformMatrix(X);
    }

    selectedIndices(): number[] {
        return this.selectedIndexArray();
    }
}
NativeEstimator.register("selection.vissa", VISSA);

/** Parameters of WVC; unset values take the native defaults. */
export interface WVCParams {
    /** Required. */
    top_k?: number;
    /** Default 2. */
    n_components?: number;
    /** Default true. */
    normalize?: boolean;
}

/** Native `selection.wvc` (selector). */
export class WVC extends NativeEstimator implements Selector {
    readonly methodId = "selection.wvc";
    protected readonly paramTypes = {
        top_k: "int",
        n_components: "int",
        normalize: "bool",
    } as const;

    constructor(params: WVCParams = {}) {
        super();
        this.params = { ...params };
    }

    transform(X: Matrix): Matrix {
        return this.transformMatrix(X);
    }

    selectedIndices(): number[] {
        return this.selectedIndexArray();
    }
}
NativeEstimator.register("selection.wvc", WVC);

/** Parameters of WVCThreshold; unset values take the native defaults. */
export interface WVCThresholdParams {
    /** Default 2. */
    n_components?: number;
    /** Default true. */
    normalize?: boolean;
    /** Default 0. */
    score_threshold?: number;
    /** Default 1. */
    threshold_factor?: number;
    /** Default 0. */
    min_selected?: number;
}

/** Native `selection.wvc_threshold` (selector). */
export class WVCThreshold extends NativeEstimator implements Selector {
    readonly methodId = "selection.wvc_threshold";
    protected readonly paramTypes = {
        n_components: "int",
        normalize: "bool",
        score_threshold: "double",
        threshold_factor: "double",
        min_selected: "int",
    } as const;

    constructor(params: WVCThresholdParams = {}) {
        super();
        this.params = { ...params };
    }

    transform(X: Matrix): Matrix {
        return this.transformMatrix(X);
    }

    selectedIndices(): number[] {
        return this.selectedIndexArray();
    }
}
NativeEstimator.register("selection.wvc_threshold", WVCThreshold);
