// SPDX-License-Identifier: CECILL-2.1
// Generated by scripts/generate_js_roles.py from `n4m_cli --manifest-json`. Do not edit.
// Native ABI 2.13.0.

import {
    type Classifier,
    NativeEstimator,
    type ProbabilisticClassifier,
    type Regressor,
    type Selector,
    type Transformer,
} from "./estimatorRoles.js";
import type { Matrix } from "./types.js";

/** Parameters of PLSLDA; unset values take the native defaults. */
export interface PLSLDAParams {
    /** Default 2. */
    n_components?: number;
}

/** Native `models.classification.pls_lda` (classifier). Required fit inputs: labels. */
export class PLSLDA extends NativeEstimator implements Classifier {
    readonly methodId = "models.classification.pls_lda";
    protected readonly paramTypes = {
        n_components: "int",
    } as const;
    protected readonly labelTarget = true;

    constructor(params: PLSLDAParams = {}) {
        super();
        this.params = { ...params };
    }

    decisionFunction(X: Matrix): Matrix {
        return this.decisionMatrix(X);
    }

    predictLabels(X: Matrix): number[] {
        return this.labelArray(X);
    }

    classes(): number[] {
        return this.classArray();
    }
}
NativeEstimator.register("models.classification.pls_lda", PLSLDA);

/** Parameters of PLSLogistic; unset values take the native defaults. */
export interface PLSLogisticParams {
    /** Default 2. */
    n_components?: number;
    /** Default 500. */
    max_iter?: number;
}

/** Native `models.classification.pls_logistic` (classifier). Required fit inputs: labels. */
export class PLSLogistic extends NativeEstimator implements ProbabilisticClassifier {
    readonly methodId = "models.classification.pls_logistic";
    protected readonly paramTypes = {
        n_components: "int",
        max_iter: "int",
    } as const;
    protected readonly labelTarget = true;

    constructor(params: PLSLogisticParams = {}) {
        super();
        this.params = { ...params };
    }

    decisionFunction(X: Matrix): Matrix {
        return this.decisionMatrix(X);
    }

    predictLabels(X: Matrix): number[] {
        return this.labelArray(X);
    }

    classes(): number[] {
        return this.classArray();
    }

    predictProba(X: Matrix): Matrix {
        return this.probaMatrix(X);
    }
}
NativeEstimator.register("models.classification.pls_logistic", PLSLogistic);

/** Parameters of PLSQDA; unset values take the native defaults. */
export interface PLSQDAParams {
    /** Default 2. */
    n_components?: number;
}

/** Native `models.classification.pls_qda` (classifier). Required fit inputs: labels. */
export class PLSQDA extends NativeEstimator implements ProbabilisticClassifier {
    readonly methodId = "models.classification.pls_qda";
    protected readonly paramTypes = {
        n_components: "int",
    } as const;
    protected readonly labelTarget = true;

    constructor(params: PLSQDAParams = {}) {
        super();
        this.params = { ...params };
    }

    decisionFunction(X: Matrix): Matrix {
        return this.decisionMatrix(X);
    }

    predictLabels(X: Matrix): number[] {
        return this.labelArray(X);
    }

    classes(): number[] {
        return this.classArray();
    }

    predictProba(X: Matrix): Matrix {
        return this.probaMatrix(X);
    }
}
NativeEstimator.register("models.classification.pls_qda", PLSQDA);

/** Parameters of BaggingPLS; unset values take the native defaults. */
export interface BaggingPLSParams {
    /** Default 2. */
    n_components?: number;
    /** Default 50. */
    n_estimators?: number;
    /** Default 0. */
    seed?: number;
}

/** Native `models.ensembles.bagging_pls` (regressor). */
export class BaggingPLS extends NativeEstimator implements Regressor {
    readonly methodId = "models.ensembles.bagging_pls";
    protected readonly paramTypes = {
        n_components: "int",
        n_estimators: "int",
        seed: "int",
    } as const;

    constructor(params: BaggingPLSParams = {}) {
        super();
        this.params = { ...params };
    }

    predict(X: Matrix): Matrix {
        return this.predictMatrix(X);
    }
}
NativeEstimator.register("models.ensembles.bagging_pls", BaggingPLS);

/** Parameters of BoostingPLS; unset values take the native defaults. */
export interface BoostingPLSParams {
    /** Default 2. */
    n_components?: number;
    /** Default 50. */
    n_estimators?: number;
    /** Default 0.1. */
    learning_rate?: number;
}

/** Native `models.ensembles.boosting_pls` (regressor). */
export class BoostingPLS extends NativeEstimator implements Regressor {
    readonly methodId = "models.ensembles.boosting_pls";
    protected readonly paramTypes = {
        n_components: "int",
        n_estimators: "int",
        learning_rate: "double",
    } as const;

    constructor(params: BoostingPLSParams = {}) {
        super();
        this.params = { ...params };
    }

    predict(X: Matrix): Matrix {
        return this.predictMatrix(X);
    }
}
NativeEstimator.register("models.ensembles.boosting_pls", BoostingPLS);

/** Parameters of RandomSubspacePLS; unset values take the native defaults. */
export interface RandomSubspacePLSParams {
    /** Default 2. */
    n_components?: number;
    /** Default 50. */
    n_estimators?: number;
    /** Default 10. */
    features_per_subspace?: number;
    /** Default 0. */
    seed?: number;
}

/** Native `models.ensembles.random_subspace_pls` (regressor). */
export class RandomSubspacePLS extends NativeEstimator implements Regressor {
    readonly methodId = "models.ensembles.random_subspace_pls";
    protected readonly paramTypes = {
        n_components: "int",
        n_estimators: "int",
        features_per_subspace: "int",
        seed: "int",
    } as const;

    constructor(params: RandomSubspacePLSParams = {}) {
        super();
        this.params = { ...params };
    }

    predict(X: Matrix): Matrix {
        return this.predictMatrix(X);
    }
}
NativeEstimator.register("models.ensembles.random_subspace_pls", RandomSubspacePLS);

/** Parameters of MBPLS; unset values take the native defaults. */
export interface MBPLSParams {
    /** Default 2. */
    n_components?: number;
}

/** Native `models.multiblock.mb_pls` (regressor). Required fit inputs: blocks. */
export class MBPLS extends NativeEstimator implements Regressor {
    readonly methodId = "models.multiblock.mb_pls";
    protected readonly paramTypes = {
        n_components: "int",
    } as const;

    constructor(params: MBPLSParams = {}) {
        super();
        this.params = { ...params };
    }

    predict(X: Matrix): Matrix {
        return this.predictMatrix(X);
    }
}
NativeEstimator.register("models.multiblock.mb_pls", MBPLS);

/** Parameters of MIRPLS; unset values take the native defaults. */
export interface MIRPLSParams {
    /** Default 2. */
    n_components?: number;
}

/** Native `models.multiblock.mir_pls` (regressor). */
export class MIRPLS extends NativeEstimator implements Regressor {
    readonly methodId = "models.multiblock.mir_pls";
    protected readonly paramTypes = {
        n_components: "int",
    } as const;

    constructor(params: MIRPLSParams = {}) {
        super();
        this.params = { ...params };
    }

    predict(X: Matrix): Matrix {
        return this.predictMatrix(X);
    }
}
NativeEstimator.register("models.multiblock.mir_pls", MIRPLS);

/** Parameters of O2PLS; unset values take the native defaults. */
export interface O2PLSParams {
    /** Default 2. */
    n_predictive?: number;
    /** Default 1. */
    n_x_orthogonal?: number;
    /** Default 1. */
    n_y_orthogonal?: number;
}

/** Native `models.multiblock.o2pls` (regressor). */
export class O2PLS extends NativeEstimator implements Regressor {
    readonly methodId = "models.multiblock.o2pls";
    protected readonly paramTypes = {
        n_predictive: "int",
        n_x_orthogonal: "int",
        n_y_orthogonal: "int",
    } as const;

    constructor(params: O2PLSParams = {}) {
        super();
        this.params = { ...params };
    }

    predict(X: Matrix): Matrix {
        return this.predictMatrix(X);
    }
}
NativeEstimator.register("models.multiblock.o2pls", O2PLS);

/** Parameters of CPPLS; unset values take the native defaults. */
export interface CPPLSParams {
    /** Default 2. */
    n_components?: number;
    /** Default 0.5. */
    gamma?: number;
}

/** Native `models.pls.cppls` (regressor). */
export class CPPLS extends NativeEstimator implements Regressor {
    readonly methodId = "models.pls.cppls";
    protected readonly paramTypes = {
        n_components: "int",
        gamma: "double",
    } as const;

    constructor(params: CPPLSParams = {}) {
        super();
        this.params = { ...params };
    }

    predict(X: Matrix): Matrix {
        return this.predictMatrix(X);
    }
}
NativeEstimator.register("models.pls.cppls", CPPLS);

/** Parameters of PCR; unset values take the native defaults. */
export interface PCRParams {
    /** Default 2. */
    n_components?: number;
    /** Default true. */
    center_x?: boolean;
    /** Default true. */
    scale_x?: boolean;
    /** Default true. */
    center_y?: boolean;
    /** Default false. */
    scale_y?: boolean;
}

/** Native `models.pls.pcr` (transformer, regressor). */
export class PCR extends NativeEstimator implements Regressor, Transformer {
    readonly methodId = "models.pls.pcr";
    protected readonly paramTypes = {
        n_components: "int",
        center_x: "bool",
        scale_x: "bool",
        center_y: "bool",
        scale_y: "bool",
    } as const;

    constructor(params: PCRParams = {}) {
        super();
        this.params = { ...params };
    }

    predict(X: Matrix): Matrix {
        return this.predictMatrix(X);
    }

    transform(X: Matrix): Matrix {
        return this.transformMatrix(X);
    }
}
NativeEstimator.register("models.pls.pcr", PCR);

/** Parameters of SimplePLS; unset values take the native defaults. */
export interface SimplePLSParams {
    /** Default 2. */
    n_components?: number;
}

/** Native `models.pls.pls_fit_simple` (transformer, regressor). */
export class SimplePLS extends NativeEstimator implements Regressor, Transformer {
    readonly methodId = "models.pls.pls_fit_simple";
    protected readonly paramTypes = {
        n_components: "int",
    } as const;

    constructor(params: SimplePLSParams = {}) {
        super();
        this.params = { ...params };
    }

    predict(X: Matrix): Matrix {
        return this.predictMatrix(X);
    }

    transform(X: Matrix): Matrix {
        return this.transformMatrix(X);
    }
}
NativeEstimator.register("models.pls.pls_fit_simple", SimplePLS);

/** Parameters of PLSRegression; unset values take the native defaults. */
export interface PLSRegressionParams {
    /** Default 2. */
    n_components?: number;
    /** Default "nipals". */
    solver?: "nipals" | "simpls" | "orthogonal_scores" | "kernel_algorithm" | "wide_kernel" | "svd" | "power" | "randomized_svd";
    /** Default true. */
    center_x?: boolean;
    /** Default true. */
    scale_x?: boolean;
    /** Default true. */
    center_y?: boolean;
    /** Default true. */
    scale_y?: boolean;
}

/** Native `models.pls.pls_regression` (transformer, regressor). */
export class PLSRegression extends NativeEstimator implements Regressor, Transformer {
    readonly methodId = "models.pls.pls_regression";
    protected readonly paramTypes = {
        n_components: "int",
        solver: "enum",
        center_x: "bool",
        scale_x: "bool",
        center_y: "bool",
        scale_y: "bool",
    } as const;

    constructor(params: PLSRegressionParams = {}) {
        super();
        this.params = { ...params };
    }

    predict(X: Matrix): Matrix {
        return this.predictMatrix(X);
    }

    transform(X: Matrix): Matrix {
        return this.transformMatrix(X);
    }
}
NativeEstimator.register("models.pls.pls_regression", PLSRegression);

/** Parameters of ContinuumRegression; unset values take the native defaults. */
export interface ContinuumRegressionParams {
    /** Default 2. */
    n_components?: number;
    /** Default 0.5. */
    tau?: number;
}

/** Native `models.regularized.continuum_regression` (regressor). */
export class ContinuumRegression extends NativeEstimator implements Regressor {
    readonly methodId = "models.regularized.continuum_regression";
    protected readonly paramTypes = {
        n_components: "int",
        tau: "double",
    } as const;

    constructor(params: ContinuumRegressionParams = {}) {
        super();
        this.params = { ...params };
    }

    predict(X: Matrix): Matrix {
        return this.predictMatrix(X);
    }
}
NativeEstimator.register("models.regularized.continuum_regression", ContinuumRegression);

/** Parameters of Ridge; unset values take the native defaults. */
export interface RidgeParams {
    /** Default 1. */
    alpha?: number;
    /** Default true. */
    center_x?: boolean;
    /** Default true. */
    scale_x?: boolean;
    /** Default true. */
    center_y?: boolean;
}

/** Native `models.regularized.ridge` (regressor). */
export class Ridge extends NativeEstimator implements Regressor {
    readonly methodId = "models.regularized.ridge";
    protected readonly paramTypes = {
        alpha: "double",
        center_x: "bool",
        scale_x: "bool",
        center_y: "bool",
    } as const;

    constructor(params: RidgeParams = {}) {
        super();
        this.params = { ...params };
    }

    predict(X: Matrix): Matrix {
        return this.predictMatrix(X);
    }
}
NativeEstimator.register("models.regularized.ridge", Ridge);

/** Parameters of RidgePLS; unset values take the native defaults. */
export interface RidgePLSParams {
    /** Default 2. */
    n_components?: number;
    /** Default 0.1. */
    ridge_lambda?: number;
    /** Default true. */
    center_x?: boolean;
    /** Default true. */
    scale_x?: boolean;
    /** Default true. */
    center_y?: boolean;
    /** Default true. */
    scale_y?: boolean;
}

/** Native `models.regularized.ridge_pls` (regressor). */
export class RidgePLS extends NativeEstimator implements Regressor {
    readonly methodId = "models.regularized.ridge_pls";
    protected readonly paramTypes = {
        n_components: "int",
        ridge_lambda: "double",
        center_x: "bool",
        scale_x: "bool",
        center_y: "bool",
        scale_y: "bool",
    } as const;

    constructor(params: RidgePLSParams = {}) {
        super();
        this.params = { ...params };
    }

    predict(X: Matrix): Matrix {
        return this.predictMatrix(X);
    }
}
NativeEstimator.register("models.regularized.ridge_pls", RidgePLS);

/** Parameters of RobustPLS; unset values take the native defaults. */
export interface RobustPLSParams {
    /** Default 2. */
    n_components?: number;
    /** Default 1.345. */
    huber_k?: number;
    /** Default 5. */
    max_irls_iter?: number;
    /** Default true. */
    center_x?: boolean;
    /** Default true. */
    scale_x?: boolean;
    /** Default true. */
    center_y?: boolean;
    /** Default true. */
    scale_y?: boolean;
}

/** Native `models.regularized.robust_pls` (regressor). */
export class RobustPLS extends NativeEstimator implements Regressor {
    readonly methodId = "models.regularized.robust_pls";
    protected readonly paramTypes = {
        n_components: "int",
        huber_k: "double",
        max_irls_iter: "int",
        center_x: "bool",
        scale_x: "bool",
        center_y: "bool",
        scale_y: "bool",
    } as const;

    constructor(params: RobustPLSParams = {}) {
        super();
        this.params = { ...params };
    }

    predict(X: Matrix): Matrix {
        return this.predictMatrix(X);
    }
}
NativeEstimator.register("models.regularized.robust_pls", RobustPLS);

/** Parameters of WeightedPLS; unset values take the native defaults. */
export interface WeightedPLSParams {
    /** Default 2. */
    n_components?: number;
    /** Default true. */
    center_x?: boolean;
    /** Default true. */
    scale_x?: boolean;
    /** Default true. */
    center_y?: boolean;
    /** Default true. */
    scale_y?: boolean;
}

/** Native `models.regularized.weighted_pls` (regressor). */
export class WeightedPLS extends NativeEstimator implements Regressor {
    readonly methodId = "models.regularized.weighted_pls";
    protected readonly paramTypes = {
        n_components: "int",
        center_x: "bool",
        scale_x: "bool",
        center_y: "bool",
        scale_y: "bool",
    } as const;

    constructor(params: WeightedPLSParams = {}) {
        super();
        this.params = { ...params };
    }

    predict(X: Matrix): Matrix {
        return this.predictMatrix(X);
    }
}
NativeEstimator.register("models.regularized.weighted_pls", WeightedPLS);

/** Parameters of FusedSparsePLS; unset values take the native defaults. */
export interface FusedSparsePLSParams {
    /** Default 2. */
    n_components?: number;
    /** Default 0.05. */
    l1_lambda?: number;
    /** Default 0.05. */
    fusion_lambda?: number;
}

/** Native `models.sparse.fused_sparse_pls` (regressor). */
export class FusedSparsePLS extends NativeEstimator implements Regressor {
    readonly methodId = "models.sparse.fused_sparse_pls";
    protected readonly paramTypes = {
        n_components: "int",
        l1_lambda: "double",
        fusion_lambda: "double",
    } as const;

    constructor(params: FusedSparsePLSParams = {}) {
        super();
        this.params = { ...params };
    }

    predict(X: Matrix): Matrix {
        return this.predictMatrix(X);
    }
}
NativeEstimator.register("models.sparse.fused_sparse_pls", FusedSparsePLS);

/** Parameters of GroupSparsePLS; unset values take the native defaults. */
export interface GroupSparsePLSParams {
    /** Default 2. */
    n_components?: number;
    /** Default 0.05. */
    group_lambda?: number;
}

/** Native `models.sparse.group_sparse_pls` (regressor). Required fit inputs: feature_groups. */
export class GroupSparsePLS extends NativeEstimator implements Regressor {
    readonly methodId = "models.sparse.group_sparse_pls";
    protected readonly paramTypes = {
        n_components: "int",
        group_lambda: "double",
    } as const;

    constructor(params: GroupSparsePLSParams = {}) {
        super();
        this.params = { ...params };
    }

    predict(X: Matrix): Matrix {
        return this.predictMatrix(X);
    }
}
NativeEstimator.register("models.sparse.group_sparse_pls", GroupSparsePLS);

/** Parameters of SparsePLSDA; unset values take the native defaults. */
export interface SparsePLSDAParams {
    /** Default 2. */
    n_components?: number;
    /** Default 0.05. */
    sparsity_lambda?: number;
}

/** Native `models.sparse.sparse_pls_da` (classifier). Required fit inputs: labels. */
export class SparsePLSDA extends NativeEstimator implements Classifier {
    readonly methodId = "models.sparse.sparse_pls_da";
    protected readonly paramTypes = {
        n_components: "int",
        sparsity_lambda: "double",
    } as const;
    protected readonly labelTarget = true;

    constructor(params: SparsePLSDAParams = {}) {
        super();
        this.params = { ...params };
    }

    decisionFunction(X: Matrix): Matrix {
        return this.decisionMatrix(X);
    }

    predictLabels(X: Matrix): number[] {
        return this.labelArray(X);
    }

    classes(): number[] {
        return this.classArray();
    }
}
NativeEstimator.register("models.sparse.sparse_pls_da", SparsePLSDA);

/** Parameters of SparseSIMPLS; unset values take the native defaults. */
export interface SparseSIMPLSParams {
    /** Default 2. */
    n_components?: number;
    /** Default 0.05. */
    sparsity_lambda?: number;
}

/** Native `models.sparse.sparse_simpls` (regressor). */
export class SparseSIMPLS extends NativeEstimator implements Regressor {
    readonly methodId = "models.sparse.sparse_simpls";
    protected readonly paramTypes = {
        n_components: "int",
        sparsity_lambda: "double",
    } as const;

    constructor(params: SparseSIMPLSParams = {}) {
        super();
        this.params = { ...params };
    }

    predict(X: Matrix): Matrix {
        return this.predictMatrix(X);
    }
}
NativeEstimator.register("models.sparse.sparse_simpls", SparseSIMPLS);

/** Parameters of ECR; unset values take the native defaults. */
export interface ECRParams {
    /** Default 2. */
    n_components?: number;
    /** Default 0.5. */
    alpha?: number;
}

/** Native `models.specialized.ecr` (regressor). */
export class ECR extends NativeEstimator implements Regressor {
    readonly methodId = "models.specialized.ecr";
    protected readonly paramTypes = {
        n_components: "int",
        alpha: "double",
    } as const;

    constructor(params: ECRParams = {}) {
        super();
        this.params = { ...params };
    }

    predict(X: Matrix): Matrix {
        return this.predictMatrix(X);
    }
}
NativeEstimator.register("models.specialized.ecr", ECR);

/** Parameters of NPLS; unset values take the native defaults. */
export interface NPLSParams {
    /** Default 2. */
    n_components?: number;
    /** Required. */
    mode_j?: number;
    /** Required. */
    mode_k?: number;
}

/** Native `models.specialized.tensor_pls` (regressor). */
export class NPLS extends NativeEstimator implements Regressor {
    readonly methodId = "models.specialized.tensor_pls";
    protected readonly paramTypes = {
        n_components: "int",
        mode_j: "int",
        mode_k: "int",
    } as const;

    constructor(params: NPLSParams = {}) {
        super();
        this.params = { ...params };
    }

    predict(X: Matrix): Matrix {
        return this.predictMatrix(X);
    }
}
NativeEstimator.register("models.specialized.tensor_pls", NPLS);

/** Parameters of DIPLS; unset values take the native defaults. */
export interface DIPLSParams {
    /** Default 2. */
    n_components?: number;
    /** Default 1. */
    di_lambda?: number;
}

/** Native `models.transfer.di_pls` (regressor). Required fit inputs: target_domain. */
export class DIPLS extends NativeEstimator implements Regressor {
    readonly methodId = "models.transfer.di_pls";
    protected readonly paramTypes = {
        n_components: "int",
        di_lambda: "double",
    } as const;

    constructor(params: DIPLSParams = {}) {
        super();
        this.params = { ...params };
    }

    predict(X: Matrix): Matrix {
        return this.predictMatrix(X);
    }
}
NativeEstimator.register("models.transfer.di_pls", DIPLS);

/** Parameters of CorrelationOptimizedWarping; unset values take the native defaults. */
export interface CorrelationOptimizedWarpingParams {
    /** Default []. */
    reference?: number[];
    /** Default 32. */
    interval_size?: number;
    /** Default 5. */
    max_shift?: number;
}

/** Native `preprocessing.alignment.cow_align` (transformer). */
export class CorrelationOptimizedWarping extends NativeEstimator implements Transformer {
    readonly methodId = "preprocessing.alignment.cow_align";
    protected readonly paramTypes = {
        reference: "double_array",
        interval_size: "int",
        max_shift: "int",
    } as const;

    constructor(params: CorrelationOptimizedWarpingParams = {}) {
        super();
        this.params = { ...params };
    }

    transform(X: Matrix): Matrix {
        return this.transformMatrix(X);
    }
}
NativeEstimator.register("preprocessing.alignment.cow_align", CorrelationOptimizedWarping);

/** Parameters of DynamicTimeWarpingAlignment; unset values take the native defaults. */
export interface DynamicTimeWarpingAlignmentParams {
    /** Default []. */
    reference?: number[];
}

/** Native `preprocessing.alignment.dtw_align` (transformer). */
export class DynamicTimeWarpingAlignment extends NativeEstimator implements Transformer {
    readonly methodId = "preprocessing.alignment.dtw_align";
    protected readonly paramTypes = {
        reference: "double_array",
    } as const;

    constructor(params: DynamicTimeWarpingAlignmentParams = {}) {
        super();
        this.params = { ...params };
    }

    transform(X: Matrix): Matrix {
        return this.transformMatrix(X);
    }
}
NativeEstimator.register("preprocessing.alignment.dtw_align", DynamicTimeWarpingAlignment);

/** Parameters of IcoshiftAlignment; unset values take the native defaults. */
export interface IcoshiftAlignmentParams {
    /** Default []. */
    reference?: number[];
    /** Default 32. */
    interval_size?: number;
    /** Default 5. */
    max_shift?: number;
}

/** Native `preprocessing.alignment.icoshift_align` (transformer). */
export class IcoshiftAlignment extends NativeEstimator implements Transformer {
    readonly methodId = "preprocessing.alignment.icoshift_align";
    protected readonly paramTypes = {
        reference: "double_array",
        interval_size: "int",
        max_shift: "int",
    } as const;

    constructor(params: IcoshiftAlignmentParams = {}) {
        super();
        this.params = { ...params };
    }

    transform(X: Matrix): Matrix {
        return this.transformMatrix(X);
    }
}
NativeEstimator.register("preprocessing.alignment.icoshift_align", IcoshiftAlignment);

/** Parameters of CrossCorrelationAlignment; unset values take the native defaults. */
export interface CrossCorrelationAlignmentParams {
    /** Default []. */
    reference?: number[];
    /** Default 5. */
    max_shift?: number;
}

/** Native `preprocessing.alignment.xcorr_align` (transformer). */
export class CrossCorrelationAlignment extends NativeEstimator implements Transformer {
    readonly methodId = "preprocessing.alignment.xcorr_align";
    protected readonly paramTypes = {
        reference: "double_array",
        max_shift: "int",
    } as const;

    constructor(params: CrossCorrelationAlignmentParams = {}) {
        super();
        this.params = { ...params };
    }

    transform(X: Matrix): Matrix {
        return this.transformMatrix(X);
    }
}
NativeEstimator.register("preprocessing.alignment.xcorr_align", CrossCorrelationAlignment);

/** Parameters of AirPLS; unset values take the native defaults. */
export interface AirPLSParams {
    /** Default 1000000. */
    lam?: number;
    /** Default 50. */
    max_iter?: number;
    /** Default 0.001. */
    tol?: number;
}

/** Native `preprocessing.baselines.airpls` (transformer). */
export class AirPLS extends NativeEstimator implements Transformer {
    readonly methodId = "preprocessing.baselines.airpls";
    protected readonly paramTypes = {
        lam: "double",
        max_iter: "int",
        tol: "double",
    } as const;

    constructor(params: AirPLSParams = {}) {
        super();
        this.params = { ...params };
    }

    transform(X: Matrix): Matrix {
        return this.transformMatrix(X);
    }
}
NativeEstimator.register("preprocessing.baselines.airpls", AirPLS);

/** Parameters of ArPLS; unset values take the native defaults. */
export interface ArPLSParams {
    /** Default 100000. */
    lam?: number;
    /** Default 50. */
    max_iter?: number;
    /** Default 0.001. */
    tol?: number;
}

/** Native `preprocessing.baselines.arpls` (transformer). */
export class ArPLS extends NativeEstimator implements Transformer {
    readonly methodId = "preprocessing.baselines.arpls";
    protected readonly paramTypes = {
        lam: "double",
        max_iter: "int",
        tol: "double",
    } as const;

    constructor(params: ArPLSParams = {}) {
        super();
        this.params = { ...params };
    }

    transform(X: Matrix): Matrix {
        return this.transformMatrix(X);
    }
}
NativeEstimator.register("preprocessing.baselines.arpls", ArPLS);

/** Parameters of AsLS; unset values take the native defaults. */
export interface AsLSParams {
    /** Default 1000000. */
    lam?: number;
    /** Default 0.01. */
    p?: number;
    /** Default 50. */
    max_iter?: number;
    /** Default 0.001. */
    tol?: number;
}

/** Native `preprocessing.baselines.asls` (transformer). */
export class AsLS extends NativeEstimator implements Transformer {
    readonly methodId = "preprocessing.baselines.asls";
    protected readonly paramTypes = {
        lam: "double",
        p: "double",
        max_iter: "int",
        tol: "double",
    } as const;

    constructor(params: AsLSParams = {}) {
        super();
        this.params = { ...params };
    }

    transform(X: Matrix): Matrix {
        return this.transformMatrix(X);
    }
}
NativeEstimator.register("preprocessing.baselines.asls", AsLS);

/** Parameters of BEADS; unset values take the native defaults. */
export interface BEADSParams {
    /** Default 100. */
    lam_0?: number;
    /** Default 0.5. */
    lam_1?: number;
    /** Default 0.5. */
    lam_2?: number;
    /** Default 50. */
    max_iter?: number;
    /** Default 0.001. */
    tol?: number;
}

/** Native `preprocessing.baselines.beads` (transformer). */
export class BEADS extends NativeEstimator implements Transformer {
    readonly methodId = "preprocessing.baselines.beads";
    protected readonly paramTypes = {
        lam_0: "double",
        lam_1: "double",
        lam_2: "double",
        max_iter: "int",
        tol: "double",
    } as const;

    constructor(params: BEADSParams = {}) {
        super();
        this.params = { ...params };
    }

    transform(X: Matrix): Matrix {
        return this.transformMatrix(X);
    }
}
NativeEstimator.register("preprocessing.baselines.beads", BEADS);

/** Parameters of Detrend; unset values take the native defaults. */
export interface DetrendParams {
    /** Default 1. */
    polyorder?: number;
}

/** Native `preprocessing.baselines.detrend` (transformer). */
export class Detrend extends NativeEstimator implements Transformer {
    readonly methodId = "preprocessing.baselines.detrend";
    protected readonly paramTypes = {
        polyorder: "int",
    } as const;

    constructor(params: DetrendParams = {}) {
        super();
        this.params = { ...params };
    }

    transform(X: Matrix): Matrix {
        return this.transformMatrix(X);
    }
}
NativeEstimator.register("preprocessing.baselines.detrend", Detrend);

/** Parameters of IAsLS; unset values take the native defaults. */
export interface IAsLSParams {
    /** Default 1000000. */
    lam?: number;
    /** Default 0.01. */
    p?: number;
    /** Default 0.0001. */
    lam_1?: number;
    /** Default 2. */
    polyorder?: number;
    /** Default 2. */
    diff_order?: number;
    /** Default 50. */
    max_iter?: number;
    /** Default 0.001. */
    tol?: number;
}

/** Native `preprocessing.baselines.iasls` (transformer). */
export class IAsLS extends NativeEstimator implements Transformer {
    readonly methodId = "preprocessing.baselines.iasls";
    protected readonly paramTypes = {
        lam: "double",
        p: "double",
        lam_1: "double",
        polyorder: "int",
        diff_order: "int",
        max_iter: "int",
        tol: "double",
    } as const;

    constructor(params: IAsLSParams = {}) {
        super();
        this.params = { ...params };
    }

    transform(X: Matrix): Matrix {
        return this.transformMatrix(X);
    }
}
NativeEstimator.register("preprocessing.baselines.iasls", IAsLS);

/** Parameters of IModPoly; unset values take the native defaults. */
export interface IModPolyParams {
    /** Default 2. */
    polyorder?: number;
    /** Default 250. */
    max_iter?: number;
    /** Default 0.001. */
    tol?: number;
}

/** Native `preprocessing.baselines.imodpoly` (transformer). */
export class IModPoly extends NativeEstimator implements Transformer {
    readonly methodId = "preprocessing.baselines.imodpoly";
    protected readonly paramTypes = {
        polyorder: "int",
        max_iter: "int",
        tol: "double",
    } as const;

    constructor(params: IModPolyParams = {}) {
        super();
        this.params = { ...params };
    }

    transform(X: Matrix): Matrix {
        return this.transformMatrix(X);
    }
}
NativeEstimator.register("preprocessing.baselines.imodpoly", IModPoly);

/** Parameters of ModPoly; unset values take the native defaults. */
export interface ModPolyParams {
    /** Default 2. */
    polyorder?: number;
    /** Default 250. */
    max_iter?: number;
    /** Default 0.001. */
    tol?: number;
}

/** Native `preprocessing.baselines.modpoly` (transformer). */
export class ModPoly extends NativeEstimator implements Transformer {
    readonly methodId = "preprocessing.baselines.modpoly";
    protected readonly paramTypes = {
        polyorder: "int",
        max_iter: "int",
        tol: "double",
    } as const;

    constructor(params: ModPolyParams = {}) {
        super();
        this.params = { ...params };
    }

    transform(X: Matrix): Matrix {
        return this.transformMatrix(X);
    }
}
NativeEstimator.register("preprocessing.baselines.modpoly", ModPoly);

/** Parameters of RollingBall; unset values take the native defaults. */
export interface RollingBallParams {
    /** Default 20. */
    half_window?: number;
    /** Default 0. */
    smooth_half_window?: number;
}

/** Native `preprocessing.baselines.rolling_ball` (transformer). */
export class RollingBall extends NativeEstimator implements Transformer {
    readonly methodId = "preprocessing.baselines.rolling_ball";
    protected readonly paramTypes = {
        half_window: "int",
        smooth_half_window: "int",
    } as const;

    constructor(params: RollingBallParams = {}) {
        super();
        this.params = { ...params };
    }

    transform(X: Matrix): Matrix {
        return this.transformMatrix(X);
    }
}
NativeEstimator.register("preprocessing.baselines.rolling_ball", RollingBall);

/** Parameters of ScoreAugmentedProjectionStandardization; unset values take the native defaults. */
export interface ScoreAugmentedProjectionStandardizationParams {
    /** Default 5. */
    n_components?: number;
    /** Default 1. */
    score_weight?: number;
    /** Default true. */
    fit_intercept?: boolean;
    /** Default 0. */
    ridge?: number;
}

/** Native `preprocessing.baselines.saps` (transformer). Required fit inputs: target_domain. */
export class ScoreAugmentedProjectionStandardization extends NativeEstimator implements Transformer {
    readonly methodId = "preprocessing.baselines.saps";
    protected readonly paramTypes = {
        n_components: "int",
        score_weight: "double",
        fit_intercept: "bool",
        ridge: "double",
    } as const;

    constructor(params: ScoreAugmentedProjectionStandardizationParams = {}) {
        super();
        this.params = { ...params };
    }

    transform(X: Matrix): Matrix {
        return this.transformMatrix(X);
    }
}
NativeEstimator.register("preprocessing.baselines.saps", ScoreAugmentedProjectionStandardization);

/** Parameters of SNIP; unset values take the native defaults. */
export interface SNIPParams {
    /** Default 20. */
    max_half_window?: number;
}

/** Native `preprocessing.baselines.snip` (transformer). */
export class SNIP extends NativeEstimator implements Transformer {
    readonly methodId = "preprocessing.baselines.snip";
    protected readonly paramTypes = {
        max_half_window: "int",
    } as const;

    constructor(params: SNIPParams = {}) {
        super();
        this.params = { ...params };
    }

    transform(X: Matrix): Matrix {
        return this.transformMatrix(X);
    }
}
NativeEstimator.register("preprocessing.baselines.snip", SNIP);

/** Parameters of Derivate; unset values take the native defaults. */
export interface DerivateParams {
    /** Default 1. */
    order?: number;
    /** Default 1. */
    delta?: number;
}

/** Native `preprocessing.derivatives.derivate` (transformer). */
export class Derivate extends NativeEstimator implements Transformer {
    readonly methodId = "preprocessing.derivatives.derivate";
    protected readonly paramTypes = {
        order: "int",
        delta: "double",
    } as const;

    constructor(params: DerivateParams = {}) {
        super();
        this.params = { ...params };
    }

    transform(X: Matrix): Matrix {
        return this.transformMatrix(X);
    }
}
NativeEstimator.register("preprocessing.derivatives.derivate", Derivate);

/** Parameters of FirstDerivative; unset values take the native defaults. */
export interface FirstDerivativeParams {
    /** Default 1. */
    delta?: number;
    /** Default 2. */
    edge_order?: number;
}

/** Native `preprocessing.derivatives.first_derivative` (transformer). */
export class FirstDerivative extends NativeEstimator implements Transformer {
    readonly methodId = "preprocessing.derivatives.first_derivative";
    protected readonly paramTypes = {
        delta: "double",
        edge_order: "int",
    } as const;

    constructor(params: FirstDerivativeParams = {}) {
        super();
        this.params = { ...params };
    }

    transform(X: Matrix): Matrix {
        return this.transformMatrix(X);
    }
}
NativeEstimator.register("preprocessing.derivatives.first_derivative", FirstDerivative);

/** Parameters of NorrisWilliams; unset values take the native defaults. */
export interface NorrisWilliamsParams {
    /** Default 5. */
    segment?: number;
    /** Default 5. */
    gap?: number;
    /** Default 1. */
    derivative_order?: number;
    /** Default 1. */
    delta?: number;
}

/** Native `preprocessing.derivatives.norris_williams` (transformer). */
export class NorrisWilliams extends NativeEstimator implements Transformer {
    readonly methodId = "preprocessing.derivatives.norris_williams";
    protected readonly paramTypes = {
        segment: "int",
        gap: "int",
        derivative_order: "int",
        delta: "double",
    } as const;

    constructor(params: NorrisWilliamsParams = {}) {
        super();
        this.params = { ...params };
    }

    transform(X: Matrix): Matrix {
        return this.transformMatrix(X);
    }
}
NativeEstimator.register("preprocessing.derivatives.norris_williams", NorrisWilliams);

/** Parameters of SavitzkyGolay; unset values take the native defaults. */
export interface SavitzkyGolayParams {
    /** Default 5. */
    window_length?: number;
    /** Default 2. */
    polyorder?: number;
    /** Default 0. */
    deriv?: number;
    /** Default 1. */
    delta?: number;
    /** Default "mirror". */
    mode?: "mirror" | "constant" | "nearest" | "wrap" | "interp";
    /** Default 0. */
    cval?: number;
}

/** Native `preprocessing.derivatives.savitzky_golay` (transformer). */
export class SavitzkyGolay extends NativeEstimator implements Transformer {
    readonly methodId = "preprocessing.derivatives.savitzky_golay";
    protected readonly paramTypes = {
        window_length: "int",
        polyorder: "int",
        deriv: "int",
        delta: "double",
        mode: "enum",
        cval: "double",
    } as const;

    constructor(params: SavitzkyGolayParams = {}) {
        super();
        this.params = { ...params };
    }

    transform(X: Matrix): Matrix {
        return this.transformMatrix(X);
    }
}
NativeEstimator.register("preprocessing.derivatives.savitzky_golay", SavitzkyGolay);

/** Parameters of SecondDerivative; unset values take the native defaults. */
export interface SecondDerivativeParams {
    /** Default 1. */
    delta?: number;
    /** Default 2. */
    edge_order?: number;
}

/** Native `preprocessing.derivatives.second_derivative` (transformer). */
export class SecondDerivative extends NativeEstimator implements Transformer {
    readonly methodId = "preprocessing.derivatives.second_derivative";
    protected readonly paramTypes = {
        delta: "double",
        edge_order: "int",
    } as const;

    constructor(params: SecondDerivativeParams = {}) {
        super();
        this.params = { ...params };
    }

    transform(X: Matrix): Matrix {
        return this.transformMatrix(X);
    }
}
NativeEstimator.register("preprocessing.derivatives.second_derivative", SecondDerivative);

/** Parameters of FlexiblePCA; unset values take the native defaults. */
export interface FlexiblePCAParams {
    /** Default 5. */
    n_components?: number;
}

/** Native `preprocessing.feature_selection.flexible_pca` (transformer). */
export class FlexiblePCA extends NativeEstimator implements Transformer {
    readonly methodId = "preprocessing.feature_selection.flexible_pca";
    protected readonly paramTypes = {
        n_components: "double",
    } as const;

    constructor(params: FlexiblePCAParams = {}) {
        super();
        this.params = { ...params };
    }

    transform(X: Matrix): Matrix {
        return this.transformMatrix(X);
    }
}
NativeEstimator.register("preprocessing.feature_selection.flexible_pca", FlexiblePCA);

/** Parameters of FlexibleSVD; unset values take the native defaults. */
export interface FlexibleSVDParams {
    /** Default 5. */
    n_components?: number;
}

/** Native `preprocessing.feature_selection.flexible_svd` (transformer). */
export class FlexibleSVD extends NativeEstimator implements Transformer {
    readonly methodId = "preprocessing.feature_selection.flexible_svd";
    protected readonly paramTypes = {
        n_components: "double",
    } as const;

    constructor(params: FlexibleSVDParams = {}) {
        super();
        this.params = { ...params };
    }

    transform(X: Matrix): Matrix {
        return this.transformMatrix(X);
    }
}
NativeEstimator.register("preprocessing.feature_selection.flexible_svd", FlexibleSVD);

/** Parameters of OSC; unset values take the native defaults. */
export interface OSCParams {
    /** Default 1. */
    n_components?: number;
    /** Default true. */
    scale?: boolean;
}

/** Native `preprocessing.orthogonalization.osc` (transformer). */
export class OSC extends NativeEstimator implements Transformer {
    readonly methodId = "preprocessing.orthogonalization.osc";
    protected readonly paramTypes = {
        n_components: "int",
        scale: "bool",
    } as const;

    constructor(params: OSCParams = {}) {
        super();
        this.params = { ...params };
    }

    transform(X: Matrix): Matrix {
        return this.transformMatrix(X);
    }
}
NativeEstimator.register("preprocessing.orthogonalization.osc", OSC);

/** Parameters of CropTransformer; unset values take the native defaults. */
export interface CropTransformerParams {
    /** Required. */
    start?: number;
    /** Required. */
    end?: number;
}

/** Native `preprocessing.resampling.crop` (transformer). */
export class CropTransformer extends NativeEstimator implements Transformer {
    readonly methodId = "preprocessing.resampling.crop";
    protected readonly paramTypes = {
        start: "int",
        end: "int",
    } as const;

    constructor(params: CropTransformerParams = {}) {
        super();
        this.params = { ...params };
    }

    transform(X: Matrix): Matrix {
        return this.transformMatrix(X);
    }
}
NativeEstimator.register("preprocessing.resampling.crop", CropTransformer);

/** Parameters of IntegerKBinsDiscretizer; unset values take the native defaults. */
export interface IntegerKBinsDiscretizerParams {
    /** Default 5. */
    n_bins?: number;
    /** Default "uniform". */
    strategy?: "uniform" | "quantile";
}

/** Native `preprocessing.resampling.kbins_discretizer` (transformer). */
export class IntegerKBinsDiscretizer extends NativeEstimator implements Transformer {
    readonly methodId = "preprocessing.resampling.kbins_discretizer";
    protected readonly paramTypes = {
        n_bins: "int",
        strategy: "enum",
    } as const;

    constructor(params: IntegerKBinsDiscretizerParams = {}) {
        super();
        this.params = { ...params };
    }

    transform(X: Matrix): Matrix {
        return this.transformMatrix(X);
    }
}
NativeEstimator.register("preprocessing.resampling.kbins_discretizer", IntegerKBinsDiscretizer);

/** Parameters of RangeDiscretizer; unset values take the native defaults. */
export interface RangeDiscretizerParams {
    /** Required. */
    edges?: number[];
}

/** Native `preprocessing.resampling.range_discretizer` (transformer). */
export class RangeDiscretizer extends NativeEstimator implements Transformer {
    readonly methodId = "preprocessing.resampling.range_discretizer";
    protected readonly paramTypes = {
        edges: "double_array",
    } as const;

    constructor(params: RangeDiscretizerParams = {}) {
        super();
        this.params = { ...params };
    }

    transform(X: Matrix): Matrix {
        return this.transformMatrix(X);
    }
}
NativeEstimator.register("preprocessing.resampling.range_discretizer", RangeDiscretizer);

/** Parameters of ResampleTransformer; unset values take the native defaults. */
export interface ResampleTransformerParams {
    /** Required. */
    num_samples?: number;
}

/** Native `preprocessing.resampling.resample_transformer` (transformer). */
export class ResampleTransformer extends NativeEstimator implements Transformer {
    readonly methodId = "preprocessing.resampling.resample_transformer";
    protected readonly paramTypes = {
        num_samples: "int",
    } as const;

    constructor(params: ResampleTransformerParams = {}) {
        super();
        this.params = { ...params };
    }

    transform(X: Matrix): Matrix {
        return this.transformMatrix(X);
    }
}
NativeEstimator.register("preprocessing.resampling.resample_transformer", ResampleTransformer);

/** Parameters of Resampler; unset values take the native defaults. */
export interface ResamplerParams {
    /** Default []. */
    target_wavelengths?: number[];
    /** Default "linear". */
    method?: "linear" | "nearest" | "cubic";
    /** Default 0. */
    crop_min?: number;
    /** Default 0. */
    crop_max?: number;
    /** Default false. */
    use_crop?: boolean;
    /** Default 0. */
    fill_value?: number;
    /** Default false. */
    bounds_error?: boolean;
    /** Default false. */
    extrapolate?: boolean;
    /** Default 0. */
    tgt_min?: number;
    /** Default 1. */
    tgt_step?: number;
    /** Default 0. */
    tgt_n?: number;
}

/** Native `preprocessing.resampling.resampler` (transformer). Required fit inputs: axis. */
export class Resampler extends NativeEstimator implements Transformer {
    readonly methodId = "preprocessing.resampling.resampler";
    protected readonly paramTypes = {
        target_wavelengths: "double_array",
        method: "enum",
        crop_min: "double",
        crop_max: "double",
        use_crop: "bool",
        fill_value: "double",
        bounds_error: "bool",
        extrapolate: "bool",
        tgt_min: "double",
        tgt_step: "double",
        tgt_n: "int",
    } as const;

    constructor(params: ResamplerParams = {}) {
        super();
        this.params = { ...params };
    }

    transform(X: Matrix): Matrix {
        return this.transformMatrix(X);
    }
}
NativeEstimator.register("preprocessing.resampling.resampler", Resampler);

/** Parameters of BaselineCenter; unset values take the native defaults. */
export interface BaselineCenterParams {
}

/** Native `preprocessing.scaling.baseline` (transformer). */
export class BaselineCenter extends NativeEstimator implements Transformer {
    readonly methodId = "preprocessing.scaling.baseline";
    protected readonly paramTypes = {
    } as const;

    constructor(params: BaselineCenterParams = {}) {
        super();
        this.params = { ...params };
    }

    transform(X: Matrix): Matrix {
        return this.transformMatrix(X);
    }
}
NativeEstimator.register("preprocessing.scaling.baseline", BaselineCenter);

/** Parameters of LogTransform; unset values take the native defaults. */
export interface LogTransformParams {
    /** Default 0. */
    base?: number;
    /** Default 0. */
    offset?: number;
    /** Default true. */
    auto_offset?: boolean;
    /** Default 1e-08. */
    min_value?: number;
}

/** Native `preprocessing.scaling.log_transform` (transformer). */
export class LogTransform extends NativeEstimator implements Transformer {
    readonly methodId = "preprocessing.scaling.log_transform";
    protected readonly paramTypes = {
        base: "double",
        offset: "double",
        auto_offset: "bool",
        min_value: "double",
    } as const;

    constructor(params: LogTransformParams = {}) {
        super();
        this.params = { ...params };
    }

    transform(X: Matrix): Matrix {
        return this.transformMatrix(X);
    }
}
NativeEstimator.register("preprocessing.scaling.log_transform", LogTransform);

/** Parameters of Normalize; unset values take the native defaults. */
export interface NormalizeParams {
    /** Default -1. */
    feature_min?: number;
    /** Default 1. */
    feature_max?: number;
}

/** Native `preprocessing.scaling.normalize` (transformer). */
export class Normalize extends NativeEstimator implements Transformer {
    readonly methodId = "preprocessing.scaling.normalize";
    protected readonly paramTypes = {
        feature_min: "double",
        feature_max: "double",
    } as const;

    constructor(params: NormalizeParams = {}) {
        super();
        this.params = { ...params };
    }

    transform(X: Matrix): Matrix {
        return this.transformMatrix(X);
    }
}
NativeEstimator.register("preprocessing.scaling.normalize", Normalize);

/** Parameters of SimpleScale; unset values take the native defaults. */
export interface SimpleScaleParams {
}

/** Native `preprocessing.scaling.simple_scale` (transformer). */
export class SimpleScale extends NativeEstimator implements Transformer {
    readonly methodId = "preprocessing.scaling.simple_scale";
    protected readonly paramTypes = {
    } as const;

    constructor(params: SimpleScaleParams = {}) {
        super();
        this.params = { ...params };
    }

    transform(X: Matrix): Matrix {
        return this.transformMatrix(X);
    }
}
NativeEstimator.register("preprocessing.scaling.simple_scale", SimpleScale);

/** Parameters of AreaNormalization; unset values take the native defaults. */
export interface AreaNormalizationParams {
    /** Default "sum". */
    method?: "sum" | "abs_sum" | "trapz";
}

/** Native `preprocessing.scatter.area_normalization` (transformer). */
export class AreaNormalization extends NativeEstimator implements Transformer {
    readonly methodId = "preprocessing.scatter.area_normalization";
    protected readonly paramTypes = {
        method: "enum",
    } as const;

    constructor(params: AreaNormalizationParams = {}) {
        super();
        this.params = { ...params };
    }

    transform(X: Matrix): Matrix {
        return this.transformMatrix(X);
    }
}
NativeEstimator.register("preprocessing.scatter.area_normalization", AreaNormalization);

/** Parameters of EMSC; unset values take the native defaults. */
export interface EMSCParams {
    /** Default 2. */
    degree?: number;
}

/** Native `preprocessing.scatter.emsc` (transformer). */
export class EMSC extends NativeEstimator implements Transformer {
    readonly methodId = "preprocessing.scatter.emsc";
    protected readonly paramTypes = {
        degree: "int",
    } as const;

    constructor(params: EMSCParams = {}) {
        super();
        this.params = { ...params };
    }

    transform(X: Matrix): Matrix {
        return this.transformMatrix(X);
    }
}
NativeEstimator.register("preprocessing.scatter.emsc", EMSC);

/** Parameters of LocalCentering; unset values take the native defaults. */
export interface LocalCenteringParams {
}

/** Native `preprocessing.scatter.local_centering` (transformer). Required fit inputs: target_domain. */
export class LocalCentering extends NativeEstimator implements Transformer {
    readonly methodId = "preprocessing.scatter.local_centering";
    protected readonly paramTypes = {
    } as const;

    constructor(params: LocalCenteringParams = {}) {
        super();
        this.params = { ...params };
    }

    transform(X: Matrix): Matrix {
        return this.transformMatrix(X);
    }
}
NativeEstimator.register("preprocessing.scatter.local_centering", LocalCentering);

/** Parameters of LSNV; unset values take the native defaults. */
export interface LSNVParams {
    /** Default 11. */
    window?: number;
    /** Default "reflect". */
    pad_mode?: "reflect" | "edge" | "constant";
    /** Default 0. */
    constant_value?: number;
}

/** Native `preprocessing.scatter.local_snv` (transformer). */
export class LSNV extends NativeEstimator implements Transformer {
    readonly methodId = "preprocessing.scatter.local_snv";
    protected readonly paramTypes = {
        window: "int",
        pad_mode: "enum",
        constant_value: "double",
    } as const;

    constructor(params: LSNVParams = {}) {
        super();
        this.params = { ...params };
    }

    transform(X: Matrix): Matrix {
        return this.transformMatrix(X);
    }
}
NativeEstimator.register("preprocessing.scatter.local_snv", LSNV);

/** Parameters of LocalizedMSC; unset values take the native defaults. */
export interface LocalizedMSCParams {
    /** Default 32. */
    window_size?: number;
    /** Default []. */
    reference?: number[];
    /** Default 1e-12. */
    eps?: number;
}

/** Native `preprocessing.scatter.localized_msc` (transformer). */
export class LocalizedMSC extends NativeEstimator implements Transformer {
    readonly methodId = "preprocessing.scatter.localized_msc";
    protected readonly paramTypes = {
        window_size: "int",
        reference: "double_array",
        eps: "double",
    } as const;

    constructor(params: LocalizedMSCParams = {}) {
        super();
        this.params = { ...params };
    }

    transform(X: Matrix): Matrix {
        return this.transformMatrix(X);
    }
}
NativeEstimator.register("preprocessing.scatter.localized_msc", LocalizedMSC);

/** Parameters of MSC; unset values take the native defaults. */
export interface MSCParams {
}

/** Native `preprocessing.scatter.msc` (transformer). */
export class MSC extends NativeEstimator implements Transformer {
    readonly methodId = "preprocessing.scatter.msc";
    protected readonly paramTypes = {
    } as const;

    constructor(params: MSCParams = {}) {
        super();
        this.params = { ...params };
    }

    transform(X: Matrix): Matrix {
        return this.transformMatrix(X);
    }
}
NativeEstimator.register("preprocessing.scatter.msc", MSC);

/** Parameters of PiecewiseMSC; unset values take the native defaults. */
export interface PiecewiseMSCParams {
    /** Default 32. */
    window_size?: number;
    /** Default []. */
    reference?: number[];
    /** Default 1e-12. */
    eps?: number;
}

/** Native `preprocessing.scatter.piecewise_msc` (transformer). */
export class PiecewiseMSC extends NativeEstimator implements Transformer {
    readonly methodId = "preprocessing.scatter.piecewise_msc";
    protected readonly paramTypes = {
        window_size: "int",
        reference: "double_array",
        eps: "double",
    } as const;

    constructor(params: PiecewiseMSCParams = {}) {
        super();
        this.params = { ...params };
    }

    transform(X: Matrix): Matrix {
        return this.transformMatrix(X);
    }
}
NativeEstimator.register("preprocessing.scatter.piecewise_msc", PiecewiseMSC);

/** Parameters of PiecewiseSNV; unset values take the native defaults. */
export interface PiecewiseSNVParams {
    /** Default 32. */
    window_size?: number;
    /** Default 0. */
    ddof?: number;
    /** Default 1e-12. */
    eps?: number;
}

/** Native `preprocessing.scatter.piecewise_snv` (transformer). */
export class PiecewiseSNV extends NativeEstimator implements Transformer {
    readonly methodId = "preprocessing.scatter.piecewise_snv";
    protected readonly paramTypes = {
        window_size: "int",
        ddof: "int",
        eps: "double",
    } as const;

    constructor(params: PiecewiseSNVParams = {}) {
        super();
        this.params = { ...params };
    }

    transform(X: Matrix): Matrix {
        return this.transformMatrix(X);
    }
}
NativeEstimator.register("preprocessing.scatter.piecewise_snv", PiecewiseSNV);

/** Parameters of RNV; unset values take the native defaults. */
export interface RNVParams {
    /** Default true. */
    with_center?: boolean;
    /** Default true. */
    with_scale?: boolean;
    /** Default 1.4826. */
    k?: number;
}

/** Native `preprocessing.scatter.robust_snv` (transformer). */
export class RNV extends NativeEstimator implements Transformer {
    readonly methodId = "preprocessing.scatter.robust_snv";
    protected readonly paramTypes = {
        with_center: "bool",
        with_scale: "bool",
        k: "double",
    } as const;

    constructor(params: RNVParams = {}) {
        super();
        this.params = { ...params };
    }

    transform(X: Matrix): Matrix {
        return this.transformMatrix(X);
    }
}
NativeEstimator.register("preprocessing.scatter.robust_snv", RNV);

/** Parameters of SNV; unset values take the native defaults. */
export interface SNVParams {
    /** Default true. */
    with_mean?: boolean;
    /** Default true. */
    with_std?: boolean;
    /** Default 0. */
    ddof?: number;
}

/** Native `preprocessing.scatter.snv` (transformer). */
export class SNV extends NativeEstimator implements Transformer {
    readonly methodId = "preprocessing.scatter.snv";
    protected readonly paramTypes = {
        with_mean: "bool",
        with_std: "bool",
        ddof: "int",
    } as const;

    constructor(params: SNVParams = {}) {
        super();
        this.params = { ...params };
    }

    transform(X: Matrix): Matrix {
        return this.transformMatrix(X);
    }
}
NativeEstimator.register("preprocessing.scatter.snv", SNV);

/** Parameters of VariableSortingNormalization; unset values take the native defaults. */
export interface VariableSortingNormalizationParams {
    /** Default 1e-12. */
    eps?: number;
}

/** Native `preprocessing.scatter.vsn` (transformer). */
export class VariableSortingNormalization extends NativeEstimator implements Transformer {
    readonly methodId = "preprocessing.scatter.vsn";
    protected readonly paramTypes = {
        eps: "double",
    } as const;

    constructor(params: VariableSortingNormalizationParams = {}) {
        super();
        this.params = { ...params };
    }

    transform(X: Matrix): Matrix {
        return this.transformMatrix(X);
    }
}
NativeEstimator.register("preprocessing.scatter.vsn", VariableSortingNormalization);

/** Parameters of WeightedSNV; unset values take the native defaults. */
export interface WeightedSNVParams {
    /** Default []. */
    weights?: number[];
    /** Default 0. */
    ddof?: number;
    /** Default 1e-12. */
    eps?: number;
}

/** Native `preprocessing.scatter.weighted_snv` (transformer). */
export class WeightedSNV extends NativeEstimator implements Transformer {
    readonly methodId = "preprocessing.scatter.weighted_snv";
    protected readonly paramTypes = {
        weights: "double_array",
        ddof: "int",
        eps: "double",
    } as const;

    constructor(params: WeightedSNVParams = {}) {
        super();
        this.params = { ...params };
    }

    transform(X: Matrix): Matrix {
        return this.transformMatrix(X);
    }
}
NativeEstimator.register("preprocessing.scatter.weighted_snv", WeightedSNV);

/** Parameters of FractionToPercent; unset values take the native defaults. */
export interface FractionToPercentParams {
}

/** Native `preprocessing.signal_conversion.fraction_to_percent` (transformer). */
export class FractionToPercent extends NativeEstimator implements Transformer {
    readonly methodId = "preprocessing.signal_conversion.fraction_to_percent";
    protected readonly paramTypes = {
    } as const;

    constructor(params: FractionToPercentParams = {}) {
        super();
        this.params = { ...params };
    }

    transform(X: Matrix): Matrix {
        return this.transformMatrix(X);
    }
}
NativeEstimator.register("preprocessing.signal_conversion.fraction_to_percent", FractionToPercent);

/** Parameters of FromAbsorbance; unset values take the native defaults. */
export interface FromAbsorbanceParams {
    /** Default false. */
    is_percent?: boolean;
}

/** Native `preprocessing.signal_conversion.from_absorbance` (transformer). */
export class FromAbsorbance extends NativeEstimator implements Transformer {
    readonly methodId = "preprocessing.signal_conversion.from_absorbance";
    protected readonly paramTypes = {
        is_percent: "bool",
    } as const;

    constructor(params: FromAbsorbanceParams = {}) {
        super();
        this.params = { ...params };
    }

    transform(X: Matrix): Matrix {
        return this.transformMatrix(X);
    }
}
NativeEstimator.register("preprocessing.signal_conversion.from_absorbance", FromAbsorbance);

/** Parameters of KubelkaMunk; unset values take the native defaults. */
export interface KubelkaMunkParams {
    /** Default false. */
    is_percent?: boolean;
    /** Default 1e-10. */
    epsilon?: number;
}

/** Native `preprocessing.signal_conversion.kubelka_munk` (transformer). */
export class KubelkaMunk extends NativeEstimator implements Transformer {
    readonly methodId = "preprocessing.signal_conversion.kubelka_munk";
    protected readonly paramTypes = {
        is_percent: "bool",
        epsilon: "double",
    } as const;

    constructor(params: KubelkaMunkParams = {}) {
        super();
        this.params = { ...params };
    }

    transform(X: Matrix): Matrix {
        return this.transformMatrix(X);
    }
}
NativeEstimator.register("preprocessing.signal_conversion.kubelka_munk", KubelkaMunk);

/** Parameters of PercentToFraction; unset values take the native defaults. */
export interface PercentToFractionParams {
}

/** Native `preprocessing.signal_conversion.percent_to_fraction` (transformer). */
export class PercentToFraction extends NativeEstimator implements Transformer {
    readonly methodId = "preprocessing.signal_conversion.percent_to_fraction";
    protected readonly paramTypes = {
    } as const;

    constructor(params: PercentToFractionParams = {}) {
        super();
        this.params = { ...params };
    }

    transform(X: Matrix): Matrix {
        return this.transformMatrix(X);
    }
}
NativeEstimator.register("preprocessing.signal_conversion.percent_to_fraction", PercentToFraction);

/** Parameters of ToAbsorbance; unset values take the native defaults. */
export interface ToAbsorbanceParams {
    /** Default false. */
    is_percent?: boolean;
    /** Default 1e-10. */
    epsilon?: number;
    /** Default true. */
    clip_negative?: boolean;
}

/** Native `preprocessing.signal_conversion.to_absorbance` (transformer). */
export class ToAbsorbance extends NativeEstimator implements Transformer {
    readonly methodId = "preprocessing.signal_conversion.to_absorbance";
    protected readonly paramTypes = {
        is_percent: "bool",
        epsilon: "double",
        clip_negative: "bool",
    } as const;

    constructor(params: ToAbsorbanceParams = {}) {
        super();
        this.params = { ...params };
    }

    transform(X: Matrix): Matrix {
        return this.transformMatrix(X);
    }
}
NativeEstimator.register("preprocessing.signal_conversion.to_absorbance", ToAbsorbance);

/** Parameters of Gaussian; unset values take the native defaults. */
export interface GaussianParams {
    /** Default 1. */
    sigma?: number;
    /** Default 0. */
    order?: number;
    /** Default "reflect". */
    mode?: "reflect" | "constant" | "nearest" | "mirror" | "wrap";
    /** Default 0. */
    cval?: number;
    /** Default 4. */
    truncate?: number;
}

/** Native `preprocessing.smoothing.gaussian` (transformer). */
export class Gaussian extends NativeEstimator implements Transformer {
    readonly methodId = "preprocessing.smoothing.gaussian";
    protected readonly paramTypes = {
        sigma: "double",
        order: "int",
        mode: "enum",
        cval: "double",
        truncate: "double",
    } as const;

    constructor(params: GaussianParams = {}) {
        super();
        this.params = { ...params };
    }

    transform(X: Matrix): Matrix {
        return this.transformMatrix(X);
    }
}
NativeEstimator.register("preprocessing.smoothing.gaussian", Gaussian);

/** Parameters of FCKStaticTransformer; unset values take the native defaults. */
export interface FCKStaticTransformerParams {
    /** Required. */
    kernel_size?: number;
    /** Required. */
    alphas?: number[];
    /** Required. */
    sigmas?: number[];
}

/** Native `preprocessing.specialized.fck_static` (transformer). */
export class FCKStaticTransformer extends NativeEstimator implements Transformer {
    readonly methodId = "preprocessing.specialized.fck_static";
    protected readonly paramTypes = {
        kernel_size: "int",
        alphas: "double_array",
        sigmas: "double_array",
    } as const;

    constructor(params: FCKStaticTransformerParams = {}) {
        super();
        this.params = { ...params };
    }

    transform(X: Matrix): Matrix {
        return this.transformMatrix(X);
    }
}
NativeEstimator.register("preprocessing.specialized.fck_static", FCKStaticTransformer);

/** Parameters of DirectStandardization; unset values take the native defaults. */
export interface DirectStandardizationParams {
    /** Default true. */
    fit_intercept?: boolean;
    /** Default 0. */
    ridge?: number;
}

/** Native `preprocessing.transfer.direct_standardization` (transformer). Required fit inputs: target_domain. */
export class DirectStandardization extends NativeEstimator implements Transformer {
    readonly methodId = "preprocessing.transfer.direct_standardization";
    protected readonly paramTypes = {
        fit_intercept: "bool",
        ridge: "double",
    } as const;

    constructor(params: DirectStandardizationParams = {}) {
        super();
        this.params = { ...params };
    }

    transform(X: Matrix): Matrix {
        return this.transformMatrix(X);
    }
}
NativeEstimator.register("preprocessing.transfer.direct_standardization", DirectStandardization);

/** Parameters of PiecewiseDirectStandardization; unset values take the native defaults. */
export interface PiecewiseDirectStandardizationParams {
    /** Default 5. */
    window_size?: number;
    /** Default true. */
    fit_intercept?: boolean;
    /** Default 0. */
    ridge?: number;
}

/** Native `preprocessing.transfer.piecewise_direct_standardization` (transformer). Required fit inputs: target_domain. */
export class PiecewiseDirectStandardization extends NativeEstimator implements Transformer {
    readonly methodId = "preprocessing.transfer.piecewise_direct_standardization";
    protected readonly paramTypes = {
        window_size: "int",
        fit_intercept: "bool",
        ridge: "double",
    } as const;

    constructor(params: PiecewiseDirectStandardizationParams = {}) {
        super();
        this.params = { ...params };
    }

    transform(X: Matrix): Matrix {
        return this.transformMatrix(X);
    }
}
NativeEstimator.register("preprocessing.transfer.piecewise_direct_standardization", PiecewiseDirectStandardization);

/** Parameters of RobustDirectStandardization; unset values take the native defaults. */
export interface RobustDirectStandardizationParams {
    /** Default true. */
    fit_intercept?: boolean;
    /** Default 0. */
    ridge?: number;
    /** Default 0.9. */
    trim_quantile?: number;
    /** Default 3. */
    max_iter?: number;
}

/** Native `preprocessing.transfer.robust_direct_standardization` (transformer). Required fit inputs: target_domain. */
export class RobustDirectStandardization extends NativeEstimator implements Transformer {
    readonly methodId = "preprocessing.transfer.robust_direct_standardization";
    protected readonly paramTypes = {
        fit_intercept: "bool",
        ridge: "double",
        trim_quantile: "double",
        max_iter: "int",
    } as const;

    constructor(params: RobustDirectStandardizationParams = {}) {
        super();
        this.params = { ...params };
    }

    transform(X: Matrix): Matrix {
        return this.transformMatrix(X);
    }
}
NativeEstimator.register("preprocessing.transfer.robust_direct_standardization", RobustDirectStandardization);

/** Parameters of Haar; unset values take the native defaults. */
export interface HaarParams {
}

/** Native `preprocessing.wavelets.haar` (transformer). */
export class Haar extends NativeEstimator implements Transformer {
    readonly methodId = "preprocessing.wavelets.haar";
    protected readonly paramTypes = {
    } as const;

    constructor(params: HaarParams = {}) {
        super();
        this.params = { ...params };
    }

    transform(X: Matrix): Matrix {
        return this.transformMatrix(X);
    }
}
NativeEstimator.register("preprocessing.wavelets.haar", Haar);

/** Parameters of Wavelet; unset values take the native defaults. */
export interface WaveletParams {
    /** Default "haar". */
    family?: "haar" | "db4" | "sym4" | "coif1";
    /** Default "periodization". */
    mode?: "periodization" | "symmetric" | "zero";
}

/** Native `preprocessing.wavelets.wavelet` (transformer). */
export class Wavelet extends NativeEstimator implements Transformer {
    readonly methodId = "preprocessing.wavelets.wavelet";
    protected readonly paramTypes = {
        family: "enum",
        mode: "enum",
    } as const;

    constructor(params: WaveletParams = {}) {
        super();
        this.params = { ...params };
    }

    transform(X: Matrix): Matrix {
        return this.transformMatrix(X);
    }
}
NativeEstimator.register("preprocessing.wavelets.wavelet", Wavelet);

/** Parameters of WaveletDenoise; unset values take the native defaults. */
export interface WaveletDenoiseParams {
    /** Default "db4". */
    family?: "haar" | "db4" | "sym4" | "coif1";
    /** Default "periodization". */
    mode?: "periodization" | "symmetric" | "zero";
    /** Default 3. */
    level?: number;
    /** Default "soft". */
    threshold_mode?: "soft" | "hard";
    /** Default "median". */
    noise_estimator?: "median" | "std";
}

/** Native `preprocessing.wavelets.wavelet_denoise` (transformer). */
export class WaveletDenoise extends NativeEstimator implements Transformer {
    readonly methodId = "preprocessing.wavelets.wavelet_denoise";
    protected readonly paramTypes = {
        family: "enum",
        mode: "enum",
        level: "int",
        threshold_mode: "enum",
        noise_estimator: "enum",
    } as const;

    constructor(params: WaveletDenoiseParams = {}) {
        super();
        this.params = { ...params };
    }

    transform(X: Matrix): Matrix {
        return this.transformMatrix(X);
    }
}
NativeEstimator.register("preprocessing.wavelets.wavelet_denoise", WaveletDenoise);

/** Parameters of WaveletFeatures; unset values take the native defaults. */
export interface WaveletFeaturesParams {
    /** Default "haar". */
    family?: "haar" | "db4" | "sym4" | "coif1";
    /** Default "periodization". */
    mode?: "periodization" | "symmetric" | "zero";
    /** Default 3. */
    max_level?: number;
    /** Default "energy". */
    entropy?: "energy" | "histogram";
}

/** Native `preprocessing.wavelets.wavelet_features` (transformer). */
export class WaveletFeatures extends NativeEstimator implements Transformer {
    readonly methodId = "preprocessing.wavelets.wavelet_features";
    protected readonly paramTypes = {
        family: "enum",
        mode: "enum",
        max_level: "int",
        entropy: "enum",
    } as const;

    constructor(params: WaveletFeaturesParams = {}) {
        super();
        this.params = { ...params };
    }

    transform(X: Matrix): Matrix {
        return this.transformMatrix(X);
    }
}
NativeEstimator.register("preprocessing.wavelets.wavelet_features", WaveletFeatures);

/** Parameters of WaveletPCA; unset values take the native defaults. */
export interface WaveletPCAParams {
    /** Default "haar". */
    family?: "haar" | "db4" | "sym4" | "coif1";
    /** Default "periodization". */
    mode?: "periodization" | "symmetric" | "zero";
    /** Default 2. */
    max_level?: number;
    /** Default 5. */
    n_components?: number;
}

/** Native `preprocessing.wavelets.wavelet_pca` (transformer). */
export class WaveletPCA extends NativeEstimator implements Transformer {
    readonly methodId = "preprocessing.wavelets.wavelet_pca";
    protected readonly paramTypes = {
        family: "enum",
        mode: "enum",
        max_level: "int",
        n_components: "double",
    } as const;

    constructor(params: WaveletPCAParams = {}) {
        super();
        this.params = { ...params };
    }

    transform(X: Matrix): Matrix {
        return this.transformMatrix(X);
    }
}
NativeEstimator.register("preprocessing.wavelets.wavelet_pca", WaveletPCA);

/** Parameters of WaveletSVD; unset values take the native defaults. */
export interface WaveletSVDParams {
    /** Default "haar". */
    family?: "haar" | "db4" | "sym4" | "coif1";
    /** Default "periodization". */
    mode?: "periodization" | "symmetric" | "zero";
    /** Default 2. */
    max_level?: number;
    /** Default 5. */
    n_components?: number;
}

/** Native `preprocessing.wavelets.wavelet_svd` (transformer). */
export class WaveletSVD extends NativeEstimator implements Transformer {
    readonly methodId = "preprocessing.wavelets.wavelet_svd";
    protected readonly paramTypes = {
        family: "enum",
        mode: "enum",
        max_level: "int",
        n_components: "double",
    } as const;

    constructor(params: WaveletSVDParams = {}) {
        super();
        this.params = { ...params };
    }

    transform(X: Matrix): Matrix {
        return this.transformMatrix(X);
    }
}
NativeEstimator.register("preprocessing.wavelets.wavelet_svd", WaveletSVD);

/** Parameters of BiPLS; unset values take the native defaults. */
export interface BiPLSParams {
    /** Default 2. */
    n_components?: number;
    /** Default 10. */
    interval_width?: number;
    /** Default 2. */
    min_intervals?: number;
    /** Default 3. */
    cv?: number;
}

/** Native `selection.bipls` (selector). */
export class BiPLS extends NativeEstimator implements Selector {
    readonly methodId = "selection.bipls";
    protected readonly paramTypes = {
        n_components: "int",
        interval_width: "int",
        min_intervals: "int",
        cv: "int",
    } as const;

    constructor(params: BiPLSParams = {}) {
        super();
        this.params = { ...params };
    }

    transform(X: Matrix): Matrix {
        return this.transformMatrix(X);
    }

    selectedIndices(): number[] {
        return this.selectedIndexArray();
    }
}
NativeEstimator.register("selection.bipls", BiPLS);

/** Parameters of BVE; unset values take the native defaults. */
export interface BVEParams {
    /** Default 2. */
    n_components?: number;
    /** Default 10. */
    n_steps?: number;
    /** Default 0. */
    min_features?: number;
    /** Default 3. */
    cv?: number;
}

/** Native `selection.bve` (selector). */
export class BVE extends NativeEstimator implements Selector {
    readonly methodId = "selection.bve";
    protected readonly paramTypes = {
        n_components: "int",
        n_steps: "int",
        min_features: "int",
        cv: "int",
    } as const;

    constructor(params: BVEParams = {}) {
        super();
        this.params = { ...params };
    }

    transform(X: Matrix): Matrix {
        return this.transformMatrix(X);
    }

    selectedIndices(): number[] {
        return this.selectedIndexArray();
    }
}
NativeEstimator.register("selection.bve", BVE);

/** Parameters of CARS; unset values take the native defaults. */
export interface CARSParams {
    /** Default 2. */
    n_components?: number;
    /** Default 50. */
    n_iterations?: number;
    /** Default 0. */
    min_features?: number;
    /** Default 3. */
    cv?: number;
}

/** Native `selection.cars` (selector). */
export class CARS extends NativeEstimator implements Selector {
    readonly methodId = "selection.cars";
    protected readonly paramTypes = {
        n_components: "int",
        n_iterations: "int",
        min_features: "int",
        cv: "int",
    } as const;

    constructor(params: CARSParams = {}) {
        super();
        this.params = { ...params };
    }

    transform(X: Matrix): Matrix {
        return this.transformMatrix(X);
    }

    selectedIndices(): number[] {
        return this.selectedIndexArray();
    }
}
NativeEstimator.register("selection.cars", CARS);

/** Parameters of EMCUVE; unset values take the native defaults. */
export interface EMCUVEParams {
    /** Default 2. */
    n_components?: number;
    /** Default 50. */
    noise_features?: number;
    /** Default 0. */
    noise_seed?: number;
    /** Default 10. */
    n_ensembles?: number;
    /** Default 0.5. */
    vote_threshold?: number;
    /** Default 3. */
    cv?: number;
}

/** Native `selection.emcuve` (selector). */
export class EMCUVE extends NativeEstimator implements Selector {
    readonly methodId = "selection.emcuve";
    protected readonly paramTypes = {
        n_components: "int",
        noise_features: "int",
        noise_seed: "int",
        n_ensembles: "int",
        vote_threshold: "double",
        cv: "int",
    } as const;

    constructor(params: EMCUVEParams = {}) {
        super();
        this.params = { ...params };
    }

    transform(X: Matrix): Matrix {
        return this.transformMatrix(X);
    }

    selectedIndices(): number[] {
        return this.selectedIndexArray();
    }
}
NativeEstimator.register("selection.emcuve", EMCUVE);

/** Parameters of GA; unset values take the native defaults. */
export interface GAParams {
    /** Default 2. */
    n_components?: number;
    /** Default 30. */
    n_generations?: number;
    /** Default 40. */
    population_size?: number;
    /** Default 0. */
    min_features?: number;
    /** Default 0. */
    max_features?: number;
    /** Default 0.05. */
    mutation_rate?: number;
    /** Default 3. */
    cv?: number;
    /** Default 0. */
    seed?: number;
}

/** Native `selection.ga` (selector). */
export class GA extends NativeEstimator implements Selector {
    readonly methodId = "selection.ga";
    protected readonly paramTypes = {
        n_components: "int",
        n_generations: "int",
        population_size: "int",
        min_features: "int",
        max_features: "int",
        mutation_rate: "double",
        cv: "int",
        seed: "int",
    } as const;

    constructor(params: GAParams = {}) {
        super();
        this.params = { ...params };
    }

    transform(X: Matrix): Matrix {
        return this.transformMatrix(X);
    }

    selectedIndices(): number[] {
        return this.selectedIndexArray();
    }
}
NativeEstimator.register("selection.ga", GA);

/** Parameters of IPW; unset values take the native defaults. */
export interface IPWParams {
    /** Required. */
    top_k?: number;
    /** Default 2. */
    n_components?: number;
    /** Default 20. */
    n_iterations?: number;
    /** Default 0.5. */
    damping?: number;
    /** Default 1e-06. */
    weight_floor?: number;
    /** Default 3. */
    cv?: number;
}

/** Native `selection.ipw` (selector). */
export class IPW extends NativeEstimator implements Selector {
    readonly methodId = "selection.ipw";
    protected readonly paramTypes = {
        top_k: "int",
        n_components: "int",
        n_iterations: "int",
        damping: "double",
        weight_floor: "double",
        cv: "int",
    } as const;

    constructor(params: IPWParams = {}) {
        super();
        this.params = { ...params };
    }

    transform(X: Matrix): Matrix {
        return this.transformMatrix(X);
    }

    selectedIndices(): number[] {
        return this.selectedIndexArray();
    }
}
NativeEstimator.register("selection.ipw", IPW);

/** Parameters of IRF; unset values take the native defaults. */
export interface IRFParams {
    /** Required. */
    top_k?: number;
    /** Default 2. */
    n_components?: number;
    /** Default 100. */
    n_iterations?: number;
    /** Default 5. */
    window_size?: number;
    /** Default 5. */
    initial_intervals?: number;
    /** Default 3. */
    cv?: number;
    /** Default 0. */
    seed?: number;
}

/** Native `selection.irf` (selector). */
export class IRF extends NativeEstimator implements Selector {
    readonly methodId = "selection.irf";
    protected readonly paramTypes = {
        top_k: "int",
        n_components: "int",
        n_iterations: "int",
        window_size: "int",
        initial_intervals: "int",
        cv: "int",
        seed: "int",
    } as const;

    constructor(params: IRFParams = {}) {
        super();
        this.params = { ...params };
    }

    transform(X: Matrix): Matrix {
        return this.transformMatrix(X);
    }

    selectedIndices(): number[] {
        return this.selectedIndexArray();
    }
}
NativeEstimator.register("selection.irf", IRF);

/** Parameters of IRIV; unset values take the native defaults. */
export interface IRIVParams {
    /** Default 2. */
    n_components?: number;
    /** Default 5. */
    max_rounds?: number;
    /** Default 5. */
    cv?: number;
    /** Default 0. */
    seed?: number;
}

/** Native `selection.iriv` (selector). */
export class IRIV extends NativeEstimator implements Selector {
    readonly methodId = "selection.iriv";
    protected readonly paramTypes = {
        n_components: "int",
        max_rounds: "int",
        cv: "int",
        seed: "int",
    } as const;

    constructor(params: IRIVParams = {}) {
        super();
        this.params = { ...params };
    }

    transform(X: Matrix): Matrix {
        return this.transformMatrix(X);
    }

    selectedIndices(): number[] {
        return this.selectedIndexArray();
    }
}
NativeEstimator.register("selection.iriv", IRIV);

/** Parameters of PSO; unset values take the native defaults. */
export interface PSOParams {
    /** Default 2. */
    n_components?: number;
    /** Default 30. */
    n_swarm?: number;
    /** Default 50. */
    n_iterations?: number;
    /** Default 0.729. */
    w?: number;
    /** Default 1.494. */
    c1?: number;
    /** Default 1.494. */
    c2?: number;
    /** Default 4. */
    v_max?: number;
    /** Default 3. */
    cv?: number;
    /** Default 0. */
    seed?: number;
}

/** Native `selection.pso` (selector). */
export class PSO extends NativeEstimator implements Selector {
    readonly methodId = "selection.pso";
    protected readonly paramTypes = {
        n_components: "int",
        n_swarm: "int",
        n_iterations: "int",
        w: "double",
        c1: "double",
        c2: "double",
        v_max: "double",
        cv: "int",
        seed: "int",
    } as const;

    constructor(params: PSOParams = {}) {
        super();
        this.params = { ...params };
    }

    transform(X: Matrix): Matrix {
        return this.transformMatrix(X);
    }

    selectedIndices(): number[] {
        return this.selectedIndexArray();
    }
}
NativeEstimator.register("selection.pso", PSO);

/** Parameters of RandomFrog; unset values take the native defaults. */
export interface RandomFrogParams {
    /** Required. */
    top_k?: number;
    /** Default 2. */
    n_components?: number;
    /** Default 100. */
    n_iterations?: number;
    /** Default 20. */
    initial_size?: number;
    /** Default 0. */
    min_size?: number;
    /** Default 0. */
    max_size?: number;
    /** Default 3. */
    cv?: number;
    /** Default 0. */
    seed?: number;
}

/** Native `selection.random_frog` (selector). */
export class RandomFrog extends NativeEstimator implements Selector {
    readonly methodId = "selection.random_frog";
    protected readonly paramTypes = {
        top_k: "int",
        n_components: "int",
        n_iterations: "int",
        initial_size: "int",
        min_size: "int",
        max_size: "int",
        cv: "int",
        seed: "int",
    } as const;

    constructor(params: RandomFrogParams = {}) {
        super();
        this.params = { ...params };
    }

    transform(X: Matrix): Matrix {
        return this.transformMatrix(X);
    }

    selectedIndices(): number[] {
        return this.selectedIndexArray();
    }
}
NativeEstimator.register("selection.random_frog", RandomFrog);

/** Parameters of Randomization; unset values take the native defaults. */
export interface RandomizationParams {
    /** Default 2. */
    n_components?: number;
    /** Default 200. */
    n_permutations?: number;
    /** Default 0. */
    randomization_seed?: number;
    /** Default 0.05. */
    alpha?: number;
}

/** Native `selection.randomization` (selector). */
export class Randomization extends NativeEstimator implements Selector {
    readonly methodId = "selection.randomization";
    protected readonly paramTypes = {
        n_components: "int",
        n_permutations: "int",
        randomization_seed: "int",
        alpha: "double",
    } as const;

    constructor(params: RandomizationParams = {}) {
        super();
        this.params = { ...params };
    }

    transform(X: Matrix): Matrix {
        return this.transformMatrix(X);
    }

    selectedIndices(): number[] {
        return this.selectedIndexArray();
    }
}
NativeEstimator.register("selection.randomization", Randomization);

/** Parameters of REP; unset values take the native defaults. */
export interface REPParams {
    /** Default 2. */
    n_components?: number;
    /** Default 10. */
    n_steps?: number;
    /** Default 0. */
    min_features?: number;
    /** Default 1. */
    remove_count?: number;
    /** Default 3. */
    cv?: number;
}

/** Native `selection.rep` (selector). */
export class REP extends NativeEstimator implements Selector {
    readonly methodId = "selection.rep";
    protected readonly paramTypes = {
        n_components: "int",
        n_steps: "int",
        min_features: "int",
        remove_count: "int",
        cv: "int",
    } as const;

    constructor(params: REPParams = {}) {
        super();
        this.params = { ...params };
    }

    transform(X: Matrix): Matrix {
        return this.transformMatrix(X);
    }

    selectedIndices(): number[] {
        return this.selectedIndexArray();
    }
}
NativeEstimator.register("selection.rep", REP);

/** Parameters of SCARS; unset values take the native defaults. */
export interface SCARSParams {
    /** Default 2. */
    n_components?: number;
    /** Default 50. */
    n_iterations?: number;
    /** Default 0. */
    min_features?: number;
    /** Default 0.8. */
    sample_fraction?: number;
    /** Default 3. */
    cv?: number;
    /** Default 0. */
    seed?: number;
}

/** Native `selection.scars` (selector). */
export class SCARS extends NativeEstimator implements Selector {
    readonly methodId = "selection.scars";
    protected readonly paramTypes = {
        n_components: "int",
        n_iterations: "int",
        min_features: "int",
        sample_fraction: "double",
        cv: "int",
        seed: "int",
    } as const;

    constructor(params: SCARSParams = {}) {
        super();
        this.params = { ...params };
    }

    transform(X: Matrix): Matrix {
        return this.transformMatrix(X);
    }

    selectedIndices(): number[] {
        return this.selectedIndexArray();
    }
}
NativeEstimator.register("selection.scars", SCARS);

/** Parameters of Shaving; unset values take the native defaults. */
export interface ShavingParams {
    /** Default 2. */
    n_components?: number;
    /** Default 10. */
    n_steps?: number;
    /** Default 0. */
    min_features?: number;
    /** Default 0.2. */
    shave_fraction?: number;
    /** Default 3. */
    cv?: number;
}

/** Native `selection.shaving` (selector). */
export class Shaving extends NativeEstimator implements Selector {
    readonly methodId = "selection.shaving";
    protected readonly paramTypes = {
        n_components: "int",
        n_steps: "int",
        min_features: "int",
        shave_fraction: "double",
        cv: "int",
    } as const;

    constructor(params: ShavingParams = {}) {
        super();
        this.params = { ...params };
    }

    transform(X: Matrix): Matrix {
        return this.transformMatrix(X);
    }

    selectedIndices(): number[] {
        return this.selectedIndexArray();
    }
}
NativeEstimator.register("selection.shaving", Shaving);

/** Parameters of SiPLS; unset values take the native defaults. */
export interface SiPLSParams {
    /** Default 2. */
    n_components?: number;
    /** Default 10. */
    interval_width?: number;
    /** Default 2. */
    combination_size?: number;
    /** Default 3. */
    cv?: number;
}

/** Native `selection.sipls` (selector). */
export class SiPLS extends NativeEstimator implements Selector {
    readonly methodId = "selection.sipls";
    protected readonly paramTypes = {
        n_components: "int",
        interval_width: "int",
        combination_size: "int",
        cv: "int",
    } as const;

    constructor(params: SiPLSParams = {}) {
        super();
        this.params = { ...params };
    }

    transform(X: Matrix): Matrix {
        return this.transformMatrix(X);
    }

    selectedIndices(): number[] {
        return this.selectedIndexArray();
    }
}
NativeEstimator.register("selection.sipls", SiPLS);

/** Parameters of SPA; unset values take the native defaults. */
export interface SPAParams {
    /** Required. */
    top_k?: number;
    /** Default 2. */
    n_components?: number;
}

/** Native `selection.spa` (selector). */
export class SPA extends NativeEstimator implements Selector {
    readonly methodId = "selection.spa";
    protected readonly paramTypes = {
        top_k: "int",
        n_components: "int",
    } as const;

    constructor(params: SPAParams = {}) {
        super();
        this.params = { ...params };
    }

    transform(X: Matrix): Matrix {
        return this.transformMatrix(X);
    }

    selectedIndices(): number[] {
        return this.selectedIndexArray();
    }
}
NativeEstimator.register("selection.spa", SPA);

/** Parameters of ST; unset values take the native defaults. */
export interface STParams {
    /** Required. */
    thresholds?: number[];
    /** Default 2. */
    n_components?: number;
    /** Default 0. */
    min_selected?: number;
    /** Default 3. */
    cv?: number;
}

/** Native `selection.st` (selector). */
export class ST extends NativeEstimator implements Selector {
    readonly methodId = "selection.st";
    protected readonly paramTypes = {
        thresholds: "double_array",
        n_components: "int",
        min_selected: "int",
        cv: "int",
    } as const;

    constructor(params: STParams = {}) {
        super();
        this.params = { ...params };
    }

    transform(X: Matrix): Matrix {
        return this.transformMatrix(X);
    }

    selectedIndices(): number[] {
        return this.selectedIndexArray();
    }
}
NativeEstimator.register("selection.st", ST);

/** Parameters of Stability; unset values take the native defaults. */
export interface StabilityParams {
    /** Required. */
    top_k?: number;
    /** Default 2. */
    n_components?: number;
    /** Default 3. */
    cv?: number;
}

/** Native `selection.stability` (selector). */
export class Stability extends NativeEstimator implements Selector {
    readonly methodId = "selection.stability";
    protected readonly paramTypes = {
        top_k: "int",
        n_components: "int",
        cv: "int",
    } as const;

    constructor(params: StabilityParams = {}) {
        super();
        this.params = { ...params };
    }

    transform(X: Matrix): Matrix {
        return this.transformMatrix(X);
    }

    selectedIndices(): number[] {
        return this.selectedIndexArray();
    }
}
NativeEstimator.register("selection.stability", Stability);

/** Parameters of T2; unset values take the native defaults. */
export interface T2Params {
    /** Required. */
    alpha_thresholds?: number[];
    /** Default 2. */
    n_components?: number;
    /** Default 0. */
    min_selected?: number;
    /** Default 3. */
    cv?: number;
}

/** Native `selection.t2` (selector). */
export class T2 extends NativeEstimator implements Selector {
    readonly methodId = "selection.t2";
    protected readonly paramTypes = {
        alpha_thresholds: "double_array",
        n_components: "int",
        min_selected: "int",
        cv: "int",
    } as const;

    constructor(params: T2Params = {}) {
        super();
        this.params = { ...params };
    }

    transform(X: Matrix): Matrix {
        return this.transformMatrix(X);
    }

    selectedIndices(): number[] {
        return this.selectedIndexArray();
    }
}
NativeEstimator.register("selection.t2", T2);

/** Parameters of UVE; unset values take the native defaults. */
export interface UVEParams {
    /** Default 2. */
    n_components?: number;
    /** Default 50. */
    noise_features?: number;
    /** Default 0. */
    noise_seed?: number;
    /** Default -1. */
    min_features?: number;
    /** Default 3. */
    cv?: number;
}

/** Native `selection.uve` (selector). */
export class UVE extends NativeEstimator implements Selector {
    readonly methodId = "selection.uve";
    protected readonly paramTypes = {
        n_components: "int",
        noise_features: "int",
        noise_seed: "int",
        min_features: "int",
        cv: "int",
    } as const;

    constructor(params: UVEParams = {}) {
        super();
        this.params = { ...params };
    }

    transform(X: Matrix): Matrix {
        return this.transformMatrix(X);
    }

    selectedIndices(): number[] {
        return this.selectedIndexArray();
    }
}
NativeEstimator.register("selection.uve", UVE);

/** Parameters of VariableSelect; unset values take the native defaults. */
export interface VariableSelectParams {
    /** Required. */
    top_k?: number;
    /** Default 2. */
    n_components?: number;
    /** Default "vip". */
    rank_method?: "vip" | "coefficient" | "selectivity_ratio";
}

/** Native `selection.variable_select` (selector). */
export class VariableSelect extends NativeEstimator implements Selector {
    readonly methodId = "selection.variable_select";
    protected readonly paramTypes = {
        top_k: "int",
        n_components: "int",
        rank_method: "enum",
    } as const;

    constructor(params: VariableSelectParams = {}) {
        super();
        this.params = { ...params };
    }

    transform(X: Matrix): Matrix {
        return this.transformMatrix(X);
    }

    selectedIndices(): number[] {
        return this.selectedIndexArray();
    }
}
NativeEstimator.register("selection.variable_select", VariableSelect);

/** Parameters of VIPSPA; unset values take the native defaults. */
export interface VIPSPAParams {
    /** Required. */
    top_k?: number;
    /** Default 2. */
    n_components?: number;
    /** Default 0.3. */
    vip_threshold?: number;
}

/** Native `selection.vip_spa` (selector). */
export class VIPSPA extends NativeEstimator implements Selector {
    readonly methodId = "selection.vip_spa";
    protected readonly paramTypes = {
        top_k: "int",
        n_components: "int",
        vip_threshold: "double",
    } as const;

    constructor(params: VIPSPAParams = {}) {
        super();
        this.params = { ...params };
    }

    transform(X: Matrix): Matrix {
        return this.transformMatrix(X);
    }

    selectedIndices(): number[] {
        return this.selectedIndexArray();
    }
}
NativeEstimator.register("selection.vip_spa", VIPSPA);

/** Parameters of VISSA; unset values take the native defaults. */
export interface VISSAParams {
    /** Default 2. */
    n_components?: number;
    /** Default 10. */
    n_iterations?: number;
    /** Default 60. */
    n_submodels?: number;
    /** Default 0.1. */
    ratio_kept?: number;
    /** Default 0.5. */
    threshold?: number;
    /** Default 0.05. */
    floor_probability?: number;
    /** Default 3. */
    cv?: number;
    /** Default 0. */
    seed?: number;
}

/** Native `selection.vissa` (selector). */
export class VISSA extends NativeEstimator implements Selector {
    readonly methodId = "selection.vissa";
    protected readonly paramTypes = {
        n_components: "int",
        n_iterations: "int",
        n_submodels: "int",
        ratio_kept: "double",
        threshold: "double",
        floor_probability: "double",
        cv: "int",
        seed: "int",
    } as const;

    constructor(params: VISSAParams = {}) {
        super();
        this.params = { ...params };
    }

    transform(X: Matrix): Matrix {
        return this.transformMatrix(X);
    }

    selectedIndices(): number[] {
        return this.selectedIndexArray();
    }
}
NativeEstimator.register("selection.vissa", VISSA);

/** Parameters of WVC; unset values take the native defaults. */
export interface WVCParams {
    /** Required. */
    top_k?: number;
    /** Default 2. */
    n_components?: number;
    /** Default true. */
    normalize?: boolean;
}

/** Native `selection.wvc` (selector). */
export class WVC extends NativeEstimator implements Selector {
    readonly methodId = "selection.wvc";
    protected readonly paramTypes = {
        top_k: "int",
        n_components: "int",
        normalize: "bool",
    } as const;

    constructor(params: WVCParams = {}) {
        super();
        this.params = { ...params };
    }

    transform(X: Matrix): Matrix {
        return this.transformMatrix(X);
    }

    selectedIndices(): number[] {
        return this.selectedIndexArray();
    }
}
NativeEstimator.register("selection.wvc", WVC);

/** Parameters of WVCThreshold; unset values take the native defaults. */
export interface WVCThresholdParams {
    /** Default 2. */
    n_components?: number;
    /** Default true. */
    normalize?: boolean;
    /** Default 0. */
    score_threshold?: number;
    /** Default 1. */
    threshold_factor?: number;
    /** Default 0. */
    min_selected?: number;
}

/** Native `selection.wvc_threshold` (selector). */
export class WVCThreshold extends NativeEstimator implements Selector {
    readonly methodId = "selection.wvc_threshold";
    protected readonly paramTypes = {
        n_components: "int",
        normalize: "bool",
        score_threshold: "double",
        threshold_factor: "double",
        min_selected: "int",
    } as const;

    constructor(params: WVCThresholdParams = {}) {
        super();
        this.params = { ...params };
    }

    transform(X: Matrix): Matrix {
        return this.transformMatrix(X);
    }

    selectedIndices(): number[] {
        return this.selectedIndexArray();
    }
}
NativeEstimator.register("selection.wvc_threshold", WVCThreshold);
