# SPDX-License-Identifier: CECILL-2.1
"""AOM-focused public facade.

This module keeps AOM discoverable as a coherent product surface while reusing
the single ``libn4m`` C/CUDA runtime and the existing ``n4m.python`` /
``n4m.sklearn`` bindings.
"""
from __future__ import annotations

from . import native as _native
from . import (
    AOMCandidateSpec,
    AOMControlSelector,
    AOMDatasetMetadata,
    AOMEndpointMarginStabilityGate,
    AOMFallbackBlendGate,
    AOMMidPEndpointStack,
    AOMOperatorPLSStack,
    AOMOperatorPLSSpec,
    AOMPreprocessingChain,
    AOMRidgeBlender,
    AOMRobustHPOCompact,
    AOMRobustHPORegressor,
    AOMRobustHPOWide,
    AOMStructuralPolicy,
    AOMStructuralPolicyWithP700BlockLocalAdmission,
    AOMStructuralPolicyWithP700ProtocolUnified,
    AOMStructuralPolicyWithPgt1200Admissions,
    AOMTrueBankEndpointPortfolio,
    EndpointStabilityDecision,
    NativeAOMChainRidgePLSRegressor,
    NativeAOMChainSweepRegressor,
    NativeAOMFixedCandidateRegressor,
    NativeAOMMomentPLSScreenRefitRegressor,
    NativeAOMMomentPLSExactScreenRefitRegressor,
    NativeAOMMomentRidgeScreenRefitRegressor,
    NativeAOMMomentScreenRefitRegressor,
    NativeAOMOperatorPLSStackRegressor,
    NativeAOMPLSRegressor,
    NativeAOMPLSSuperblockRegressor,
    NativeAOMRidgePLSSuperblockRegressor,
    NativeAOMRidgeBlenderRegressor,
    NativeAOMRidgeActiveSuperblockRegressor,
    NativeAOMRidgeGlobalRegressor,
    NativeAOMRidgeMKLSuperblockRegressor,
    NativeAOMRidgeSuperblockRegressor,
    NativeAOMRobustHPORegressor,
    NativeAOMSavgolFocusRegressor,
    NativeAOMScreenRefitRegressor,
    NativeAOMStrictFamilyLiteRegressor,
    NativeAOMStagedChainCampaignRegressor,
    NativeAOMSweepRegressor,
    NativePOPPLSRegressor,
    build_aom_control_chain_bank,
)

aom_robust_hpo = _native.aom_robust_hpo
aom_global_select = _native.aom_global_select
aom_per_component_select = _native.aom_per_component_select
aom_pls = _native.aom_pls
aom_pls_superblock = _native.aom_pls_superblock
pop_pls = _native.pop_pls
aom_preprocess = _native.aom_preprocess
aom_chain_ridge_pls = _native.aom_chain_ridge_pls
aom_sweep_run = _native.aom_sweep_run
aom_chain_sweep_run = _native.aom_chain_sweep_run
aom_chain_fixed_fit_run = _native.aom_chain_fixed_fit_run
aom_chain_score_campaign = _native.aom_chain_score_campaign
aom_chain_screen_refit_campaign = _native.aom_chain_screen_refit_campaign
aom_moment_screen_refit_campaign = _native.aom_moment_screen_refit_campaign
aom_staged_chain_campaign = _native.aom_staged_chain_campaign
aom_screen_refit_candidate_pool = _native.aom_screen_refit_candidate_pool
aom_refit_execution_plan = _native.aom_refit_execution_plan
aom_refit_candidates = _native.aom_refit_candidates
aom_evaluate_candidates = _native.aom_evaluate_candidates
aom_candidate_table = _native.aom_candidate_table
aom_candidate_operator_summary = _native.aom_candidate_operator_summary
aom_candidate_preprocessing_impact = _native.aom_candidate_preprocessing_impact
aom_candidate_route_summary = _native.aom_candidate_route_summary
aom_candidate_rank_diagnostics = _native.aom_candidate_rank_diagnostics
aom_candidate_report_records = _native.aom_candidate_report_records
aom_load_candidate_report = _native.aom_load_candidate_report
aom_save_candidate_report = _native.aom_save_candidate_report
build_aom_strict_chain_grid = _native.build_aom_strict_chain_grid
iter_aom_strict_chain_grid = _native.iter_aom_strict_chain_grid
decode_aom_chains = _native.decode_aom_chains
aom_ridge_blender = _native.aom_ridge_blender
aom_ridge_active_superblock = _native.aom_ridge_active_superblock
aom_ridge_global = _native.aom_ridge_global
aom_ridge_mkl_superblock = _native.aom_ridge_mkl_superblock
aom_ridge_pls_superblock = _native.aom_ridge_pls_superblock
aom_ridge_superblock = _native.aom_ridge_superblock
aom_operator_pls_stack = _native.aom_operator_pls_stack

_MODEL_SCALE_OPTIONS = (
    "center_x",
    "scale_x",
    "center_y",
    "scale_y",
)
_CUDA_PLS_OPTIONS = (
    "cuda_pls_parallel_folds",
    "cuda_pls_min_device_features",
    "cuda_pls_many_batched",
)
_SCORE_CAMPAIGN_OPTIONS = (
    "chains",
    "profile",
    "families",
    "templates",
    "max_chains",
    "chain_chunk_size",
    "top_k",
    "cv",
    "fold_ids",
    "ridge_lambdas",
    "pls_components",
    "heads",
    *_MODEL_SCALE_OPTIONS,
    "moment_policy",
    "pls_score_mode",
    "chain_ordering",
    "split_head_scoring",
    *_CUDA_PLS_OPTIONS,
    "backend_cuda_available",
    "backend_min_cuda_product",
    "checkpoint_path",
    "resume",
    "max_chunks_per_run",
)
_SCREEN_REFIT_OPTIONS = (
    "chains",
    "profile",
    "families",
    "templates",
    "max_chains",
    "chain_chunk_size",
    "top_k",
    "refit_top_k",
    "refit_per_head_top_k",
    "final_rank",
    "cv",
    "fold_ids",
    "ridge_lambdas",
    "pls_components",
    "heads",
    *_MODEL_SCALE_OPTIONS,
    "moment_policy",
    "refit_moment_policy",
    "final_moment_policy",
    "pls_score_mode",
    "chain_ordering",
    "split_head_scoring",
    "checkpoint_path",
    "resume",
    "max_chunks_per_run",
    "backend_cuda_available",
    "backend_min_cuda_product",
    *_CUDA_PLS_OPTIONS,
    "refit_sort_by",
    "refit_execution",
    "refit_auto_max_extra_fraction",
)
_STAGED_CAMPAIGN_OPTIONS = (
    "stages",
    "plan",
    "cv",
    "fold_ids",
    "ridge_lambdas",
    "pls_components",
    "heads",
    "top_k",
    "refit_top_k",
    "refit_per_head_top_k",
    "families",
    "templates",
    "max_chains",
    "chain_chunk_size",
    "checkpoint_dir",
    "resume",
    "max_chunks_per_run",
    *_MODEL_SCALE_OPTIONS,
    "scale_x_values",
    "moment_policy",
    "refit_moment_policy",
    "pls_score_mode",
    "chain_ordering",
    "split_head_scoring",
    "backend_cuda_available",
    "backend_min_cuda_product",
    *_CUDA_PLS_OPTIONS,
    "refit_sort_by",
    "refit_execution",
    "refit_auto_max_extra_fraction",
    "return_predictions",
    "impact",
    "rank_diagnostics",
    "impact_top_k",
    "X_audit",
    "y_audit",
    "audit_top_k",
    "return_stage_screens",
)
_STAGED_CAMPAIGN_ESTIMATOR_OPTIONS = tuple(
    option for option in _STAGED_CAMPAIGN_OPTIONS
    if option not in {
        "return_predictions",
        "X_audit",
        "y_audit",
        "audit_top_k",
    }
) + (
    "final_rank",
    "final_moment_policy",
)
_SAVGOL_FOCUS_ESTIMATOR_OPTIONS = tuple(
    option for option in _STAGED_CAMPAIGN_ESTIMATOR_OPTIONS
    if option not in {"stages", "plan", "families", "templates"}
)
_STRICT_FAMILY_LITE_ESTIMATOR_OPTIONS = _SAVGOL_FOCUS_ESTIMATOR_OPTIONS
_SWEEP_OPTIONS = (
    "chains",
    "profile",
    "cv",
    "fold_ids",
    "ridge_lambdas",
    "pls_components",
    "heads",
    *_MODEL_SCALE_OPTIONS,
    "moment_policy",
    "pls_score_mode",
    "score_only",
    *_CUDA_PLS_OPTIONS,
)
_FIXED_CANDIDATE_OPTIONS = (
    "chain",
    "head",
    "param",
    "fit_mode",
    "precomputed_cv_rmse",
    "cv",
    "fold_ids",
    *_MODEL_SCALE_OPTIONS,
    "moment_policy",
    *_CUDA_PLS_OPTIONS,
)
_RIDGE_BLENDER_OPTIONS = (
    "profile",
    "cv",
    "fold_ids",
    "ridge_lambdas",
    "regularizer",
    *_MODEL_SCALE_OPTIONS,
)
_RIDGE_SUPERBLOCK_OPTIONS = (
    "operators",
    "alpha",
    "alphas",
    "cv",
    "fold_ids",
    "block_scaling",
    "center_x",
    "center_y",
)
_RIDGE_PLS_SUPERBLOCK_OPTIONS = (
    "operators",
    "n_components",
    "pls_components",
    "ridge_lambda",
    "ridge_lambdas",
    "cv",
    "fold_ids",
    "block_scaling",
    "center_x",
)
_CHAIN_RIDGE_PLS_OPTIONS = (
    "chains",
    "profile",
    "families",
    "templates",
    "max_chains",
    "n_components",
    "pls_components",
    "ridge_lambda",
    "ridge_lambdas",
    "cv",
    "fold_ids",
    "center_x",
    "center_y",
)
_RIDGE_MKL_SUPERBLOCK_OPTIONS = (
    "operators",
    "alpha",
    "alphas",
    "cv",
    "fold_ids",
    "mkl_top_k",
    "block_scaling",
    "center_x",
    "center_y",
)
_RIDGE_ACTIVE_SUPERBLOCK_OPTIONS = (
    "operators",
    "alpha",
    "alphas",
    "cv",
    "fold_ids",
    "active_top_m",
    "active_diversity_threshold",
    "active_score_method",
    "active_max_per_family",
    "keep_identity",
    "block_scaling",
    "center_x",
    "center_y",
)
_RIDGE_GLOBAL_OPTIONS = (
    "operators",
    "cv",
    "fold_ids",
    "ridge_lambdas",
    *_MODEL_SCALE_OPTIONS,
    "moment_policy",
)
_PLS_SUPERBLOCK_OPTIONS = (
    "operators",
    "n_components",
    "pls_components",
    "cv",
    "fold_ids",
    "block_scaling",
    "center_x",
    "center_y",
    *_CUDA_PLS_OPTIONS,
)
_OPERATOR_PLS_STACK_OPTIONS = (
    "profile",
    "cv",
    "fold_ids",
    "components",
    "alphas",
    "std_penalty",
    "gap_penalty",
    *_MODEL_SCALE_OPTIONS,
)
_ROBUST_HPO_OPTIONS = (
    "profile",
    "cv",
    "heads",
)
_AOM_SELECTOR_OPTIONS = (
    "operators",
    "max_components",
    "cv",
    "fold_ids",
    "scale_x",
)
_AOM_PREPROCESS_OPTIONS = (
    "operators",
    "gating_mode",
)
_AOM_SCREEN_POOL_OPTIONS = (
    "refit_top_k",
    "refit_per_head_top_k",
)
_AOM_REFIT_OPTIONS = (
    "top_k",
    "sort_by",
    "cv",
    "fold_ids",
    *_MODEL_SCALE_OPTIONS,
    "moment_policy",
    "execution_mode",
    "auto_max_extra_fraction",
    "return_predictions",
    *_CUDA_PLS_OPTIONS,
)
_AOM_CHAIN_GRID_OPTIONS = (
    "profile",
    "families",
    "templates",
    "include_identity",
    "max_chains",
)
_AOM_CHAIN_GRID_ITER_OPTIONS = (
    *_AOM_CHAIN_GRID_OPTIONS,
    "start",
    "stop",
    "chunk_size",
    "with_ids",
)
_AOM_CANDIDATE_TABLE_OPTIONS = (
    "sort",
)
_AOM_EVALUATE_OPTIONS = (
    "top_k",
    "sort_by",
    "cv",
    "fold_ids",
    *_MODEL_SCALE_OPTIONS,
    "moment_policy",
    "return_predictions",
)
_AOM_OPERATOR_SUMMARY_OPTIONS = (
    "score_key",
    "top_k",
)
_AOM_PREPROCESSING_IMPACT_OPTIONS = (
    "score_key",
    "top_k",
    "higher_is_better",
)
_AOM_ROUTE_SUMMARY_OPTIONS = ()
_AOM_RANK_DIAGNOSTICS_OPTIONS = (
    "screen_score_key",
    "eval_score_key",
    "cutoffs",
)
_AOM_SAVE_REPORT_OPTIONS = (
    "format",
    "include_predictions",
)
_AOM_LOAD_REPORT_OPTIONS = (
    "format",
)

_METHOD_INVENTORY = (
    {
        "name": "preprocess",
        "entry": "aom_preprocess",
        "kind": "function",
        "role": "operator_bank_preprocess",
        "heads": (),
        "reuse": "transformed_operator_views",
        "cpu": True,
        "cuda": True,
        "catalog_id": "aom_pop.aom_preprocessing",
        "catalog_role": "catalog_binding",
        "doc_path": "docs/methods/aom_preprocess.md",
        "config_options": _AOM_PREPROCESS_OPTIONS,
        "notes": "Native AOM operator-bank preprocessing primitive returning transformed views, per-operator outputs, weights and operator ids.",
    },
    {
        "name": "moment_mixed_screen_refit",
        "entry": "NativeAOMMomentScreenRefitRegressor",
        "kind": "sklearn_estimator",
        "role": "global_screen_refit",
        "heads": ("ridge", "pls"),
        "reuse": "selected_final_model",
        "cpu": True,
        "cuda": True,
        "catalog_id": "aom_pop.aom_chain_screen_refit",
        "catalog_role": "sklearn_wrapper",
        "wrapper_of": "aom_chain_screen_refit_campaign",
        "doc_path": "docs/methods/aom_chain_sweep_run.md",
        "config_options": _SCREEN_REFIT_OPTIONS,
        "notes": "Mixed Ridge exact-CV plus PLS GCV-proxy screen with split-head scoring, exact-CV refit, final-only reusable winner.",
    },
    {
        "name": "moment_pls_screen_refit",
        "entry": "NativeAOMMomentPLSScreenRefitRegressor",
        "kind": "sklearn_estimator",
        "role": "global_screen_refit",
        "heads": ("pls",),
        "reuse": "selected_final_model",
        "cpu": True,
        "cuda": True,
        "catalog_id": "aom_pop.aom_chain_screen_refit",
        "catalog_role": "sklearn_wrapper",
        "wrapper_of": "aom_chain_screen_refit_campaign",
        "doc_path": "docs/methods/aom_chain_sweep_run.md",
        "config_options": _SCREEN_REFIT_OPTIONS,
        "notes": "PLS GCV-proxy broad strict-linear preprocessing screen followed by exact-CV refit.",
    },
    {
        "name": "moment_pls_exact_screen_refit",
        "entry": "NativeAOMMomentPLSExactScreenRefitRegressor",
        "kind": "sklearn_estimator",
        "role": "global_screen_refit",
        "heads": ("pls",),
        "reuse": "selected_final_model",
        "cpu": True,
        "cuda": True,
        "catalog_id": "aom_pop.aom_chain_screen_refit",
        "catalog_role": "sklearn_wrapper",
        "wrapper_of": "aom_chain_screen_refit_campaign",
        "doc_path": "docs/methods/aom_chain_sweep_run.md",
        "config_options": _SCREEN_REFIT_OPTIONS,
        "notes": "PLS exact-CV broad strict-linear preprocessing screen followed by exact-CV refit.",
    },
    {
        "name": "moment_ridge_screen_refit",
        "entry": "NativeAOMMomentRidgeScreenRefitRegressor",
        "kind": "sklearn_estimator",
        "role": "global_screen_refit",
        "heads": ("ridge",),
        "reuse": "selected_final_model",
        "cpu": True,
        "cuda": True,
        "catalog_id": "aom_pop.aom_chain_screen_refit",
        "catalog_role": "sklearn_wrapper",
        "wrapper_of": "aom_chain_screen_refit_campaign",
        "doc_path": "docs/methods/aom_chain_sweep_run.md",
        "config_options": _SCREEN_REFIT_OPTIONS,
        "notes": "Ridge exact-CV broad strict-linear preprocessing screen followed by exact-CV refit.",
    },
    {
        "name": "screen_refit_campaign",
        "entry": "aom_chain_screen_refit_campaign",
        "kind": "function",
        "role": "ultra_configurable_campaign",
        "heads": ("ridge", "pls"),
        "reuse": "refit_report_rows",
        "cpu": True,
        "cuda": True,
        "catalog_id": "aom_pop.aom_chain_screen_refit",
        "catalog_role": "catalog_binding",
        "doc_path": "docs/methods/aom_chain_sweep_run.md",
        "config_options": _SCREEN_REFIT_OPTIONS,
        "notes": "Chunked score-only campaign, retained candidate pool, exact-CV refit and audit reports.",
    },
    {
        "name": "chain_score_campaign",
        "entry": "aom_chain_score_campaign",
        "kind": "function",
        "role": "ultra_configurable_score_screen",
        "heads": ("ridge", "pls"),
        "reuse": "candidate_table",
        "cpu": True,
        "cuda": True,
        "catalog_id": "aom_pop.aom_chain_sweep",
        "catalog_role": "campaign_helper",
        "wrapper_of": "aom_chain_sweep_run",
        "doc_path": "docs/methods/aom_chain_sweep_run.md",
        "config_options": _SCORE_CAMPAIGN_OPTIONS,
        "notes": "Chunked score-only strict-linear AOM/moment preprocessing screen with checkpoint/resume, top-k aggregation and audit reports.",
    },
    {
        "name": "staged_chain_campaign",
        "entry": "aom_staged_chain_campaign",
        "kind": "function",
        "role": "staged_screen_refit_orchestration",
        "heads": ("ridge", "pls"),
        "reuse": "staged_refit_report_rows",
        "cpu": True,
        "cuda": True,
        "catalog_id": "aom_pop.aom_staged_chain_campaign",
        "catalog_role": "catalog_binding",
        "doc_path": "docs/methods/aom_staged_chain_campaign.md",
        "config_options": _STAGED_CAMPAIGN_OPTIONS,
        "notes": "Staged compact/wide/lab strict-chain screens over Ridge/PLS/mixed heads with cross-stage global/per-head retention, one exact-CV refit, and impact/rank/audit diagnostics.",
    },
    {
        "name": "staged_chain_campaign_estimator",
        "entry": "NativeAOMStagedChainCampaignRegressor",
        "kind": "sklearn_estimator",
        "role": "staged_screen_refit_estimator",
        "heads": ("ridge", "pls"),
        "reuse": "selected_final_model",
        "cpu": True,
        "cuda": True,
        "catalog_id": "aom_pop.aom_staged_chain_campaign",
        "catalog_role": "sklearn_wrapper",
        "wrapper_of": "aom_staged_chain_campaign",
        "doc_path": "docs/methods/aom_staged_chain_campaign.md",
        "config_options": _STAGED_CAMPAIGN_ESTIMATOR_OPTIONS,
        "notes": "Reusable sklearn wrapper over staged compact/wide/lab AOM/moment screen-refit; fit selects only by train exact-CV refit and then fits the selected final-only candidate.",
    },
    {
        "name": "savgol_focus_regressor",
        "entry": "NativeAOMSavgolFocusRegressor",
        "kind": "sklearn_estimator",
        "role": "winning_preconfigured_screen_refit",
        "heads": ("ridge", "pls"),
        "reuse": "selected_final_model",
        "cpu": True,
        "cuda": True,
        "catalog_id": "aom_pop.aom_staged_chain_campaign",
        "catalog_role": "preset_sklearn_wrapper",
        "wrapper_of": "aom_staged_chain_campaign",
        "doc_path": "docs/methods/aom_staged_chain_campaign.md",
        "config_options": _SAVGOL_FOCUS_ESTIMATOR_OPTIONS,
        "preset_plan": "savgol_focus",
        "notes": "Fast SavGol-focused staged AOM/moment preset with train-CV-selected scale_x grid and final-only selected-candidate reuse.",
    },
    {
        "name": "strict_family_lite_regressor",
        "entry": "NativeAOMStrictFamilyLiteRegressor",
        "kind": "sklearn_estimator",
        "role": "cost_safe_family_audit",
        "heads": ("ridge", "pls"),
        "reuse": "selected_final_model",
        "cpu": True,
        "cuda": True,
        "catalog_id": "aom_pop.aom_staged_chain_campaign",
        "catalog_role": "preset_sklearn_wrapper",
        "wrapper_of": "aom_staged_chain_campaign",
        "doc_path": "docs/methods/aom_staged_chain_campaign.md",
        "config_options": _STRICT_FAMILY_LITE_ESTIMATOR_OPTIONS,
        "preset_plan": "strict_family_focus",
        "notes": "Cost-safe strict-family staged AOM/moment preset over SavGol, Norris-Williams, finite-difference, Gaussian, FCK and Whittaker stages with small default refit budget.",
    },
    {
        "name": "moment_fast_screen_refit_campaign",
        "entry": "aom_moment_screen_refit_campaign",
        "kind": "function",
        "role": "preconfigured_global_screen_refit",
        "heads": ("ridge", "pls"),
        "reuse": "refit_report_rows",
        "cpu": True,
        "cuda": True,
        "catalog_id": "aom_pop.aom_chain_screen_refit",
        "catalog_role": "preset_function",
        "wrapper_of": "aom_chain_screen_refit_campaign",
        "doc_path": "docs/methods/aom_chain_sweep_run.md",
        "config_options": _SCREEN_REFIT_OPTIONS,
        "notes": "Fast functional AOM/moment screen-refit preset using prefix chain packing, split-head scoring, PLS GCV-proxy screen and exact-CV refit.",
    },
    {
        "name": "aom_screen_refit_candidate_pool",
        "entry": "aom_screen_refit_candidate_pool",
        "kind": "function",
        "role": "screen_refit_pool",
        "heads": ("ridge", "pls"),
        "reuse": "retained_candidate_rows",
        "cpu": True,
        "cuda": True,
        "catalog_id": "aom_pop.aom_chain_screen_refit",
        "catalog_role": "campaign_helper",
        "wrapper_of": "aom_chain_screen_refit_campaign",
        "doc_path": "docs/methods/aom_chain_sweep_run.md",
        "config_options": _AOM_SCREEN_POOL_OPTIONS,
        "notes": "Extract the global/per-head retained candidate pool from an AOM/moment screen report before exact refit.",
    },
    {
        "name": "aom_refit_execution_plan",
        "entry": "aom_refit_execution_plan",
        "kind": "function",
        "role": "refit_launch_planning",
        "heads": ("ridge", "pls"),
        "reuse": "source_free_refit_plan",
        "cpu": True,
        "cuda": True,
        "non_catalog_reason": "planning helper over a campaign report; not a fit/predict method catalog entry",
        "config_options": (
            "top_k",
            "refit_per_head_top_k",
            "auto_max_extra_fraction",
        ),
        "notes": "Source-free execution-mode planning for exact-CV refit of retained AOM/moment candidates.",
    },
    {
        "name": "aom_refit_candidates",
        "entry": "aom_refit_candidates",
        "kind": "function",
        "role": "exact_cv_refit",
        "heads": ("ridge", "pls"),
        "reuse": "refit_report_rows",
        "cpu": True,
        "cuda": True,
        "catalog_id": "aom_pop.aom_chain_screen_refit",
        "catalog_role": "campaign_helper",
        "wrapper_of": "aom_chain_screen_refit_campaign",
        "doc_path": "docs/methods/aom_chain_sweep_run.md",
        "config_options": _AOM_REFIT_OPTIONS,
        "notes": "Exact-CV verification of retained AOM/moment candidate rows with grouped/batched refit execution modes.",
    },
    {
        "name": "aom_chain_fixed_fit",
        "entry": "aom_chain_fixed_fit_run",
        "kind": "function",
        "role": "winner_reuse",
        "heads": ("ridge", "pls"),
        "reuse": "selected_final_model",
        "cpu": True,
        "cuda": True,
        "catalog_id": "aom_pop.aom_chain_fixed_fit",
        "catalog_role": "catalog_binding",
        "doc_path": "docs/methods/aom_chain_sweep_run.md",
        "config_options": _FIXED_CANDIDATE_OPTIONS,
        "notes": "Fit one already-selected strict-linear AOM/moment chain/head/parameter without rerunning CV.",
    },
    {
        "name": "fixed_candidate",
        "entry": "NativeAOMFixedCandidateRegressor",
        "kind": "sklearn_estimator",
        "role": "winner_reuse",
        "heads": ("ridge", "pls"),
        "reuse": "explicit_candidate_or_refit_row",
        "cpu": True,
        "cuda": True,
        "catalog_id": "aom_pop.aom_chain_fixed_fit",
        "catalog_role": "sklearn_wrapper",
        "wrapper_of": "aom_chain_fixed_fit_run",
        "doc_path": "docs/methods/aom_chain_sweep_run.md",
        "config_options": _FIXED_CANDIDATE_OPTIONS,
        "notes": "Fit one selected strict-linear chain/head/parameter and predict from folded input coefficients.",
    },
    {
        "name": "chain_sweep",
        "entry": "aom_chain_sweep_run",
        "kind": "function",
        "role": "native_candidate_screen",
        "heads": ("ridge", "pls"),
        "reuse": "candidate_table",
        "cpu": True,
        "cuda": True,
        "catalog_id": "aom_pop.aom_chain_sweep",
        "catalog_role": "catalog_binding",
        "doc_path": "docs/methods/aom_chain_sweep_run.md",
        "config_options": _SWEEP_OPTIONS,
        "notes": "Caller-provided strict-linear chain sweep over Ridge/PLS grids.",
    },
    {
        "name": "profile_sweep",
        "entry": "aom_sweep_run",
        "kind": "function",
        "role": "native_candidate_screen",
        "heads": ("ridge", "pls"),
        "reuse": "candidate_table",
        "cpu": True,
        "cuda": True,
        "catalog_id": "aom_pop.aom_sweep",
        "catalog_role": "catalog_binding",
        "doc_path": "docs/methods/aom_sweep_run.md",
        "config_options": _SWEEP_OPTIONS,
        "notes": "Built-in compact/wide strict-linear profile sweep.",
    },
    {
        "name": "build_aom_strict_chain_grid",
        "entry": "build_aom_strict_chain_grid",
        "kind": "function",
        "role": "preprocessing_grid_builder",
        "heads": (),
        "reuse": "strict_linear_chain_descriptors",
        "cpu": True,
        "cuda": True,
        "non_catalog_reason": "campaign grid builder; not a fit/predict method catalog entry",
        "config_options": _AOM_CHAIN_GRID_OPTIONS,
        "notes": "Construct deterministic compact/wide/lab strict-linear preprocessing chain grids for AOM/moment campaigns.",
    },
    {
        "name": "iter_aom_strict_chain_grid",
        "entry": "iter_aom_strict_chain_grid",
        "kind": "function",
        "role": "preprocessing_grid_stream",
        "heads": (),
        "reuse": "strict_linear_chain_descriptors",
        "cpu": True,
        "cuda": True,
        "non_catalog_reason": "campaign grid iterator; not a fit/predict method catalog entry",
        "config_options": _AOM_CHAIN_GRID_ITER_OPTIONS,
        "notes": "Stream deterministic compact/wide/lab strict-linear preprocessing chains with stable ids, slicing and chunks.",
    },
    {
        "name": "decode_aom_chains",
        "entry": "decode_aom_chains",
        "kind": "function",
        "role": "candidate_decode",
        "heads": (),
        "reuse": "decoded_chain_descriptors",
        "cpu": True,
        "cuda": True,
        "non_catalog_reason": "candidate-report decoder; not a fit/predict method catalog entry",
        "config_options": (),
        "notes": "Decode flat AOM chain descriptors from native sweep/campaign results.",
    },
    {
        "name": "aom_candidate_table",
        "entry": "aom_candidate_table",
        "kind": "function",
        "role": "candidate_decode",
        "heads": ("ridge", "pls"),
        "reuse": "decoded_candidate_rows",
        "cpu": True,
        "cuda": True,
        "non_catalog_reason": "candidate-table decoder; not a fit/predict method catalog entry",
        "config_options": _AOM_CANDIDATE_TABLE_OPTIONS,
        "notes": "Decode native AOM candidate scores into row dictionaries with chain/head/route provenance.",
    },
    {
        "name": "aom_evaluate_candidates",
        "entry": "aom_evaluate_candidates",
        "kind": "function",
        "role": "holdout_candidate_audit",
        "heads": ("ridge", "pls"),
        "reuse": "evaluated_candidate_rows",
        "cpu": True,
        "cuda": True,
        "non_catalog_reason": "offline holdout audit helper; not a fit/predict method catalog entry",
        "config_options": _AOM_EVALUATE_OPTIONS,
        "notes": "Evaluate decoded AOM/moment candidate rows on an explicit holdout split for CV-vs-test rank diagnostics.",
    },
    {
        "name": "aom_candidate_operator_summary",
        "entry": "aom_candidate_operator_summary",
        "kind": "function",
        "role": "candidate_audit",
        "heads": ("ridge", "pls"),
        "reuse": "operator_summary",
        "cpu": True,
        "cuda": True,
        "non_catalog_reason": "candidate-report audit helper; not a fit/predict method catalog entry",
        "config_options": _AOM_OPERATOR_SUMMARY_OPTIONS,
        "notes": "Summarize scored AOM/moment candidates by head, operator, route and chain length.",
    },
    {
        "name": "aom_candidate_preprocessing_impact",
        "entry": "aom_candidate_preprocessing_impact",
        "kind": "function",
        "role": "candidate_audit",
        "heads": ("ridge", "pls"),
        "reuse": "preprocessing_impact_summary",
        "cpu": True,
        "cuda": True,
        "non_catalog_reason": "candidate-report audit helper; not a fit/predict method catalog entry",
        "config_options": _AOM_PREPROCESSING_IMPACT_OPTIONS,
        "notes": "Summarize preprocessing option/stage impact, including deltas vs identity baselines.",
    },
    {
        "name": "aom_candidate_route_summary",
        "entry": "aom_candidate_route_summary",
        "kind": "function",
        "role": "candidate_audit",
        "heads": ("ridge", "pls"),
        "reuse": "route_coverage_summary",
        "cpu": True,
        "cuda": True,
        "non_catalog_reason": "candidate-report audit helper; not a fit/predict method catalog entry",
        "config_options": _AOM_ROUTE_SUMMARY_OPTIONS,
        "notes": "Summarize materialized vs dense/banded/structured operator-moment route coverage by head and chain.",
    },
    {
        "name": "aom_candidate_rank_diagnostics",
        "entry": "aom_candidate_rank_diagnostics",
        "kind": "function",
        "role": "candidate_audit",
        "heads": ("ridge", "pls"),
        "reuse": "rank_recall_diagnostics",
        "cpu": True,
        "cuda": True,
        "non_catalog_reason": "candidate-report audit helper; not a fit/predict method catalog entry",
        "config_options": _AOM_RANK_DIAGNOSTICS_OPTIONS,
        "notes": "Compute screen-vs-holdout rank drift and top-k recall diagnostics from evaluated candidates.",
    },
    {
        "name": "aom_candidate_report_records",
        "entry": "aom_candidate_report_records",
        "kind": "function",
        "role": "candidate_report_io",
        "heads": ("ridge", "pls"),
        "reuse": "json_safe_candidate_rows",
        "cpu": True,
        "cuda": True,
        "non_catalog_reason": "candidate-report serialization helper; not a fit/predict method catalog entry",
        "config_options": ("include_predictions",),
        "notes": "Flatten AOM/moment campaign or holdout reports into JSON-safe candidate records.",
    },
    {
        "name": "aom_save_candidate_report",
        "entry": "aom_save_candidate_report",
        "kind": "function",
        "role": "candidate_report_io",
        "heads": ("ridge", "pls"),
        "reuse": "saved_candidate_report",
        "cpu": True,
        "cuda": True,
        "non_catalog_reason": "candidate-report serialization helper; not a fit/predict method catalog entry",
        "config_options": _AOM_SAVE_REPORT_OPTIONS,
        "notes": "Save AOM/moment candidate reports as JSON, JSONL or CSV for offline replay and audit.",
    },
    {
        "name": "aom_load_candidate_report",
        "entry": "aom_load_candidate_report",
        "kind": "function",
        "role": "candidate_report_io",
        "heads": ("ridge", "pls"),
        "reuse": "loaded_candidate_report",
        "cpu": True,
        "cuda": True,
        "non_catalog_reason": "candidate-report serialization helper; not a fit/predict method catalog entry",
        "config_options": _AOM_LOAD_REPORT_OPTIONS,
        "notes": "Reload JSON/JSONL/CSV AOM/moment candidate reports for offline audit and replay.",
    },
    {
        "name": "ridge_blender",
        "entry": "NativeAOMRidgeBlenderRegressor",
        "kind": "sklearn_estimator",
        "role": "linear_aom_diversity",
        "heads": ("ridge",),
        "reuse": "selected_blend_model",
        "cpu": True,
        "cuda": True,
        "catalog_id": "aom_pop.ridge_blender",
        "catalog_role": "sklearn_wrapper",
        "wrapper_of": "aom_ridge_blender",
        "doc_path": "docs/methods/aom_ridge_blender.md",
        "config_options": _RIDGE_BLENDER_OPTIONS,
        "notes": "Strict-linear AOM Ridge OOF simplex blender with folded input coefficients.",
    },
    {
        "name": "ridge_superblock",
        "entry": "NativeAOMRidgeSuperblockRegressor",
        "kind": "sklearn_estimator",
        "role": "linear_aom_diversity",
        "heads": ("ridge",),
        "reuse": "selected_superblock_model",
        "cpu": True,
        "cuda": True,
        "catalog_id": "aom_pop.ridge_superblock",
        "catalog_role": "sklearn_wrapper",
        "wrapper_of": "aom_ridge_superblock",
        "doc_path": "docs/methods/aom_ridge_superblock.md",
        "config_options": _RIDGE_SUPERBLOCK_OPTIONS,
        "notes": "Strict-linear single-operator AOM superblock Ridge with folded input coefficients.",
    },
    {
        "name": "ridge_active_superblock",
        "entry": "NativeAOMRidgeActiveSuperblockRegressor",
        "kind": "sklearn_estimator",
        "role": "linear_aom_diversity",
        "heads": ("ridge",),
        "reuse": "selected_active_superblock_model",
        "cpu": True,
        "cuda": True,
        "catalog_id": "aom_pop.ridge_active_superblock",
        "catalog_role": "sklearn_wrapper",
        "wrapper_of": "aom_ridge_active_superblock",
        "doc_path": "docs/methods/aom_ridge_active_superblock.md",
        "config_options": _RIDGE_ACTIVE_SUPERBLOCK_OPTIONS,
        "notes": "Strict-linear AOM Ridge superblock after train-only active operator pruning, with folded input coefficients.",
    },
    {
        "name": "ridge_pls_superblock",
        "entry": "NativeAOMRidgePLSSuperblockRegressor",
        "kind": "sklearn_estimator",
        "role": "linear_aom_diversity",
        "heads": ("ridge", "pls"),
        "reuse": "selected_ridge_pls_superblock_model",
        "cpu": True,
        "cuda": True,
        "catalog_id": "aom_pop.aom_ridge_pls_superblock",
        "catalog_role": "sklearn_wrapper",
        "wrapper_of": "aom_ridge_pls_superblock",
        "doc_path": "docs/methods/aom_ridge_pls_superblock.md",
        "config_options": _RIDGE_PLS_SUPERBLOCK_OPTIONS,
        "notes": "Strict-linear AOM operator superblock with a native Ridge-PLS head and folded input coefficients.",
    },
    {
        "name": "chain_ridge_pls",
        "entry": "NativeAOMChainRidgePLSRegressor",
        "kind": "sklearn_estimator",
        "role": "linear_aom_diversity",
        "heads": ("ridge", "pls"),
        "reuse": "selected_chain_model",
        "cpu": True,
        "cuda": True,
        "catalog_id": "aom_pop.aom_chain_ridge_pls",
        "catalog_role": "sklearn_wrapper",
        "wrapper_of": "aom_chain_ridge_pls",
        "doc_path": "docs/methods/aom_chain_ridge_pls.md",
        "config_options": _CHAIN_RIDGE_PLS_OPTIONS,
        "notes": "Strict-linear sequential AOM chain selector with native Ridge-PLS head and folded input coefficients.",
    },
    {
        "name": "ridge_mkl_superblock",
        "entry": "NativeAOMRidgeMKLSuperblockRegressor",
        "kind": "sklearn_estimator",
        "role": "linear_aom_diversity",
        "heads": ("ridge",),
        "reuse": "selected_mkl_superblock_model",
        "cpu": True,
        "cuda": True,
        "catalog_id": "aom_pop.ridge_mkl_superblock",
        "catalog_role": "sklearn_wrapper",
        "wrapper_of": "aom_ridge_mkl_superblock",
        "doc_path": "docs/methods/aom_ridge_mkl_superblock.md",
        "config_options": _RIDGE_MKL_SUPERBLOCK_OPTIONS,
        "notes": "Strict-linear AOM Ridge superblock with train-only KTA block weights and folded input coefficients.",
    },
    {
        "name": "ridge_global",
        "entry": "NativeAOMRidgeGlobalRegressor",
        "kind": "sklearn_estimator",
        "role": "linear_aom_selector",
        "heads": ("ridge",),
        "reuse": "selected_operator_model",
        "cpu": True,
        "cuda": True,
        "catalog_id": "aom_pop.ridge_global",
        "catalog_role": "sklearn_wrapper",
        "wrapper_of": "aom_ridge_global",
        "doc_path": "docs/methods/aom_ridge_global.md",
        "config_options": _RIDGE_GLOBAL_OPTIONS,
        "notes": "Select one strict-linear AOM operator and Ridge alpha by native CV, then reuse folded input coefficients.",
    },
    {
        "name": "pls_superblock",
        "entry": "NativeAOMPLSSuperblockRegressor",
        "kind": "sklearn_estimator",
        "role": "linear_aom_diversity",
        "heads": ("pls",),
        "reuse": "selected_pls_superblock_model",
        "cpu": True,
        "cuda": True,
        "catalog_id": "aom_pop.aom_pls_superblock",
        "catalog_role": "sklearn_wrapper",
        "wrapper_of": "aom_pls_superblock",
        "doc_path": "docs/methods/aom_pls_superblock.md",
        "config_options": _PLS_SUPERBLOCK_OPTIONS,
        "notes": "Strict-linear AOM operator superblock with a PLS head and folded input coefficients.",
    },
    {
        "name": "operator_pls_stack",
        "entry": "NativeAOMOperatorPLSStackRegressor",
        "kind": "sklearn_estimator",
        "role": "linear_aom_diversity",
        "heads": ("pls", "ridge"),
        "reuse": "selected_stack_model",
        "cpu": True,
        "cuda": True,
        "catalog_id": "aom_pop.operator_pls_stack",
        "catalog_role": "sklearn_wrapper",
        "wrapper_of": "aom_operator_pls_stack",
        "doc_path": "docs/methods/aom_operator_pls_stack.md",
        "config_options": _OPERATOR_PLS_STACK_OPTIONS,
        "notes": "Strict-operator PLS1 score stack with Ridge head and folded input coefficients.",
    },
    {
        "name": "robust_hpo",
        "entry": "NativeAOMRobustHPORegressor",
        "kind": "sklearn_estimator",
        "role": "preconfigured_aom_profile",
        "heads": ("ridge", "pls"),
        "reuse": "selected_profile_model",
        "cpu": True,
        "cuda": True,
        "catalog_id": "aom_pop.robust_hpo",
        "catalog_role": "sklearn_wrapper",
        "wrapper_of": "aom_robust_hpo",
        "doc_path": "docs/methods/aom_robust_hpo.md",
        "config_options": _ROBUST_HPO_OPTIONS,
        "notes": "Compact/wide native strict-linear AOM product screen.",
    },
    {
        "name": "aom_pls",
        "entry": "NativeAOMPLSRegressor",
        "kind": "sklearn_estimator",
        "role": "legacy_aom_selector",
        "heads": ("pls",),
        "reuse": "selected_operator_model",
        "cpu": True,
        "cuda": True,
        "catalog_id": "aom_pop.aom_pls",
        "catalog_role": "sklearn_wrapper",
        "wrapper_of": "aom_global_select",
        "doc_path": "docs/methods/aom_pls.md",
        "config_options": _AOM_SELECTOR_OPTIONS,
        "notes": "Existing global AOM PLS selector surface.",
    },
    {
        "name": "pop_pls",
        "entry": "NativePOPPLSRegressor",
        "kind": "sklearn_estimator",
        "role": "legacy_aom_selector",
        "heads": ("pls",),
        "reuse": "per_component_operator_model",
        "cpu": True,
        "cuda": True,
        "catalog_id": "aom_pop.pop_pls",
        "catalog_role": "sklearn_wrapper",
        "wrapper_of": "aom_per_component_select",
        "doc_path": "docs/methods/pop_pls.md",
        "config_options": _AOM_SELECTOR_OPTIONS,
        "notes": "Existing per-component POP-PLS selector surface.",
    },
)


def available_methods() -> list[dict[str, object]]:
    """Return the public AOM method inventory as JSON-safe dictionaries."""
    return [dict(item) for item in _METHOD_INVENTORY]


__all__ = [
    "AOMCandidateSpec",
    "AOMControlSelector",
    "AOMDatasetMetadata",
    "AOMEndpointMarginStabilityGate",
    "AOMFallbackBlendGate",
    "AOMMidPEndpointStack",
    "AOMOperatorPLSStack",
    "AOMOperatorPLSSpec",
    "AOMPreprocessingChain",
    "AOMRidgeBlender",
    "AOMRobustHPOCompact",
    "AOMRobustHPORegressor",
    "AOMRobustHPOWide",
    "AOMStructuralPolicy",
    "AOMStructuralPolicyWithP700BlockLocalAdmission",
    "AOMStructuralPolicyWithP700ProtocolUnified",
    "AOMStructuralPolicyWithPgt1200Admissions",
    "AOMTrueBankEndpointPortfolio",
    "EndpointStabilityDecision",
    "NativeAOMChainRidgePLSRegressor",
    "NativeAOMChainSweepRegressor",
    "NativeAOMFixedCandidateRegressor",
    "NativeAOMMomentPLSScreenRefitRegressor",
    "NativeAOMMomentPLSExactScreenRefitRegressor",
    "NativeAOMMomentRidgeScreenRefitRegressor",
    "NativeAOMMomentScreenRefitRegressor",
    "NativeAOMOperatorPLSStackRegressor",
    "NativeAOMPLSRegressor",
    "NativeAOMPLSSuperblockRegressor",
    "NativeAOMRidgePLSSuperblockRegressor",
    "NativeAOMRidgeBlenderRegressor",
    "NativeAOMRidgeActiveSuperblockRegressor",
    "NativeAOMRidgeGlobalRegressor",
    "NativeAOMRidgeMKLSuperblockRegressor",
    "NativeAOMRidgeSuperblockRegressor",
    "NativeAOMRobustHPORegressor",
    "NativeAOMSavgolFocusRegressor",
    "NativeAOMScreenRefitRegressor",
    "NativeAOMStrictFamilyLiteRegressor",
    "NativeAOMStagedChainCampaignRegressor",
    "NativeAOMSweepRegressor",
    "NativePOPPLSRegressor",
    "aom_candidate_operator_summary",
    "aom_candidate_preprocessing_impact",
    "aom_candidate_route_summary",
    "aom_candidate_rank_diagnostics",
    "aom_candidate_report_records",
    "aom_candidate_table",
    "aom_chain_fixed_fit_run",
    "aom_chain_ridge_pls",
    "aom_chain_score_campaign",
    "aom_chain_screen_refit_campaign",
    "aom_chain_sweep_run",
    "aom_evaluate_candidates",
    "aom_global_select",
    "aom_load_candidate_report",
    "aom_moment_screen_refit_campaign",
    "aom_operator_pls_stack",
    "aom_per_component_select",
    "aom_preprocess",
    "aom_pls",
    "aom_pls_superblock",
    "aom_refit_candidates",
    "aom_refit_execution_plan",
    "aom_ridge_blender",
    "aom_ridge_active_superblock",
    "aom_ridge_global",
    "aom_ridge_mkl_superblock",
    "aom_ridge_pls_superblock",
    "aom_ridge_superblock",
    "aom_robust_hpo",
    "aom_save_candidate_report",
    "aom_screen_refit_candidate_pool",
    "aom_staged_chain_campaign",
    "aom_sweep_run",
    "available_methods",
    "build_aom_control_chain_bank",
    "build_aom_strict_chain_grid",
    "decode_aom_chains",
    "iter_aom_strict_chain_grid",
    "pop_pls",
]
