# SPDX-License-Identifier: CECILL-2.1
"""Moment-focused public facade.

The singular module name avoids shadowing the historical ``n4m.moments``
function while grouping the native sufficient-statistics and linear-screen
surfaces under one discoverable namespace.
"""
from __future__ import annotations

from . import native as _native
from . import (
    NativeAOMChainRidgePLSRegressor,
    NativeAOMChainSweepRegressor,
    NativeAOMFixedCandidateRegressor,
    NativeAOMMomentPLSScreenRefitRegressor,
    NativeAOMMomentPLSExactScreenRefitRegressor,
    NativeAOMMomentRidgeScreenRefitRegressor,
    NativeAOMMomentScreenRefitRegressor,
    NativeAOMOperatorPLSStackRegressor,
    NativeAOMPLSRegressor,
    NativeAOMPLSSuperblockRegressor,
    NativeAOMRidgePLSSuperblockRegressor,
    NativeAOMRidgeActiveSuperblockRegressor,
    NativeAOMRidgeBlenderRegressor,
    NativeAOMRidgeGlobalRegressor,
    NativeAOMRidgeMKLSuperblockRegressor,
    NativeAOMRidgeSuperblockRegressor,
    NativeAOMRobustHPORegressor,
    NativeAOMSavgolFocusRegressor,
    NativeAOMScreenRefitRegressor,
    NativeAOMStrictFamilyLiteRegressor,
    NativeAOMStagedChainCampaignRegressor,
    NativeAOMSweepRegressor,
    NativeContinuumRegressionRegressor,
    NativeCPPLSRegressor,
    NativeECRRegressor,
    NativeMomentStackRegressor,
    NativeMomentSweepRegressor,
    NativePCRRegressor,
    NativePLSRegressor,
    NativeRidgeRegressor,
    NativeRidgePLSRegressor,
    NativeRobustPLSRegressor,
    NativeWeightedPLSRegressor,
    NativePOPPLSRegressor,
)

moments = _native.moments
moments_train_from_heldout = _native.moments_train_from_heldout
moment_screen_backend_recommendation = _native.moment_screen_backend_recommendation
sweep_run = _native.sweep_run
pls_cross_validate = _native.pls_cross_validate
aom_preprocess = _native.aom_preprocess
aom_global_select = _native.aom_global_select
aom_per_component_select = _native.aom_per_component_select
aom_sweep_run = _native.aom_sweep_run
aom_chain_sweep_run = _native.aom_chain_sweep_run
aom_chain_screen_refit_campaign = _native.aom_chain_screen_refit_campaign
aom_moment_screen_refit_campaign = _native.aom_moment_screen_refit_campaign
aom_staged_chain_campaign = _native.aom_staged_chain_campaign
aom_screen_refit_candidate_pool = _native.aom_screen_refit_candidate_pool
aom_refit_execution_plan = _native.aom_refit_execution_plan
aom_refit_candidates = _native.aom_refit_candidates
aom_chain_fixed_fit_run = _native.aom_chain_fixed_fit_run
aom_robust_hpo = _native.aom_robust_hpo
aom_ridge_blender = _native.aom_ridge_blender
aom_chain_ridge_pls = _native.aom_chain_ridge_pls
aom_operator_pls_stack = _native.aom_operator_pls_stack
aom_pls_superblock = _native.aom_pls_superblock
aom_ridge_active_superblock = _native.aom_ridge_active_superblock
aom_ridge_global = _native.aom_ridge_global
aom_ridge_mkl_superblock = _native.aom_ridge_mkl_superblock
aom_ridge_pls_superblock = _native.aom_ridge_pls_superblock
aom_ridge_superblock = _native.aom_ridge_superblock
build_aom_strict_chain_grid = _native.build_aom_strict_chain_grid
iter_aom_strict_chain_grid = _native.iter_aom_strict_chain_grid
decode_aom_chains = _native.decode_aom_chains
aom_candidate_table = _native.aom_candidate_table
aom_evaluate_candidates = _native.aom_evaluate_candidates
aom_candidate_operator_summary = _native.aom_candidate_operator_summary
aom_candidate_preprocessing_impact = _native.aom_candidate_preprocessing_impact
aom_candidate_route_summary = _native.aom_candidate_route_summary
aom_candidate_rank_diagnostics = _native.aom_candidate_rank_diagnostics
aom_candidate_report_records = _native.aom_candidate_report_records
aom_save_candidate_report = _native.aom_save_candidate_report
aom_load_candidate_report = _native.aom_load_candidate_report
ridge = _native.ridge
pls = _native.pls
pcr = _native.pcr
cppls = _native.cppls
weighted_pls = _native.weighted_pls
robust_pls = _native.robust_pls
ridge_pls = _native.ridge_pls
continuum_regression = _native.continuum_regression
ecr = _native.ecr
moment_stack = _native.moment_stack

_MODEL_SCALE_OPTIONS = (
    "center_x",
    "scale_x",
    "center_y",
    "scale_y",
)
_CUDA_PLS_OPTIONS = (
    "cuda_pls_parallel_folds",
    "cuda_pls_min_device_features",
    "cuda_pls_many_batched",
)
_MOMENT_STATS_OPTIONS = (
    "row_indices",
)
_MOMENT_TRAIN_OPTIONS = (
    "heldout_indices",
)
_MOMENT_SWEEP_OPTIONS = (
    "cv",
    "fold_ids",
    "ridge_lambdas",
    "pls_components",
    "heads",
    *_MODEL_SCALE_OPTIONS,
    "score_only",
    *_CUDA_PLS_OPTIONS,
)
_PLS_CV_OPTIONS = (
    "cv",
    "fold_ids",
    "component_grid",
    *_MODEL_SCALE_OPTIONS,
    "score_only",
    *_CUDA_PLS_OPTIONS,
)
_MOMENT_SWEEP_ESTIMATOR_OPTIONS = tuple(
    option for option in _MOMENT_SWEEP_OPTIONS if option != "score_only"
)
_AOM_PREPROCESS_OPTIONS = (
    "operators",
    "gating_mode",
)
_AOM_SWEEP_OPTIONS = (
    "chains",
    "profile",
    "cv",
    "fold_ids",
    "ridge_lambdas",
    "pls_components",
    "heads",
    *_MODEL_SCALE_OPTIONS,
    "moment_policy",
    "pls_score_mode",
    "score_only",
    *_CUDA_PLS_OPTIONS,
)
_AOM_RIDGE_BLENDER_OPTIONS = (
    "profile",
    "cv",
    "fold_ids",
    "ridge_lambdas",
    "regularizer",
    *_MODEL_SCALE_OPTIONS,
)
_AOM_RIDGE_SUPERBLOCK_OPTIONS = (
    "operators",
    "alpha",
    "alphas",
    "cv",
    "fold_ids",
    "block_scaling",
    "center_x",
    "center_y",
)
_AOM_RIDGE_ACTIVE_SUPERBLOCK_OPTIONS = (
    "operators",
    "alpha",
    "alphas",
    "cv",
    "fold_ids",
    "active_top_m",
    "active_diversity_threshold",
    "active_score_method",
    "active_max_per_family",
    "keep_identity",
    "block_scaling",
    "center_x",
    "center_y",
)
_AOM_RIDGE_GLOBAL_OPTIONS = (
    "operators",
    "cv",
    "fold_ids",
    "ridge_lambdas",
    "center_x",
    "scale_x",
    "center_y",
    "scale_y",
    "moment_policy",
)
_AOM_PLS_SUPERBLOCK_OPTIONS = (
    "operators",
    "n_components",
    "pls_components",
    "cv",
    "fold_ids",
    "block_scaling",
    "center_x",
    "center_y",
    *_CUDA_PLS_OPTIONS,
)
_AOM_RIDGE_PLS_SUPERBLOCK_OPTIONS = (
    "operators",
    "n_components",
    "pls_components",
    "ridge_lambda",
    "ridge_lambdas",
    "cv",
    "fold_ids",
    "block_scaling",
    "center_x",
)
_AOM_CHAIN_RIDGE_PLS_OPTIONS = (
    "chains",
    "profile",
    "families",
    "templates",
    "max_chains",
    "n_components",
    "pls_components",
    "ridge_lambda",
    "ridge_lambdas",
    "cv",
    "fold_ids",
    "center_x",
    "center_y",
)
_AOM_RIDGE_MKL_SUPERBLOCK_OPTIONS = (
    "operators",
    "alpha",
    "alphas",
    "cv",
    "fold_ids",
    "mkl_top_k",
    "block_scaling",
    "center_x",
    "center_y",
)
_AOM_OPERATOR_PLS_STACK_OPTIONS = (
    "profile",
    "cv",
    "fold_ids",
    "components",
    "alphas",
    "std_penalty",
    "gap_penalty",
    *_MODEL_SCALE_OPTIONS,
)
_AOM_ROBUST_HPO_OPTIONS = (
    "profile",
    "cv",
    "heads",
)
_AOM_SELECTOR_OPTIONS = (
    "operators",
    "max_components",
    "cv",
    "fold_ids",
    "scale_x",
)
_AOM_MOMENT_SCREEN_REFIT_OPTIONS = (
    "chains",
    "profile",
    "families",
    "templates",
    "max_chains",
    "chain_chunk_size",
    "top_k",
    "refit_top_k",
    "refit_per_head_top_k",
    "cv",
    "fold_ids",
    "ridge_lambdas",
    "pls_components",
    "heads",
    *_MODEL_SCALE_OPTIONS,
    "moment_policy",
    "refit_moment_policy",
    "pls_score_mode",
    "chain_ordering",
    "split_head_scoring",
    "checkpoint_path",
    "resume",
    "max_chunks_per_run",
    "backend_cuda_available",
    "backend_min_cuda_product",
    *_CUDA_PLS_OPTIONS,
    "refit_sort_by",
    "refit_execution",
    "refit_auto_max_extra_fraction",
)
_STAGED_CAMPAIGN_OPTIONS = (
    "stages",
    "plan",
    "cv",
    "fold_ids",
    "ridge_lambdas",
    "pls_components",
    "heads",
    "top_k",
    "refit_top_k",
    "refit_per_head_top_k",
    "families",
    "templates",
    "max_chains",
    "chain_chunk_size",
    "checkpoint_dir",
    "resume",
    "max_chunks_per_run",
    *_MODEL_SCALE_OPTIONS,
    "scale_x_values",
    "moment_policy",
    "refit_moment_policy",
    "pls_score_mode",
    "chain_ordering",
    "split_head_scoring",
    "backend_cuda_available",
    "backend_min_cuda_product",
    *_CUDA_PLS_OPTIONS,
    "refit_sort_by",
    "refit_execution",
    "refit_auto_max_extra_fraction",
    "return_predictions",
    "impact",
    "rank_diagnostics",
    "impact_top_k",
    "X_audit",
    "y_audit",
    "audit_top_k",
    "return_stage_screens",
)
_STAGED_CAMPAIGN_ESTIMATOR_OPTIONS = tuple(
    option for option in _STAGED_CAMPAIGN_OPTIONS
    if option not in {
        "return_predictions",
        "X_audit",
        "y_audit",
        "audit_top_k",
    }
) + (
    "final_rank",
    "final_moment_policy",
)
_SAVGOL_FOCUS_ESTIMATOR_OPTIONS = tuple(
    option for option in _STAGED_CAMPAIGN_ESTIMATOR_OPTIONS
    if option not in {"stages", "plan", "families", "templates"}
)
_STRICT_FAMILY_LITE_ESTIMATOR_OPTIONS = _SAVGOL_FOCUS_ESTIMATOR_OPTIONS
_AOM_SCREEN_POOL_OPTIONS = (
    "refit_top_k",
    "refit_per_head_top_k",
)
_AOM_REFIT_OPTIONS = (
    "top_k",
    "sort_by",
    "cv",
    "fold_ids",
    *_MODEL_SCALE_OPTIONS,
    "moment_policy",
    "execution_mode",
    "auto_max_extra_fraction",
    "return_predictions",
    *_CUDA_PLS_OPTIONS,
)
_AOM_FIXED_CANDIDATE_OPTIONS = (
    "chain",
    "head",
    "param",
    "fit_mode",
    "precomputed_cv_rmse",
    "cv",
    "fold_ids",
    *_MODEL_SCALE_OPTIONS,
    "moment_policy",
    *_CUDA_PLS_OPTIONS,
)
_AOM_CHAIN_GRID_OPTIONS = (
    "profile",
    "families",
    "templates",
    "include_identity",
    "max_chains",
)
_AOM_CHAIN_GRID_ITER_OPTIONS = (
    *_AOM_CHAIN_GRID_OPTIONS,
    "start",
    "stop",
    "chunk_size",
    "with_ids",
)
_AOM_CANDIDATE_TABLE_OPTIONS = (
    "sort",
)
_AOM_EVALUATE_OPTIONS = (
    "top_k",
    "sort_by",
    "cv",
    "fold_ids",
    *_MODEL_SCALE_OPTIONS,
    "moment_policy",
    "return_predictions",
)
_AOM_OPERATOR_SUMMARY_OPTIONS = (
    "score_key",
    "top_k",
)
_AOM_PREPROCESSING_IMPACT_OPTIONS = (
    "score_key",
    "top_k",
    "higher_is_better",
)
_AOM_ROUTE_SUMMARY_OPTIONS = ()
_AOM_RANK_DIAGNOSTICS_OPTIONS = (
    "screen_score_key",
    "eval_score_key",
    "cutoffs",
)
_AOM_SAVE_REPORT_OPTIONS = (
    "format",
    "include_predictions",
)
_AOM_LOAD_REPORT_OPTIONS = (
    "format",
)
_RIDGE_OPTIONS = (
    "alpha",
    "center_x",
    "scale_x",
    "center_y",
)
_PCR_OPTIONS = (
    "n_components",
    "center_x",
    "scale_x",
    "center_y",
    "scale_y",
)
_PLS_OPTIONS = (
    "n_components",
    "pls_components",
    "cv",
    "fold_ids",
    *_MODEL_SCALE_OPTIONS,
    *_CUDA_PLS_OPTIONS,
)
_CPPLS_OPTIONS = (
    "gamma",
    "n_components",
)
_WEIGHTED_PLS_OPTIONS = (
    "sample_weights",
    "n_components",
    *_MODEL_SCALE_OPTIONS,
)
_ROBUST_PLS_OPTIONS = (
    "huber_k",
    "max_irls_iter",
    "n_components",
    *_MODEL_SCALE_OPTIONS,
)
_RIDGE_PLS_OPTIONS = (
    "ridge_lambda",
    "n_components",
    *_MODEL_SCALE_OPTIONS,
)
_CONTINUUM_OPTIONS = (
    "tau",
    "n_components",
)
_ECR_OPTIONS = (
    "alpha",
    "n_components",
)
_MOMENT_STACK_OPTIONS = (
    "base_models",
    "cv",
    "fold_ids",
    "inner_cv",
    "meta_alpha",
    "ridge_alpha",
    "n_components",
    "pls_components",
    "cppls_gamma",
    "continuum_tau",
    "ecr_alpha",
    "center_x",
    "scale_x",
    "center_y",
    "scale_y",
    "cuda_pls_parallel_folds",
    "cuda_pls_min_device_features",
    "cuda_pls_many_batched",
)
_BACKEND_RECOMMENDATION_OPTIONS = (
    "n_samples",
    "n_features",
    "head",
    "cuda_available",
    "min_cuda_product",
    "cuda_pls_min_device_features",
    "cuda_pls_many_batched",
)

_METHOD_INVENTORY = (
    {
        "name": "moments",
        "entry": "moments",
        "kind": "function",
        "role": "sufficient_statistics",
        "heads": (),
        "reuse": "row_additive_statistics",
        "cpu": True,
        "cuda": True,
        "catalog_id": "utilities.moments",
        "catalog_role": "catalog_binding",
        "doc_path": "docs/methods/moments.md",
        "config_options": _MOMENT_STATS_OPTIONS,
        "notes": "Raw and centered row-additive moments used by exact linear screens.",
    },
    {
        "name": "train_from_heldout",
        "entry": "moments_train_from_heldout",
        "kind": "function",
        "role": "fold_moment_subtraction",
        "heads": (),
        "reuse": "train_fold_statistics",
        "cpu": True,
        "cuda": True,
        "catalog_id": "utilities.moments",
        "catalog_role": "alias",
        "wrapper_of": "moments",
        "doc_path": "docs/methods/moments.md",
        "config_options": _MOMENT_TRAIN_OPTIONS,
        "notes": "Exact train moments as all-row moments minus held-out moments.",
    },
    {
        "name": "moment_sweep",
        "entry": "NativeMomentSweepRegressor",
        "kind": "sklearn_estimator",
        "role": "linear_screen",
        "heads": ("ridge", "pls"),
        "reuse": "selected_linear_model",
        "cpu": True,
        "cuda": True,
        "catalog_id": "utilities.sweep",
        "catalog_role": "sklearn_wrapper",
        "wrapper_of": "sweep_run",
        "doc_path": "docs/methods/sweep_run.md",
        "config_options": _MOMENT_SWEEP_ESTIMATOR_OPTIONS,
        "notes": "Native Ridge/PLS moment sweep with reusable sklearn-style predictions.",
    },
    {
        "name": "sweep_run",
        "entry": "sweep_run",
        "kind": "function",
        "role": "linear_screen",
        "heads": ("ridge", "pls"),
        "reuse": "candidate_scores",
        "cpu": True,
        "cuda": True,
        "catalog_id": "utilities.sweep",
        "catalog_role": "catalog_binding",
        "doc_path": "docs/methods/sweep_run.md",
        "config_options": _MOMENT_SWEEP_OPTIONS,
        "notes": "ABI-close Ridge/PLS moment screen over candidate lambdas/components.",
    },
    {
        "name": "pls_cross_validate",
        "entry": "pls_cross_validate",
        "kind": "function",
        "role": "pls_cv_reference",
        "heads": ("pls",),
        "reuse": "candidate_scores",
        "cpu": True,
        "cuda": True,
        "catalog_id": "utilities.sweep",
        "catalog_role": "campaign_helper",
        "wrapper_of": "sweep_run",
        "doc_path": "docs/methods/sweep_run.md",
        "config_options": _PLS_CV_OPTIONS,
        "notes": "ABI 1.22 exact PLS-only CV reference surface; currently score-equivalent to the PLS branch of sweep_run.",
    },
    {
        "name": "aom_preprocess",
        "entry": "aom_preprocess",
        "kind": "function",
        "role": "strict_operator_preprocess",
        "heads": (),
        "reuse": "transformed_operator_views",
        "cpu": True,
        "cuda": True,
        "catalog_id": "aom_pop.aom_preprocessing",
        "catalog_role": "catalog_binding",
        "doc_path": "docs/methods/aom_preprocess.md",
        "config_options": _AOM_PREPROCESS_OPTIONS,
        "notes": "Native strict-linear AOM preprocessing primitive for reusable operator views.",
    },
    {
        "name": "aom_chain_sweep",
        "entry": "aom_chain_sweep_run",
        "kind": "function",
        "role": "native_aom_candidate_screen",
        "heads": ("ridge", "pls"),
        "reuse": "candidate_table",
        "cpu": True,
        "cuda": True,
        "catalog_id": "aom_pop.aom_chain_sweep",
        "catalog_role": "catalog_binding",
        "doc_path": "docs/methods/aom_chain_sweep_run.md",
        "config_options": _AOM_SWEEP_OPTIONS,
        "notes": "Caller-provided strict-linear chain screen over Ridge/PLS grids with moment-policy route control.",
    },
    {
        "name": "aom_chain_sweep_regressor",
        "entry": "NativeAOMChainSweepRegressor",
        "kind": "sklearn_estimator",
        "role": "native_aom_candidate_screen",
        "heads": ("ridge", "pls"),
        "reuse": "selected_final_model",
        "cpu": True,
        "cuda": True,
        "catalog_id": "aom_pop.aom_chain_sweep",
        "catalog_role": "sklearn_wrapper",
        "wrapper_of": "aom_chain_sweep_run",
        "doc_path": "docs/methods/aom_chain_sweep_run.md",
        "config_options": tuple(
            option for option in _AOM_SWEEP_OPTIONS if option != "score_only"
        ),
        "notes": "Reusable estimator over explicit strict-linear chain grids.",
    },
    {
        "name": "aom_profile_sweep",
        "entry": "aom_sweep_run",
        "kind": "function",
        "role": "native_aom_candidate_screen",
        "heads": ("ridge", "pls"),
        "reuse": "candidate_table",
        "cpu": True,
        "cuda": True,
        "catalog_id": "aom_pop.aom_sweep",
        "catalog_role": "catalog_binding",
        "doc_path": "docs/methods/aom_sweep_run.md",
        "config_options": _AOM_SWEEP_OPTIONS,
        "notes": "Built-in compact/wide strict-linear AOM profile screen over Ridge/PLS grids.",
    },
    {
        "name": "aom_profile_sweep_regressor",
        "entry": "NativeAOMSweepRegressor",
        "kind": "sklearn_estimator",
        "role": "native_aom_candidate_screen",
        "heads": ("ridge", "pls"),
        "reuse": "selected_final_model",
        "cpu": True,
        "cuda": True,
        "catalog_id": "aom_pop.aom_sweep",
        "catalog_role": "sklearn_wrapper",
        "wrapper_of": "aom_sweep_run",
        "doc_path": "docs/methods/aom_sweep_run.md",
        "config_options": tuple(
            option for option in _AOM_SWEEP_OPTIONS
            if option not in {"chains", "score_only"}
        ),
        "notes": "Reusable estimator over built-in strict-linear AOM profiles.",
    },
    {
        "name": "aom_moment_screen_refit_campaign",
        "entry": "aom_moment_screen_refit_campaign",
        "kind": "function",
        "role": "preconfigured_aom_moment_screen_refit",
        "heads": ("ridge", "pls"),
        "reuse": "refit_report_rows",
        "cpu": True,
        "cuda": True,
        "catalog_id": "aom_pop.aom_chain_screen_refit",
        "catalog_role": "preset_function",
        "wrapper_of": "aom_chain_screen_refit_campaign",
        "doc_path": "docs/methods/aom_chain_sweep_run.md",
        "config_options": _AOM_MOMENT_SCREEN_REFIT_OPTIONS,
        "notes": "Fast AOM/moment preprocessing screen-refit preset with strict moment routes, split-head scoring and exact-CV refit.",
    },
    {
        "name": "staged_chain_campaign",
        "entry": "aom_staged_chain_campaign",
        "kind": "function",
        "role": "staged_screen_refit_orchestration",
        "heads": ("ridge", "pls"),
        "reuse": "staged_refit_report_rows",
        "cpu": True,
        "cuda": True,
        "catalog_id": "aom_pop.aom_staged_chain_campaign",
        "catalog_role": "catalog_binding",
        "doc_path": "docs/methods/aom_staged_chain_campaign.md",
        "config_options": _STAGED_CAMPAIGN_OPTIONS,
        "notes": "Staged compact/wide/lab strict-chain screens over Ridge/PLS/mixed heads with cross-stage global/per-head retention, one exact-CV refit, and impact/rank/audit diagnostics.",
    },
    {
        "name": "staged_chain_campaign_estimator",
        "entry": "NativeAOMStagedChainCampaignRegressor",
        "kind": "sklearn_estimator",
        "role": "staged_screen_refit_estimator",
        "heads": ("ridge", "pls"),
        "reuse": "selected_final_model",
        "cpu": True,
        "cuda": True,
        "catalog_id": "aom_pop.aom_staged_chain_campaign",
        "catalog_role": "sklearn_wrapper",
        "wrapper_of": "aom_staged_chain_campaign",
        "doc_path": "docs/methods/aom_staged_chain_campaign.md",
        "config_options": _STAGED_CAMPAIGN_ESTIMATOR_OPTIONS,
        "notes": "Reusable sklearn wrapper over staged compact/wide/lab AOM/moment screen-refit; fit selects only by train exact-CV refit and then fits the selected final-only candidate.",
    },
    {
        "name": "savgol_focus_regressor",
        "entry": "NativeAOMSavgolFocusRegressor",
        "kind": "sklearn_estimator",
        "role": "winning_preconfigured_aom_moment_screen_refit",
        "heads": ("ridge", "pls"),
        "reuse": "selected_final_model",
        "cpu": True,
        "cuda": True,
        "catalog_id": "aom_pop.aom_staged_chain_campaign",
        "catalog_role": "preset_sklearn_wrapper",
        "wrapper_of": "aom_staged_chain_campaign",
        "doc_path": "docs/methods/aom_staged_chain_campaign.md",
        "config_options": _SAVGOL_FOCUS_ESTIMATOR_OPTIONS,
        "preset_plan": "savgol_focus",
        "notes": "Fast SavGol-focused staged AOM/moment preset with train-CV-selected scale_x grid and final-only selected-candidate reuse.",
    },
    {
        "name": "strict_family_lite_regressor",
        "entry": "NativeAOMStrictFamilyLiteRegressor",
        "kind": "sklearn_estimator",
        "role": "cost_safe_family_audit",
        "heads": ("ridge", "pls"),
        "reuse": "selected_final_model",
        "cpu": True,
        "cuda": True,
        "catalog_id": "aom_pop.aom_staged_chain_campaign",
        "catalog_role": "preset_sklearn_wrapper",
        "wrapper_of": "aom_staged_chain_campaign",
        "doc_path": "docs/methods/aom_staged_chain_campaign.md",
        "config_options": _STRICT_FAMILY_LITE_ESTIMATOR_OPTIONS,
        "preset_plan": "strict_family_focus",
        "notes": "Cost-safe strict-family staged AOM/moment preset over SavGol, Norris-Williams, finite-difference, Gaussian, FCK and Whittaker stages with small default refit budget.",
    },
    {
        "name": "aom_screen_refit_regressor",
        "entry": "NativeAOMScreenRefitRegressor",
        "kind": "sklearn_estimator",
        "role": "ultra_configurable_screen_refit_estimator",
        "heads": ("ridge", "pls"),
        "reuse": "selected_final_model",
        "cpu": True,
        "cuda": True,
        "catalog_id": "aom_pop.aom_chain_screen_refit",
        "catalog_role": "sklearn_wrapper",
        "wrapper_of": "aom_chain_screen_refit_campaign",
        "doc_path": "docs/methods/aom_chain_sweep_run.md",
        "config_options": _AOM_MOMENT_SCREEN_REFIT_OPTIONS,
        "notes": "Fully configurable sklearn screen-refit estimator over strict AOM/moment chains.",
    },
    {
        "name": "aom_ridge_blender",
        "entry": "NativeAOMRidgeBlenderRegressor",
        "kind": "sklearn_estimator",
        "role": "linear_aom_diversity",
        "heads": ("ridge",),
        "reuse": "selected_blend_model",
        "cpu": True,
        "cuda": True,
        "catalog_id": "aom_pop.ridge_blender",
        "catalog_role": "sklearn_wrapper",
        "wrapper_of": "aom_ridge_blender",
        "doc_path": "docs/methods/aom_ridge_blender.md",
        "config_options": _AOM_RIDGE_BLENDER_OPTIONS,
        "notes": "Strict-linear AOM Ridge OOF simplex blender with folded input coefficients.",
    },
    {
        "name": "aom_ridge_superblock",
        "entry": "NativeAOMRidgeSuperblockRegressor",
        "kind": "sklearn_estimator",
        "role": "strict_operator_superblock",
        "heads": ("ridge",),
        "reuse": "selected_superblock_model",
        "cpu": True,
        "cuda": True,
        "catalog_id": "aom_pop.ridge_superblock",
        "catalog_role": "sklearn_wrapper",
        "wrapper_of": "aom_ridge_superblock",
        "doc_path": "docs/methods/aom_ridge_superblock.md",
        "config_options": _AOM_RIDGE_SUPERBLOCK_OPTIONS,
        "notes": "Concatenate strict-linear AOM operator views and fit one Ridge head with folded input coefficients.",
    },
    {
        "name": "aom_ridge_active_superblock",
        "entry": "NativeAOMRidgeActiveSuperblockRegressor",
        "kind": "sklearn_estimator",
        "role": "strict_operator_active_superblock",
        "heads": ("ridge",),
        "reuse": "selected_active_superblock_model",
        "cpu": True,
        "cuda": True,
        "catalog_id": "aom_pop.ridge_active_superblock",
        "catalog_role": "sklearn_wrapper",
        "wrapper_of": "aom_ridge_active_superblock",
        "doc_path": "docs/methods/aom_ridge_active_superblock.md",
        "config_options": _AOM_RIDGE_ACTIVE_SUPERBLOCK_OPTIONS,
        "notes": "Prune strict-linear AOM operators on train-only response signatures, then fit one Ridge superblock with folded input coefficients.",
    },
    {
        "name": "aom_ridge_global",
        "entry": "NativeAOMRidgeGlobalRegressor",
        "kind": "sklearn_estimator",
        "role": "strict_operator_global_selector",
        "heads": ("ridge",),
        "reuse": "selected_operator_model",
        "cpu": True,
        "cuda": True,
        "catalog_id": "aom_pop.ridge_global",
        "catalog_role": "sklearn_wrapper",
        "wrapper_of": "aom_ridge_global",
        "doc_path": "docs/methods/aom_ridge_global.md",
        "config_options": _AOM_RIDGE_GLOBAL_OPTIONS,
        "notes": "Select one strict-linear AOM operator plus Ridge alpha by native CV, with folded input coefficients.",
    },
    {
        "name": "aom_pls_superblock",
        "entry": "NativeAOMPLSSuperblockRegressor",
        "kind": "sklearn_estimator",
        "role": "strict_operator_pls_superblock",
        "heads": ("pls",),
        "reuse": "selected_pls_superblock_model",
        "cpu": True,
        "cuda": True,
        "catalog_id": "aom_pop.aom_pls_superblock",
        "catalog_role": "sklearn_wrapper",
        "wrapper_of": "aom_pls_superblock",
        "doc_path": "docs/methods/aom_pls_superblock.md",
        "config_options": _AOM_PLS_SUPERBLOCK_OPTIONS,
        "notes": "Concatenate strict-linear AOM operator views and fit one PLS head with folded input coefficients.",
    },
    {
        "name": "aom_ridge_pls_superblock",
        "entry": "NativeAOMRidgePLSSuperblockRegressor",
        "kind": "sklearn_estimator",
        "role": "strict_operator_ridge_pls_superblock",
        "heads": ("ridge", "pls"),
        "reuse": "selected_ridge_pls_superblock_model",
        "cpu": True,
        "cuda": True,
        "catalog_id": "aom_pop.aom_ridge_pls_superblock",
        "catalog_role": "sklearn_wrapper",
        "wrapper_of": "aom_ridge_pls_superblock",
        "doc_path": "docs/methods/aom_ridge_pls_superblock.md",
        "config_options": _AOM_RIDGE_PLS_SUPERBLOCK_OPTIONS,
        "notes": "Concatenate strict-linear AOM operator views and fit one native Ridge-PLS head with folded input coefficients.",
    },
    {
        "name": "aom_chain_ridge_pls",
        "entry": "NativeAOMChainRidgePLSRegressor",
        "kind": "sklearn_estimator",
        "role": "strict_chain_ridge_pls_selector",
        "heads": ("ridge", "pls"),
        "reuse": "selected_chain_model",
        "cpu": True,
        "cuda": True,
        "catalog_id": "aom_pop.aom_chain_ridge_pls",
        "catalog_role": "sklearn_wrapper",
        "wrapper_of": "aom_chain_ridge_pls",
        "doc_path": "docs/methods/aom_chain_ridge_pls.md",
        "config_options": _AOM_CHAIN_RIDGE_PLS_OPTIONS,
        "notes": "Select one strict-linear sequential AOM chain plus Ridge-PLS components/lambda by train CV, then fold coefficients back to raw input space.",
    },
    {
        "name": "aom_operator_pls_stack",
        "entry": "NativeAOMOperatorPLSStackRegressor",
        "kind": "sklearn_estimator",
        "role": "linear_aom_diversity",
        "heads": ("pls", "ridge"),
        "reuse": "selected_stack_model",
        "cpu": True,
        "cuda": True,
        "catalog_id": "aom_pop.operator_pls_stack",
        "catalog_role": "sklearn_wrapper",
        "wrapper_of": "aom_operator_pls_stack",
        "doc_path": "docs/methods/aom_operator_pls_stack.md",
        "config_options": _AOM_OPERATOR_PLS_STACK_OPTIONS,
        "notes": "Strict-operator PLS1 score stack with Ridge head and folded input coefficients.",
    },
    {
        "name": "aom_ridge_mkl_superblock",
        "entry": "NativeAOMRidgeMKLSuperblockRegressor",
        "kind": "sklearn_estimator",
        "role": "strict_operator_mkl_superblock",
        "heads": ("ridge",),
        "reuse": "selected_mkl_superblock_model",
        "cpu": True,
        "cuda": True,
        "catalog_id": "aom_pop.ridge_mkl_superblock",
        "catalog_role": "sklearn_wrapper",
        "wrapper_of": "aom_ridge_mkl_superblock",
        "doc_path": "docs/methods/aom_ridge_mkl_superblock.md",
        "config_options": _AOM_RIDGE_MKL_SUPERBLOCK_OPTIONS,
        "notes": "Concatenate strict-linear AOM operator views, learn train-only KTA block weights, and fit one Ridge head with folded input coefficients.",
    },
    {
        "name": "aom_robust_hpo",
        "entry": "NativeAOMRobustHPORegressor",
        "kind": "sklearn_estimator",
        "role": "preconfigured_aom_profile",
        "heads": ("ridge", "pls"),
        "reuse": "selected_profile_model",
        "cpu": True,
        "cuda": True,
        "catalog_id": "aom_pop.robust_hpo",
        "catalog_role": "sklearn_wrapper",
        "wrapper_of": "aom_robust_hpo",
        "doc_path": "docs/methods/aom_robust_hpo.md",
        "config_options": _AOM_ROBUST_HPO_OPTIONS,
        "notes": "Compact/wide native strict-linear AOM product screen preset.",
    },
    {
        "name": "aom_pls",
        "entry": "NativeAOMPLSRegressor",
        "kind": "sklearn_estimator",
        "role": "legacy_aom_selector",
        "heads": ("pls",),
        "reuse": "selected_operator_model",
        "cpu": True,
        "cuda": True,
        "catalog_id": "aom_pop.aom_pls",
        "catalog_role": "sklearn_wrapper",
        "wrapper_of": "aom_global_select",
        "doc_path": "docs/methods/aom_pls.md",
        "config_options": _AOM_SELECTOR_OPTIONS,
        "notes": "Global AOM PLS selector surface exposed from the moment facade for reuse.",
    },
    {
        "name": "pop_pls",
        "entry": "NativePOPPLSRegressor",
        "kind": "sklearn_estimator",
        "role": "legacy_aom_selector",
        "heads": ("pls",),
        "reuse": "per_component_operator_model",
        "cpu": True,
        "cuda": True,
        "catalog_id": "aom_pop.pop_pls",
        "catalog_role": "sklearn_wrapper",
        "wrapper_of": "aom_per_component_select",
        "doc_path": "docs/methods/pop_pls.md",
        "config_options": _AOM_SELECTOR_OPTIONS,
        "notes": "Per-component POP-PLS selector surface exposed from the moment facade for reuse.",
    },
    {
        "name": "moment_mixed_screen_refit",
        "entry": "NativeAOMMomentScreenRefitRegressor",
        "kind": "sklearn_estimator",
        "role": "preconfigured_aom_moment_screen_refit",
        "heads": ("ridge", "pls"),
        "reuse": "selected_final_model",
        "cpu": True,
        "cuda": True,
        "catalog_id": "aom_pop.aom_chain_screen_refit",
        "catalog_role": "sklearn_wrapper",
        "wrapper_of": "aom_chain_screen_refit_campaign",
        "doc_path": "docs/methods/aom_chain_sweep_run.md",
        "config_options": _AOM_MOMENT_SCREEN_REFIT_OPTIONS,
        "notes": "Mixed Ridge/PLS AOM moment screen-refit estimator with split-head scoring, exact-CV refit and final-only winner reuse.",
    },
    {
        "name": "moment_pls_screen_refit",
        "entry": "NativeAOMMomentPLSScreenRefitRegressor",
        "kind": "sklearn_estimator",
        "role": "preconfigured_aom_moment_screen_refit",
        "heads": ("pls",),
        "reuse": "selected_final_model",
        "cpu": True,
        "cuda": True,
        "catalog_id": "aom_pop.aom_chain_screen_refit",
        "catalog_role": "sklearn_wrapper",
        "wrapper_of": "aom_chain_screen_refit_campaign",
        "doc_path": "docs/methods/aom_chain_sweep_run.md",
        "config_options": _AOM_MOMENT_SCREEN_REFIT_OPTIONS,
        "notes": "PLS-only AOM moment GCV-proxy screen with exact-CV refit and final-only winner reuse.",
    },
    {
        "name": "moment_pls_exact_screen_refit",
        "entry": "NativeAOMMomentPLSExactScreenRefitRegressor",
        "kind": "sklearn_estimator",
        "role": "preconfigured_aom_moment_screen_refit",
        "heads": ("pls",),
        "reuse": "selected_final_model",
        "cpu": True,
        "cuda": True,
        "catalog_id": "aom_pop.aom_chain_screen_refit",
        "catalog_role": "sklearn_wrapper",
        "wrapper_of": "aom_chain_screen_refit_campaign",
        "doc_path": "docs/methods/aom_chain_sweep_run.md",
        "config_options": _AOM_MOMENT_SCREEN_REFIT_OPTIONS,
        "notes": "PLS-only AOM moment exact-CV screen with exact-CV refit and final-only winner reuse.",
    },
    {
        "name": "moment_ridge_screen_refit",
        "entry": "NativeAOMMomentRidgeScreenRefitRegressor",
        "kind": "sklearn_estimator",
        "role": "preconfigured_aom_moment_screen_refit",
        "heads": ("ridge",),
        "reuse": "selected_final_model",
        "cpu": True,
        "cuda": True,
        "catalog_id": "aom_pop.aom_chain_screen_refit",
        "catalog_role": "sklearn_wrapper",
        "wrapper_of": "aom_chain_screen_refit_campaign",
        "doc_path": "docs/methods/aom_chain_sweep_run.md",
        "config_options": _AOM_MOMENT_SCREEN_REFIT_OPTIONS,
        "notes": "Ridge-only AOM moment exact-CV screen with exact-CV refit and final-only winner reuse.",
    },
    {
        "name": "aom_screen_refit_candidate_pool",
        "entry": "aom_screen_refit_candidate_pool",
        "kind": "function",
        "role": "screen_refit_pool",
        "heads": ("ridge", "pls"),
        "reuse": "retained_candidate_rows",
        "cpu": True,
        "cuda": True,
        "catalog_id": "aom_pop.aom_chain_screen_refit",
        "catalog_role": "campaign_helper",
        "wrapper_of": "aom_chain_screen_refit_campaign",
        "doc_path": "docs/methods/aom_chain_sweep_run.md",
        "config_options": _AOM_SCREEN_POOL_OPTIONS,
        "notes": "Extract the global/per-head retained candidate pool from an AOM/moment screen report before exact refit.",
    },
    {
        "name": "aom_refit_execution_plan",
        "entry": "aom_refit_execution_plan",
        "kind": "function",
        "role": "refit_launch_planning",
        "heads": ("ridge", "pls"),
        "reuse": "source_free_refit_plan",
        "cpu": True,
        "cuda": True,
        "non_catalog_reason": "planning helper over a campaign report; not a fit/predict method catalog entry",
        "config_options": (
            "top_k",
            "refit_per_head_top_k",
            "auto_max_extra_fraction",
        ),
        "notes": "Source-free execution-mode planning for exact-CV refit of retained AOM/moment candidates.",
    },
    {
        "name": "aom_refit_candidates",
        "entry": "aom_refit_candidates",
        "kind": "function",
        "role": "exact_cv_refit",
        "heads": ("ridge", "pls"),
        "reuse": "refit_report_rows",
        "cpu": True,
        "cuda": True,
        "catalog_id": "aom_pop.aom_chain_screen_refit",
        "catalog_role": "campaign_helper",
        "wrapper_of": "aom_chain_screen_refit_campaign",
        "doc_path": "docs/methods/aom_chain_sweep_run.md",
        "config_options": _AOM_REFIT_OPTIONS,
        "notes": "Exact-CV verification of retained AOM/moment candidate rows with grouped/batched refit execution modes.",
    },
    {
        "name": "aom_chain_fixed_fit",
        "entry": "aom_chain_fixed_fit_run",
        "kind": "function",
        "role": "winner_reuse",
        "heads": ("ridge", "pls"),
        "reuse": "selected_final_model",
        "cpu": True,
        "cuda": True,
        "catalog_id": "aom_pop.aom_chain_fixed_fit",
        "catalog_role": "catalog_binding",
        "doc_path": "docs/methods/aom_chain_sweep_run.md",
        "config_options": _AOM_FIXED_CANDIDATE_OPTIONS,
        "notes": "Fit one already-selected strict-linear AOM/moment chain/head/parameter without rerunning CV.",
    },
    {
        "name": "fixed_candidate",
        "entry": "NativeAOMFixedCandidateRegressor",
        "kind": "sklearn_estimator",
        "role": "winner_reuse",
        "heads": ("ridge", "pls"),
        "reuse": "explicit_candidate_or_refit_row",
        "cpu": True,
        "cuda": True,
        "catalog_id": "aom_pop.aom_chain_fixed_fit",
        "catalog_role": "sklearn_wrapper",
        "wrapper_of": "aom_chain_fixed_fit_run",
        "doc_path": "docs/methods/aom_chain_sweep_run.md",
        "config_options": _AOM_FIXED_CANDIDATE_OPTIONS,
        "notes": "Reusable estimator built from an AOM/moment campaign or refit winner row with folded input coefficients.",
    },
    {
        "name": "build_aom_strict_chain_grid",
        "entry": "build_aom_strict_chain_grid",
        "kind": "function",
        "role": "preprocessing_grid_builder",
        "heads": (),
        "reuse": "strict_linear_chain_descriptors",
        "cpu": True,
        "cuda": True,
        "non_catalog_reason": "campaign grid builder; not a fit/predict method catalog entry",
        "config_options": _AOM_CHAIN_GRID_OPTIONS,
        "notes": "Construct deterministic compact/wide/lab strict-linear preprocessing chain grids for AOM/moment campaigns.",
    },
    {
        "name": "iter_aom_strict_chain_grid",
        "entry": "iter_aom_strict_chain_grid",
        "kind": "function",
        "role": "preprocessing_grid_stream",
        "heads": (),
        "reuse": "strict_linear_chain_descriptors",
        "cpu": True,
        "cuda": True,
        "non_catalog_reason": "campaign grid iterator; not a fit/predict method catalog entry",
        "config_options": _AOM_CHAIN_GRID_ITER_OPTIONS,
        "notes": "Stream deterministic compact/wide/lab strict-linear preprocessing chains with stable ids, slicing and chunks.",
    },
    {
        "name": "decode_aom_chains",
        "entry": "decode_aom_chains",
        "kind": "function",
        "role": "candidate_decode",
        "heads": (),
        "reuse": "decoded_chain_descriptors",
        "cpu": True,
        "cuda": True,
        "non_catalog_reason": "candidate-report decoder; not a fit/predict method catalog entry",
        "config_options": (),
        "notes": "Decode flat AOM chain descriptors from native sweep/campaign results.",
    },
    {
        "name": "aom_candidate_table",
        "entry": "aom_candidate_table",
        "kind": "function",
        "role": "candidate_decode",
        "heads": ("ridge", "pls"),
        "reuse": "decoded_candidate_rows",
        "cpu": True,
        "cuda": True,
        "non_catalog_reason": "candidate-table decoder; not a fit/predict method catalog entry",
        "config_options": _AOM_CANDIDATE_TABLE_OPTIONS,
        "notes": "Decode native AOM candidate scores into row dictionaries with chain/head/route provenance.",
    },
    {
        "name": "aom_evaluate_candidates",
        "entry": "aom_evaluate_candidates",
        "kind": "function",
        "role": "holdout_candidate_audit",
        "heads": ("ridge", "pls"),
        "reuse": "evaluated_candidate_rows",
        "cpu": True,
        "cuda": True,
        "non_catalog_reason": "offline holdout audit helper; not a fit/predict method catalog entry",
        "config_options": _AOM_EVALUATE_OPTIONS,
        "notes": "Evaluate decoded AOM/moment candidate rows on an explicit holdout split for CV-vs-test rank diagnostics.",
    },
    {
        "name": "aom_candidate_operator_summary",
        "entry": "aom_candidate_operator_summary",
        "kind": "function",
        "role": "candidate_audit",
        "heads": ("ridge", "pls"),
        "reuse": "operator_summary",
        "cpu": True,
        "cuda": True,
        "non_catalog_reason": "candidate-report audit helper; not a fit/predict method catalog entry",
        "config_options": _AOM_OPERATOR_SUMMARY_OPTIONS,
        "notes": "Summarize scored AOM/moment candidates by head, operator, route and chain length.",
    },
    {
        "name": "aom_candidate_preprocessing_impact",
        "entry": "aom_candidate_preprocessing_impact",
        "kind": "function",
        "role": "candidate_audit",
        "heads": ("ridge", "pls"),
        "reuse": "preprocessing_impact_summary",
        "cpu": True,
        "cuda": True,
        "non_catalog_reason": "candidate-report audit helper; not a fit/predict method catalog entry",
        "config_options": _AOM_PREPROCESSING_IMPACT_OPTIONS,
        "notes": "Summarize preprocessing option/stage impact, including deltas vs identity baselines.",
    },
    {
        "name": "aom_candidate_route_summary",
        "entry": "aom_candidate_route_summary",
        "kind": "function",
        "role": "candidate_audit",
        "heads": ("ridge", "pls"),
        "reuse": "route_coverage_summary",
        "cpu": True,
        "cuda": True,
        "non_catalog_reason": "candidate-report audit helper; not a fit/predict method catalog entry",
        "config_options": _AOM_ROUTE_SUMMARY_OPTIONS,
        "notes": "Summarize materialized vs dense/banded/structured operator-moment route coverage by head and chain.",
    },
    {
        "name": "aom_candidate_rank_diagnostics",
        "entry": "aom_candidate_rank_diagnostics",
        "kind": "function",
        "role": "candidate_audit",
        "heads": ("ridge", "pls"),
        "reuse": "rank_recall_diagnostics",
        "cpu": True,
        "cuda": True,
        "non_catalog_reason": "candidate-report audit helper; not a fit/predict method catalog entry",
        "config_options": _AOM_RANK_DIAGNOSTICS_OPTIONS,
        "notes": "Compute screen-vs-holdout rank drift and top-k recall diagnostics from evaluated candidates.",
    },
    {
        "name": "aom_candidate_report_records",
        "entry": "aom_candidate_report_records",
        "kind": "function",
        "role": "candidate_report_io",
        "heads": ("ridge", "pls"),
        "reuse": "json_safe_candidate_rows",
        "cpu": True,
        "cuda": True,
        "non_catalog_reason": "candidate-report serialization helper; not a fit/predict method catalog entry",
        "config_options": ("include_predictions",),
        "notes": "Flatten AOM/moment campaign or holdout reports into JSON-safe candidate records.",
    },
    {
        "name": "aom_save_candidate_report",
        "entry": "aom_save_candidate_report",
        "kind": "function",
        "role": "candidate_report_io",
        "heads": ("ridge", "pls"),
        "reuse": "saved_candidate_report",
        "cpu": True,
        "cuda": True,
        "non_catalog_reason": "candidate-report serialization helper; not a fit/predict method catalog entry",
        "config_options": _AOM_SAVE_REPORT_OPTIONS,
        "notes": "Save AOM/moment candidate reports as JSON, JSONL or CSV for offline replay and audit.",
    },
    {
        "name": "aom_load_candidate_report",
        "entry": "aom_load_candidate_report",
        "kind": "function",
        "role": "candidate_report_io",
        "heads": ("ridge", "pls"),
        "reuse": "loaded_candidate_rows",
        "cpu": True,
        "cuda": True,
        "non_catalog_reason": "candidate-report loading helper; not a fit/predict method catalog entry",
        "config_options": _AOM_LOAD_REPORT_OPTIONS,
        "notes": "Load JSON, JSONL or CSV AOM/moment candidate reports back into refittable row dictionaries.",
    },
    {
        "name": "ridge",
        "entry": "ridge",
        "kind": "function",
        "role": "direct_linear_head",
        "heads": ("ridge",),
        "reuse": "method_result_coefficients",
        "cpu": True,
        "cuda": True,
        "catalog_id": "models.regularized.ridge",
        "catalog_role": "catalog_binding",
        "doc_path": "docs/methods/ridge.md",
        "config_options": _RIDGE_OPTIONS,
        "notes": "Closed-form Ridge head backed by libn4m.",
    },
    {
        "name": "ridge_regressor",
        "entry": "NativeRidgeRegressor",
        "kind": "sklearn_estimator",
        "role": "direct_linear_head",
        "heads": ("ridge",),
        "reuse": "selected_linear_model",
        "cpu": True,
        "cuda": True,
        "catalog_id": "models.regularized.ridge",
        "catalog_role": "sklearn_wrapper",
        "wrapper_of": "ridge",
        "doc_path": "docs/methods/ridge.md",
        "config_options": _RIDGE_OPTIONS,
        "notes": "Reusable sklearn-style wrapper for the native Ridge head.",
    },
    {
        "name": "pls",
        "entry": "pls",
        "kind": "function",
        "role": "direct_component_head",
        "heads": ("pls",),
        "reuse": "method_result_coefficients",
        "cpu": True,
        "cuda": True,
        "catalog_id": "models.pls.pls_fit_simple",
        "catalog_role": "catalog_binding",
        "doc_path": "docs/methods/pls.md",
        "config_options": _PLS_OPTIONS,
        "notes": "Direct moment PLS head backed by n4m_model_selection_sweep_run with replayable coefficients.",
    },
    {
        "name": "pls_regressor",
        "entry": "NativePLSRegressor",
        "kind": "sklearn_estimator",
        "role": "direct_component_head",
        "heads": ("pls",),
        "reuse": "selected_linear_model",
        "cpu": True,
        "cuda": True,
        "catalog_id": "models.pls.pls_fit_simple",
        "catalog_role": "sklearn_wrapper",
        "wrapper_of": "pls",
        "doc_path": "docs/methods/pls.md",
        "config_options": _PLS_OPTIONS,
        "notes": "Reusable sklearn-style wrapper for native moment PLS.",
    },
    {
        "name": "pcr",
        "entry": "pcr",
        "kind": "function",
        "role": "direct_component_head",
        "heads": ("pcr",),
        "reuse": "fit_predict_method_result",
        "cpu": True,
        "cuda": True,
        "catalog_id": "models.pls.pcr",
        "catalog_role": "catalog_binding",
        "doc_path": "docs/methods/pcr.md",
        "config_options": _PCR_OPTIONS,
        "notes": "Direct native Principal Components Regression head with replayable coefficients.",
    },
    {
        "name": "pcr_regressor",
        "entry": "NativePCRRegressor",
        "kind": "sklearn_estimator",
        "role": "direct_component_head",
        "heads": ("pcr",),
        "reuse": "fit_predict_estimator",
        "cpu": True,
        "cuda": True,
        "catalog_id": "models.pls.pcr",
        "catalog_role": "sklearn_wrapper",
        "wrapper_of": "pcr",
        "doc_path": "docs/methods/pcr.md",
        "config_options": _PCR_OPTIONS,
        "notes": "Reusable sklearn-style PCR wrapper over the native MethodResult ABI.",
    },
    {
        "name": "cppls",
        "entry": "cppls",
        "kind": "function",
        "role": "direct_component_head",
        "heads": ("pls",),
        "reuse": "method_result_coefficients",
        "cpu": True,
        "cuda": True,
        "catalog_id": "models.pls.cppls",
        "catalog_role": "direct_native_binding",
        "doc_path": "docs/methods/cppls.md",
        "config_options": _CPPLS_OPTIONS,
        "notes": "Powered PLS component head backed by libn4m.",
    },
    {
        "name": "cppls_regressor",
        "entry": "NativeCPPLSRegressor",
        "kind": "sklearn_estimator",
        "role": "direct_component_head",
        "heads": ("pls",),
        "reuse": "selected_linear_model",
        "cpu": True,
        "cuda": True,
        "catalog_id": "models.pls.cppls",
        "catalog_role": "sklearn_wrapper",
        "wrapper_of": "cppls",
        "doc_path": "docs/methods/cppls.md",
        "config_options": _CPPLS_OPTIONS,
        "notes": "Reusable sklearn-style wrapper for native Powered PLS.",
    },
    {
        "name": "weighted_pls",
        "entry": "weighted_pls",
        "kind": "function",
        "role": "direct_component_head",
        "heads": ("pls",),
        "reuse": "method_result_coefficients",
        "cpu": True,
        "cuda": True,
        "catalog_id": "models.regularized.weighted_pls",
        "catalog_role": "catalog_binding",
        "doc_path": "docs/methods/weighted_pls.md",
        "config_options": _WEIGHTED_PLS_OPTIONS,
        "notes": "Weighted linear PLS head backed by the native MethodResult ABI with replayable coefficients.",
    },
    {
        "name": "weighted_pls_regressor",
        "entry": "NativeWeightedPLSRegressor",
        "kind": "sklearn_estimator",
        "role": "direct_component_head",
        "heads": ("pls",),
        "reuse": "selected_linear_model",
        "cpu": True,
        "cuda": True,
        "catalog_id": "models.regularized.weighted_pls",
        "catalog_role": "sklearn_wrapper",
        "wrapper_of": "weighted_pls",
        "doc_path": "docs/methods/weighted_pls.md",
        "config_options": _WEIGHTED_PLS_OPTIONS,
        "notes": "Reusable sklearn-style wrapper for native weighted PLS.",
    },
    {
        "name": "robust_pls",
        "entry": "robust_pls",
        "kind": "function",
        "role": "direct_component_head",
        "heads": ("pls",),
        "reuse": "method_result_coefficients",
        "cpu": True,
        "cuda": True,
        "catalog_id": "models.regularized.robust_pls",
        "catalog_role": "catalog_binding",
        "doc_path": "docs/methods/robust_pls.md",
        "config_options": _ROBUST_PLS_OPTIONS,
        "notes": "Robust Huber-weighted linear PLS head backed by the native MethodResult ABI with replayable coefficients.",
    },
    {
        "name": "robust_pls_regressor",
        "entry": "NativeRobustPLSRegressor",
        "kind": "sklearn_estimator",
        "role": "direct_component_head",
        "heads": ("pls",),
        "reuse": "selected_linear_model",
        "cpu": True,
        "cuda": True,
        "catalog_id": "models.regularized.robust_pls",
        "catalog_role": "sklearn_wrapper",
        "wrapper_of": "robust_pls",
        "doc_path": "docs/methods/robust_pls.md",
        "config_options": _ROBUST_PLS_OPTIONS,
        "notes": "Reusable sklearn-style wrapper for native robust PLS.",
    },
    {
        "name": "ridge_pls",
        "entry": "ridge_pls",
        "kind": "function",
        "role": "direct_component_head",
        "heads": ("pls",),
        "reuse": "method_result_coefficients",
        "cpu": True,
        "cuda": True,
        "catalog_id": "models.regularized.ridge_pls",
        "catalog_role": "catalog_binding",
        "doc_path": "docs/methods/ridge_pls.md",
        "config_options": _RIDGE_PLS_OPTIONS,
        "notes": "Ridge-augmented linear SIMPLS head backed by the native MethodResult ABI with replayable coefficients.",
    },
    {
        "name": "ridge_pls_regressor",
        "entry": "NativeRidgePLSRegressor",
        "kind": "sklearn_estimator",
        "role": "direct_component_head",
        "heads": ("pls",),
        "reuse": "selected_linear_model",
        "cpu": True,
        "cuda": True,
        "catalog_id": "models.regularized.ridge_pls",
        "catalog_role": "sklearn_wrapper",
        "wrapper_of": "ridge_pls",
        "doc_path": "docs/methods/ridge_pls.md",
        "config_options": _RIDGE_PLS_OPTIONS,
        "notes": "Reusable sklearn-style wrapper for native ridge-augmented PLS.",
    },
    {
        "name": "continuum_regression",
        "entry": "continuum_regression",
        "kind": "function",
        "role": "direct_component_head",
        "heads": ("pls", "ols"),
        "reuse": "method_result_coefficients",
        "cpu": True,
        "cuda": True,
        "catalog_id": "models.regularized.continuum_regression",
        "catalog_role": "direct_native_binding",
        "doc_path": "docs/methods/continuum_regression.md",
        "config_options": _CONTINUUM_OPTIONS,
        "notes": "Continuum regression head backed by libn4m.",
    },
    {
        "name": "continuum_regression_regressor",
        "entry": "NativeContinuumRegressionRegressor",
        "kind": "sklearn_estimator",
        "role": "direct_component_head",
        "heads": ("pls", "ols"),
        "reuse": "selected_linear_model",
        "cpu": True,
        "cuda": True,
        "catalog_id": "models.regularized.continuum_regression",
        "catalog_role": "sklearn_wrapper",
        "wrapper_of": "continuum_regression",
        "doc_path": "docs/methods/continuum_regression.md",
        "config_options": _CONTINUUM_OPTIONS,
        "notes": "Reusable sklearn-style wrapper for native continuum regression.",
    },
    {
        "name": "ecr",
        "entry": "ecr",
        "kind": "function",
        "role": "direct_component_head",
        "heads": ("pls",),
        "reuse": "method_result_coefficients",
        "cpu": True,
        "cuda": True,
        "catalog_id": "models.specialized.ecr",
        "catalog_role": "direct_native_binding",
        "doc_path": "docs/methods/ecr.md",
        "config_options": _ECR_OPTIONS,
        "notes": "Elastic Component Regression head backed by libn4m.",
    },
    {
        "name": "ecr_regressor",
        "entry": "NativeECRRegressor",
        "kind": "sklearn_estimator",
        "role": "direct_component_head",
        "heads": ("pls",),
        "reuse": "selected_linear_model",
        "cpu": True,
        "cuda": True,
        "catalog_id": "models.specialized.ecr",
        "catalog_role": "sklearn_wrapper",
        "wrapper_of": "ecr",
        "doc_path": "docs/methods/ecr.md",
        "config_options": _ECR_OPTIONS,
        "notes": "Reusable sklearn-style wrapper for native Elastic Component Regression.",
    },
    {
        "name": "moment_stack",
        "entry": "moment_stack",
        "kind": "function",
        "role": "moment_model_stack",
        "heads": ("ridge", "pls", "pcr", "continuum", "ecr", "cppls"),
        "reuse": "fit_predict_estimator",
        "cpu": True,
        "cuda": True,
        "catalog_id": "models.ensembles.moment_stack",
        "catalog_role": "catalog_binding",
        "doc_path": "docs/methods/moment_stack.md",
        "config_options": _MOMENT_STACK_OPTIONS,
        "notes": "Factory that fits NativeMomentStackRegressor with train-only OOF meta-model selection.",
    },
    {
        "name": "moment_stack_regressor",
        "entry": "NativeMomentStackRegressor",
        "kind": "sklearn_estimator",
        "role": "moment_model_stack",
        "heads": ("ridge", "pls", "pcr", "continuum", "ecr", "cppls"),
        "reuse": "oof_meta_model",
        "cpu": True,
        "cuda": True,
        "catalog_id": "models.ensembles.moment_stack",
        "catalog_role": "sklearn_wrapper",
        "wrapper_of": "moment_stack",
        "doc_path": "docs/methods/moment_stack.md",
        "config_options": _MOMENT_STACK_OPTIONS,
        "notes": "Train-only OOF Ridge stack over native moment-compatible base heads.",
    },
    {
        "name": "backend_recommendation",
        "entry": "moment_screen_backend_recommendation",
        "kind": "function",
        "role": "cpu_cuda_launch_planning",
        "heads": ("ridge", "pls"),
        "reuse": "source_free_policy",
        "cpu": True,
        "cuda": True,
        "non_catalog_reason": "backend policy helper; not a fit/predict method catalog entry",
        "config_options": _BACKEND_RECOMMENDATION_OPTIONS,
        "notes": "Source-free CPU/CUDA recommendation from shape, head and CUDA availability.",
    },
)


def available_methods() -> list[dict[str, object]]:
    """Return the public moment method inventory as JSON-safe dictionaries."""
    return [dict(item) for item in _METHOD_INVENTORY]


__all__ = [
    "NativeAOMChainRidgePLSRegressor",
    "NativeAOMChainSweepRegressor",
    "NativeAOMFixedCandidateRegressor",
    "NativeAOMMomentPLSScreenRefitRegressor",
    "NativeAOMMomentPLSExactScreenRefitRegressor",
    "NativeAOMMomentRidgeScreenRefitRegressor",
    "NativeAOMMomentScreenRefitRegressor",
    "NativeAOMOperatorPLSStackRegressor",
    "NativeAOMPLSRegressor",
    "NativeAOMPLSSuperblockRegressor",
    "NativeAOMRidgePLSSuperblockRegressor",
    "NativeAOMRidgeActiveSuperblockRegressor",
    "NativeAOMRidgeBlenderRegressor",
    "NativeAOMRidgeGlobalRegressor",
    "NativeAOMRidgeMKLSuperblockRegressor",
    "NativeAOMRidgeSuperblockRegressor",
    "NativeAOMRobustHPORegressor",
    "NativeAOMSavgolFocusRegressor",
    "NativeAOMScreenRefitRegressor",
    "NativeAOMStrictFamilyLiteRegressor",
    "NativeAOMStagedChainCampaignRegressor",
    "NativeAOMSweepRegressor",
    "NativeContinuumRegressionRegressor",
    "NativeCPPLSRegressor",
    "NativeECRRegressor",
    "NativeMomentStackRegressor",
    "NativeMomentSweepRegressor",
    "NativePLSRegressor",
    "NativeRidgeRegressor",
    "NativeRidgePLSRegressor",
    "NativeRobustPLSRegressor",
    "NativeWeightedPLSRegressor",
    "NativePOPPLSRegressor",
    "aom_chain_sweep_run",
    "aom_chain_screen_refit_campaign",
    "aom_chain_fixed_fit_run",
    "aom_chain_ridge_pls",
    "aom_candidate_operator_summary",
    "aom_candidate_preprocessing_impact",
    "aom_candidate_route_summary",
    "aom_candidate_rank_diagnostics",
    "aom_candidate_report_records",
    "aom_candidate_table",
    "aom_evaluate_candidates",
    "aom_global_select",
    "aom_load_candidate_report",
    "aom_moment_screen_refit_campaign",
    "aom_operator_pls_stack",
    "aom_per_component_select",
    "aom_pls_superblock",
    "aom_preprocess",
    "aom_refit_candidates",
    "aom_refit_execution_plan",
    "aom_ridge_active_superblock",
    "aom_ridge_blender",
    "aom_ridge_global",
    "aom_ridge_mkl_superblock",
    "aom_ridge_pls_superblock",
    "aom_ridge_superblock",
    "aom_robust_hpo",
    "aom_save_candidate_report",
    "aom_screen_refit_candidate_pool",
    "aom_staged_chain_campaign",
    "aom_sweep_run",
    "available_methods",
    "build_aom_strict_chain_grid",
    "continuum_regression",
    "cppls",
    "decode_aom_chains",
    "ecr",
    "iter_aom_strict_chain_grid",
    "moment_screen_backend_recommendation",
    "moments",
    "moments_train_from_heldout",
    "moment_stack",
    "NativePCRRegressor",
    "pcr",
    "pls_cross_validate",
    "pls",
    "ridge",
    "ridge_pls",
    "robust_pls",
    "sweep_run",
    "weighted_pls",
]
