#!/usr/bin/env python3
"""Deterministically render global bibliography Markdown, BibTeX, CFF and link report."""

from __future__ import annotations

import argparse
import re
from pathlib import Path
from urllib.parse import urlparse

from bibliography_catalog import CATALOG_PATH, REPO, canonical_json, load_catalog

DOC_PAGE = REPO / "docs" / "bibliography.md"
BIB_FILE = REPO / "docs" / "_static" / "bibliography.bib"
CFF_FILE = REPO / "docs" / "_static" / "nirs4all-methods.cff"
LINK_REPORT = REPO / "docs" / "_static" / "bibliography-links.json"
SOURCE_REPOSITORY_URL = "https://github.com/GBeurier/nirs4all-methods/blob"
DOI_RE = re.compile(r"^10\.\d{4,9}/\S+$", re.IGNORECASE)
DOI_TEXT_RE = re.compile(r"(?i)\bdoi:\s*(10\.\d{4,9}/\S+)")
DOI_URL_RE = re.compile(r"(?i)https?://(?:dx\.)?doi\.org/(10\.\d{4,9}/\S+)")
# ``*`` deliberately captures a bare ``https://`` too: it is invalid, but an
# offline gate must report malformed link text rather than silently ignoring it.
HTTP_URL_RE = re.compile(r"(?i)https?://\S*")
CFF_URL_RE = re.compile(
    r'^(?:repository-code|url):\s*["\']([^"\']+)["\']\s*$', re.MULTILINE
)


def escape_markdown(value: str) -> str:
    return value.replace("\n", " ").strip()


def bibtex_escape(value: str) -> str:
    """Escape a literal into a braced BibTeX field without inventing metadata."""
    replacements = {
        "\\": r"\textbackslash{}",
        "{": r"\{",
        "}": r"\}",
        "%": r"\%",
        "&": r"\&",
        "_": r"\_",
        "#": r"\#",
        "$": r"\$",
        "^": r"\^{}",
        "~": r"\~{}",
    }
    return "".join(replacements.get(char, char) for char in value)


def _source_link(path: str, revision: str) -> str:
    """Link provenance to the exact repository blob named by its digest record."""
    return f"[{path}]({SOURCE_REPOSITORY_URL}/{revision}/{path})"


def _structured_links(entry: dict) -> str:
    """Render reviewed DOI/URL fields as explicit, clickable Markdown links."""
    links: list[str] = []
    if entry.get("doi"):
        doi = entry["doi"]
        links.append(f"[DOI: {escape_markdown(doi)}](https://doi.org/{doi})")
    if entry.get("url"):
        url = entry["url"]
        links.append(f"[URL]({entry['url']})")
    return " · ".join(links)


def render_page(data: dict) -> str:
    lines = [
        "# Global bibliography",
        "",
        "This page is generated by `catalog/scripts/generate_bibliography.py`. "
        "The historical method citations are lossless unstructured imports; the "
        "separate finetuning records are structured only because their tracked "
        "BibTeX source and per-entry digests are reviewed by the scientific gate.",
        "",
        "Download [BibTeX](_static/bibliography.bib) or the preserved "
        "[software CFF](_static/nirs4all-methods.cff).",
        "",
        "## Software citation",
        "",
        "The CFF artifact is copied verbatim from the repository's `CITATION.cff`; "
        "it is not reconstructed from inferred fields.",
        "",
        "## Source provenance",
        "",
        "Baseline and donor material is pinned by content digest:",
        "",
        f"- {_source_link(data['baseline']['legacy_python'], data['baseline']['source_revision'])} — `{data['baseline']['legacy_python_sha256']}`",
    ]
    for source in data["parity_provenance"]:
        lines.append(f"- {_source_link(source['path'], data['baseline']['source_revision'])} — `{source['sha256']}`")
    for source in data["reviewed_sources"]:
        lines.append(f"- {_source_link(source['path'], data['baseline']['source_revision'])} — `{source['sha256']}` (reviewed structured source)")
    lines.extend(
        [
            "",
        "## Method-linked historical citations",
        "",
        ]
    )
    for entry in data["publications"]:
        if entry["provenance"]["fields_status"] != "unstructured_legacy":
            continue
        missing = ", ".join(entry["provenance"]["missing_fields"])
        lines.extend(
            [
                f"### `{entry['method_key']}` — {escape_markdown(entry['method_title'])}",
                "",
                "Historical citation (verbatim; links and DOI text remain literal here "
                "to avoid MyST auto-linkification):",
                "",
                "````text",
                entry["legacy_citation"],
                "````",
                "",
                f"_Structured fields unavailable in the historical source: {missing}._",
                "",
            ]
        )
    lines.extend(["## Reviewed finetuning references", ""])
    for entry in data["publications"]:
        if entry["provenance"]["fields_status"] != "reviewed_structured":
            continue
        venue = entry["journal"]
        citation_parts = [", ".join(entry["authors"]), entry["title"], str(entry["year"])]
        if venue:
            citation_parts.append(venue)
        links = _structured_links(entry)
        lines.extend(
            [
                f"### `{entry['provenance']['entry_key']}`",
                "",
                ". ".join(escape_markdown(part) for part in citation_parts) + ".",
                "",
                *( [links, ""] if links else [] ),
                "Reviewed structured provenance: "
                f"{_source_link(entry['provenance']['source'], data['baseline']['source_revision'])} entry "
                f"`{entry['provenance']['entry_key']}` — source digest "
                f"`{entry['provenance']['source_sha256']}`, entry digest "
                f"`{entry['provenance']['entry_sha256']}`.",
                "",
            ]
        )
    return "\n".join(lines)


def render_bibtex(data: dict) -> str:
    lines = [
        "% Generated by catalog/scripts/generate_bibliography.py; do not edit.",
        "% Legacy entries are lossless import notes, not reviewed bibliographic",
        "% record. Its title is the legacy method title and its note preserves the",
        "% historical citation string; no authors, venue, year, DOI, or URL is inferred.",
        "",
    ]
    for entry in data["publications"]:
        if entry["provenance"]["fields_status"] == "reviewed_structured":
            lines.extend([entry["bibtex"], ""])
            continue
        lines.extend(
            [
                f"@misc{{{entry['id']},",
                f"  title = {{{bibtex_escape(entry['method_title'])}}},",
                "  howpublished = {Historical method bibliography catalog},",
                f"  note = {{{bibtex_escape(entry['legacy_citation'])}}}",
                "}",
                "",
            ]
        )
    lines.append("% Software citation is preserved verbatim in nirs4all-methods.cff.")
    return "\n".join(lines) + "\n"


def _trim_terminal_punctuation(value: str) -> str:
    """Remove prose punctuation that cannot belong to the terminal URL/DOI token."""
    return value.rstrip(".,;:!?")


def _legacy_links(entry: dict) -> list[dict[str, str]]:
    """Find every HTTP(S) URL and explicit DOI token in an opaque legacy string."""
    citation = entry["legacy_citation"]
    links: list[dict[str, str]] = []
    for match in DOI_TEXT_RE.finditer(citation):
        links.append(
            {
                "id": entry["id"],
                "field": "legacy_doi",
                "value": _trim_terminal_punctuation(match.group(1)),
            }
        )
    for match in DOI_URL_RE.finditer(citation):
        links.append(
            {
                "id": entry["id"],
                "field": "legacy_doi",
                "value": _trim_terminal_punctuation(match.group(1)),
            }
        )
    for match in HTTP_URL_RE.finditer(citation):
        value = _trim_terminal_punctuation(match.group(0))
        parsed = urlparse(value)
        if parsed.hostname and parsed.hostname.lower() in {"doi.org", "dx.doi.org"}:
            continue
        links.append({"id": entry["id"], "field": "legacy_url", "value": value})
    return links


def link_report(data: dict) -> dict:
    links: list[dict[str, str]] = []
    for entry in data["publications"]:
        if entry["provenance"]["fields_status"] == "unstructured_legacy":
            links.extend(_legacy_links(entry))
        for field in ("doi", "url"):
            value = entry[field]
            if value:
                links.append({"id": entry["id"], "field": field, "value": value})
    for software in data["software_citations"]:
        for value in CFF_URL_RE.findall(software["cff"]):
            links.append({"id": software["id"], "field": "cff_url", "value": value})
    checked = []
    seen: set[tuple[str, str, str]] = set()
    for link in sorted(
        links, key=lambda item: (item["id"], item["field"], item["value"])
    ):
        identity = (link["id"], link["field"], link["value"])
        if identity in seen:
            continue
        seen.add(identity)
        value = link["value"]
        if link["field"] in {"doi", "legacy_doi"}:
            valid = bool(
                DOI_RE.fullmatch(
                    value.removeprefix("https://doi.org/").removeprefix(
                        "http://doi.org/"
                    )
                )
            )
        else:
            parsed = urlparse(value)
            valid = (
                parsed.scheme == "https"
                and bool(parsed.netloc)
                and not parsed.username
                and not parsed.password
            )
        checked.append({**link, "offline_syntax_valid": valid})
    return {
        "network_access": "not_attempted",
        "checked_links": checked,
        "missing_structured_links": sum(
            1
            for entry in data["publications"]
            for field in ("doi", "url")
            if entry[field] is None
        ),
        "legacy_citations_scanned": len(data["publications"]),
    }


def outputs(data: dict) -> dict[Path, str]:
    software = data["software_citations"]
    if len(software) != 1 or software[0]["id"] != "nirs4all-methods":
        raise ValueError(
            "bibliography v1 requires exactly the nirs4all-methods CFF citation"
        )
    return {
        DOC_PAGE: render_page(data),
        BIB_FILE: render_bibtex(data),
        CFF_FILE: software[0]["cff"],
        LINK_REPORT: canonical_json(link_report(data)),
    }


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--catalog", type=Path, default=CATALOG_PATH)
    parser.add_argument(
        "--check", action="store_true", help="fail if generated artifacts are stale"
    )
    args = parser.parse_args(argv)
    rendered = outputs(load_catalog(args.catalog))
    stale = [
        path
        for path, text in rendered.items()
        if not path.exists() or path.read_text(encoding="utf-8") != text
    ]
    if args.check:
        if stale:
            print("FAIL: stale bibliography artifacts: " + ", ".join(map(str, stale)))
            return 1
        print("PASS: bibliography artifacts are reproducible")
        return 0
    for path, text in rendered.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text, encoding="utf-8")
    print("WROTE: " + ", ".join(map(str, rendered)))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
