#!/usr/bin/env python3
"""Generate the R constructors of the generic estimator roles from the native manifest.

Writes, from ``n4m_cli --manifest-json``:
  - bindings/r/n4m/R/estimator_roles_generated.R (one constructor per estimator
    plus the method -> roles table used by n4m_estimator_import());
  - bindings/r/n4m/man/n4m_estimator_role_constructors.Rd;
  - the marked role block of bindings/r/n4m/NAMESPACE.

    python scripts/generate_r_roles.py --cli build/dev-release/cpp/cli/n4m_cli [--check]
"""

from __future__ import annotations

import argparse
import json
import subprocess
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
PKG = REPO / "bindings" / "r" / "n4m"
R_OUT = PKG / "R" / "estimator_roles_generated.R"
RD_OUT = PKG / "man" / "n4m_estimator_role_constructors.Rd"
NAMESPACE = PKG / "NAMESPACE"
BEGIN = "# BEGIN generated estimator roles (scripts/generate_r_roles.py)"
END = "# END generated estimator roles"

# Role interface -> R S3 class with its methods (docs/abi/estimator_roles_design.md, D0b).
ROLE_METHODS = {
    "regressor": ["S3method(predict, n4m_regressor)"],
    "transformer": ["S3method(n4m_estimator_transform, n4m_transformer)"],
    "selector": [
        "S3method(n4m_estimator_transform, n4m_selector)",
        "S3method(n4m_selected_indices, n4m_selector)",
        "export(n4m_selected_indices)",
    ],
}
COMMON_EXPORTS = [
    "export(n4m_estimator_export)",
    "export(n4m_estimator_fit)",
    "export(n4m_estimator_import)",
    "export(n4m_estimator_transform)",
    "S3method(n4m_estimator_fit, n4m_estimator)",
    "S3method(print, n4m_estimator)",
]


def constructor_name(method: dict) -> str:
    return "n4m_" + method["method_id"].rsplit(".", 1)[-1]


def r_literal(param: dict) -> str:
    value = param["default"]
    if value is None:
        return "NULL"
    if param["type"] == "bool":
        return "TRUE" if value else "FALSE"
    if param["type"] == "enum":
        return json.dumps(value)
    if param["type"] == "int":
        return f"{value}L"
    if param["type"] == "int_array":
        return "c(" + ", ".join(f"{v}L" for v in value) + ")"
    if param["type"] == "double_array":
        return "c(" + ", ".join(repr(float(v)) for v in value) + ")"
    return repr(float(value))


def estimators(manifest: dict) -> list[dict]:
    return sorted(
        (m for m in manifest["methods"] if m["kind"] == "estimator"),
        key=lambda m: m["method_id"],
    )


def render_r(manifest: dict) -> str:
    out = [
        "# SPDX-License-Identifier: CECILL-2.1",
        "# Generated by scripts/generate_r_roles.py from `n4m_cli --manifest-json`. Do not edit.",
        f"# Native ABI {manifest['abi']}.",
        "",
        ".n4m_method_roles <- list(",
    ]
    methods = estimators(manifest)
    rows = [
        f'  "{m["method_id"]}" = c({", ".join(json.dumps(r) for r in m["roles"])})'
        for m in methods
    ]
    out += [",\n".join(rows), ")", "", ".n4m_method_constructors <- c("]
    out.append(
        ",\n".join(f'  "{m["method_id"]}" = "{constructor_name(m)}"' for m in methods)
    )
    out.append(")")
    for m in methods:
        for role in m["roles"]:
            if role not in ROLE_METHODS:
                raise SystemExit(f"{m['method_id']}: no R role class for {role}")
        params = m["params"]
        args = ", ".join(f"{p['name']} = {r_literal(p)}" for p in params)
        values = ", ".join(f"{p['name']} = {p['name']}" for p in params)
        roles = ", ".join(json.dumps(r) for r in m["roles"])
        out += [
            "",
            "#' @rdname n4m_estimator_role_constructors",
            "#' @export",
            f"{constructor_name(m)} <- function({args}) {{",
            f'  .n4m_estimator("{m["method_id"]}", c({roles}), list({values}))',
            "}",
        ]
    out.append("")
    return "\n".join(out)


def render_rd(manifest: dict) -> str:
    methods = estimators(manifest)
    lines = [
        "% Generated by scripts/generate_r_roles.py. Do not edit.",
        "\\name{n4m_estimator_role_constructors}",
        "\\alias{n4m_estimator_role_constructors}",
    ]
    lines += [f"\\alias{{{constructor_name(m)}}}" for m in methods]
    lines += [
        "\\title{Constructors of the generic native estimator roles}",
        "\\usage{",
    ]
    for m in methods:
        args = ", ".join(f"{p['name']} = {r_literal(p)}" for p in m["params"])
        lines.append(f"{constructor_name(m)}({args})")
    lines += [
        "}",
        "\\arguments{",
    ]
    seen: dict[str, str] = {}
    for m in methods:
        for p in m["params"]:
            seen.setdefault(p["name"], p["type"])
    for name, ptype in sorted(seen.items()):
        lines.append(
            f"\\item{{{name}}}{{Native parameter ({ptype}); defaults come from the n4m manifest.}}"
        )
    lines += [
        "}",
        "\\value{An unfitted estimator whose classes are its role interfaces;",
        "fit it with \\code{\\link{n4m_estimator_fit}}.}",
        "\\description{",
        "One constructor per native method of the n4m manifest:",
        "\\itemize{",
    ]
    for m in methods:
        lines.append(
            f"\\item \\code{{{constructor_name(m)}}}: \\code{{{m['method_id']}}} ({', '.join(m['roles'])})"
        )
    lines += ["}", "}", ""]
    return "\n".join(lines)


def render_namespace(manifest: dict, current: str) -> str:
    entries = list(COMMON_EXPORTS)
    entries += [f"export({constructor_name(m)})" for m in estimators(manifest)]
    entries += [line for methods in ROLE_METHODS.values() for line in methods]
    block = "\n".join([BEGIN, *sorted(set(entries)), END])
    if BEGIN in current:
        head, rest = current.split(BEGIN, 1)
        tail = rest.split(END, 1)[1]
        return head + block + tail
    return current.rstrip("\n") + "\n\n" + block + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--cli", required=True, type=Path, help="path to the built n4m_cli"
    )
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    manifest = json.loads(
        subprocess.run(
            [str(args.cli), "--manifest-json"],
            check=True,
            capture_output=True,
            text=True,
        ).stdout
    )
    outputs = {
        R_OUT: render_r(manifest),
        RD_OUT: render_rd(manifest),
        NAMESPACE: render_namespace(manifest, NAMESPACE.read_text(encoding="utf-8")),
    }
    stale = False
    for path, text in outputs.items():
        if not args.check:
            path.write_text(text, encoding="utf-8")
            print(f"wrote {path.relative_to(REPO)}")
        elif not path.exists() or path.read_text(encoding="utf-8") != text:
            print(
                f"error: {path.relative_to(REPO)} is stale; rerun without --check",
                file=sys.stderr,
            )
            stale = True
    if args.check and not stale:
        print("R roles up to date")
    return 1 if stale else 0


if __name__ == "__main__":
    raise SystemExit(main())
