#!/usr/bin/env python3
"""Generate ``bindings/js/src/estimatorRolesGenerated.ts`` from the native manifest.

Class names match the Python ``n4m.roles`` classes; each class implements the
TypeScript role interfaces of its native method.

    python scripts/generate_js_roles.py --cli build/dev-release/cpp/cli/n4m_cli [--check]
"""

from __future__ import annotations

import argparse
import json
import subprocess
import sys
from pathlib import Path

from generate_python_roles import class_name, role_methods

REPO = Path(__file__).resolve().parents[1]
OUTPUT = REPO / "bindings" / "js" / "src" / "estimatorRolesGenerated.ts"

# Role interface -> (TypeScript interface, method name, protected helper).
ROLE_METHODS = {
    "regressor": ("Regressor", "predict", "predictMatrix"),
    "classifier": ("Classifier", "decisionFunction", "decisionMatrix"),
    "transformer": ("Transformer", "transform", "transformMatrix"),
    "selector": ("Selector", "transform", "transformMatrix"),
    "sample_filter": ("SampleFilter", "getMask", "maskArray"),
}
# Procedure role -> (TypeScript interface, method signature, body).
PROCEDURE_METHODS = {
    "splitter": (
        "Splitter",
        "split(X: Matrix, y?: Float64Array | ArrayLike<number>, groups?: number[]): Fold[]",
        "return this.splitFolds(X, y, groups);",
    ),
    "augmenter": (
        "Augmenter",
        "augment(X: Matrix, axis?: Float64Array | number[]): Matrix",
        "return this.augmentMatrix(X, axis);",
    ),
    "generic": (
        "Procedure",
        (
            "run(X: Matrix, y?: Matrix | Float64Array | ArrayLike<number>, inputs: FitInputs = {}):"
            " Record<string, ProcedureOutput>"
        ),
        "return this.runOutputs(X, y, inputs);",
    ),
}
TS_TYPES = {
    "int": "number",
    "double": "number",
    "bool": "boolean",
    "int_array": "number[]",
    "double_array": "number[]",
}


def ts_type(param: dict) -> str:
    if param["type"] == "enum":
        return " | ".join(json.dumps(c) for c in param["choices"])
    return TS_TYPES[param["type"]]


def render(manifest: dict) -> str:
    out = [
        "// SPDX-License-Identifier: CECILL-2.1",
        "// Generated by scripts/generate_js_roles.py from `n4m_cli --manifest-json`. Do not edit.",
        f"// Native ABI {manifest['abi']}.",
        "",
        "import {",
        "    type Augmenter,",
        "    type Classifier,",
        "    type FitInputs,",
        "    type Fold,",
        "    NativeEstimator,",
        "    NativeMethod,",
        "    NativeProcedure,",
        "    type ProbabilisticClassifier,",
        "    type Procedure,",
        "    type ProcedureOutput,",
        "    type Regressor,",
        "    type SampleFilter,",
        "    type Selector,",
        "    type Splitter,",
        "    type Transformer,",
        '} from "./estimatorRoles.js";',
        'import type { Matrix } from "./types.js";',
    ]
    for m in role_methods(manifest):
        name = class_name(m)
        if m["kind"] == "procedure":
            out += render_procedure(m, name)
            continue
        roles = [
            ROLE_METHODS[r]
            for r in (
                "regressor",
                "classifier",
                "transformer",
                "selector",
                "sample_filter",
            )
            if r in m["roles"]
        ]
        missing = set(m["roles"]) - set(ROLE_METHODS)
        if missing:
            raise SystemExit(
                f"{m['method_id']}: no TypeScript role interface for {sorted(missing)}"
            )
        proba = "predict_proba" in m["capabilities"]
        implements = ", ".join(
            "ProbabilisticClassifier" if r[0] == "Classifier" and proba else r[0]
            for r in roles
        )
        out += params_interface(m, name)
        needed = [k for k, v in m["inputs"].items() if v == "required" and k != "y"]
        doc = f"Native `{m['method_id']}` ({', '.join(m['roles'])})."
        if needed:
            doc += f" Required fit inputs: {', '.join(needed)}."
        out += [
            "",
            f"/** {doc} */",
            f"export class {name} extends NativeEstimator implements {implements} {{",
            f"    readonly methodId = {json.dumps(m['method_id'])};",
            "    readonly paramTypes = {",
        ]
        out += [f"        {p['name']}: {json.dumps(p['type'])}," for p in m["params"]]
        out += ["    } as const;"]
        if m["inputs"]["labels"] == "required":
            out.append("    protected readonly labelTarget = true;")
        out += [
            "",
            f"    constructor(params: {name}Params = {{}}) {{",
            "        super();",
            "        this.params = { ...params };",
            "    }",
        ]
        for iface, method, helper in roles:
            if iface == "SampleFilter":
                out += [
                    "",
                    f"    {method}(X: Matrix, y?: Float64Array | ArrayLike<number>): boolean[] {{",
                    f"        return this.{helper}(X, y);",
                    "    }",
                ]
                continue
            out += [
                "",
                f"    {method}(X: Matrix): Matrix {{",
                f"        return this.{helper}(X);",
                "    }",
            ]
        if "classifier" in m["roles"]:
            out += [
                "",
                "    predictLabels(X: Matrix): number[] {",
                "        return this.labelArray(X);",
                "    }",
                "",
                "    classes(): number[] {",
                "        return this.classArray();",
                "    }",
            ]
            if proba:
                out += [
                    "",
                    "    predictProba(X: Matrix): Matrix {",
                    "        return this.probaMatrix(X);",
                    "    }",
                ]
        if "selector" in m["roles"]:
            out += [
                "",
                "    selectedIndices(): number[] {",
                "        return this.selectedIndexArray();",
                "    }",
            ]
        out += ["}", f"NativeMethod.register({json.dumps(m['method_id'])}, {name});"]
    out.append("")
    return "\n".join(out)


def params_interface(m: dict, name: str) -> list[str]:
    out = ["", f"/** Parameters of {name}; unset values take the native defaults. */"]
    out.append(f"export interface {name}Params {{")
    for p in m["params"]:
        default = (
            "" if p["default"] is None else f" Default {json.dumps(p['default'])}."
        )
        required = " Required." if p["required"] else ""
        out.append(f"    /**{required}{default} */")
        out.append(f"    {p['name']}?: {ts_type(p)};")
    out.append("}")
    return out


def render_procedure(m: dict, name: str) -> list[str]:
    (role,) = m["roles"]
    iface, signature, body = PROCEDURE_METHODS[role]
    needed = [k for k, v in m["inputs"].items() if v == "required"]
    doc = f"Native `{m['method_id']}` ({role})."
    if needed:
        doc += f" Required inputs: {', '.join(needed)}."
    out = params_interface(m, name)
    out += [
        "",
        f"/** {doc} */",
        f"export class {name} extends NativeProcedure implements {iface} {{",
        f"    readonly methodId = {json.dumps(m['method_id'])};",
        "    readonly paramTypes = {",
        *[f"        {p['name']}: {json.dumps(p['type'])}," for p in m["params"]],
        "    } as const;",
        "",
        f"    constructor(params: {name}Params = {{}}) {{",
        "        super();",
        "        this.params = { ...params };",
        "    }",
        "",
        f"    {signature} {{",
        f"        {body}",
        "    }",
        "}",
        f"NativeMethod.register({json.dumps(m['method_id'])}, {name});",
    ]
    return out


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--cli", required=True, type=Path, help="path to the built n4m_cli"
    )
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    manifest = json.loads(
        subprocess.run(
            [str(args.cli), "--manifest-json"],
            check=True,
            capture_output=True,
            text=True,
        ).stdout
    )
    text = render(manifest)
    if args.check:
        if not OUTPUT.exists() or OUTPUT.read_text(encoding="utf-8") != text:
            print(
                f"error: {OUTPUT.relative_to(REPO)} is stale; rerun without --check",
                file=sys.stderr,
            )
            return 1
        print("JS roles up to date")
        return 0
    OUTPUT.write_text(text, encoding="utf-8")
    print(f"wrote {OUTPUT.relative_to(REPO)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
