#!/usr/bin/env python3
"""Write docs/parity/estimator_roles_coverage.md: one row per catalog entry.

For every catalog method it reports whether the generic role surface covers
it (kind and roles from the native manifest), and whether the shared N4ME
fixture validates it in Python, R and JS/WASM. This page is the only basis for
coverage claims.

    python scripts/generate_role_coverage.py --cli build/dev-release/cpp/cli/n4m_cli [--check]
"""

from __future__ import annotations

import argparse
import json
import subprocess
import sys
from collections import Counter
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO / "catalog" / "scripts"))
from catalog_loader import METHODS_DIR, load_yaml_file  # noqa: E402

OUTPUT = REPO / "docs" / "parity" / "estimator_roles_coverage.md"
FIXTURE = REPO / "parity" / "fixtures" / "estimator_roles_n4me.json"


def render(manifest: dict) -> str:
    by_id = {m["method_id"]: m for m in manifest["methods"]}
    fixture = {
        c["method_id"] for c in json.loads(FIXTURE.read_text(encoding="utf-8"))["cases"]
    }
    rows = []
    per_category: Counter[tuple[str, bool]] = Counter()
    for path in sorted(METHODS_DIR.glob("*.yaml")):
        doc = load_yaml_file(path)
        method_id = doc["method_id"]
        m = by_id.get(method_id)
        covered = m is not None
        per_category[(doc["category"], covered)] += 1
        if covered:
            roles = ", ".join(m["roles"]) or "-"
            validated = (
                "Python, R, JS/WASM" if method_id in fixture else "manifest only"
            )
            rows.append(f"| `{method_id}` | {m['kind']} | {roles} | {validated} |")
        else:
            rows.append(f"| `{method_id}` | not yet | - | - |")
    categories = sorted({c for c, _ in per_category})
    total = sum(per_category.values())
    covered_total = sum(n for (_, cov), n in per_category.items() if cov)
    out = [
        "# Generic role coverage",
        "",
        "Generated by `scripts/generate_role_coverage.py` from the native manifest",
        f"(ABI {manifest['abi']}) and `parity/fixtures/estimator_roles_n4me.json`. Do not edit.",
        "",
        "A method is covered when it is reachable through the generic role surface",
        "(`n4m_estimator_*` or a procedure call) with parameters from the manifest.",
        "*Python, R, JS/WASM* means the shared fixture replays its N4ME state in all",
        "three bindings and each binding's own fit reproduces the Python fit.",
        "",
        f"**{covered_total} of {total} catalog entries covered.**",
        "",
        "| Category | Covered | Total |",
        "|---|---:|---:|",
    ]
    for c in categories:
        cov = per_category[(c, True)]
        out.append(f"| {c} | {cov} | {cov + per_category[(c, False)]} |")
    out += [
        "",
        "| Method | Kind | Roles | Validated in |",
        "|---|---|---|---|",
        *rows,
        "",
    ]
    return "\n".join(out)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--cli", required=True, type=Path, help="path to the built n4m_cli"
    )
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    manifest = json.loads(
        subprocess.run(
            [str(args.cli), "--manifest-json"],
            check=True,
            capture_output=True,
            text=True,
        ).stdout
    )
    text = render(manifest)
    if args.check:
        if not OUTPUT.exists() or OUTPUT.read_text(encoding="utf-8") != text:
            print(
                f"error: {OUTPUT.relative_to(REPO)} is stale; rerun without --check",
                file=sys.stderr,
            )
            return 1
        print("role coverage up to date")
        return 0
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(text, encoding="utf-8")
    print(f"wrote {OUTPUT.relative_to(REPO)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
