#!/usr/bin/env python3
"""Generate ``bindings/python/src/n4m/roles/_generated.py`` from the native manifest.

The manifest is the JSON printed by the built library's CLI
(``n4m_cli --manifest-json``), so the Python classes always mirror the
compiled table: parameters, defaults and roles are never written by hand.

    python scripts/generate_python_roles.py --cli build/dev-release/cpp/cli/n4m_cli
    python scripts/generate_python_roles.py --cli ... --check
"""

from __future__ import annotations

import argparse
import json
import subprocess
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
ROLES = REPO / "bindings" / "python" / "src" / "n4m" / "roles"
OUTPUT = ROLES / "_generated.py"
INIT = ROLES / "__init__.py"

ACRONYMS = {
    "pls",
    "pcr",
    "cppls",
    "mb",
    "mir",
    "ecr",
    "di",
    "simpls",
    "o2pls",
    "spa",
    "vip",
    "uve",
    "cars",
    "scars",
    "ga",
    "pso",
    "vissa",
    "bve",
    "rep",
    "ipw",
    "st",
    "t2",
    "wvc",
    "emcuve",
    "iriv",
    "irf",
}
CLASS_NAMES = {
    "models.specialized.tensor_pls": "NPLS",
    "models.pls.pls_fit_simple": "SimplePLS",
    "selection.bipls": "BiPLS",
    "selection.sipls": "SiPLS",
    "preprocessing.baselines.airpls": "AirPLS",
    "preprocessing.baselines.arpls": "ArPLS",
    "preprocessing.baselines.asls": "AsLS",
    "preprocessing.baselines.beads": "BEADS",
    "preprocessing.baselines.iasls": "IAsLS",
    "preprocessing.baselines.imodpoly": "IModPoly",
    "preprocessing.baselines.modpoly": "ModPoly",
    "preprocessing.baselines.snip": "SNIP",
    "preprocessing.resampling.crop": "CropTransformer",
    "preprocessing.scatter.local_snv": "LSNV",
    "preprocessing.scatter.robust_snv": "RNV",
    "preprocessing.scatter.snv": "SNV",
}
# Role interface -> Python role base class (docs/abi/estimator_roles_design.md, D0b).
ROLE_BASES = {
    "regressor": "NativeRegressor",
    "selector": "NativeSelector",
    "transformer": "NativeTransformer",
}


def class_name(method: dict) -> str:
    if method["method_id"] in CLASS_NAMES:
        return CLASS_NAMES[method["method_id"]]
    leaf = method["method_id"].rsplit(".", 1)[-1]
    return "".join(
        t.upper() if t in ACRONYMS else t.capitalize() for t in leaf.split("_")
    )


def literal(value) -> str:
    """Python literal with double-quoted strings (ruff format style)."""
    if value is None or isinstance(value, bool):
        return repr(value)
    if isinstance(value, str):
        return json.dumps(value)
    if isinstance(value, list):
        return "[" + ", ".join(literal(v) for v in value) + "]"
    if isinstance(value, tuple):
        return (
            "("
            + ", ".join(literal(v) for v in value)
            + ("," if len(value) == 1 else "")
            + ")"
        )
    return repr(value)


def render(manifest: dict) -> str:
    out = [
        "# SPDX-License-Identifier: CECILL-2.1",
        "# Generated by scripts/generate_python_roles.py from `n4m_cli --manifest-json`.",
        "# Do not edit: parameters, defaults and roles come from the native manifest.",
        f"# Native ABI {manifest['abi']}.",
        '"""Generated scikit-learn classes for the n4m generic estimator roles."""',
        "",
        "from __future__ import annotations",
        "",
        "from typing import ClassVar",
        "",
        "from ._base import {bases}",
    ]
    names = []
    used_bases: set[str] = set()
    for m in estimators(manifest):
        name = class_name(m)
        names.append(name)
        role_bases = [ROLE_BASES[r] for r in ROLE_BASES if r in m["roles"]]
        missing = set(m["roles"]) - set(ROLE_BASES)
        if missing:
            raise SystemExit(
                f"{m['method_id']}: no Python role base for {sorted(missing)}"
            )
        used_bases.update(role_bases)
        bases = ", ".join(role_bases)
        params = m["params"]

        needed = [k for k, v in m["inputs"].items() if v == "required" and k != "y"]
        out += ["", "", f"class {name}({bases}):"]
        doc = f'    """Native ``{m["method_id"]}`` ({", ".join(m["roles"])}).'
        if needed:
            doc += f"\n\n    Required fit inputs: {', '.join(needed)}.\n    "
        out.append(doc + '"""')
        out.append("")
        out.append(f"    _method_id = {literal(m['method_id'])}")
        out.append("    _param_types: ClassVar[dict[str, str]] = {")
        out += [f"        {literal(p['name'])}: {literal(p['type'])}," for p in params]
        out.append("    }")
        enums = [
            (p["name"], tuple(p["choices"])) for p in params if p["type"] == "enum"
        ]
        if enums:
            out.append("    _enum_choices: ClassVar[dict[str, tuple[str, ...]]] = {")
            for key, choices in enums:
                out.append(f"        {literal(key)}: (")
                out += [f"            {literal(c)}," for c in choices]
                out.append("        ),")
            out.append("    }")
        out.append("")
        if params:
            out += ["    def __init__(", "        self,", "        *,"]
            out += [f"        {p['name']}={literal(p['default'])}," for p in params]
            out.append("    ) -> None:")
        else:
            out += ["    def __init__(self) -> None:", "        pass"]
        for p in params:
            out.append(f"        self.{p['name']} = {p['name']}")
    out += (
        ["", "", "__all__ = ["]
        + [f"    {literal(n)}," for n in sorted(names, key=isort_key)]
        + ["]", ""]
    )
    return "\n".join(out).replace("{bases}", ", ".join(sorted(used_bases)))


def isort_key(name: str) -> tuple[int, str]:
    """ruff/isort order: CONSTANT_CASE, then CamelCase, then lowercase."""
    return (0 if name.isupper() else 1 if name[0].isupper() else 2, name)


def estimators(manifest: dict) -> list[dict]:
    methods = [m for m in manifest["methods"] if m["kind"] == "estimator"]
    return sorted(methods, key=lambda m: m["method_id"])


def render_init(manifest: dict) -> str:
    names = sorted((class_name(m) for m in estimators(manifest)), key=isort_key)
    out = [
        "# SPDX-License-Identifier: CECILL-2.1",
        "# Generated by scripts/generate_python_roles.py. Do not edit.",
        '"""Generic native estimator roles.',
        "",
        "Each class wraps one catalog method through the shared ``n4m_estimator_*``",
        "life cycle: fit, out-of-sample transform/predict, and a portable fitted state",
        "(:meth:`NativeEstimator.to_n4me` / :meth:`NativeEstimator.from_n4me`) that the",
        "R and JS/WASM bindings read unchanged.",
        '"""',
        "",
        "from ._base import NativeEstimator, NativeRegressor, NativeSelector, NativeTransformer, method_info",
        "from ._generated import (",
        *[f"    {n}," for n in names],
        ")",
        "",
        "__all__ = [",
        *[
            f"    {literal(n)},"
            for n in sorted(
                [
                    *names,
                    "NativeEstimator",
                    "NativeRegressor",
                    "NativeSelector",
                    "NativeTransformer",
                    "method_info",
                ],
                key=isort_key,
            )
        ],
        "]",
        "",
    ]
    return "\n".join(out)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--cli", required=True, type=Path, help="path to the built n4m_cli"
    )
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    manifest = json.loads(
        subprocess.run(
            [str(args.cli), "--manifest-json"],
            check=True,
            capture_output=True,
            text=True,
        ).stdout
    )
    outputs = {OUTPUT: render(manifest), INIT: render_init(manifest)}
    stale = False
    for path, text in outputs.items():
        if not args.check:
            path.write_text(text, encoding="utf-8")
            print(f"wrote {path.relative_to(REPO)}")
        elif not path.exists() or path.read_text(encoding="utf-8") != text:
            print(
                f"error: {path.relative_to(REPO)} is stale; rerun without --check",
                file=sys.stderr,
            )
            stale = True
    if args.check and not stale:
        print("python roles up to date")
    return 1 if stale else 0


if __name__ == "__main__":
    raise SystemExit(main())
