#!/usr/bin/env python3
"""Write the cross-language N4ME fixture of the generic estimator roles.

Every estimator of the native manifest is fitted once on a fixed synthetic
dataset; the fixture stores its N4ME bytes, the held-out rows and the native
outputs. The R and JS/WASM suites import the same bytes and must reproduce the
outputs, which is the Level 2 (trained-state) portability check.

    N4M_LIB_PATH=... PYTHONPATH=bindings/python/src python scripts/generate_estimator_fixtures.py
"""

from __future__ import annotations

import base64
import json
from pathlib import Path

import n4m
import numpy as np
from n4m import roles
from n4m.roles._base import _REGISTRY

REPO = Path(__file__).resolve().parents[1]
OUTPUT = REPO / "parity" / "fixtures" / "estimator_roles_n4me.json"
# Same content as R source, so the R package tests need no JSON dependency.
R_OUTPUT = (
    REPO / "bindings" / "r" / "n4m" / "tests" / "testthat" / "fixture-estimator-roles.R"
)
N_FEATURES = 12


def dataset():
    rng = np.random.default_rng(20260927)
    scores = rng.normal(size=(48, 2)) * np.array([3.0, 2.0])
    loadings = rng.normal(size=(2, N_FEATURES))
    X = scores @ loadings + 0.1 * rng.normal(size=(48, N_FEATURES))
    y = scores[:, 0] - 0.5 * scores[:, 1] + 0.05 * rng.normal(size=48)
    X_target = rng.normal(size=(30, 2)) @ loadings + 0.3
    return X[:36], y[:36], X[36:], X_target


def fit_inputs(cls, X_target):
    return {
        roles.GroupSparsePLS: {"feature_groups": np.arange(N_FEATURES) // 4},
        roles.MBPLS: {"blocks": [4, 4, 4]},
        roles.DIPLS: {"X_target": X_target},
    }.get(cls, {})


def main() -> None:
    X, y, X_test, X_target = dataset()
    cases = []
    for method_id in sorted(_REGISTRY):
        cls = _REGISTRY[method_id]
        est = (cls(mode_j=3, mode_k=4) if cls is roles.NPLS else cls()).fit(
            X, y, **fit_inputs(cls, X_target)
        )
        params = {
            k: v for k, v in est.get_params().items() if cls._param_types[k] != "enum"
        }
        case = {
            "method_id": method_id,
            "fit_inputs": sorted(fit_inputs(cls, X_target)),
            "int_params": {
                k: v for k, v in params.items() if cls._param_types[k] == "int"
            },
            "n4me_base64": base64.b64encode(est.to_n4me()).decode(),
            "predict": est.predict(X_test).tolist(),
        }
        if isinstance(est, roles.NativeTransformer):
            case["transform"] = est.transform(X_test).tolist()
        cases.append(case)
    doc = {
        "abi": ".".join(map(str, n4m.abi_version())),
        "x_train": X.tolist(),
        "y_train": y.tolist(),
        "x_target": X_target.tolist(),
        "feature_groups": (np.arange(N_FEATURES) // 4).tolist(),
        "blocks": [4, 4, 4],
        "x_test": X_test.tolist(),
        "cases": cases,
    }
    OUTPUT.write_text(json.dumps(doc, indent=1) + "\n", encoding="utf-8")
    R_OUTPUT.write_text(render_r(doc), encoding="utf-8")
    print(
        f"wrote {OUTPUT.relative_to(REPO)} and {R_OUTPUT.relative_to(REPO)} ({len(cases)} estimators)"
    )


def r_vector(values) -> str:
    return "c(" + ", ".join(repr(float(v)) for v in values) + ")"


def r_matrix(rows) -> str:
    arr = np.asarray(rows, dtype=float)
    return f"matrix({r_vector(arr.ravel())}, nrow = {arr.shape[0]}, byrow = TRUE)"


def render_r(doc: dict) -> str:
    out = [
        "# Generated by scripts/generate_estimator_fixtures.py from the Python binding. Do not edit.",
        f"# N4ME states written by n4m ABI {doc['abi']}.",
        "estimator_roles_fixture <- list(",
        f"  x_train = {r_matrix(doc['x_train'])},",
        f"  y_train = {r_vector(doc['y_train'])},",
        f"  x_target = {r_matrix(doc['x_target'])},",
        f"  feature_groups = {r_vector(doc['feature_groups'])},",
        f"  blocks = {r_vector(doc['blocks'])},",
        f"  x_test = {r_matrix(doc['x_test'])},",
        "  cases = list(",
    ]
    cases = []
    for case in doc["cases"]:
        hexa = base64.b64decode(case["n4me_base64"]).hex()
        fields = [
            f'    method_id = "{case["method_id"]}"',
            f'    n4me = "{hexa}"',
            "    fit_inputs = c("
            + ", ".join(f'"{n}"' for n in case["fit_inputs"])
            + ")",
            "    int_params = list("
            + ", ".join(f"{k} = {v}L" for k, v in case["int_params"].items())
            + ")",
            f"    predict = {r_vector(case['predict'])}",
        ]
        if "transform" in case:
            fields.append(f"    transform = {r_matrix(case['transform'])}")
        cases.append("   list(\n" + ",\n".join(fields) + ")")
    out += [",\n".join(cases), "  )", ")", ""]
    return "\n".join(out)


if __name__ == "__main__":
    main()
