# SPDX-License-Identifier: CECILL-2.1
"""Auto-generated ctypes argtypes/restype declarations for libn4m.

Do not edit by hand. Regenerate with::

    python scripts/generate_ffi_decls.py
"""

from __future__ import annotations

from ctypes import (
    POINTER,
    c_char_p,
    c_double,
    c_int,
    c_int32,
    c_int64,
    c_size_t,
    c_uint8,
    c_uint32,
    c_uint64,
    c_void_p,
)

from ._types import (
    MatrixView,
    LinearPredictorSpec,
    SerializedModelInfoV1,
    FilterStats,
    OptimizerOptions,
    SplitResult,
    TransferMetrics,
)

# Symbols: tuple of (symbol_name, argtypes_tuple, restype).
# restype = None for void; argtypes = () for parameter-less.
SYMBOLS = (
    ("n4m_array_dtype", (c_void_p, POINTER(c_int32)), c_int),
    ("n4m_array_free", (c_void_p,), None),
    ("n4m_array_shape", (c_void_p, POINTER(c_int64), POINTER(c_int64)), c_int),
    ("n4m_array_view", (c_void_p, POINTER(MatrixView)), c_int),
    ("n4m_augmentation_band_mask_apply", (c_void_p, MatrixView, MatrixView), c_int),
    (
        "n4m_augmentation_band_mask_create",
        (POINTER(c_void_p), c_void_p, c_int32, c_int32, c_int32, c_int32, c_int32),
        c_int,
    ),
    ("n4m_augmentation_band_mask_destroy", (c_void_p,), None),
    ("n4m_augmentation_band_perturb_apply", (c_void_p, MatrixView, MatrixView), c_int),
    (
        "n4m_augmentation_band_perturb_create",
        (
            POINTER(c_void_p),
            c_void_p,
            c_int32,
            c_int32,
            c_int32,
            c_double,
            c_double,
            c_double,
            c_double,
        ),
        c_int,
    ),
    ("n4m_augmentation_band_perturb_destroy", (c_void_p,), None),
    ("n4m_augmentation_batch_effect_apply", (c_void_p, MatrixView, MatrixView), c_int),
    (
        "n4m_augmentation_batch_effect_create",
        (
            POINTER(c_void_p),
            c_void_p,
            c_double,
            c_double,
            c_double,
            c_int32,
            POINTER(c_double),
            c_int64,
        ),
        c_int,
    ),
    ("n4m_augmentation_batch_effect_destroy", (c_void_p,), None),
    (
        "n4m_augmentation_channel_dropout_apply",
        (c_void_p, MatrixView, MatrixView),
        c_int,
    ),
    (
        "n4m_augmentation_channel_dropout_create",
        (POINTER(c_void_p), c_void_p, c_double, c_int32),
        c_int,
    ),
    ("n4m_augmentation_channel_dropout_destroy", (c_void_p,), None),
    ("n4m_augmentation_dead_band_apply", (c_void_p, MatrixView, MatrixView), c_int),
    (
        "n4m_augmentation_dead_band_create",
        (
            POINTER(c_void_p),
            c_void_p,
            c_int32,
            c_int32,
            c_int32,
            c_double,
            c_double,
            c_int32,
        ),
        c_int,
    ),
    ("n4m_augmentation_dead_band_destroy", (c_void_p,), None),
    (
        "n4m_augmentation_detector_rolloff_apply",
        (c_void_p, MatrixView, MatrixView, MatrixView),
        c_int,
    ),
    (
        "n4m_augmentation_detector_rolloff_create",
        (POINTER(c_void_p), c_void_p, c_int32, c_double, c_double, c_int32),
        c_int,
    ),
    ("n4m_augmentation_detector_rolloff_destroy", (c_void_p,), None),
    (
        "n4m_augmentation_edge_artifacts_apply",
        (c_void_p, MatrixView, MatrixView, MatrixView),
        c_int,
    ),
    (
        "n4m_augmentation_edge_artifacts_create",
        (POINTER(c_void_p), c_void_p, c_int32, c_double, c_int32),
        c_int,
    ),
    ("n4m_augmentation_edge_artifacts_destroy", (c_void_p,), None),
    (
        "n4m_augmentation_edge_curvature_apply",
        (c_void_p, MatrixView, MatrixView, MatrixView),
        c_int,
    ),
    (
        "n4m_augmentation_edge_curvature_create",
        (POINTER(c_void_p), c_void_p, c_double, c_int32, c_double, c_double),
        c_int,
    ),
    ("n4m_augmentation_edge_curvature_destroy", (c_void_p,), None),
    ("n4m_augmentation_emsc_distort_apply", (c_void_p, MatrixView, MatrixView), c_int),
    (
        "n4m_augmentation_emsc_distort_create",
        (
            POINTER(c_void_p),
            c_void_p,
            c_double,
            c_double,
            c_double,
            c_double,
            c_int32,
            c_double,
            c_double,
            POINTER(c_double),
            c_int64,
        ),
        c_int,
    ),
    ("n4m_augmentation_emsc_distort_destroy", (c_void_p,), None),
    ("n4m_augmentation_gauss_jitter_apply", (c_void_p, MatrixView, MatrixView), c_int),
    (
        "n4m_augmentation_gauss_jitter_create",
        (POINTER(c_void_p), c_void_p, c_double, c_double, c_int32),
        c_int,
    ),
    ("n4m_augmentation_gauss_jitter_destroy", (c_void_p,), None),
    (
        "n4m_augmentation_gaussian_noise_apply",
        (c_void_p, MatrixView, MatrixView),
        c_int,
    ),
    (
        "n4m_augmentation_gaussian_noise_create",
        (POINTER(c_void_p), c_void_p, c_double),
        c_int,
    ),
    ("n4m_augmentation_gaussian_noise_destroy", (c_void_p,), None),
    ("n4m_augmentation_hetero_noise_apply", (c_void_p, MatrixView, MatrixView), c_int),
    (
        "n4m_augmentation_hetero_noise_create",
        (POINTER(c_void_p), c_void_p, c_double, c_double),
        c_int,
    ),
    ("n4m_augmentation_hetero_noise_destroy", (c_void_p,), None),
    (
        "n4m_augmentation_instrument_broaden_apply",
        (c_void_p, MatrixView, MatrixView),
        c_int,
    ),
    (
        "n4m_augmentation_instrument_broaden_create",
        (
            POINTER(c_void_p),
            c_void_p,
            c_double,
            c_int,
            c_double,
            c_double,
            c_int32,
            POINTER(c_double),
            c_int64,
        ),
        c_int,
    ),
    ("n4m_augmentation_instrument_broaden_destroy", (c_void_p,), None),
    ("n4m_augmentation_linear_drift_apply", (c_void_p, MatrixView, MatrixView), c_int),
    (
        "n4m_augmentation_linear_drift_create",
        (POINTER(c_void_p), c_void_p, c_double, c_double, c_double, c_double),
        c_int,
    ),
    ("n4m_augmentation_linear_drift_destroy", (c_void_p,), None),
    ("n4m_augmentation_local_clip_apply", (c_void_p, MatrixView, MatrixView), c_int),
    (
        "n4m_augmentation_local_clip_create",
        (POINTER(c_void_p), c_void_p, c_int32, c_int32, c_int32),
        c_int,
    ),
    ("n4m_augmentation_local_clip_destroy", (c_void_p,), None),
    ("n4m_augmentation_local_mixup_apply", (c_void_p, MatrixView, MatrixView), c_int),
    (
        "n4m_augmentation_local_mixup_create",
        (POINTER(c_void_p), c_void_p, c_double, c_int32),
        c_int,
    ),
    ("n4m_augmentation_local_mixup_destroy", (c_void_p,), None),
    ("n4m_augmentation_local_warp_apply", (c_void_p, MatrixView, MatrixView), c_int),
    (
        "n4m_augmentation_local_warp_create",
        (POINTER(c_void_p), c_void_p, c_int32, c_double, POINTER(c_double), c_int64),
        c_int,
    ),
    ("n4m_augmentation_local_warp_destroy", (c_void_p,), None),
    (
        "n4m_augmentation_magnitude_warp_apply",
        (c_void_p, MatrixView, MatrixView),
        c_int,
    ),
    (
        "n4m_augmentation_magnitude_warp_create",
        (
            POINTER(c_void_p),
            c_void_p,
            c_int32,
            c_double,
            c_double,
            POINTER(c_double),
            c_int64,
        ),
        c_int,
    ),
    ("n4m_augmentation_magnitude_warp_destroy", (c_void_p,), None),
    ("n4m_augmentation_mixup_apply", (c_void_p, MatrixView, MatrixView), c_int),
    ("n4m_augmentation_mixup_create", (POINTER(c_void_p), c_void_p, c_double), c_int),
    ("n4m_augmentation_mixup_destroy", (c_void_p,), None),
    ("n4m_augmentation_moisture_apply", (c_void_p, MatrixView, MatrixView), c_int),
    (
        "n4m_augmentation_moisture_create",
        (
            POINTER(c_void_p),
            c_void_p,
            c_double,
            c_int,
            c_double,
            c_double,
            c_double,
            c_double,
            c_double,
            c_double,
            c_int,
            c_int,
            POINTER(c_double),
            c_int64,
        ),
        c_int,
    ),
    ("n4m_augmentation_moisture_destroy", (c_void_p,), None),
    (
        "n4m_augmentation_multiplicative_noise_apply",
        (c_void_p, MatrixView, MatrixView),
        c_int,
    ),
    (
        "n4m_augmentation_multiplicative_noise_create",
        (POINTER(c_void_p), c_void_p, c_double),
        c_int,
    ),
    ("n4m_augmentation_multiplicative_noise_destroy", (c_void_p,), None),
    ("n4m_augmentation_particle_size_apply", (c_void_p, MatrixView, MatrixView), c_int),
    (
        "n4m_augmentation_particle_size_create",
        (
            POINTER(c_void_p),
            c_void_p,
            c_double,
            c_double,
            c_int,
            c_double,
            c_double,
            c_double,
            c_double,
            c_double,
            c_int,
            c_double,
            POINTER(c_double),
            c_int64,
        ),
        c_int,
    ),
    ("n4m_augmentation_particle_size_destroy", (c_void_p,), None),
    ("n4m_augmentation_path_length_apply", (c_void_p, MatrixView, MatrixView), c_int),
    (
        "n4m_augmentation_path_length_create",
        (POINTER(c_void_p), c_void_p, c_double, c_double),
        c_int,
    ),
    ("n4m_augmentation_path_length_destroy", (c_void_p,), None),
    ("n4m_augmentation_poly_drift_apply", (c_void_p, MatrixView, MatrixView), c_int),
    (
        "n4m_augmentation_poly_drift_create",
        (POINTER(c_void_p), c_void_p, c_int32, POINTER(c_double), POINTER(c_double)),
        c_int,
    ),
    ("n4m_augmentation_poly_drift_destroy", (c_void_p,), None),
    ("n4m_augmentation_random_x_op_apply", (c_void_p, MatrixView, MatrixView), c_int),
    (
        "n4m_augmentation_random_x_op_create",
        (POINTER(c_void_p), c_void_p, c_int32, c_double, c_double),
        c_int,
    ),
    ("n4m_augmentation_random_x_op_destroy", (c_void_p,), None),
    (
        "n4m_augmentation_rotate_translate_apply",
        (c_void_p, MatrixView, MatrixView),
        c_int,
    ),
    (
        "n4m_augmentation_rotate_translate_create",
        (POINTER(c_void_p), c_void_p, c_double, c_double),
        c_int,
    ),
    ("n4m_augmentation_rotate_translate_destroy", (c_void_p,), None),
    (
        "n4m_augmentation_scatter_sim_msc_apply",
        (c_void_p, MatrixView, MatrixView),
        c_int,
    ),
    (
        "n4m_augmentation_scatter_sim_msc_create",
        (POINTER(c_void_p), c_void_p, c_double, c_double, c_double, c_double),
        c_int,
    ),
    ("n4m_augmentation_scatter_sim_msc_destroy", (c_void_p,), None),
    ("n4m_augmentation_spike_noise_apply", (c_void_p, MatrixView, MatrixView), c_int),
    (
        "n4m_augmentation_spike_noise_create",
        (POINTER(c_void_p), c_void_p, c_int32, c_int32, c_double, c_double),
        c_int,
    ),
    ("n4m_augmentation_spike_noise_destroy", (c_void_p,), None),
    (
        "n4m_augmentation_spline_curve_simplification_apply",
        (c_void_p, MatrixView, MatrixView),
        c_int,
    ),
    (
        "n4m_augmentation_spline_curve_simplification_create",
        (POINTER(c_void_p), c_void_p, c_int32, c_int32),
        c_int,
    ),
    ("n4m_augmentation_spline_curve_simplification_destroy", (c_void_p,), None),
    (
        "n4m_augmentation_spline_smoothing_apply",
        (c_void_p, MatrixView, MatrixView),
        c_int,
    ),
    ("n4m_augmentation_spline_smoothing_create", (POINTER(c_void_p), c_void_p), c_int),
    ("n4m_augmentation_spline_smoothing_destroy", (c_void_p,), None),
    (
        "n4m_augmentation_spline_x_perturbations_apply",
        (c_void_p, MatrixView, MatrixView),
        c_int,
    ),
    (
        "n4m_augmentation_spline_x_perturbations_create",
        (POINTER(c_void_p), c_void_p, c_int32, c_double, c_double, c_double),
        c_int,
    ),
    ("n4m_augmentation_spline_x_perturbations_destroy", (c_void_p,), None),
    (
        "n4m_augmentation_spline_x_simplification_apply",
        (c_void_p, MatrixView, MatrixView),
        c_int,
    ),
    (
        "n4m_augmentation_spline_x_simplification_create",
        (POINTER(c_void_p), c_void_p, c_int32, c_int32),
        c_int,
    ),
    ("n4m_augmentation_spline_x_simplification_destroy", (c_void_p,), None),
    (
        "n4m_augmentation_spline_y_perturbations_apply",
        (c_void_p, MatrixView, MatrixView),
        c_int,
    ),
    (
        "n4m_augmentation_spline_y_perturbations_create",
        (POINTER(c_void_p), c_void_p, c_int32, c_double),
        c_int,
    ),
    ("n4m_augmentation_spline_y_perturbations_destroy", (c_void_p,), None),
    (
        "n4m_augmentation_stray_light_apply",
        (c_void_p, MatrixView, MatrixView, MatrixView),
        c_int,
    ),
    (
        "n4m_augmentation_stray_light_create",
        (POINTER(c_void_p), c_void_p, c_double, c_double, c_double, c_int32),
        c_int,
    ),
    ("n4m_augmentation_stray_light_destroy", (c_void_p,), None),
    ("n4m_augmentation_temperature_apply", (c_void_p, MatrixView, MatrixView), c_int),
    (
        "n4m_augmentation_temperature_create",
        (
            POINTER(c_void_p),
            c_void_p,
            c_double,
            c_int,
            c_double,
            c_double,
            c_int,
            c_int,
            c_int,
            c_int,
            POINTER(c_double),
            c_int64,
        ),
        c_int,
    ),
    ("n4m_augmentation_temperature_destroy", (c_void_p,), None),
    (
        "n4m_augmentation_truncated_peak_apply",
        (c_void_p, MatrixView, MatrixView, MatrixView),
        c_int,
    ),
    (
        "n4m_augmentation_truncated_peak_create",
        (
            POINTER(c_void_p),
            c_void_p,
            c_double,
            c_double,
            c_double,
            c_double,
            c_double,
            c_int32,
            c_int32,
        ),
        c_int,
    ),
    ("n4m_augmentation_truncated_peak_destroy", (c_void_p,), None),
    ("n4m_augmentation_unsharp_mask_apply", (c_void_p, MatrixView, MatrixView), c_int),
    (
        "n4m_augmentation_unsharp_mask_create",
        (POINTER(c_void_p), c_void_p, c_double, c_double, c_double, c_int32),
        c_int,
    ),
    ("n4m_augmentation_unsharp_mask_destroy", (c_void_p,), None),
    (
        "n4m_augmentation_wavelength_shift_apply",
        (c_void_p, MatrixView, MatrixView),
        c_int,
    ),
    (
        "n4m_augmentation_wavelength_shift_create",
        (POINTER(c_void_p), c_void_p, c_double, c_double, POINTER(c_double), c_int64),
        c_int,
    ),
    ("n4m_augmentation_wavelength_shift_destroy", (c_void_p,), None),
    (
        "n4m_augmentation_wavelength_stretch_apply",
        (c_void_p, MatrixView, MatrixView),
        c_int,
    ),
    (
        "n4m_augmentation_wavelength_stretch_create",
        (POINTER(c_void_p), c_void_p, c_double, c_double, POINTER(c_double), c_int64),
        c_int,
    ),
    ("n4m_augmentation_wavelength_stretch_destroy", (c_void_p,), None),
    ("n4m_backend_is_available", (c_int,), c_int),
    ("n4m_backend_to_string", (c_int,), c_void_p),
    ("n4m_check_abi_compatibility", (c_uint32, c_uint32), c_int),
    ("n4m_config_clone", (c_void_p, POINTER(c_void_p)), c_int),
    ("n4m_config_create", (POINTER(c_void_p),), c_int),
    ("n4m_config_destroy", (c_void_p,), None),
    ("n4m_config_get_algorithm", (c_void_p, POINTER(c_int32)), c_int),
    ("n4m_config_get_aom_moment_policy", (c_void_p, POINTER(c_int32)), c_int),
    ("n4m_config_get_aom_pls_score_mode", (c_void_p, POINTER(c_int32)), c_int),
    ("n4m_config_get_aom_score_only", (c_void_p, POINTER(c_int32)), c_int),
    ("n4m_config_get_approximate_press_legacy", (c_void_p, POINTER(c_int32)), c_int),
    ("n4m_config_get_center_x", (c_void_p, POINTER(c_int32)), c_int),
    ("n4m_config_get_center_y", (c_void_p, POINTER(c_int32)), c_int),
    ("n4m_config_get_cuda_pls_many_batched", (c_void_p, POINTER(c_int32)), c_int),
    (
        "n4m_config_get_cuda_pls_min_device_features",
        (c_void_p, POINTER(c_int32)),
        c_int,
    ),
    ("n4m_config_get_cuda_pls_parallel_folds", (c_void_p, POINTER(c_int32)), c_int),
    ("n4m_config_get_deflation", (c_void_p, POINTER(c_int32)), c_int),
    ("n4m_config_get_dtype", (c_void_p, POINTER(c_int32)), c_int),
    ("n4m_config_get_gating_strategy", (c_void_p, POINTER(c_void_p)), c_int),
    ("n4m_config_get_max_iter", (c_void_p, POINTER(c_int32)), c_int),
    ("n4m_config_get_n_components", (c_void_p, POINTER(c_int32)), c_int),
    ("n4m_config_get_operator_bank", (c_void_p, POINTER(c_void_p)), c_int),
    ("n4m_config_get_pipeline", (c_void_p, POINTER(c_void_p)), c_int),
    ("n4m_config_get_rng_kind", (c_void_p, POINTER(c_int32)), c_int),
    ("n4m_config_get_robust_pls_legacy", (c_void_p, POINTER(c_int32)), c_int),
    ("n4m_config_get_scale_x", (c_void_p, POINTER(c_int32)), c_int),
    ("n4m_config_get_scale_y", (c_void_p, POINTER(c_int32)), c_int),
    ("n4m_config_get_solver", (c_void_p, POINTER(c_int32)), c_int),
    ("n4m_config_get_sparse_simpls_legacy", (c_void_p, POINTER(c_int32)), c_int),
    ("n4m_config_get_store_diagnostics", (c_void_p, POINTER(c_int32)), c_int),
    ("n4m_config_get_store_scores", (c_void_p, POINTER(c_int32)), c_int),
    ("n4m_config_get_tol", (c_void_p, POINTER(c_double)), c_int),
    ("n4m_config_set_algorithm", (c_void_p, c_int), c_int),
    ("n4m_config_set_aom_moment_policy", (c_void_p, c_int), c_int),
    ("n4m_config_set_aom_pls_score_mode", (c_void_p, c_int), c_int),
    ("n4m_config_set_aom_score_only", (c_void_p, c_int32), c_int),
    ("n4m_config_set_approximate_press_legacy", (c_void_p, c_int32), c_int),
    ("n4m_config_set_center_x", (c_void_p, c_int32), c_int),
    ("n4m_config_set_center_y", (c_void_p, c_int32), c_int),
    ("n4m_config_set_cuda_pls_many_batched", (c_void_p, c_int32), c_int),
    ("n4m_config_set_cuda_pls_min_device_features", (c_void_p, c_int32), c_int),
    ("n4m_config_set_cuda_pls_parallel_folds", (c_void_p, c_int32), c_int),
    ("n4m_config_set_deflation", (c_void_p, c_int), c_int),
    ("n4m_config_set_dtype", (c_void_p, c_int), c_int),
    ("n4m_config_set_gating_strategy", (c_void_p, c_void_p), c_int),
    ("n4m_config_set_max_iter", (c_void_p, c_int32), c_int),
    ("n4m_config_set_n_components", (c_void_p, c_int32), c_int),
    ("n4m_config_set_operator_bank", (c_void_p, c_void_p), c_int),
    ("n4m_config_set_pipeline", (c_void_p, c_void_p), c_int),
    ("n4m_config_set_rng_kind", (c_void_p, c_int), c_int),
    ("n4m_config_set_robust_pls_legacy", (c_void_p, c_int32), c_int),
    ("n4m_config_set_scale_x", (c_void_p, c_int32), c_int),
    ("n4m_config_set_scale_y", (c_void_p, c_int32), c_int),
    ("n4m_config_set_solver", (c_void_p, c_int), c_int),
    ("n4m_config_set_sparse_simpls_legacy", (c_void_p, c_int32), c_int),
    ("n4m_config_set_store_diagnostics", (c_void_p, c_int32), c_int),
    ("n4m_config_set_store_scores", (c_void_p, c_int32), c_int),
    ("n4m_config_set_tol", (c_void_p, c_double), c_int),
    ("n4m_context_clear_error", (c_void_p,), None),
    ("n4m_context_create", (POINTER(c_void_p),), c_int),
    ("n4m_context_destroy", (c_void_p,), None),
    ("n4m_context_get_backend", (c_void_p, POINTER(c_int32)), c_int),
    ("n4m_context_get_num_threads", (c_void_p, POINTER(c_int32)), c_int),
    ("n4m_context_get_seed", (c_void_p, POINTER(c_uint64)), c_int),
    ("n4m_context_get_user_data", (c_void_p,), c_void_p),
    ("n4m_context_last_error", (c_void_p,), c_void_p),
    ("n4m_context_set_backend", (c_void_p, c_int), c_int),
    ("n4m_context_set_num_threads", (c_void_p, c_int32), c_int),
    ("n4m_context_set_seed", (c_void_p, c_uint64), c_int),
    ("n4m_context_set_user_data", (c_void_p, c_void_p), c_int),
    ("n4m_decomposition_flexible_pca_create", (POINTER(c_void_p), c_double), c_int),
    ("n4m_decomposition_flexible_pca_destroy", (c_void_p,), None),
    ("n4m_decomposition_flexible_pca_fit", (c_void_p, MatrixView), c_int),
    ("n4m_decomposition_flexible_pca_is_fitted", (c_void_p, POINTER(c_int)), c_int),
    ("n4m_decomposition_flexible_pca_output_cols", (c_void_p, POINTER(c_int64)), c_int),
    (
        "n4m_decomposition_flexible_pca_transform",
        (c_void_p, MatrixView, MatrixView),
        c_int,
    ),
    ("n4m_decomposition_flexible_svd_create", (POINTER(c_void_p), c_double), c_int),
    ("n4m_decomposition_flexible_svd_destroy", (c_void_p,), None),
    ("n4m_decomposition_flexible_svd_fit", (c_void_p, MatrixView), c_int),
    ("n4m_decomposition_flexible_svd_is_fitted", (c_void_p, POINTER(c_int)), c_int),
    ("n4m_decomposition_flexible_svd_output_cols", (c_void_p, POINTER(c_int64)), c_int),
    (
        "n4m_decomposition_flexible_svd_transform",
        (c_void_p, MatrixView, MatrixView),
        c_int,
    ),
    (
        "n4m_domain_adaptation_di_pls_fit",
        (
            c_void_p,
            c_void_p,
            POINTER(MatrixView),
            POINTER(MatrixView),
            POINTER(MatrixView),
            c_double,
            POINTER(c_void_p),
        ),
        c_int,
    ),
    (
        "n4m_domain_adaptation_direct_standardization_create",
        (POINTER(c_void_p), c_int, c_double),
        c_int,
    ),
    ("n4m_domain_adaptation_direct_standardization_destroy", (c_void_p,), None),
    (
        "n4m_domain_adaptation_direct_standardization_fit",
        (c_void_p, MatrixView, MatrixView),
        c_int,
    ),
    (
        "n4m_domain_adaptation_direct_standardization_is_fitted",
        (c_void_p, POINTER(c_int)),
        c_int,
    ),
    (
        "n4m_domain_adaptation_direct_standardization_transform",
        (c_void_p, MatrixView, MatrixView),
        c_int,
    ),
    (
        "n4m_domain_adaptation_ds_fit",
        (c_void_p, POINTER(MatrixView), POINTER(MatrixView), POINTER(c_void_p)),
        c_int,
    ),
    ("n4m_domain_adaptation_epo_create", (POINTER(c_void_p), c_int), c_int),
    ("n4m_domain_adaptation_epo_destroy", (c_void_p,), None),
    (
        "n4m_domain_adaptation_epo_fit",
        (c_void_p, MatrixView, POINTER(c_double), c_int64),
        c_int,
    ),
    (
        "n4m_domain_adaptation_epo_inverse_transform",
        (c_void_p, MatrixView, MatrixView),
        c_int,
    ),
    ("n4m_domain_adaptation_epo_is_fitted", (c_void_p, POINTER(c_int)), c_int),
    ("n4m_domain_adaptation_epo_transform", (c_void_p, MatrixView, MatrixView), c_int),
    (
        "n4m_domain_adaptation_epo_transform_with_d",
        (c_void_p, MatrixView, POINTER(c_double), c_int64, MatrixView),
        c_int,
    ),
    (
        "n4m_domain_adaptation_pds_fit",
        (
            c_void_p,
            POINTER(MatrixView),
            POINTER(MatrixView),
            c_int32,
            POINTER(c_void_p),
        ),
        c_int,
    ),
    (
        "n4m_domain_adaptation_piecewise_direct_standardization_create",
        (POINTER(c_void_p), c_int32, c_int, c_double),
        c_int,
    ),
    (
        "n4m_domain_adaptation_piecewise_direct_standardization_destroy",
        (c_void_p,),
        None,
    ),
    (
        "n4m_domain_adaptation_piecewise_direct_standardization_fit",
        (c_void_p, MatrixView, MatrixView),
        c_int,
    ),
    (
        "n4m_domain_adaptation_piecewise_direct_standardization_is_fitted",
        (c_void_p, POINTER(c_int)),
        c_int,
    ),
    (
        "n4m_domain_adaptation_piecewise_direct_standardization_transform",
        (c_void_p, MatrixView, MatrixView),
        c_int,
    ),
    (
        "n4m_domain_adaptation_robust_direct_standardization_create",
        (POINTER(c_void_p), c_int, c_double, c_double, c_int32),
        c_int,
    ),
    ("n4m_domain_adaptation_robust_direct_standardization_destroy", (c_void_p,), None),
    (
        "n4m_domain_adaptation_robust_direct_standardization_fit",
        (c_void_p, MatrixView, MatrixView),
        c_int,
    ),
    (
        "n4m_domain_adaptation_robust_direct_standardization_is_fitted",
        (c_void_p, POINTER(c_int)),
        c_int,
    ),
    (
        "n4m_domain_adaptation_robust_direct_standardization_transform",
        (c_void_p, MatrixView, MatrixView),
        c_int,
    ),
    ("n4m_domain_adaptation_slope_bias_create", (POINTER(c_void_p),), c_int),
    ("n4m_domain_adaptation_slope_bias_destroy", (c_void_p,), None),
    (
        "n4m_domain_adaptation_slope_bias_fit",
        (c_void_p, POINTER(c_double), POINTER(c_double), c_int64),
        c_int,
    ),
    ("n4m_domain_adaptation_slope_bias_is_fitted", (c_void_p, POINTER(c_int)), c_int),
    (
        "n4m_domain_adaptation_slope_bias_transform",
        (c_void_p, POINTER(c_double), c_int64, POINTER(c_double)),
        c_int,
    ),
    (
        "n4m_domain_adaptation_transfer_metrics_compute",
        (MatrixView, MatrixView, c_int32, c_int32, c_uint64, POINTER(TransferMetrics)),
        c_int,
    ),
    ("n4m_dtype_size", (c_int,), c_size_t),
    ("n4m_dtype_to_string", (c_int,), c_void_p),
    (
        "n4m_ensemble_aom_operator_pls_stack_fit",
        (
            c_void_p,
            c_void_p,
            POINTER(MatrixView),
            POINTER(MatrixView),
            c_int32,
            c_int32,
            POINTER(c_int32),
            c_int64,
            POINTER(c_int32),
            c_int64,
            POINTER(c_double),
            c_int64,
            c_double,
            c_double,
            POINTER(c_void_p),
        ),
        c_int,
    ),
    (
        "n4m_ensemble_aom_ridge_blender_fit",
        (
            c_void_p,
            c_void_p,
            POINTER(MatrixView),
            POINTER(MatrixView),
            c_int32,
            c_int32,
            POINTER(c_int32),
            c_int64,
            POINTER(c_double),
            c_int64,
            c_double,
            POINTER(c_void_p),
        ),
        c_int,
    ),
    (
        "n4m_ensemble_bagging_pls_fit",
        (
            c_void_p,
            c_void_p,
            POINTER(MatrixView),
            POINTER(MatrixView),
            c_int32,
            c_uint64,
            POINTER(c_void_p),
        ),
        c_int,
    ),
    (
        "n4m_ensemble_boosting_pls_fit",
        (
            c_void_p,
            c_void_p,
            POINTER(MatrixView),
            POINTER(MatrixView),
            c_int32,
            c_double,
            POINTER(c_void_p),
        ),
        c_int,
    ),
    (
        "n4m_ensemble_random_subspace_pls_fit",
        (
            c_void_p,
            c_void_p,
            POINTER(MatrixView),
            POINTER(MatrixView),
            c_int32,
            c_int32,
            c_uint64,
            POINTER(c_void_p),
        ),
        c_int,
    ),
    (
        "n4m_estimators_continuum_regression_fit",
        (
            c_void_p,
            c_void_p,
            POINTER(MatrixView),
            POINTER(MatrixView),
            c_double,
            POINTER(c_void_p),
        ),
        c_int,
    ),
    (
        "n4m_estimators_cppls_fit",
        (
            c_void_p,
            c_void_p,
            POINTER(MatrixView),
            POINTER(MatrixView),
            c_double,
            POINTER(c_void_p),
        ),
        c_int,
    ),
    (
        "n4m_estimators_ecr_fit",
        (
            c_void_p,
            c_void_p,
            POINTER(MatrixView),
            POINTER(MatrixView),
            c_double,
            POINTER(c_void_p),
        ),
        c_int,
    ),
    (
        "n4m_estimators_fused_sparse_pls_fit",
        (
            c_void_p,
            c_void_p,
            POINTER(MatrixView),
            POINTER(MatrixView),
            c_double,
            c_double,
            POINTER(c_void_p),
        ),
        c_int,
    ),
    (
        "n4m_estimators_gpr_pls_fit",
        (
            c_void_p,
            c_void_p,
            POINTER(MatrixView),
            POINTER(MatrixView),
            c_double,
            c_double,
            c_uint64,
            POINTER(c_void_p),
        ),
        c_int,
    ),
    (
        "n4m_estimators_group_sparse_pls_fit",
        (
            c_void_p,
            c_void_p,
            POINTER(MatrixView),
            POINTER(MatrixView),
            POINTER(c_int32),
            c_int64,
            c_double,
            POINTER(c_void_p),
        ),
        c_int,
    ),
    (
        "n4m_estimators_kernel_pls_fit",
        (
            c_void_p,
            c_void_p,
            c_int32,
            c_double,
            c_double,
            c_int32,
            POINTER(MatrixView),
            POINTER(MatrixView),
            POINTER(c_void_p),
        ),
        c_int,
    ),
    (
        "n4m_estimators_lw_pls_fit",
        (
            c_void_p,
            c_void_p,
            POINTER(MatrixView),
            POINTER(MatrixView),
            c_int32,
            POINTER(c_void_p),
        ),
        c_int,
    ),
    (
        "n4m_estimators_mb_pls_fit",
        (
            c_void_p,
            c_void_p,
            POINTER(MatrixView),
            POINTER(MatrixView),
            POINTER(c_int64),
            c_int64,
            POINTER(c_void_p),
        ),
        c_int,
    ),
    (
        "n4m_estimators_mir_pls_fit",
        (
            c_void_p,
            c_void_p,
            POINTER(MatrixView),
            POINTER(MatrixView),
            POINTER(c_void_p),
        ),
        c_int,
    ),
    (
        "n4m_estimators_missing_aware_nipals_fit",
        (
            c_void_p,
            c_void_p,
            POINTER(MatrixView),
            POINTER(MatrixView),
            POINTER(c_void_p),
        ),
        c_int,
    ),
    (
        "n4m_estimators_n_pls_fit",
        (
            c_void_p,
            c_void_p,
            POINTER(MatrixView),
            c_int32,
            c_int32,
            POINTER(MatrixView),
            POINTER(c_void_p),
        ),
        c_int,
    ),
    (
        "n4m_estimators_o2pls_fit",
        (
            c_void_p,
            c_void_p,
            POINTER(MatrixView),
            POINTER(MatrixView),
            c_int32,
            c_int32,
            c_int32,
            POINTER(c_void_p),
        ),
        c_int,
    ),
    (
        "n4m_estimators_on_pls_fit",
        (
            c_void_p,
            c_void_p,
            POINTER(MatrixView),
            c_int32,
            c_int32,
            POINTER(c_int32),
            c_int64,
            POINTER(c_void_p),
        ),
        c_int,
    ),
    (
        "n4m_estimators_pcr_fit",
        (
            c_void_p,
            c_void_p,
            POINTER(MatrixView),
            POINTER(MatrixView),
            POINTER(c_void_p),
        ),
        c_int,
    ),
    (
        "n4m_estimators_pls_cox_fit",
        (
            c_void_p,
            c_void_p,
            POINTER(MatrixView),
            POINTER(c_double),
            c_int64,
            POINTER(c_int32),
            c_int64,
            POINTER(c_void_p),
        ),
        c_int,
    ),
    (
        "n4m_estimators_pls_fit",
        (
            POINTER(c_double),
            POINTER(c_double),
            c_int32,
            c_int32,
            c_int32,
            c_int32,
            POINTER(c_double),
            POINTER(c_double),
            POINTER(c_double),
            POINTER(c_double),
        ),
        c_int,
    ),
    (
        "n4m_estimators_pls_glm_fit",
        (
            c_void_p,
            c_void_p,
            POINTER(MatrixView),
            POINTER(MatrixView),
            c_int32,
            POINTER(c_void_p),
        ),
        c_int,
    ),
    (
        "n4m_estimators_pls_lda_fit",
        (
            c_void_p,
            c_void_p,
            POINTER(MatrixView),
            POINTER(c_int32),
            c_int64,
            c_int32,
            POINTER(c_void_p),
        ),
        c_int,
    ),
    (
        "n4m_estimators_pls_logistic_fit",
        (
            c_void_p,
            c_void_p,
            POINTER(MatrixView),
            POINTER(c_int32),
            c_int64,
            c_int32,
            POINTER(c_void_p),
        ),
        c_int,
    ),
    (
        "n4m_estimators_pls_qda_fit",
        (
            c_void_p,
            c_void_p,
            POINTER(MatrixView),
            POINTER(c_int32),
            c_int64,
            POINTER(c_void_p),
        ),
        c_int,
    ),
    (
        "n4m_estimators_recursive_pls_run",
        (
            c_void_p,
            c_void_p,
            POINTER(MatrixView),
            POINTER(MatrixView),
            c_int32,
            POINTER(c_void_p),
        ),
        c_int,
    ),
    (
        "n4m_estimators_ridge_fit",
        (
            c_void_p,
            c_void_p,
            POINTER(MatrixView),
            POINTER(MatrixView),
            POINTER(c_double),
            c_int64,
            POINTER(c_void_p),
        ),
        c_int,
    ),
    (
        "n4m_estimators_ridge_pls_fit",
        (
            c_void_p,
            c_void_p,
            POINTER(MatrixView),
            POINTER(MatrixView),
            c_double,
            POINTER(c_void_p),
        ),
        c_int,
    ),
    (
        "n4m_estimators_robust_pls_fit",
        (
            c_void_p,
            c_void_p,
            POINTER(MatrixView),
            POINTER(MatrixView),
            c_double,
            c_int32,
            POINTER(c_void_p),
        ),
        c_int,
    ),
    (
        "n4m_estimators_rosa_fit",
        (
            c_void_p,
            c_void_p,
            POINTER(MatrixView),
            c_int32,
            POINTER(MatrixView),
            c_int32,
            POINTER(c_void_p),
        ),
        c_int,
    ),
    (
        "n4m_estimators_so_pls_fit",
        (
            c_void_p,
            c_void_p,
            POINTER(MatrixView),
            c_int32,
            POINTER(MatrixView),
            POINTER(c_int32),
            c_int64,
            POINTER(c_void_p),
        ),
        c_int,
    ),
    (
        "n4m_estimators_sparse_pls_da_fit",
        (
            c_void_p,
            c_void_p,
            POINTER(MatrixView),
            POINTER(c_int32),
            c_int64,
            POINTER(c_void_p),
        ),
        c_int,
    ),
    (
        "n4m_estimators_sparse_simpls_fit",
        (
            c_void_p,
            c_void_p,
            POINTER(MatrixView),
            POINTER(MatrixView),
            c_double,
            POINTER(c_void_p),
        ),
        c_int,
    ),
    (
        "n4m_estimators_weighted_pls_fit",
        (
            c_void_p,
            c_void_p,
            POINTER(MatrixView),
            POINTER(MatrixView),
            POINTER(c_double),
            c_int64,
            POINTER(c_void_p),
        ),
        c_int,
    ),
    (
        "n4m_feature_selection_bipls_select",
        (
            c_void_p,
            c_void_p,
            POINTER(MatrixView),
            POINTER(MatrixView),
            c_void_p,
            c_int32,
            c_int32,
            POINTER(c_void_p),
        ),
        c_int,
    ),
    (
        "n4m_feature_selection_bve_select",
        (
            c_void_p,
            c_void_p,
            POINTER(MatrixView),
            POINTER(MatrixView),
            c_void_p,
            c_int32,
            c_int32,
            POINTER(c_void_p),
        ),
        c_int,
    ),
    (
        "n4m_feature_selection_cars_select",
        (
            c_void_p,
            c_void_p,
            POINTER(MatrixView),
            POINTER(MatrixView),
            c_void_p,
            c_int32,
            c_int32,
            POINTER(c_void_p),
        ),
        c_int,
    ),
    (
        "n4m_feature_selection_correlation_create",
        (POINTER(c_void_p), c_double, c_int32),
        c_int,
    ),
    ("n4m_feature_selection_correlation_destroy", (c_void_p,), None),
    (
        "n4m_feature_selection_correlation_fit",
        (c_void_p, MatrixView, POINTER(c_double), c_int64),
        c_int,
    ),
    ("n4m_feature_selection_correlation_is_fitted", (c_void_p, POINTER(c_int)), c_int),
    (
        "n4m_feature_selection_correlation_output_cols",
        (c_void_p, POINTER(c_int64)),
        c_int,
    ),
    (
        "n4m_feature_selection_correlation_transform",
        (c_void_p, MatrixView, MatrixView),
        c_int,
    ),
    (
        "n4m_feature_selection_emcuve_select",
        (
            c_void_p,
            c_void_p,
            POINTER(MatrixView),
            POINTER(MatrixView),
            c_void_p,
            c_int32,
            c_uint64,
            c_int32,
            c_double,
            POINTER(c_void_p),
        ),
        c_int,
    ),
    (
        "n4m_feature_selection_ga_select",
        (
            c_void_p,
            c_void_p,
            POINTER(MatrixView),
            POINTER(MatrixView),
            c_void_p,
            c_int32,
            c_int32,
            c_int32,
            c_int32,
            c_double,
            c_uint64,
            POINTER(c_void_p),
        ),
        c_int,
    ),
    (
        "n4m_feature_selection_interval_generator_create",
        (POINTER(c_void_p), c_int32, c_int32),
        c_int,
    ),
    ("n4m_feature_selection_interval_generator_destroy", (c_void_p,), None),
    ("n4m_feature_selection_interval_generator_fit", (c_void_p, MatrixView), c_int),
    (
        "n4m_feature_selection_interval_generator_is_fitted",
        (c_void_p, POINTER(c_int)),
        c_int,
    ),
    (
        "n4m_feature_selection_interval_generator_output_cols",
        (c_void_p, POINTER(c_int64)),
        c_int,
    ),
    (
        "n4m_feature_selection_interval_generator_transform",
        (c_void_p, MatrixView, MatrixView),
        c_int,
    ),
    (
        "n4m_feature_selection_interval_select",
        (
            c_void_p,
            c_void_p,
            POINTER(MatrixView),
            POINTER(MatrixView),
            c_void_p,
            c_int32,
            c_int32,
            POINTER(c_void_p),
        ),
        c_int,
    ),
    (
        "n4m_feature_selection_ipw_select",
        (
            c_void_p,
            c_void_p,
            POINTER(MatrixView),
            POINTER(MatrixView),
            c_void_p,
            c_int32,
            c_int32,
            c_double,
            c_double,
            POINTER(c_void_p),
        ),
        c_int,
    ),
    (
        "n4m_feature_selection_irf_select",
        (
            c_void_p,
            c_void_p,
            POINTER(MatrixView),
            POINTER(MatrixView),
            c_void_p,
            c_int32,
            c_int32,
            c_int32,
            c_int32,
            c_uint64,
            POINTER(c_void_p),
        ),
        c_int,
    ),
    (
        "n4m_feature_selection_iriv_select",
        (
            c_void_p,
            c_void_p,
            POINTER(MatrixView),
            POINTER(MatrixView),
            c_void_p,
            c_int32,
            c_uint64,
            POINTER(c_void_p),
        ),
        c_int,
    ),
    (
        "n4m_feature_selection_pso_select",
        (
            c_void_p,
            c_void_p,
            POINTER(MatrixView),
            POINTER(MatrixView),
            c_void_p,
            c_int32,
            c_int32,
            c_double,
            c_double,
            c_double,
            c_double,
            c_uint64,
            POINTER(c_void_p),
        ),
        c_int,
    ),
    (
        "n4m_feature_selection_random_frog_select",
        (
            c_void_p,
            c_void_p,
            POINTER(MatrixView),
            POINTER(MatrixView),
            c_void_p,
            c_int32,
            c_int32,
            c_int32,
            c_int32,
            c_int32,
            c_uint64,
            POINTER(c_void_p),
        ),
        c_int,
    ),
    (
        "n4m_feature_selection_randomization_select",
        (
            c_void_p,
            c_void_p,
            POINTER(MatrixView),
            POINTER(MatrixView),
            c_int32,
            c_uint64,
            c_double,
            POINTER(c_void_p),
        ),
        c_int,
    ),
    (
        "n4m_feature_selection_rep_select",
        (
            c_void_p,
            c_void_p,
            POINTER(MatrixView),
            POINTER(MatrixView),
            c_void_p,
            c_int32,
            c_int32,
            c_int32,
            POINTER(c_void_p),
        ),
        c_int,
    ),
    (
        "n4m_feature_selection_scars_select",
        (
            c_void_p,
            c_void_p,
            POINTER(MatrixView),
            POINTER(MatrixView),
            c_void_p,
            c_int32,
            c_int32,
            c_double,
            c_uint64,
            POINTER(c_void_p),
        ),
        c_int,
    ),
    (
        "n4m_feature_selection_shaving_select",
        (
            c_void_p,
            c_void_p,
            POINTER(MatrixView),
            POINTER(MatrixView),
            c_void_p,
            c_int32,
            c_int32,
            c_double,
            POINTER(c_void_p),
        ),
        c_int,
    ),
    (
        "n4m_feature_selection_sipls_select",
        (
            c_void_p,
            c_void_p,
            POINTER(MatrixView),
            POINTER(MatrixView),
            c_void_p,
            c_int32,
            c_int32,
            POINTER(c_void_p),
        ),
        c_int,
    ),
    (
        "n4m_feature_selection_spa_select",
        (
            c_void_p,
            c_void_p,
            POINTER(MatrixView),
            POINTER(MatrixView),
            c_int32,
            POINTER(c_void_p),
        ),
        c_int,
    ),
    (
        "n4m_feature_selection_st_select",
        (
            c_void_p,
            c_void_p,
            POINTER(MatrixView),
            POINTER(MatrixView),
            c_void_p,
            POINTER(c_double),
            c_int64,
            c_int32,
            POINTER(c_void_p),
        ),
        c_int,
    ),
    (
        "n4m_feature_selection_stability_select",
        (
            c_void_p,
            c_void_p,
            POINTER(MatrixView),
            POINTER(MatrixView),
            c_void_p,
            c_int32,
            POINTER(c_void_p),
        ),
        c_int,
    ),
    (
        "n4m_feature_selection_t2_select",
        (
            c_void_p,
            c_void_p,
            POINTER(MatrixView),
            POINTER(MatrixView),
            c_void_p,
            POINTER(c_double),
            c_int64,
            c_int32,
            POINTER(c_void_p),
        ),
        c_int,
    ),
    (
        "n4m_feature_selection_uve_select",
        (
            c_void_p,
            c_void_p,
            POINTER(MatrixView),
            POINTER(MatrixView),
            c_void_p,
            c_int32,
            c_uint64,
            POINTER(c_void_p),
        ),
        c_int,
    ),
    (
        "n4m_feature_selection_variable_select_rank",
        (c_void_p, c_void_p, POINTER(MatrixView), c_int32, c_int32, POINTER(c_void_p)),
        c_int,
    ),
    (
        "n4m_feature_selection_variance_create",
        (POINTER(c_void_p), c_double, c_int32),
        c_int,
    ),
    ("n4m_feature_selection_variance_destroy", (c_void_p,), None),
    ("n4m_feature_selection_variance_fit", (c_void_p, MatrixView), c_int),
    ("n4m_feature_selection_variance_is_fitted", (c_void_p, POINTER(c_int)), c_int),
    ("n4m_feature_selection_variance_output_cols", (c_void_p, POINTER(c_int64)), c_int),
    (
        "n4m_feature_selection_variance_transform",
        (c_void_p, MatrixView, MatrixView),
        c_int,
    ),
    (
        "n4m_feature_selection_vip_spa_select",
        (
            c_void_p,
            c_void_p,
            POINTER(MatrixView),
            POINTER(MatrixView),
            c_double,
            c_int32,
            POINTER(c_void_p),
        ),
        c_int,
    ),
    (
        "n4m_feature_selection_vissa_select",
        (
            c_void_p,
            c_void_p,
            POINTER(MatrixView),
            POINTER(MatrixView),
            c_void_p,
            c_int32,
            c_int32,
            c_double,
            c_double,
            c_double,
            c_uint64,
            POINTER(c_void_p),
        ),
        c_int,
    ),
    (
        "n4m_feature_selection_wvc_select",
        (
            c_void_p,
            POINTER(MatrixView),
            POINTER(MatrixView),
            c_int32,
            c_int32,
            c_int32,
            POINTER(c_void_p),
        ),
        c_int,
    ),
    (
        "n4m_feature_selection_wvc_threshold_select",
        (
            c_void_p,
            POINTER(MatrixView),
            POINTER(MatrixView),
            c_int32,
            c_int32,
            c_double,
            c_double,
            c_int32,
            POINTER(c_void_p),
        ),
        c_int,
    ),
    ("n4m_gating_strategy_create", (POINTER(c_void_p), c_int), c_int),
    ("n4m_gating_strategy_destroy", (c_void_p,), None),
    ("n4m_get_abi_version_int", (), c_uint32),
    ("n4m_get_abi_version_major", (), c_uint32),
    ("n4m_get_abi_version_minor", (), c_uint32),
    ("n4m_get_abi_version_patch", (), c_uint32),
    ("n4m_get_build_info", (), c_void_p),
    ("n4m_get_git_revision", (), c_void_p),
    ("n4m_get_version_string", (), c_void_p),
    (
        "n4m_lowlevel_moments_compute",
        (c_void_p, POINTER(MatrixView), POINTER(MatrixView), POINTER(c_void_p)),
        c_int,
    ),
    (
        "n4m_lowlevel_moments_subset_compute",
        (
            c_void_p,
            POINTER(MatrixView),
            POINTER(MatrixView),
            POINTER(c_int64),
            c_int64,
            POINTER(c_void_p),
        ),
        c_int,
    ),
    (
        "n4m_lowlevel_moments_subtract",
        (c_void_p, c_void_p, c_void_p, POINTER(c_void_p)),
        c_int,
    ),
    (
        "n4m_matrix_view_init_colmajor",
        (POINTER(MatrixView), c_void_p, c_int64, c_int64, c_int),
        c_int,
    ),
    (
        "n4m_matrix_view_init_rowmajor",
        (POINTER(MatrixView), c_void_p, c_int64, c_int64, c_int),
        c_int,
    ),
    (
        "n4m_matrix_view_init_strided",
        (POINTER(MatrixView), c_void_p, c_int64, c_int64, c_int64, c_int64, c_int),
        c_int,
    ),
    ("n4m_matrix_view_validate", (POINTER(MatrixView),), c_int),
    ("n4m_method_result_destroy", (c_void_p,), None),
    (
        "n4m_method_result_get_double_matrix",
        (
            c_void_p,
            c_char_p,
            POINTER(POINTER(c_double)),
            POINTER(c_int64),
            POINTER(c_int64),
        ),
        c_int,
    ),
    (
        "n4m_method_result_get_int64_vector",
        (c_void_p, c_char_p, POINTER(POINTER(c_int64)), POINTER(c_int64)),
        c_int,
    ),
    (
        "n4m_method_result_get_int_vector",
        (c_void_p, c_char_p, POINTER(POINTER(c_int32)), POINTER(c_int32)),
        c_int,
    ),
    ("n4m_method_result_get_scalar", (c_void_p, c_char_p, POINTER(c_double)), c_int),
    (
        "n4m_metrics_approximate_press_compute",
        (
            c_void_p,
            c_void_p,
            POINTER(MatrixView),
            POINTER(MatrixView),
            c_int32,
            POINTER(c_void_p),
        ),
        c_int,
    ),
    (
        "n4m_metrics_one_se_rule_compute",
        (c_void_p, POINTER(c_double), c_int32, c_int32, POINTER(c_void_p)),
        c_int,
    ),
    (
        "n4m_metrics_pls_diagnostics_compute",
        (
            c_void_p,
            c_void_p,
            POINTER(MatrixView),
            POINTER(MatrixView),
            POINTER(c_void_p),
        ),
        c_int,
    ),
    (
        "n4m_metrics_pls_monitoring_run",
        (
            c_void_p,
            c_void_p,
            POINTER(MatrixView),
            POINTER(MatrixView),
            c_double,
            POINTER(c_void_p),
        ),
        c_int,
    ),
    (
        "n4m_metrics_regression_metrics_bias",
        (POINTER(c_double), POINTER(c_double), c_int64, POINTER(c_double)),
        c_int,
    ),
    (
        "n4m_metrics_regression_metrics_mae",
        (POINTER(c_double), POINTER(c_double), c_int64, POINTER(c_double)),
        c_int,
    ),
    (
        "n4m_metrics_regression_metrics_nrmse",
        (POINTER(c_double), POINTER(c_double), c_int64, POINTER(c_double)),
        c_int,
    ),
    (
        "n4m_metrics_regression_metrics_r2",
        (POINTER(c_double), POINTER(c_double), c_int64, POINTER(c_double)),
        c_int,
    ),
    (
        "n4m_metrics_regression_metrics_rmse",
        (POINTER(c_double), POINTER(c_double), c_int64, POINTER(c_double)),
        c_int,
    ),
    (
        "n4m_metrics_regression_metrics_rpd",
        (POINTER(c_double), POINTER(c_double), c_int64, POINTER(c_double)),
        c_int,
    ),
    (
        "n4m_metrics_regression_metrics_rpiq",
        (POINTER(c_double), POINTER(c_double), c_int64, POINTER(c_double)),
        c_int,
    ),
    (
        "n4m_metrics_regression_metrics_sep",
        (POINTER(c_double), POINTER(c_double), c_int64, POINTER(c_double)),
        c_int,
    ),
    ("n4m_model_destroy", (c_void_p,), None),
    ("n4m_model_export_size", (c_void_p, POINTER(c_size_t)), c_int),
    (
        "n4m_model_export_to_buffer",
        (c_void_p, c_void_p, c_size_t, POINTER(c_size_t)),
        c_int,
    ),
    (
        "n4m_model_fit",
        (
            c_void_p,
            c_void_p,
            POINTER(MatrixView),
            POINTER(MatrixView),
            POINTER(c_void_p),
        ),
        c_int,
    ),
    ("n4m_model_get_array", (c_void_p, c_void_p, c_int, POINTER(c_void_p)), c_int),
    ("n4m_model_get_n_components", (c_void_p, POINTER(c_int32)), c_int),
    ("n4m_model_get_n_features", (c_void_p, POINTER(c_int32)), c_int),
    ("n4m_model_get_n_targets", (c_void_p, POINTER(c_int32)), c_int),
    (
        "n4m_model_import_from_buffer",
        (c_void_p, c_void_p, c_size_t, POINTER(c_void_p)),
        c_int,
    ),
    (
        "n4m_model_import_linear_predictor",
        (c_void_p, POINTER(LinearPredictorSpec), POINTER(c_void_p)),
        c_int,
    ),
    (
        "n4m_model_predict",
        (c_void_p, c_void_p, POINTER(MatrixView), POINTER(MatrixView)),
        c_int,
    ),
    (
        "n4m_model_predict_alloc",
        (c_void_p, c_void_p, POINTER(MatrixView), POINTER(c_void_p)),
        c_int,
    ),
    (
        "n4m_model_selection_aom_chain_fixed_fit_run",
        (
            c_void_p,
            c_void_p,
            POINTER(MatrixView),
            POINTER(MatrixView),
            POINTER(c_int32),
            c_int64,
            POINTER(c_int32),
            c_int64,
            POINTER(c_int32),
            c_int64,
            POINTER(c_double),
            c_int64,
            c_int32,
            c_double,
            POINTER(c_void_p),
        ),
        c_int,
    ),
    (
        "n4m_model_selection_aom_chain_sweep_run",
        (
            c_void_p,
            c_void_p,
            POINTER(MatrixView),
            POINTER(MatrixView),
            c_int32,
            POINTER(c_int32),
            c_int64,
            POINTER(c_int32),
            c_int64,
            POINTER(c_int32),
            c_int64,
            POINTER(c_int32),
            c_int64,
            POINTER(c_double),
            c_int64,
            POINTER(c_double),
            c_int64,
            POINTER(c_int32),
            c_int64,
            c_int32,
            POINTER(c_void_p),
        ),
        c_int,
    ),
    ("n4m_model_selection_aom_pls_result_destroy", (c_void_p,), None),
    (
        "n4m_model_selection_aom_pls_result_get_best_score",
        (c_void_p, POINTER(c_double)),
        c_int,
    ),
    (
        "n4m_model_selection_aom_pls_result_get_coefficients",
        (c_void_p, POINTER(POINTER(c_double)), POINTER(c_int64), POINTER(c_int64)),
        c_int,
    ),
    (
        "n4m_model_selection_aom_pls_result_get_input_coefficients",
        (c_void_p, POINTER(POINTER(c_double)), POINTER(c_int64), POINTER(c_int64)),
        c_int,
    ),
    (
        "n4m_model_selection_aom_pls_result_get_intercept",
        (c_void_p, POINTER(POINTER(c_double)), POINTER(c_int64), POINTER(c_int64)),
        c_int,
    ),
    (
        "n4m_model_selection_aom_pls_result_get_max_components",
        (c_void_p, POINTER(c_int32)),
        c_int,
    ),
    (
        "n4m_model_selection_aom_pls_result_get_n_operators",
        (c_void_p, POINTER(c_int32)),
        c_int,
    ),
    (
        "n4m_model_selection_aom_pls_result_get_operator_kinds",
        (c_void_p, POINTER(POINTER(c_int32)), POINTER(c_int32)),
        c_int,
    ),
    (
        "n4m_model_selection_aom_pls_result_get_operator_scores",
        (c_void_p, POINTER(POINTER(c_double)), POINTER(c_int32)),
        c_int,
    ),
    (
        "n4m_model_selection_aom_pls_result_get_predictions",
        (c_void_p, POINTER(POINTER(c_double)), POINTER(c_int64), POINTER(c_int64)),
        c_int,
    ),
    (
        "n4m_model_selection_aom_pls_result_get_rmse_curves",
        (c_void_p, POINTER(POINTER(c_double)), POINTER(c_int32), POINTER(c_int32)),
        c_int,
    ),
    (
        "n4m_model_selection_aom_pls_result_get_selected_n_components",
        (c_void_p, POINTER(c_int32)),
        c_int,
    ),
    (
        "n4m_model_selection_aom_pls_result_get_selected_operator_index",
        (c_void_p, POINTER(c_int32)),
        c_int,
    ),
    (
        "n4m_model_selection_aom_pls_select",
        (
            c_void_p,
            c_void_p,
            c_void_p,
            POINTER(MatrixView),
            POINTER(MatrixView),
            c_void_p,
            c_int32,
            POINTER(c_void_p),
        ),
        c_int,
    ),
    (
        "n4m_model_selection_aom_preprocessing_fit",
        (
            c_void_p,
            c_void_p,
            c_void_p,
            POINTER(MatrixView),
            POINTER(MatrixView),
            POINTER(c_void_p),
        ),
        c_int,
    ),
    (
        "n4m_model_selection_aom_sweep_run",
        (
            c_void_p,
            c_void_p,
            POINTER(MatrixView),
            POINTER(MatrixView),
            c_int32,
            c_int32,
            POINTER(c_int32),
            c_int64,
            POINTER(c_double),
            c_int64,
            POINTER(c_int32),
            c_int64,
            c_int32,
            POINTER(c_void_p),
        ),
        c_int,
    ),
    (
        "n4m_model_selection_binned_strat_group_kfold_create",
        (POINTER(c_void_p), c_int32, c_int32, c_int32, c_int32, c_uint64),
        c_int,
    ),
    ("n4m_model_selection_binned_strat_group_kfold_destroy", (c_void_p,), None),
    (
        "n4m_model_selection_binned_strat_group_kfold_n_splits",
        (c_void_p, POINTER(c_int32)),
        c_int,
    ),
    (
        "n4m_model_selection_binned_strat_group_kfold_split_fold",
        (
            c_void_p,
            MatrixView,
            POINTER(c_int64),
            c_int64,
            c_int32,
            POINTER(SplitResult),
        ),
        c_int,
    ),
    (
        "n4m_model_selection_data_twinning_create",
        (POINTER(c_void_p), c_double, c_uint64),
        c_int,
    ),
    ("n4m_model_selection_data_twinning_destroy", (c_void_p,), None),
    (
        "n4m_model_selection_data_twinning_split",
        (c_void_p, MatrixView, POINTER(SplitResult)),
        c_int,
    ),
    (
        "n4m_model_selection_kbins_stratified_create",
        (POINTER(c_void_p), c_double, c_uint64, c_int32, c_int32),
        c_int,
    ),
    ("n4m_model_selection_kbins_stratified_destroy", (c_void_p,), None),
    (
        "n4m_model_selection_kbins_stratified_split",
        (c_void_p, MatrixView, POINTER(SplitResult)),
        c_int,
    ),
    ("n4m_model_selection_kennard_stone_create", (POINTER(c_void_p), c_double), c_int),
    ("n4m_model_selection_kennard_stone_destroy", (c_void_p,), None),
    (
        "n4m_model_selection_kennard_stone_split",
        (c_void_p, MatrixView, POINTER(SplitResult)),
        c_int,
    ),
    (
        "n4m_model_selection_kmeans_create",
        (POINTER(c_void_p), c_double, c_uint64, c_int32),
        c_int,
    ),
    ("n4m_model_selection_kmeans_destroy", (c_void_p,), None),
    (
        "n4m_model_selection_kmeans_split",
        (c_void_p, MatrixView, POINTER(SplitResult)),
        c_int,
    ),
    ("n4m_model_selection_pop_pls_result_destroy", (c_void_p,), None),
    (
        "n4m_model_selection_pop_pls_result_get_best_score",
        (c_void_p, POINTER(c_double)),
        c_int,
    ),
    (
        "n4m_model_selection_pop_pls_result_get_coefficients",
        (c_void_p, POINTER(POINTER(c_double)), POINTER(c_int64), POINTER(c_int64)),
        c_int,
    ),
    (
        "n4m_model_selection_pop_pls_result_get_component_scores",
        (c_void_p, POINTER(POINTER(c_double)), POINTER(c_int32), POINTER(c_int32)),
        c_int,
    ),
    (
        "n4m_model_selection_pop_pls_result_get_input_coefficients",
        (c_void_p, POINTER(POINTER(c_double)), POINTER(c_int64), POINTER(c_int64)),
        c_int,
    ),
    (
        "n4m_model_selection_pop_pls_result_get_intercept",
        (c_void_p, POINTER(POINTER(c_double)), POINTER(c_int64), POINTER(c_int64)),
        c_int,
    ),
    (
        "n4m_model_selection_pop_pls_result_get_max_components",
        (c_void_p, POINTER(c_int32)),
        c_int,
    ),
    (
        "n4m_model_selection_pop_pls_result_get_n_operators",
        (c_void_p, POINTER(c_int32)),
        c_int,
    ),
    (
        "n4m_model_selection_pop_pls_result_get_operator_kinds",
        (c_void_p, POINTER(POINTER(c_int32)), POINTER(c_int32)),
        c_int,
    ),
    (
        "n4m_model_selection_pop_pls_result_get_predictions",
        (c_void_p, POINTER(POINTER(c_double)), POINTER(c_int64), POINTER(c_int64)),
        c_int,
    ),
    (
        "n4m_model_selection_pop_pls_result_get_prefix_scores",
        (c_void_p, POINTER(POINTER(c_double)), POINTER(c_int32)),
        c_int,
    ),
    (
        "n4m_model_selection_pop_pls_result_get_selected_n_components",
        (c_void_p, POINTER(c_int32)),
        c_int,
    ),
    (
        "n4m_model_selection_pop_pls_result_get_selected_operator_indices",
        (c_void_p, POINTER(POINTER(c_int32)), POINTER(c_int32)),
        c_int,
    ),
    (
        "n4m_model_selection_pop_pls_select",
        (
            c_void_p,
            c_void_p,
            c_void_p,
            POINTER(MatrixView),
            POINTER(MatrixView),
            c_void_p,
            c_int32,
            POINTER(c_void_p),
        ),
        c_int,
    ),
    (
        "n4m_model_selection_robust_hpo_fit",
        (
            c_void_p,
            c_void_p,
            POINTER(MatrixView),
            POINTER(MatrixView),
            c_int32,
            c_int32,
            c_int32,
            POINTER(c_void_p),
        ),
        c_int,
    ),
    ("n4m_model_selection_spxy_create", (POINTER(c_void_p), c_double), c_int),
    ("n4m_model_selection_spxy_destroy", (c_void_p,), None),
    (
        "n4m_model_selection_spxy_fold_create",
        (POINTER(c_void_p), c_int32, c_int32),
        c_int,
    ),
    ("n4m_model_selection_spxy_fold_destroy", (c_void_p,), None),
    ("n4m_model_selection_spxy_fold_n_splits", (c_void_p, POINTER(c_int32)), c_int),
    (
        "n4m_model_selection_spxy_fold_split_fold",
        (c_void_p, MatrixView, MatrixView, c_int32, POINTER(SplitResult)),
        c_int,
    ),
    (
        "n4m_model_selection_spxy_g_fold_create",
        (POINTER(c_void_p), c_int32, c_int32, c_int32),
        c_int,
    ),
    ("n4m_model_selection_spxy_g_fold_destroy", (c_void_p,), None),
    ("n4m_model_selection_spxy_g_fold_n_splits", (c_void_p, POINTER(c_int32)), c_int),
    (
        "n4m_model_selection_spxy_g_fold_split_fold",
        (
            c_void_p,
            MatrixView,
            MatrixView,
            POINTER(c_int64),
            c_int64,
            c_int32,
            POINTER(SplitResult),
        ),
        c_int,
    ),
    (
        "n4m_model_selection_spxy_split",
        (c_void_p, MatrixView, MatrixView, POINTER(SplitResult)),
        c_int,
    ),
    (
        "n4m_model_selection_sweep_run",
        (
            c_void_p,
            c_void_p,
            POINTER(MatrixView),
            POINTER(MatrixView),
            c_int32,
            POINTER(c_int32),
            c_int64,
            POINTER(c_double),
            c_int64,
            POINTER(c_int32),
            c_int64,
            c_int32,
            POINTER(c_void_p),
        ),
        c_int,
    ),
    (
        "n4m_model_selection_systematic_circular_create",
        (POINTER(c_void_p), c_double, c_uint64),
        c_int,
    ),
    ("n4m_model_selection_systematic_circular_destroy", (c_void_p,), None),
    (
        "n4m_model_selection_systematic_circular_split",
        (c_void_p, MatrixView, POINTER(SplitResult)),
        c_int,
    ),
    (
        "n4m_model_transform",
        (c_void_p, c_void_p, POINTER(MatrixView), POINTER(MatrixView)),
        c_int,
    ),
    (
        "n4m_model_transform_alloc",
        (c_void_p, c_void_p, POINTER(MatrixView), POINTER(c_void_p)),
        c_int,
    ),
    ("n4m_operator_bank_add", (c_void_p, c_int, POINTER(c_double), c_int32), c_int),
    ("n4m_operator_bank_create", (POINTER(c_void_p),), c_int),
    ("n4m_operator_bank_destroy", (c_void_p,), None),
    ("n4m_operator_bank_size", (c_void_p, POINTER(c_int32)), c_int),
    ("n4m_outlier_detection_composite_add_leverage", (c_void_p, c_void_p), c_int),
    ("n4m_outlier_detection_composite_add_quality", (c_void_p, c_void_p), c_int),
    (
        "n4m_outlier_detection_composite_apply",
        (c_void_p, MatrixView, POINTER(c_uint8), POINTER(FilterStats)),
        c_int,
    ),
    ("n4m_outlier_detection_composite_create", (POINTER(c_void_p), c_int32), c_int),
    ("n4m_outlier_detection_composite_destroy", (c_void_p,), None),
    (
        "n4m_outlier_detection_high_leverage_apply",
        (c_void_p, MatrixView, POINTER(c_uint8), POINTER(FilterStats)),
        c_int,
    ),
    (
        "n4m_outlier_detection_high_leverage_create",
        (POINTER(c_void_p), c_int32, c_double, c_int, c_double, c_int32, c_int),
        c_int,
    ),
    ("n4m_outlier_detection_high_leverage_destroy", (c_void_p,), None),
    ("n4m_outlier_detection_high_leverage_fit", (c_void_p, MatrixView), c_int),
    (
        "n4m_outlier_detection_high_leverage_is_fitted",
        (c_void_p, POINTER(c_int)),
        c_int,
    ),
    ("n4m_outlier_detection_high_leverage_threshold", (c_void_p,), c_double),
    (
        "n4m_outlier_detection_hotelling_t2",
        (MatrixView, c_int32, c_double, POINTER(c_double), c_int64, POINTER(c_double)),
        c_int,
    ),
    (
        "n4m_outlier_detection_q_residuals",
        (MatrixView, c_int32, c_double, POINTER(c_double), c_int64, POINTER(c_double)),
        c_int,
    ),
    (
        "n4m_outlier_detection_spectral_quality_apply",
        (c_void_p, MatrixView, POINTER(c_uint8), POINTER(FilterStats)),
        c_int,
    ),
    (
        "n4m_outlier_detection_spectral_quality_create",
        (
            POINTER(c_void_p),
            c_double,
            c_double,
            c_double,
            c_int,
            c_double,
            c_int,
            c_double,
            c_int,
        ),
        c_int,
    ),
    ("n4m_outlier_detection_spectral_quality_destroy", (c_void_p,), None),
    (
        "n4m_outlier_detection_x_outlier_apply",
        (c_void_p, MatrixView, POINTER(c_uint8), POINTER(FilterStats)),
        c_int,
    ),
    (
        "n4m_outlier_detection_x_outlier_create",
        (
            POINTER(c_void_p),
            c_int32,
            c_int,
            c_double,
            c_int32,
            c_double,
            c_uint64,
            c_int32,
            c_int64,
        ),
        c_int,
    ),
    ("n4m_outlier_detection_x_outlier_destroy", (c_void_p,), None),
    ("n4m_outlier_detection_x_outlier_fit", (c_void_p, MatrixView), c_int),
    ("n4m_outlier_detection_x_outlier_is_fitted", (c_void_p, POINTER(c_int)), c_int),
    (
        "n4m_outlier_detection_y_outlier_apply",
        (c_void_p, POINTER(c_double), c_int64, POINTER(c_uint8), POINTER(FilterStats)),
        c_int,
    ),
    (
        "n4m_outlier_detection_y_outlier_create",
        (POINTER(c_void_p), c_int32, c_double, c_double, c_double),
        c_int,
    ),
    ("n4m_outlier_detection_y_outlier_destroy", (c_void_p,), None),
    (
        "n4m_outlier_detection_y_outlier_fit",
        (c_void_p, POINTER(c_double), c_int64),
        c_int,
    ),
    ("n4m_outlier_detection_y_outlier_is_fitted", (c_void_p, POINTER(c_int)), c_int),
    ("n4m_pipeline_add_operator", (c_void_p, c_int, POINTER(c_double), c_int32), c_int),
    ("n4m_pipeline_clone", (c_void_p, POINTER(c_void_p)), c_int),
    ("n4m_pipeline_create", (POINTER(c_void_p),), c_int),
    ("n4m_pipeline_destroy", (c_void_p,), None),
    (
        "n4m_pipeline_fit",
        (c_void_p, c_void_p, POINTER(MatrixView), POINTER(MatrixView)),
        c_int,
    ),
    ("n4m_pipeline_size", (c_void_p, POINTER(c_int32)), c_int),
    (
        "n4m_pipeline_transform",
        (c_void_p, c_void_p, POINTER(MatrixView), POINTER(MatrixView)),
        c_int,
    ),
    (
        "n4m_pipeline_transform_alloc",
        (c_void_p, c_void_p, POINTER(MatrixView), POINTER(c_void_p)),
        c_int,
    ),
    (
        "n4m_pls_cross_validate",
        (
            c_void_p,
            c_void_p,
            POINTER(MatrixView),
            POINTER(MatrixView),
            POINTER(c_int32),
            c_int64,
            c_int32,
            POINTER(c_int32),
            c_int64,
            POINTER(c_void_p),
        ),
        c_int,
    ),
    ("n4m_rng_pcg64_advance", (c_void_p, c_uint64), c_int),
    ("n4m_rng_pcg64_create", (c_uint64, POINTER(c_void_p)), c_int),
    ("n4m_rng_pcg64_destroy", (c_void_p,), None),
    ("n4m_rng_pcg64_set_seed", (c_void_p, c_uint64), c_int),
    (
        "n4m_rng_pcg64_standard_normal_fill",
        (c_void_p, POINTER(c_double), c_size_t),
        c_int,
    ),
    ("n4m_rng_pcg64_uint64", (c_void_p, POINTER(c_uint64)), c_int),
    ("n4m_rng_pcg64_uint64_fill", (c_void_p, POINTER(c_uint64), c_size_t), c_int),
    (
        "n4m_serialization_inspect",
        (
            c_void_p,
            c_size_t,
            POINTER(c_uint32),
            POINTER(c_uint32),
            POINTER(c_uint32),
            POINTER(c_uint32),
        ),
        c_int,
    ),
    (
        "n4m_serialization_inspect_model_v1",
        (c_void_p, c_size_t, POINTER(SerializedModelInfoV1)),
        c_int,
    ),
    ("n4m_split_result_destroy", (POINTER(SplitResult),), None),
    ("n4m_status_to_string", (c_int,), c_void_p),
    (
        "n4m_transform_airpls_create",
        (POINTER(c_void_p), c_double, c_int32, c_double),
        c_int,
    ),
    ("n4m_transform_airpls_destroy", (c_void_p,), None),
    ("n4m_transform_airpls_transform", (c_void_p, MatrixView, MatrixView), c_int),
    ("n4m_transform_area_normalization_create", (POINTER(c_void_p), c_int32), c_int),
    ("n4m_transform_area_normalization_destroy", (c_void_p,), None),
    (
        "n4m_transform_area_normalization_transform",
        (c_void_p, MatrixView, MatrixView),
        c_int,
    ),
    (
        "n4m_transform_arpls_create",
        (POINTER(c_void_p), c_double, c_int32, c_double),
        c_int,
    ),
    ("n4m_transform_arpls_destroy", (c_void_p,), None),
    ("n4m_transform_arpls_transform", (c_void_p, MatrixView, MatrixView), c_int),
    (
        "n4m_transform_asls_create",
        (POINTER(c_void_p), c_double, c_double, c_int32, c_double),
        c_int,
    ),
    ("n4m_transform_asls_destroy", (c_void_p,), None),
    ("n4m_transform_asls_transform", (c_void_p, MatrixView, MatrixView), c_int),
    ("n4m_transform_baseline_center_create", (POINTER(c_void_p),), c_int),
    ("n4m_transform_baseline_center_destroy", (c_void_p,), None),
    ("n4m_transform_baseline_center_fit", (c_void_p, MatrixView), c_int),
    (
        "n4m_transform_baseline_center_inverse_transform",
        (c_void_p, MatrixView, MatrixView),
        c_int,
    ),
    ("n4m_transform_baseline_center_is_fitted", (c_void_p, POINTER(c_int)), c_int),
    (
        "n4m_transform_baseline_center_transform",
        (c_void_p, MatrixView, MatrixView),
        c_int,
    ),
    (
        "n4m_transform_beads_create",
        (POINTER(c_void_p), c_double, c_double, c_double, c_int32, c_double),
        c_int,
    ),
    ("n4m_transform_beads_destroy", (c_void_p,), None),
    ("n4m_transform_beads_transform", (c_void_p, MatrixView, MatrixView), c_int),
    (
        "n4m_transform_cow_align_create",
        (POINTER(c_void_p), POINTER(c_double), c_int64, c_int32, c_int32),
        c_int,
    ),
    ("n4m_transform_cow_align_destroy", (c_void_p,), None),
    ("n4m_transform_cow_align_fit", (c_void_p, MatrixView), c_int),
    ("n4m_transform_cow_align_is_fitted", (c_void_p, POINTER(c_int)), c_int),
    ("n4m_transform_cow_align_transform", (c_void_p, MatrixView, MatrixView), c_int),
    ("n4m_transform_crop_create", (POINTER(c_void_p), c_int64, c_int64), c_int),
    ("n4m_transform_crop_destroy", (c_void_p,), None),
    ("n4m_transform_crop_output_cols", (c_void_p, c_int64), c_int64),
    ("n4m_transform_crop_transform", (c_void_p, MatrixView, MatrixView), c_int),
    ("n4m_transform_derivative_create", (POINTER(c_void_p), c_int32, c_double), c_int),
    ("n4m_transform_derivative_destroy", (c_void_p,), None),
    ("n4m_transform_derivative_fit", (c_void_p, MatrixView), c_int),
    ("n4m_transform_derivative_output_cols", (c_int32, c_int64), c_int64),
    ("n4m_transform_derivative_transform", (c_void_p, MatrixView, MatrixView), c_int),
    ("n4m_transform_detrend_create", (POINTER(c_void_p), c_int32), c_int),
    ("n4m_transform_detrend_destroy", (c_void_p,), None),
    ("n4m_transform_detrend_transform", (c_void_p, MatrixView, MatrixView), c_int),
    (
        "n4m_transform_dtw_align_create",
        (POINTER(c_void_p), POINTER(c_double), c_int64, c_int32, c_int32),
        c_int,
    ),
    ("n4m_transform_dtw_align_destroy", (c_void_p,), None),
    ("n4m_transform_dtw_align_fit", (c_void_p, MatrixView), c_int),
    ("n4m_transform_dtw_align_is_fitted", (c_void_p, POINTER(c_int)), c_int),
    ("n4m_transform_dtw_align_transform", (c_void_p, MatrixView, MatrixView), c_int),
    ("n4m_transform_emsc_create", (POINTER(c_void_p), c_int32), c_int),
    ("n4m_transform_emsc_destroy", (c_void_p,), None),
    ("n4m_transform_emsc_fit", (c_void_p, MatrixView), c_int),
    ("n4m_transform_emsc_is_fitted", (c_void_p, POINTER(c_int)), c_int),
    ("n4m_transform_emsc_transform", (c_void_p, MatrixView, MatrixView), c_int),
    (
        "n4m_transform_fck_static_create",
        (
            POINTER(c_void_p),
            c_int32,
            POINTER(c_double),
            c_int32,
            POINTER(c_double),
            c_int32,
        ),
        c_int,
    ),
    ("n4m_transform_fck_static_destroy", (c_void_p,), None),
    (
        "n4m_transform_fck_static_output_cols",
        (c_int32, c_int32, POINTER(c_int32)),
        c_int,
    ),
    ("n4m_transform_fck_static_transform", (c_void_p, MatrixView, MatrixView), c_int),
    (
        "n4m_transform_first_derivative_create",
        (POINTER(c_void_p), c_double, c_int32),
        c_int,
    ),
    ("n4m_transform_first_derivative_destroy", (c_void_p,), None),
    (
        "n4m_transform_first_derivative_transform",
        (c_void_p, MatrixView, MatrixView),
        c_int,
    ),
    ("n4m_transform_fraction_to_percent_create", (POINTER(c_void_p),), c_int),
    ("n4m_transform_fraction_to_percent_destroy", (c_void_p,), None),
    (
        "n4m_transform_fraction_to_percent_transform",
        (c_void_p, MatrixView, MatrixView),
        c_int,
    ),
    ("n4m_transform_from_absorbance_create", (POINTER(c_void_p), c_int), c_int),
    ("n4m_transform_from_absorbance_destroy", (c_void_p,), None),
    (
        "n4m_transform_from_absorbance_transform",
        (c_void_p, MatrixView, MatrixView),
        c_int,
    ),
    (
        "n4m_transform_gaussian_create",
        (POINTER(c_void_p), c_double, c_int32, c_int, c_double, c_double),
        c_int,
    ),
    ("n4m_transform_gaussian_destroy", (c_void_p,), None),
    ("n4m_transform_gaussian_transform", (c_void_p, MatrixView, MatrixView), c_int),
    ("n4m_transform_haar_create", (POINTER(c_void_p),), c_int),
    ("n4m_transform_haar_destroy", (c_void_p,), None),
    ("n4m_transform_haar_output_cols", (c_int64, POINTER(c_int64)), c_int),
    ("n4m_transform_haar_transform", (c_void_p, MatrixView, MatrixView), c_int),
    (
        "n4m_transform_iasls_create",
        (POINTER(c_void_p), c_double, c_double, c_int32, c_int32, c_double),
        c_int,
    ),
    (
        "n4m_transform_iasls_create_ex",
        (
            POINTER(c_void_p),
            c_double,
            c_double,
            c_double,
            c_int32,
            c_int32,
            c_int32,
            c_double,
        ),
        c_int,
    ),
    ("n4m_transform_iasls_destroy", (c_void_p,), None),
    ("n4m_transform_iasls_transform", (c_void_p, MatrixView, MatrixView), c_int),
    (
        "n4m_transform_icoshift_align_create",
        (POINTER(c_void_p), POINTER(c_double), c_int64, c_int32, c_int32),
        c_int,
    ),
    ("n4m_transform_icoshift_align_destroy", (c_void_p,), None),
    ("n4m_transform_icoshift_align_fit", (c_void_p, MatrixView), c_int),
    ("n4m_transform_icoshift_align_is_fitted", (c_void_p, POINTER(c_int)), c_int),
    (
        "n4m_transform_icoshift_align_transform",
        (c_void_p, MatrixView, MatrixView),
        c_int,
    ),
    (
        "n4m_transform_imodpoly_create",
        (POINTER(c_void_p), c_int32, c_int32, c_double),
        c_int,
    ),
    ("n4m_transform_imodpoly_destroy", (c_void_p,), None),
    ("n4m_transform_imodpoly_transform", (c_void_p, MatrixView, MatrixView), c_int),
    (
        "n4m_transform_kbins_discretizer_create",
        (POINTER(c_void_p), c_int32, c_int32),
        c_int,
    ),
    ("n4m_transform_kbins_discretizer_destroy", (c_void_p,), None),
    ("n4m_transform_kbins_discretizer_fit", (c_void_p, MatrixView), c_int),
    ("n4m_transform_kbins_discretizer_is_fitted", (c_void_p, POINTER(c_int)), c_int),
    (
        "n4m_transform_kbins_discretizer_transform",
        (c_void_p, MatrixView, MatrixView),
        c_int,
    ),
    ("n4m_transform_kubelka_munk_create", (POINTER(c_void_p), c_int, c_double), c_int),
    ("n4m_transform_kubelka_munk_destroy", (c_void_p,), None),
    ("n4m_transform_kubelka_munk_transform", (c_void_p, MatrixView, MatrixView), c_int),
    ("n4m_transform_local_centering_create", (POINTER(c_void_p),), c_int),
    ("n4m_transform_local_centering_destroy", (c_void_p,), None),
    ("n4m_transform_local_centering_fit", (c_void_p, MatrixView, MatrixView), c_int),
    ("n4m_transform_local_centering_is_fitted", (c_void_p, POINTER(c_int)), c_int),
    (
        "n4m_transform_local_centering_transform",
        (c_void_p, MatrixView, MatrixView),
        c_int,
    ),
    (
        "n4m_transform_local_snv_create",
        (POINTER(c_void_p), c_int32, c_int32, c_double),
        c_int,
    ),
    ("n4m_transform_local_snv_destroy", (c_void_p,), None),
    ("n4m_transform_local_snv_transform", (c_void_p, MatrixView, MatrixView), c_int),
    (
        "n4m_transform_localized_msc_create",
        (POINTER(c_void_p), POINTER(c_double), c_int64, c_int32, c_double),
        c_int,
    ),
    ("n4m_transform_localized_msc_destroy", (c_void_p,), None),
    ("n4m_transform_localized_msc_fit", (c_void_p, MatrixView), c_int),
    ("n4m_transform_localized_msc_is_fitted", (c_void_p, POINTER(c_int)), c_int),
    (
        "n4m_transform_localized_msc_transform",
        (c_void_p, MatrixView, MatrixView),
        c_int,
    ),
    (
        "n4m_transform_log_transform_create",
        (POINTER(c_void_p), c_double, c_double, c_int, c_double),
        c_int,
    ),
    ("n4m_transform_log_transform_destroy", (c_void_p,), None),
    ("n4m_transform_log_transform_fit", (c_void_p, MatrixView), c_int),
    ("n4m_transform_log_transform_is_fitted", (c_void_p, POINTER(c_int)), c_int),
    (
        "n4m_transform_log_transform_transform",
        (c_void_p, MatrixView, MatrixView),
        c_int,
    ),
    (
        "n4m_transform_modpoly_create",
        (POINTER(c_void_p), c_int32, c_int32, c_double),
        c_int,
    ),
    ("n4m_transform_modpoly_destroy", (c_void_p,), None),
    ("n4m_transform_modpoly_transform", (c_void_p, MatrixView, MatrixView), c_int),
    ("n4m_transform_msc_create", (POINTER(c_void_p),), c_int),
    ("n4m_transform_msc_destroy", (c_void_p,), None),
    ("n4m_transform_msc_fit", (c_void_p, MatrixView), c_int),
    ("n4m_transform_msc_inverse_transform", (c_void_p, MatrixView, MatrixView), c_int),
    ("n4m_transform_msc_is_fitted", (c_void_p, POINTER(c_int)), c_int),
    ("n4m_transform_msc_transform", (c_void_p, MatrixView, MatrixView), c_int),
    ("n4m_transform_normalize_create", (POINTER(c_void_p), c_double, c_double), c_int),
    ("n4m_transform_normalize_destroy", (c_void_p,), None),
    ("n4m_transform_normalize_transform", (c_void_p, MatrixView, MatrixView), c_int),
    (
        "n4m_transform_norris_williams_create",
        (POINTER(c_void_p), c_int32, c_int32, c_int32, c_double),
        c_int,
    ),
    ("n4m_transform_norris_williams_destroy", (c_void_p,), None),
    (
        "n4m_transform_norris_williams_transform",
        (c_void_p, MatrixView, MatrixView),
        c_int,
    ),
    ("n4m_transform_osc_create", (POINTER(c_void_p), c_int32, c_int), c_int),
    ("n4m_transform_osc_destroy", (c_void_p,), None),
    (
        "n4m_transform_osc_fit",
        (c_void_p, MatrixView, POINTER(c_double), c_int64),
        c_int,
    ),
    ("n4m_transform_osc_inverse_transform", (c_void_p, MatrixView, MatrixView), c_int),
    ("n4m_transform_osc_is_fitted", (c_void_p, POINTER(c_int)), c_int),
    ("n4m_transform_osc_transform", (c_void_p, MatrixView, MatrixView), c_int),
    ("n4m_transform_percent_to_fraction_create", (POINTER(c_void_p),), c_int),
    ("n4m_transform_percent_to_fraction_destroy", (c_void_p,), None),
    (
        "n4m_transform_percent_to_fraction_transform",
        (c_void_p, MatrixView, MatrixView),
        c_int,
    ),
    (
        "n4m_transform_piecewise_msc_create",
        (POINTER(c_void_p), POINTER(c_double), c_int64, c_int32, c_double),
        c_int,
    ),
    ("n4m_transform_piecewise_msc_destroy", (c_void_p,), None),
    ("n4m_transform_piecewise_msc_fit", (c_void_p, MatrixView), c_int),
    ("n4m_transform_piecewise_msc_is_fitted", (c_void_p, POINTER(c_int)), c_int),
    (
        "n4m_transform_piecewise_msc_transform",
        (c_void_p, MatrixView, MatrixView),
        c_int,
    ),
    (
        "n4m_transform_piecewise_snv_create",
        (POINTER(c_void_p), c_int32, c_int32, c_double),
        c_int,
    ),
    ("n4m_transform_piecewise_snv_destroy", (c_void_p,), None),
    ("n4m_transform_piecewise_snv_fit", (c_void_p, MatrixView), c_int),
    ("n4m_transform_piecewise_snv_is_fitted", (c_void_p, POINTER(c_int)), c_int),
    (
        "n4m_transform_piecewise_snv_transform",
        (c_void_p, MatrixView, MatrixView),
        c_int,
    ),
    (
        "n4m_transform_range_discretizer_create",
        (POINTER(c_void_p), POINTER(c_double), c_int64),
        c_int,
    ),
    ("n4m_transform_range_discretizer_destroy", (c_void_p,), None),
    (
        "n4m_transform_range_discretizer_transform",
        (c_void_p, MatrixView, MatrixView),
        c_int,
    ),
    ("n4m_transform_resample_transformer_create", (POINTER(c_void_p), c_int64), c_int),
    ("n4m_transform_resample_transformer_destroy", (c_void_p,), None),
    ("n4m_transform_resample_transformer_output_cols", (c_void_p, c_int64), c_int64),
    (
        "n4m_transform_resample_transformer_transform",
        (c_void_p, MatrixView, MatrixView),
        c_int,
    ),
    (
        "n4m_transform_resampler_create",
        (
            POINTER(c_void_p),
            POINTER(c_double),
            c_int64,
            c_int32,
            c_double,
            c_double,
            c_int,
            c_double,
            c_int,
            c_int,
        ),
        c_int,
    ),
    ("n4m_transform_resampler_destroy", (c_void_p,), None),
    ("n4m_transform_resampler_fit", (c_void_p, POINTER(c_double), c_int64), c_int),
    ("n4m_transform_resampler_is_fitted", (c_void_p, POINTER(c_int)), c_int),
    ("n4m_transform_resampler_output_cols", (c_void_p,), c_int64),
    ("n4m_transform_resampler_transform", (c_void_p, MatrixView, MatrixView), c_int),
    (
        "n4m_transform_robust_snv_create",
        (POINTER(c_void_p), c_int, c_int, c_double),
        c_int,
    ),
    ("n4m_transform_robust_snv_destroy", (c_void_p,), None),
    ("n4m_transform_robust_snv_transform", (c_void_p, MatrixView, MatrixView), c_int),
    ("n4m_transform_rolling_ball_create", (POINTER(c_void_p), c_int32, c_int32), c_int),
    ("n4m_transform_rolling_ball_destroy", (c_void_p,), None),
    ("n4m_transform_rolling_ball_transform", (c_void_p, MatrixView, MatrixView), c_int),
    (
        "n4m_transform_saps_create",
        (POINTER(c_void_p), c_int32, c_double, c_int, c_double),
        c_int,
    ),
    ("n4m_transform_saps_destroy", (c_void_p,), None),
    ("n4m_transform_saps_fit", (c_void_p, MatrixView, MatrixView), c_int),
    ("n4m_transform_saps_is_fitted", (c_void_p, POINTER(c_int)), c_int),
    ("n4m_transform_saps_transform", (c_void_p, MatrixView, MatrixView), c_int),
    (
        "n4m_transform_savitzky_golay_create",
        (POINTER(c_void_p), c_int32, c_int32, c_int32, c_double, c_int, c_double),
        c_int,
    ),
    ("n4m_transform_savitzky_golay_destroy", (c_void_p,), None),
    (
        "n4m_transform_savitzky_golay_transform",
        (c_void_p, MatrixView, MatrixView),
        c_int,
    ),
    (
        "n4m_transform_second_derivative_create",
        (POINTER(c_void_p), c_double, c_int32),
        c_int,
    ),
    ("n4m_transform_second_derivative_destroy", (c_void_p,), None),
    (
        "n4m_transform_second_derivative_transform",
        (c_void_p, MatrixView, MatrixView),
        c_int,
    ),
    (
        "n4m_transform_signal_type_detector",
        (
            MatrixView,
            POINTER(c_double),
            c_int64,
            c_double,
            POINTER(c_int32),
            POINTER(c_double),
            c_char_p,
        ),
        c_int,
    ),
    ("n4m_transform_simple_scale_create", (POINTER(c_void_p),), c_int),
    ("n4m_transform_simple_scale_destroy", (c_void_p,), None),
    ("n4m_transform_simple_scale_transform", (c_void_p, MatrixView, MatrixView), c_int),
    ("n4m_transform_snip_create", (POINTER(c_void_p), c_int32), c_int),
    ("n4m_transform_snip_destroy", (c_void_p,), None),
    ("n4m_transform_snip_transform", (c_void_p, MatrixView, MatrixView), c_int),
    ("n4m_transform_snv_create", (POINTER(c_void_p), c_int, c_int, c_int), c_int),
    ("n4m_transform_snv_destroy", (c_void_p,), None),
    ("n4m_transform_snv_transform", (c_void_p, MatrixView, MatrixView), c_int),
    (
        "n4m_transform_to_absorbance_create",
        (POINTER(c_void_p), c_int, c_double, c_int),
        c_int,
    ),
    ("n4m_transform_to_absorbance_destroy", (c_void_p,), None),
    (
        "n4m_transform_to_absorbance_transform",
        (c_void_p, MatrixView, MatrixView),
        c_int,
    ),
    ("n4m_transform_vsn_create", (POINTER(c_void_p), c_double), c_int),
    ("n4m_transform_vsn_destroy", (c_void_p,), None),
    ("n4m_transform_vsn_fit", (c_void_p, MatrixView), c_int),
    ("n4m_transform_vsn_is_fitted", (c_void_p, POINTER(c_int)), c_int),
    ("n4m_transform_vsn_transform", (c_void_p, MatrixView, MatrixView), c_int),
    ("n4m_transform_wavelet_create", (POINTER(c_void_p), c_int, c_int), c_int),
    (
        "n4m_transform_wavelet_denoise_create",
        (POINTER(c_void_p), c_int, c_int, c_int32, c_int, c_int),
        c_int,
    ),
    ("n4m_transform_wavelet_denoise_destroy", (c_void_p,), None),
    (
        "n4m_transform_wavelet_denoise_transform",
        (c_void_p, MatrixView, MatrixView),
        c_int,
    ),
    ("n4m_transform_wavelet_destroy", (c_void_p,), None),
    (
        "n4m_transform_wavelet_features_create",
        (POINTER(c_void_p), c_int, c_int, c_int32),
        c_int,
    ),
    (
        "n4m_transform_wavelet_features_create_ex",
        (POINTER(c_void_p), c_int, c_int, c_int32, c_int),
        c_int,
    ),
    ("n4m_transform_wavelet_features_destroy", (c_void_p,), None),
    (
        "n4m_transform_wavelet_features_output_cols",
        (c_void_p, c_int64, POINTER(c_int64)),
        c_int,
    ),
    (
        "n4m_transform_wavelet_features_transform",
        (c_void_p, MatrixView, MatrixView),
        c_int,
    ),
    ("n4m_transform_wavelet_output_cols", (c_void_p, c_int64, POINTER(c_int64)), c_int),
    (
        "n4m_transform_wavelet_pca_create",
        (POINTER(c_void_p), c_int, c_int, c_int32, c_double),
        c_int,
    ),
    ("n4m_transform_wavelet_pca_destroy", (c_void_p,), None),
    ("n4m_transform_wavelet_pca_fit", (c_void_p, MatrixView), c_int),
    ("n4m_transform_wavelet_pca_is_fitted", (c_void_p, POINTER(c_int)), c_int),
    ("n4m_transform_wavelet_pca_output_cols", (c_void_p, POINTER(c_int64)), c_int),
    ("n4m_transform_wavelet_pca_transform", (c_void_p, MatrixView, MatrixView), c_int),
    (
        "n4m_transform_wavelet_svd_create",
        (POINTER(c_void_p), c_int, c_int, c_int32, c_double),
        c_int,
    ),
    ("n4m_transform_wavelet_svd_destroy", (c_void_p,), None),
    ("n4m_transform_wavelet_svd_fit", (c_void_p, MatrixView), c_int),
    ("n4m_transform_wavelet_svd_is_fitted", (c_void_p, POINTER(c_int)), c_int),
    ("n4m_transform_wavelet_svd_output_cols", (c_void_p, POINTER(c_int64)), c_int),
    ("n4m_transform_wavelet_svd_transform", (c_void_p, MatrixView, MatrixView), c_int),
    ("n4m_transform_wavelet_transform", (c_void_p, MatrixView, MatrixView), c_int),
    (
        "n4m_transform_weighted_snv_create",
        (POINTER(c_void_p), POINTER(c_double), c_int64, c_int32, c_double),
        c_int,
    ),
    ("n4m_transform_weighted_snv_destroy", (c_void_p,), None),
    ("n4m_transform_weighted_snv_fit", (c_void_p, MatrixView), c_int),
    ("n4m_transform_weighted_snv_is_fitted", (c_void_p, POINTER(c_int)), c_int),
    ("n4m_transform_weighted_snv_transform", (c_void_p, MatrixView, MatrixView), c_int),
    (
        "n4m_transform_xcorr_align_create",
        (POINTER(c_void_p), POINTER(c_double), c_int64, c_int32, c_int32),
        c_int,
    ),
    ("n4m_transform_xcorr_align_destroy", (c_void_p,), None),
    ("n4m_transform_xcorr_align_fit", (c_void_p, MatrixView), c_int),
    ("n4m_transform_xcorr_align_is_fitted", (c_void_p, POINTER(c_int)), c_int),
    ("n4m_transform_xcorr_align_transform", (c_void_p, MatrixView, MatrixView), c_int),
    (
        "n4m_validation_plan_add_fold",
        (c_void_p, POINTER(c_int64), c_int64, POINTER(c_int64), c_int64),
        c_int,
    ),
    ("n4m_validation_plan_create", (POINTER(c_void_p),), c_int),
    ("n4m_validation_plan_destroy", (c_void_p,), None),
    ("n4m_validation_plan_get_n_folds", (c_void_p, POINTER(c_int32)), c_int),
    ("n4m_validation_plan_get_n_samples", (c_void_p, POINTER(c_int64)), c_int),
    ("n4m_validation_plan_set_n_samples", (c_void_p, c_int64), c_int),
    # -- optimization role (native HPO, ABI 2.2) ---------------------------
    ("n4m_optimizer_options_init", (POINTER(OptimizerOptions),), None),
    ("n4m_search_space_create", (POINTER(c_void_p),), c_int),
    ("n4m_search_space_destroy", (c_void_p,), None),
    (
        "n4m_search_space_add_int",
        (c_void_p, c_char_p, c_int64, c_int64, c_int64, c_int32),
        c_int,
    ),
    (
        "n4m_search_space_add_float",
        (c_void_p, c_char_p, c_double, c_double, c_double, c_int32),
        c_int,
    ),
    (
        "n4m_search_space_add_categorical",
        (c_void_p, c_char_p, c_int, c_void_p, c_int32),
        c_int,
    ),
    (
        "n4m_search_space_add_ordinal",
        (c_void_p, c_char_p, POINTER(c_double), c_int32),
        c_int,
    ),
    (
        "n4m_search_space_add_sorted_tuple",
        (c_void_p, c_char_p, c_int32, c_double, c_double, c_int32),
        c_int,
    ),
    (
        "n4m_search_space_add_constraint",
        (c_void_p, c_int, POINTER(c_char_p), POINTER(c_char_p), c_int32),
        c_int,
    ),
    ("n4m_search_space_num_params", (c_void_p, POINTER(c_int32)), c_int),
    (
        "n4m_optimizer_create",
        (c_void_p, c_void_p, POINTER(OptimizerOptions), POINTER(c_void_p)),
        c_int,
    ),
    ("n4m_optimizer_destroy", (c_void_p,), None),
    (
        "n4m_optimizer_enqueue",
        (c_void_p, POINTER(c_char_p), POINTER(c_double), c_int32),
        c_int,
    ),
    ("n4m_optimizer_ask", (c_void_p, POINTER(c_void_p)), c_int),
    (
        "n4m_optimizer_ask_batch",
        (c_void_p, c_int32, POINTER(c_void_p), POINTER(c_int32)),
        c_int,
    ),
    ("n4m_optimizer_tell", (c_void_p, c_int64, c_double), c_int),
    (
        "n4m_optimizer_tell_result",
        (c_void_p, c_int64, c_int, c_double, c_char_p),
        c_int,
    ),
    (
        "n4m_optimizer_tell_intermediate",
        (c_void_p, c_int64, c_int32, c_double, POINTER(c_int32)),
        c_int,
    ),
    ("n4m_optimizer_best", (c_void_p, POINTER(c_void_p), POINTER(c_double)), c_int),
    ("n4m_optimizer_get_trials", (c_void_p, c_int64, POINTER(c_void_p)), c_int),
    ("n4m_optimizer_save", (c_void_p, POINTER(c_void_p)), c_int),
    (
        "n4m_optimizer_load",
        (c_void_p, POINTER(c_uint8), c_uint64, POINTER(c_void_p)),
        c_int,
    ),
    ("n4m_trial_get_id", (c_void_p, POINTER(c_int64)), c_int),
    ("n4m_trial_get_int", (c_void_p, c_char_p, POINTER(c_int64)), c_int),
    ("n4m_trial_get_float", (c_void_p, c_char_p, POINTER(c_double)), c_int),
    (
        "n4m_trial_get_category",
        (c_void_p, c_char_p, POINTER(c_int32), POINTER(c_char_p)),
        c_int,
    ),
    ("n4m_trial_is_active", (c_void_p, c_char_p, POINTER(c_int32)), c_int),
    ("n4m_trial_get_rung", (c_void_p, POINTER(c_int32)), c_int),
    ("n4m_trial_get_status", (c_void_p, POINTER(c_int)), c_int),
    ("n4m_trial_get_duration", (c_void_p, POINTER(c_double)), c_int),
    (
        "n4m_finetune_estimator",
        (
            c_void_p,
            c_int,
            POINTER(MatrixView),
            POINTER(MatrixView),
            c_void_p,
            c_void_p,
            POINTER(OptimizerOptions),
            c_int32,
            POINTER(c_void_p),
        ),
        c_int,
    ),
)


def apply_argtypes(lib):
    """Bind argtypes/restype for every exported function on ``lib``."""
    for name, argtypes, restype in SYMBOLS:
        fn = getattr(lib, name, None)
        if fn is None:
            continue
        fn.argtypes = list(argtypes)
        fn.restype = restype
