# SPDX-License-Identifier: CECILL-2.1
# Generated by scripts/generate_python_roles.py. Do not edit.
"""Generic native estimator roles.

Each class wraps one catalog method through the shared ``n4m_estimator_*``
life cycle: fit, out-of-sample transform/predict, and a portable fitted state
(:meth:`NativeEstimator.to_n4me` / :meth:`NativeEstimator.from_n4me`) that the
R and JS/WASM bindings read unchanged.
"""

from ._base import NativeEstimator, method_info
from ._generated import (
    CPPLS,
    DIPLS,
    ECR,
    MBPLS,
    MIRPLS,
    NPLS,
    PCR,
    BaggingPLS,
    BoostingPLS,
    ContinuumRegression,
    FusedSparsePLS,
    GroupSparsePLS,
    PLSRegression,
    RandomSubspacePLS,
    Ridge,
    RidgePLS,
    RobustPLS,
    SimplePLS,
    SparseSIMPLS,
)

__all__ = [
    "CPPLS",
    "DIPLS",
    "ECR",
    "MBPLS",
    "MIRPLS",
    "NPLS",
    "PCR",
    "BaggingPLS",
    "BoostingPLS",
    "ContinuumRegression",
    "FusedSparsePLS",
    "GroupSparsePLS",
    "NativeEstimator",
    "PLSRegression",
    "RandomSubspacePLS",
    "Ridge",
    "RidgePLS",
    "RobustPLS",
    "SimplePLS",
    "SparseSIMPLS",
    "method_info",
]
