# SPDX-License-Identifier: CECILL-2.1
# Generated by scripts/generate_python_roles.py from `n4m_cli --manifest-json`.
# Do not edit: parameters, defaults and roles come from the native manifest.
# Native ABI 2.13.0.
"""Generated scikit-learn classes for the n4m generic estimator roles."""

from __future__ import annotations

from typing import ClassVar

from sklearn.base import RegressorMixin, TransformerMixin

from ._base import NativeEstimator


class BaggingPLS(RegressorMixin, NativeEstimator):
    """Native ``models.ensembles.bagging_pls`` (regressor)."""

    _method_id = "models.ensembles.bagging_pls"
    _param_types: ClassVar[dict[str, str]] = {
        "n_components": "int",
        "n_estimators": "int",
    }

    def __init__(
        self,
        *,
        n_components=2,
        n_estimators=50,
    ) -> None:
        self.n_components = n_components
        self.n_estimators = n_estimators


class BoostingPLS(RegressorMixin, NativeEstimator):
    """Native ``models.ensembles.boosting_pls`` (regressor)."""

    _method_id = "models.ensembles.boosting_pls"
    _param_types: ClassVar[dict[str, str]] = {
        "n_components": "int",
        "n_estimators": "int",
        "learning_rate": "double",
    }

    def __init__(
        self,
        *,
        n_components=2,
        n_estimators=50,
        learning_rate=0.1,
    ) -> None:
        self.n_components = n_components
        self.n_estimators = n_estimators
        self.learning_rate = learning_rate


class RandomSubspacePLS(RegressorMixin, NativeEstimator):
    """Native ``models.ensembles.random_subspace_pls`` (regressor)."""

    _method_id = "models.ensembles.random_subspace_pls"
    _param_types: ClassVar[dict[str, str]] = {
        "n_components": "int",
        "n_estimators": "int",
        "features_per_subspace": "int",
    }

    def __init__(
        self,
        *,
        n_components=2,
        n_estimators=50,
        features_per_subspace=10,
    ) -> None:
        self.n_components = n_components
        self.n_estimators = n_estimators
        self.features_per_subspace = features_per_subspace


class MBPLS(RegressorMixin, NativeEstimator):
    """Native ``models.multiblock.mb_pls`` (regressor).

    Required fit inputs: blocks.
    """

    _method_id = "models.multiblock.mb_pls"
    _param_types: ClassVar[dict[str, str]] = {
        "n_components": "int",
    }

    def __init__(
        self,
        *,
        n_components=2,
    ) -> None:
        self.n_components = n_components


class MIRPLS(RegressorMixin, NativeEstimator):
    """Native ``models.multiblock.mir_pls`` (regressor)."""

    _method_id = "models.multiblock.mir_pls"
    _param_types: ClassVar[dict[str, str]] = {
        "n_components": "int",
    }

    def __init__(
        self,
        *,
        n_components=2,
    ) -> None:
        self.n_components = n_components


class CPPLS(RegressorMixin, NativeEstimator):
    """Native ``models.pls.cppls`` (regressor)."""

    _method_id = "models.pls.cppls"
    _param_types: ClassVar[dict[str, str]] = {
        "n_components": "int",
        "gamma": "double",
    }

    def __init__(
        self,
        *,
        n_components=2,
        gamma=0.5,
    ) -> None:
        self.n_components = n_components
        self.gamma = gamma


class PCR(RegressorMixin, TransformerMixin, NativeEstimator):
    """Native ``models.pls.pcr`` (transformer, regressor)."""

    _method_id = "models.pls.pcr"
    _param_types: ClassVar[dict[str, str]] = {
        "n_components": "int",
        "center_x": "bool",
        "scale_x": "bool",
        "center_y": "bool",
        "scale_y": "bool",
    }

    def __init__(
        self,
        *,
        n_components=2,
        center_x=True,
        scale_x=True,
        center_y=True,
        scale_y=False,
    ) -> None:
        self.n_components = n_components
        self.center_x = center_x
        self.scale_x = scale_x
        self.center_y = center_y
        self.scale_y = scale_y


class SimplePLS(RegressorMixin, TransformerMixin, NativeEstimator):
    """Native ``models.pls.pls_fit_simple`` (transformer, regressor)."""

    _method_id = "models.pls.pls_fit_simple"
    _param_types: ClassVar[dict[str, str]] = {
        "n_components": "int",
    }

    def __init__(
        self,
        *,
        n_components=2,
    ) -> None:
        self.n_components = n_components


class PLSRegression(RegressorMixin, TransformerMixin, NativeEstimator):
    """Native ``models.pls.pls_regression`` (transformer, regressor)."""

    _method_id = "models.pls.pls_regression"
    _param_types: ClassVar[dict[str, str]] = {
        "n_components": "int",
        "solver": "enum",
        "center_x": "bool",
        "scale_x": "bool",
        "center_y": "bool",
        "scale_y": "bool",
    }
    _enum_choices: ClassVar[dict[str, tuple[str, ...]]] = {
        "solver": (
            "nipals",
            "simpls",
            "orthogonal_scores",
            "kernel_algorithm",
            "wide_kernel",
            "svd",
            "power",
            "randomized_svd",
        ),
    }

    def __init__(
        self,
        *,
        n_components=2,
        solver="nipals",
        center_x=True,
        scale_x=True,
        center_y=True,
        scale_y=True,
    ) -> None:
        self.n_components = n_components
        self.solver = solver
        self.center_x = center_x
        self.scale_x = scale_x
        self.center_y = center_y
        self.scale_y = scale_y


class ContinuumRegression(RegressorMixin, NativeEstimator):
    """Native ``models.regularized.continuum_regression`` (regressor)."""

    _method_id = "models.regularized.continuum_regression"
    _param_types: ClassVar[dict[str, str]] = {
        "n_components": "int",
        "tau": "double",
    }

    def __init__(
        self,
        *,
        n_components=2,
        tau=0.5,
    ) -> None:
        self.n_components = n_components
        self.tau = tau


class Ridge(RegressorMixin, NativeEstimator):
    """Native ``models.regularized.ridge`` (regressor)."""

    _method_id = "models.regularized.ridge"
    _param_types: ClassVar[dict[str, str]] = {
        "alpha": "double",
        "center_x": "bool",
        "scale_x": "bool",
        "center_y": "bool",
    }

    def __init__(
        self,
        *,
        alpha=1,
        center_x=True,
        scale_x=True,
        center_y=True,
    ) -> None:
        self.alpha = alpha
        self.center_x = center_x
        self.scale_x = scale_x
        self.center_y = center_y


class RidgePLS(RegressorMixin, NativeEstimator):
    """Native ``models.regularized.ridge_pls`` (regressor)."""

    _method_id = "models.regularized.ridge_pls"
    _param_types: ClassVar[dict[str, str]] = {
        "n_components": "int",
        "ridge_lambda": "double",
        "center_x": "bool",
        "scale_x": "bool",
        "center_y": "bool",
        "scale_y": "bool",
    }

    def __init__(
        self,
        *,
        n_components=2,
        ridge_lambda=0.1,
        center_x=True,
        scale_x=True,
        center_y=True,
        scale_y=True,
    ) -> None:
        self.n_components = n_components
        self.ridge_lambda = ridge_lambda
        self.center_x = center_x
        self.scale_x = scale_x
        self.center_y = center_y
        self.scale_y = scale_y


class RobustPLS(RegressorMixin, NativeEstimator):
    """Native ``models.regularized.robust_pls`` (regressor)."""

    _method_id = "models.regularized.robust_pls"
    _param_types: ClassVar[dict[str, str]] = {
        "n_components": "int",
        "huber_k": "double",
        "max_irls_iter": "int",
        "center_x": "bool",
        "scale_x": "bool",
        "center_y": "bool",
        "scale_y": "bool",
    }

    def __init__(
        self,
        *,
        n_components=2,
        huber_k=1.345,
        max_irls_iter=5,
        center_x=True,
        scale_x=True,
        center_y=True,
        scale_y=True,
    ) -> None:
        self.n_components = n_components
        self.huber_k = huber_k
        self.max_irls_iter = max_irls_iter
        self.center_x = center_x
        self.scale_x = scale_x
        self.center_y = center_y
        self.scale_y = scale_y


class FusedSparsePLS(RegressorMixin, NativeEstimator):
    """Native ``models.sparse.fused_sparse_pls`` (regressor)."""

    _method_id = "models.sparse.fused_sparse_pls"
    _param_types: ClassVar[dict[str, str]] = {
        "n_components": "int",
        "l1_lambda": "double",
        "fusion_lambda": "double",
    }

    def __init__(
        self,
        *,
        n_components=2,
        l1_lambda=0.05,
        fusion_lambda=0.05,
    ) -> None:
        self.n_components = n_components
        self.l1_lambda = l1_lambda
        self.fusion_lambda = fusion_lambda


class GroupSparsePLS(RegressorMixin, NativeEstimator):
    """Native ``models.sparse.group_sparse_pls`` (regressor).

    Required fit inputs: feature_groups.
    """

    _method_id = "models.sparse.group_sparse_pls"
    _param_types: ClassVar[dict[str, str]] = {
        "n_components": "int",
        "group_lambda": "double",
    }

    def __init__(
        self,
        *,
        n_components=2,
        group_lambda=0.05,
    ) -> None:
        self.n_components = n_components
        self.group_lambda = group_lambda


class SparseSIMPLS(RegressorMixin, NativeEstimator):
    """Native ``models.sparse.sparse_simpls`` (regressor)."""

    _method_id = "models.sparse.sparse_simpls"
    _param_types: ClassVar[dict[str, str]] = {
        "n_components": "int",
        "sparsity_lambda": "double",
    }

    def __init__(
        self,
        *,
        n_components=2,
        sparsity_lambda=0.05,
    ) -> None:
        self.n_components = n_components
        self.sparsity_lambda = sparsity_lambda


class ECR(RegressorMixin, NativeEstimator):
    """Native ``models.specialized.ecr`` (regressor)."""

    _method_id = "models.specialized.ecr"
    _param_types: ClassVar[dict[str, str]] = {
        "n_components": "int",
        "alpha": "double",
    }

    def __init__(
        self,
        *,
        n_components=2,
        alpha=0.5,
    ) -> None:
        self.n_components = n_components
        self.alpha = alpha


class NPLS(RegressorMixin, NativeEstimator):
    """Native ``models.specialized.tensor_pls`` (regressor)."""

    _method_id = "models.specialized.tensor_pls"
    _param_types: ClassVar[dict[str, str]] = {
        "n_components": "int",
        "mode_j": "int",
        "mode_k": "int",
    }

    def __init__(
        self,
        *,
        n_components=2,
        mode_j=None,
        mode_k=None,
    ) -> None:
        self.n_components = n_components
        self.mode_j = mode_j
        self.mode_k = mode_k


class DIPLS(RegressorMixin, NativeEstimator):
    """Native ``models.transfer.di_pls`` (regressor).

    Required fit inputs: target_domain.
    """

    _method_id = "models.transfer.di_pls"
    _param_types: ClassVar[dict[str, str]] = {
        "n_components": "int",
        "di_lambda": "double",
    }

    def __init__(
        self,
        *,
        n_components=2,
        di_lambda=1,
    ) -> None:
        self.n_components = n_components
        self.di_lambda = di_lambda


__all__ = [
    "CPPLS",
    "DIPLS",
    "ECR",
    "MBPLS",
    "MIRPLS",
    "NPLS",
    "PCR",
    "BaggingPLS",
    "BoostingPLS",
    "ContinuumRegression",
    "FusedSparsePLS",
    "GroupSparsePLS",
    "PLSRegression",
    "RandomSubspacePLS",
    "Ridge",
    "RidgePLS",
    "RobustPLS",
    "SimplePLS",
    "SparseSIMPLS",
]
