# SPDX-License-Identifier: CECILL-2.1
# Generated by scripts/generate_r_roles.py from `n4m_cli --manifest-json`. Do not edit.
# Native ABI 2.13.0.

.n4m_method_roles <- list(
  "filters.correlation" = c("selector"),
  "filters.high_leverage" = c("sample_filter"),
  "filters.spectral_quality" = c("sample_filter"),
  "filters.variance" = c("selector"),
  "filters.x_outlier" = c("sample_filter"),
  "filters.y_outlier" = c("sample_filter"),
  "models.classification.pls_lda" = c("classifier"),
  "models.classification.pls_logistic" = c("classifier"),
  "models.classification.pls_qda" = c("classifier"),
  "models.ensembles.bagging_pls" = c("regressor"),
  "models.ensembles.boosting_pls" = c("regressor"),
  "models.ensembles.random_subspace_pls" = c("regressor"),
  "models.multiblock.mb_pls" = c("regressor"),
  "models.multiblock.mir_pls" = c("regressor"),
  "models.multiblock.o2pls" = c("regressor"),
  "models.pls.cppls" = c("regressor"),
  "models.pls.pcr" = c("transformer", "regressor"),
  "models.pls.pls_fit_simple" = c("transformer", "regressor"),
  "models.pls.pls_regression" = c("transformer", "regressor"),
  "models.regularized.continuum_regression" = c("regressor"),
  "models.regularized.ridge" = c("regressor"),
  "models.regularized.ridge_pls" = c("regressor"),
  "models.regularized.robust_pls" = c("regressor"),
  "models.regularized.weighted_pls" = c("regressor"),
  "models.sparse.fused_sparse_pls" = c("regressor"),
  "models.sparse.group_sparse_pls" = c("regressor"),
  "models.sparse.sparse_pls_da" = c("classifier"),
  "models.sparse.sparse_simpls" = c("regressor"),
  "models.specialized.ecr" = c("regressor"),
  "models.specialized.tensor_pls" = c("regressor"),
  "models.transfer.di_pls" = c("regressor"),
  "preprocessing.alignment.cow_align" = c("transformer"),
  "preprocessing.alignment.dtw_align" = c("transformer"),
  "preprocessing.alignment.icoshift_align" = c("transformer"),
  "preprocessing.alignment.xcorr_align" = c("transformer"),
  "preprocessing.baselines.airpls" = c("transformer"),
  "preprocessing.baselines.arpls" = c("transformer"),
  "preprocessing.baselines.asls" = c("transformer"),
  "preprocessing.baselines.beads" = c("transformer"),
  "preprocessing.baselines.detrend" = c("transformer"),
  "preprocessing.baselines.iasls" = c("transformer"),
  "preprocessing.baselines.imodpoly" = c("transformer"),
  "preprocessing.baselines.modpoly" = c("transformer"),
  "preprocessing.baselines.rolling_ball" = c("transformer"),
  "preprocessing.baselines.saps" = c("transformer"),
  "preprocessing.baselines.snip" = c("transformer"),
  "preprocessing.derivatives.derivate" = c("transformer"),
  "preprocessing.derivatives.first_derivative" = c("transformer"),
  "preprocessing.derivatives.norris_williams" = c("transformer"),
  "preprocessing.derivatives.savitzky_golay" = c("transformer"),
  "preprocessing.derivatives.second_derivative" = c("transformer"),
  "preprocessing.feature_selection.flexible_pca" = c("transformer"),
  "preprocessing.feature_selection.flexible_svd" = c("transformer"),
  "preprocessing.orthogonalization.osc" = c("transformer"),
  "preprocessing.resampling.crop" = c("transformer"),
  "preprocessing.resampling.kbins_discretizer" = c("transformer"),
  "preprocessing.resampling.range_discretizer" = c("transformer"),
  "preprocessing.resampling.resample_transformer" = c("transformer"),
  "preprocessing.resampling.resampler" = c("transformer"),
  "preprocessing.scaling.baseline" = c("transformer"),
  "preprocessing.scaling.log_transform" = c("transformer"),
  "preprocessing.scaling.normalize" = c("transformer"),
  "preprocessing.scaling.simple_scale" = c("transformer"),
  "preprocessing.scatter.area_normalization" = c("transformer"),
  "preprocessing.scatter.emsc" = c("transformer"),
  "preprocessing.scatter.local_centering" = c("transformer"),
  "preprocessing.scatter.local_snv" = c("transformer"),
  "preprocessing.scatter.localized_msc" = c("transformer"),
  "preprocessing.scatter.msc" = c("transformer"),
  "preprocessing.scatter.piecewise_msc" = c("transformer"),
  "preprocessing.scatter.piecewise_snv" = c("transformer"),
  "preprocessing.scatter.robust_snv" = c("transformer"),
  "preprocessing.scatter.snv" = c("transformer"),
  "preprocessing.scatter.vsn" = c("transformer"),
  "preprocessing.scatter.weighted_snv" = c("transformer"),
  "preprocessing.signal_conversion.fraction_to_percent" = c("transformer"),
  "preprocessing.signal_conversion.from_absorbance" = c("transformer"),
  "preprocessing.signal_conversion.kubelka_munk" = c("transformer"),
  "preprocessing.signal_conversion.percent_to_fraction" = c("transformer"),
  "preprocessing.signal_conversion.to_absorbance" = c("transformer"),
  "preprocessing.smoothing.gaussian" = c("transformer"),
  "preprocessing.specialized.fck_static" = c("transformer"),
  "preprocessing.transfer.direct_standardization" = c("transformer"),
  "preprocessing.transfer.piecewise_direct_standardization" = c("transformer"),
  "preprocessing.transfer.robust_direct_standardization" = c("transformer"),
  "preprocessing.wavelets.haar" = c("transformer"),
  "preprocessing.wavelets.wavelet" = c("transformer"),
  "preprocessing.wavelets.wavelet_denoise" = c("transformer"),
  "preprocessing.wavelets.wavelet_features" = c("transformer"),
  "preprocessing.wavelets.wavelet_pca" = c("transformer"),
  "preprocessing.wavelets.wavelet_svd" = c("transformer"),
  "selection.bipls" = c("selector"),
  "selection.bve" = c("selector"),
  "selection.cars" = c("selector"),
  "selection.emcuve" = c("selector"),
  "selection.ga" = c("selector"),
  "selection.ipw" = c("selector"),
  "selection.irf" = c("selector"),
  "selection.iriv" = c("selector"),
  "selection.pso" = c("selector"),
  "selection.random_frog" = c("selector"),
  "selection.randomization" = c("selector"),
  "selection.rep" = c("selector"),
  "selection.scars" = c("selector"),
  "selection.shaving" = c("selector"),
  "selection.sipls" = c("selector"),
  "selection.spa" = c("selector"),
  "selection.st" = c("selector"),
  "selection.stability" = c("selector"),
  "selection.t2" = c("selector"),
  "selection.uve" = c("selector"),
  "selection.variable_select" = c("selector"),
  "selection.vip_spa" = c("selector"),
  "selection.vissa" = c("selector"),
  "selection.wvc" = c("selector"),
  "selection.wvc_threshold" = c("selector")
)

.n4m_method_constructors <- c(
  "filters.correlation" = "n4m_correlation",
  "filters.high_leverage" = "n4m_high_leverage",
  "filters.spectral_quality" = "n4m_spectral_quality",
  "filters.variance" = "n4m_variance",
  "filters.x_outlier" = "n4m_x_outlier",
  "filters.y_outlier" = "n4m_y_outlier",
  "models.classification.pls_lda" = "n4m_pls_lda",
  "models.classification.pls_logistic" = "n4m_pls_logistic",
  "models.classification.pls_qda" = "n4m_pls_qda",
  "models.ensembles.bagging_pls" = "n4m_bagging_pls",
  "models.ensembles.boosting_pls" = "n4m_boosting_pls",
  "models.ensembles.random_subspace_pls" = "n4m_random_subspace_pls",
  "models.multiblock.mb_pls" = "n4m_mb_pls",
  "models.multiblock.mir_pls" = "n4m_mir_pls",
  "models.multiblock.o2pls" = "n4m_o2pls",
  "models.pls.cppls" = "n4m_cppls",
  "models.pls.pcr" = "n4m_pcr",
  "models.pls.pls_fit_simple" = "n4m_pls_fit_simple",
  "models.pls.pls_regression" = "n4m_pls_regression",
  "models.regularized.continuum_regression" = "n4m_continuum_regression",
  "models.regularized.ridge" = "n4m_ridge",
  "models.regularized.ridge_pls" = "n4m_ridge_pls",
  "models.regularized.robust_pls" = "n4m_robust_pls",
  "models.regularized.weighted_pls" = "n4m_weighted_pls",
  "models.sparse.fused_sparse_pls" = "n4m_fused_sparse_pls",
  "models.sparse.group_sparse_pls" = "n4m_group_sparse_pls",
  "models.sparse.sparse_pls_da" = "n4m_sparse_pls_da",
  "models.sparse.sparse_simpls" = "n4m_sparse_simpls",
  "models.specialized.ecr" = "n4m_ecr",
  "models.specialized.tensor_pls" = "n4m_tensor_pls",
  "models.transfer.di_pls" = "n4m_di_pls",
  "preprocessing.alignment.cow_align" = "n4m_cow_align",
  "preprocessing.alignment.dtw_align" = "n4m_dtw_align",
  "preprocessing.alignment.icoshift_align" = "n4m_icoshift_align",
  "preprocessing.alignment.xcorr_align" = "n4m_xcorr_align",
  "preprocessing.baselines.airpls" = "n4m_airpls",
  "preprocessing.baselines.arpls" = "n4m_arpls",
  "preprocessing.baselines.asls" = "n4m_asls",
  "preprocessing.baselines.beads" = "n4m_beads",
  "preprocessing.baselines.detrend" = "n4m_detrend",
  "preprocessing.baselines.iasls" = "n4m_iasls",
  "preprocessing.baselines.imodpoly" = "n4m_imodpoly",
  "preprocessing.baselines.modpoly" = "n4m_modpoly",
  "preprocessing.baselines.rolling_ball" = "n4m_rolling_ball",
  "preprocessing.baselines.saps" = "n4m_saps",
  "preprocessing.baselines.snip" = "n4m_snip",
  "preprocessing.derivatives.derivate" = "n4m_derivate",
  "preprocessing.derivatives.first_derivative" = "n4m_first_derivative",
  "preprocessing.derivatives.norris_williams" = "n4m_norris_williams",
  "preprocessing.derivatives.savitzky_golay" = "n4m_savitzky_golay",
  "preprocessing.derivatives.second_derivative" = "n4m_second_derivative",
  "preprocessing.feature_selection.flexible_pca" = "n4m_flexible_pca",
  "preprocessing.feature_selection.flexible_svd" = "n4m_flexible_svd",
  "preprocessing.orthogonalization.osc" = "n4m_osc",
  "preprocessing.resampling.crop" = "n4m_crop",
  "preprocessing.resampling.kbins_discretizer" = "n4m_kbins_discretizer",
  "preprocessing.resampling.range_discretizer" = "n4m_range_discretizer",
  "preprocessing.resampling.resample_transformer" = "n4m_resample_transformer",
  "preprocessing.resampling.resampler" = "n4m_resampler",
  "preprocessing.scaling.baseline" = "n4m_baseline",
  "preprocessing.scaling.log_transform" = "n4m_log_transform",
  "preprocessing.scaling.normalize" = "n4m_normalize",
  "preprocessing.scaling.simple_scale" = "n4m_simple_scale",
  "preprocessing.scatter.area_normalization" = "n4m_area_normalization",
  "preprocessing.scatter.emsc" = "n4m_emsc",
  "preprocessing.scatter.local_centering" = "n4m_local_centering",
  "preprocessing.scatter.local_snv" = "n4m_local_snv",
  "preprocessing.scatter.localized_msc" = "n4m_localized_msc",
  "preprocessing.scatter.msc" = "n4m_msc",
  "preprocessing.scatter.piecewise_msc" = "n4m_piecewise_msc",
  "preprocessing.scatter.piecewise_snv" = "n4m_piecewise_snv",
  "preprocessing.scatter.robust_snv" = "n4m_robust_snv",
  "preprocessing.scatter.snv" = "n4m_snv",
  "preprocessing.scatter.vsn" = "n4m_vsn",
  "preprocessing.scatter.weighted_snv" = "n4m_weighted_snv",
  "preprocessing.signal_conversion.fraction_to_percent" = "n4m_fraction_to_percent",
  "preprocessing.signal_conversion.from_absorbance" = "n4m_from_absorbance",
  "preprocessing.signal_conversion.kubelka_munk" = "n4m_kubelka_munk",
  "preprocessing.signal_conversion.percent_to_fraction" = "n4m_percent_to_fraction",
  "preprocessing.signal_conversion.to_absorbance" = "n4m_to_absorbance",
  "preprocessing.smoothing.gaussian" = "n4m_gaussian",
  "preprocessing.specialized.fck_static" = "n4m_fck_static",
  "preprocessing.transfer.direct_standardization" = "n4m_direct_standardization",
  "preprocessing.transfer.piecewise_direct_standardization" = "n4m_piecewise_direct_standardization",
  "preprocessing.transfer.robust_direct_standardization" = "n4m_robust_direct_standardization",
  "preprocessing.wavelets.haar" = "n4m_haar",
  "preprocessing.wavelets.wavelet" = "n4m_wavelet",
  "preprocessing.wavelets.wavelet_denoise" = "n4m_wavelet_denoise",
  "preprocessing.wavelets.wavelet_features" = "n4m_wavelet_features",
  "preprocessing.wavelets.wavelet_pca" = "n4m_wavelet_pca",
  "preprocessing.wavelets.wavelet_svd" = "n4m_wavelet_svd",
  "selection.bipls" = "n4m_bipls",
  "selection.bve" = "n4m_bve",
  "selection.cars" = "n4m_cars",
  "selection.emcuve" = "n4m_emcuve",
  "selection.ga" = "n4m_ga",
  "selection.ipw" = "n4m_ipw",
  "selection.irf" = "n4m_irf",
  "selection.iriv" = "n4m_iriv",
  "selection.pso" = "n4m_pso",
  "selection.random_frog" = "n4m_random_frog",
  "selection.randomization" = "n4m_randomization",
  "selection.rep" = "n4m_rep",
  "selection.scars" = "n4m_scars",
  "selection.shaving" = "n4m_shaving",
  "selection.sipls" = "n4m_sipls",
  "selection.spa" = "n4m_spa",
  "selection.st" = "n4m_st",
  "selection.stability" = "n4m_stability",
  "selection.t2" = "n4m_t2",
  "selection.uve" = "n4m_uve",
  "selection.variable_select" = "n4m_variable_select",
  "selection.vip_spa" = "n4m_vip_spa",
  "selection.vissa" = "n4m_vissa",
  "selection.wvc" = "n4m_wvc",
  "selection.wvc_threshold" = "n4m_wvc_threshold"
)

#' @rdname n4m_estimator_role_constructors
#' @export
n4m_correlation <- function(threshold = 0.0, top_k = -1L) {
  .n4m_estimator("filters.correlation", c("selector"), list(threshold = threshold, top_k = top_k))
}

#' @rdname n4m_estimator_role_constructors
#' @export
n4m_high_leverage <- function(method = "hat", threshold_multiplier = 2.0, absolute_threshold = NULL, n_components = 0L, center = TRUE) {
  .n4m_estimator("filters.high_leverage", c("sample_filter"), list(method = method, threshold_multiplier = threshold_multiplier, absolute_threshold = absolute_threshold, n_components = n_components, center = center))
}

#' @rdname n4m_estimator_role_constructors
#' @export
n4m_spectral_quality <- function(max_nan_ratio = 0.1, max_zero_ratio = 0.5, min_variance = 1e-08, max_value = NULL, min_value = NULL, check_inf = TRUE) {
  .n4m_estimator("filters.spectral_quality", c("sample_filter"), list(max_nan_ratio = max_nan_ratio, max_zero_ratio = max_zero_ratio, min_variance = min_variance, max_value = max_value, min_value = min_value, check_inf = check_inf))
}

#' @rdname n4m_estimator_role_constructors
#' @export
n4m_variance <- function(threshold = 0.0, top_k = -1L) {
  .n4m_estimator("filters.variance", c("selector"), list(threshold = threshold, top_k = top_k))
}

#' @rdname n4m_estimator_role_constructors
#' @export
n4m_x_outlier <- function(method = "mahalanobis", threshold = NULL, n_components = 0L, contamination = 0.1, seed = 0L, n_estimators = 100L, max_samples = 256L) {
  .n4m_estimator("filters.x_outlier", c("sample_filter"), list(method = method, threshold = threshold, n_components = n_components, contamination = contamination, seed = seed, n_estimators = n_estimators, max_samples = max_samples))
}

#' @rdname n4m_estimator_role_constructors
#' @export
n4m_y_outlier <- function(method = "iqr", threshold = 1.5, lower_percentile = 1.0, upper_percentile = 99.0) {
  .n4m_estimator("filters.y_outlier", c("sample_filter"), list(method = method, threshold = threshold, lower_percentile = lower_percentile, upper_percentile = upper_percentile))
}

#' @rdname n4m_estimator_role_constructors
#' @export
n4m_pls_lda <- function(n_components = 2L) {
  .n4m_estimator("models.classification.pls_lda", c("classifier"), list(n_components = n_components))
}

#' @rdname n4m_estimator_role_constructors
#' @export
n4m_pls_logistic <- function(n_components = 2L, max_iter = 500L) {
  .n4m_estimator("models.classification.pls_logistic", c("classifier"), list(n_components = n_components, max_iter = max_iter))
}

#' @rdname n4m_estimator_role_constructors
#' @export
n4m_pls_qda <- function(n_components = 2L) {
  .n4m_estimator("models.classification.pls_qda", c("classifier"), list(n_components = n_components))
}

#' @rdname n4m_estimator_role_constructors
#' @export
n4m_bagging_pls <- function(n_components = 2L, n_estimators = 50L, seed = 0L) {
  .n4m_estimator("models.ensembles.bagging_pls", c("regressor"), list(n_components = n_components, n_estimators = n_estimators, seed = seed))
}

#' @rdname n4m_estimator_role_constructors
#' @export
n4m_boosting_pls <- function(n_components = 2L, n_estimators = 50L, learning_rate = 0.1) {
  .n4m_estimator("models.ensembles.boosting_pls", c("regressor"), list(n_components = n_components, n_estimators = n_estimators, learning_rate = learning_rate))
}

#' @rdname n4m_estimator_role_constructors
#' @export
n4m_random_subspace_pls <- function(n_components = 2L, n_estimators = 50L, features_per_subspace = 10L, seed = 0L) {
  .n4m_estimator("models.ensembles.random_subspace_pls", c("regressor"), list(n_components = n_components, n_estimators = n_estimators, features_per_subspace = features_per_subspace, seed = seed))
}

#' @rdname n4m_estimator_role_constructors
#' @export
n4m_mb_pls <- function(n_components = 2L) {
  .n4m_estimator("models.multiblock.mb_pls", c("regressor"), list(n_components = n_components))
}

#' @rdname n4m_estimator_role_constructors
#' @export
n4m_mir_pls <- function(n_components = 2L) {
  .n4m_estimator("models.multiblock.mir_pls", c("regressor"), list(n_components = n_components))
}

#' @rdname n4m_estimator_role_constructors
#' @export
n4m_o2pls <- function(n_predictive = 2L, n_x_orthogonal = 1L, n_y_orthogonal = 1L) {
  .n4m_estimator("models.multiblock.o2pls", c("regressor"), list(n_predictive = n_predictive, n_x_orthogonal = n_x_orthogonal, n_y_orthogonal = n_y_orthogonal))
}

#' @rdname n4m_estimator_role_constructors
#' @export
n4m_cppls <- function(n_components = 2L, gamma = 0.5) {
  .n4m_estimator("models.pls.cppls", c("regressor"), list(n_components = n_components, gamma = gamma))
}

#' @rdname n4m_estimator_role_constructors
#' @export
n4m_pcr <- function(n_components = 2L, center_x = TRUE, scale_x = TRUE, center_y = TRUE, scale_y = FALSE) {
  .n4m_estimator("models.pls.pcr", c("transformer", "regressor"), list(n_components = n_components, center_x = center_x, scale_x = scale_x, center_y = center_y, scale_y = scale_y))
}

#' @rdname n4m_estimator_role_constructors
#' @export
n4m_pls_fit_simple <- function(n_components = 2L) {
  .n4m_estimator("models.pls.pls_fit_simple", c("transformer", "regressor"), list(n_components = n_components))
}

#' @rdname n4m_estimator_role_constructors
#' @export
n4m_pls_regression <- function(n_components = 2L, solver = "nipals", center_x = TRUE, scale_x = TRUE, center_y = TRUE, scale_y = TRUE) {
  .n4m_estimator("models.pls.pls_regression", c("transformer", "regressor"), list(n_components = n_components, solver = solver, center_x = center_x, scale_x = scale_x, center_y = center_y, scale_y = scale_y))
}

#' @rdname n4m_estimator_role_constructors
#' @export
n4m_continuum_regression <- function(n_components = 2L, tau = 0.5) {
  .n4m_estimator("models.regularized.continuum_regression", c("regressor"), list(n_components = n_components, tau = tau))
}

#' @rdname n4m_estimator_role_constructors
#' @export
n4m_ridge <- function(alpha = 1.0, center_x = TRUE, scale_x = TRUE, center_y = TRUE) {
  .n4m_estimator("models.regularized.ridge", c("regressor"), list(alpha = alpha, center_x = center_x, scale_x = scale_x, center_y = center_y))
}

#' @rdname n4m_estimator_role_constructors
#' @export
n4m_ridge_pls <- function(n_components = 2L, ridge_lambda = 0.1, center_x = TRUE, scale_x = TRUE, center_y = TRUE, scale_y = TRUE) {
  .n4m_estimator("models.regularized.ridge_pls", c("regressor"), list(n_components = n_components, ridge_lambda = ridge_lambda, center_x = center_x, scale_x = scale_x, center_y = center_y, scale_y = scale_y))
}

#' @rdname n4m_estimator_role_constructors
#' @export
n4m_robust_pls <- function(n_components = 2L, huber_k = 1.345, max_irls_iter = 5L, center_x = TRUE, scale_x = TRUE, center_y = TRUE, scale_y = TRUE) {
  .n4m_estimator("models.regularized.robust_pls", c("regressor"), list(n_components = n_components, huber_k = huber_k, max_irls_iter = max_irls_iter, center_x = center_x, scale_x = scale_x, center_y = center_y, scale_y = scale_y))
}

#' @rdname n4m_estimator_role_constructors
#' @export
n4m_weighted_pls <- function(n_components = 2L, center_x = TRUE, scale_x = TRUE, center_y = TRUE, scale_y = TRUE) {
  .n4m_estimator("models.regularized.weighted_pls", c("regressor"), list(n_components = n_components, center_x = center_x, scale_x = scale_x, center_y = center_y, scale_y = scale_y))
}

#' @rdname n4m_estimator_role_constructors
#' @export
n4m_fused_sparse_pls <- function(n_components = 2L, l1_lambda = 0.05, fusion_lambda = 0.05) {
  .n4m_estimator("models.sparse.fused_sparse_pls", c("regressor"), list(n_components = n_components, l1_lambda = l1_lambda, fusion_lambda = fusion_lambda))
}

#' @rdname n4m_estimator_role_constructors
#' @export
n4m_group_sparse_pls <- function(n_components = 2L, group_lambda = 0.05) {
  .n4m_estimator("models.sparse.group_sparse_pls", c("regressor"), list(n_components = n_components, group_lambda = group_lambda))
}

#' @rdname n4m_estimator_role_constructors
#' @export
n4m_sparse_pls_da <- function(n_components = 2L, sparsity_lambda = 0.05) {
  .n4m_estimator("models.sparse.sparse_pls_da", c("classifier"), list(n_components = n_components, sparsity_lambda = sparsity_lambda))
}

#' @rdname n4m_estimator_role_constructors
#' @export
n4m_sparse_simpls <- function(n_components = 2L, sparsity_lambda = 0.05) {
  .n4m_estimator("models.sparse.sparse_simpls", c("regressor"), list(n_components = n_components, sparsity_lambda = sparsity_lambda))
}

#' @rdname n4m_estimator_role_constructors
#' @export
n4m_ecr <- function(n_components = 2L, alpha = 0.5) {
  .n4m_estimator("models.specialized.ecr", c("regressor"), list(n_components = n_components, alpha = alpha))
}

#' @rdname n4m_estimator_role_constructors
#' @export
n4m_tensor_pls <- function(n_components = 2L, mode_j = NULL, mode_k = NULL) {
  .n4m_estimator("models.specialized.tensor_pls", c("regressor"), list(n_components = n_components, mode_j = mode_j, mode_k = mode_k))
}

#' @rdname n4m_estimator_role_constructors
#' @export
n4m_di_pls <- function(n_components = 2L, di_lambda = 1.0) {
  .n4m_estimator("models.transfer.di_pls", c("regressor"), list(n_components = n_components, di_lambda = di_lambda))
}

#' @rdname n4m_estimator_role_constructors
#' @export
n4m_cow_align <- function(reference = c(), interval_size = 32L, max_shift = 5L) {
  .n4m_estimator("preprocessing.alignment.cow_align", c("transformer"), list(reference = reference, interval_size = interval_size, max_shift = max_shift))
}

#' @rdname n4m_estimator_role_constructors
#' @export
n4m_dtw_align <- function(reference = c()) {
  .n4m_estimator("preprocessing.alignment.dtw_align", c("transformer"), list(reference = reference))
}

#' @rdname n4m_estimator_role_constructors
#' @export
n4m_icoshift_align <- function(reference = c(), interval_size = 32L, max_shift = 5L) {
  .n4m_estimator("preprocessing.alignment.icoshift_align", c("transformer"), list(reference = reference, interval_size = interval_size, max_shift = max_shift))
}

#' @rdname n4m_estimator_role_constructors
#' @export
n4m_xcorr_align <- function(reference = c(), max_shift = 5L) {
  .n4m_estimator("preprocessing.alignment.xcorr_align", c("transformer"), list(reference = reference, max_shift = max_shift))
}

#' @rdname n4m_estimator_role_constructors
#' @export
n4m_airpls <- function(lam = 1000000.0, max_iter = 50L, tol = 0.001) {
  .n4m_estimator("preprocessing.baselines.airpls", c("transformer"), list(lam = lam, max_iter = max_iter, tol = tol))
}

#' @rdname n4m_estimator_role_constructors
#' @export
n4m_arpls <- function(lam = 100000.0, max_iter = 50L, tol = 0.001) {
  .n4m_estimator("preprocessing.baselines.arpls", c("transformer"), list(lam = lam, max_iter = max_iter, tol = tol))
}

#' @rdname n4m_estimator_role_constructors
#' @export
n4m_asls <- function(lam = 1000000.0, p = 0.01, max_iter = 50L, tol = 0.001) {
  .n4m_estimator("preprocessing.baselines.asls", c("transformer"), list(lam = lam, p = p, max_iter = max_iter, tol = tol))
}

#' @rdname n4m_estimator_role_constructors
#' @export
n4m_beads <- function(lam_0 = 100.0, lam_1 = 0.5, lam_2 = 0.5, max_iter = 50L, tol = 0.001) {
  .n4m_estimator("preprocessing.baselines.beads", c("transformer"), list(lam_0 = lam_0, lam_1 = lam_1, lam_2 = lam_2, max_iter = max_iter, tol = tol))
}

#' @rdname n4m_estimator_role_constructors
#' @export
n4m_detrend <- function(polyorder = 1L) {
  .n4m_estimator("preprocessing.baselines.detrend", c("transformer"), list(polyorder = polyorder))
}

#' @rdname n4m_estimator_role_constructors
#' @export
n4m_iasls <- function(lam = 1000000.0, p = 0.01, lam_1 = 0.0001, polyorder = 2L, diff_order = 2L, max_iter = 50L, tol = 0.001) {
  .n4m_estimator("preprocessing.baselines.iasls", c("transformer"), list(lam = lam, p = p, lam_1 = lam_1, polyorder = polyorder, diff_order = diff_order, max_iter = max_iter, tol = tol))
}

#' @rdname n4m_estimator_role_constructors
#' @export
n4m_imodpoly <- function(polyorder = 2L, max_iter = 250L, tol = 0.001) {
  .n4m_estimator("preprocessing.baselines.imodpoly", c("transformer"), list(polyorder = polyorder, max_iter = max_iter, tol = tol))
}

#' @rdname n4m_estimator_role_constructors
#' @export
n4m_modpoly <- function(polyorder = 2L, max_iter = 250L, tol = 0.001) {
  .n4m_estimator("preprocessing.baselines.modpoly", c("transformer"), list(polyorder = polyorder, max_iter = max_iter, tol = tol))
}

#' @rdname n4m_estimator_role_constructors
#' @export
n4m_rolling_ball <- function(half_window = 20L, smooth_half_window = 0L) {
  .n4m_estimator("preprocessing.baselines.rolling_ball", c("transformer"), list(half_window = half_window, smooth_half_window = smooth_half_window))
}

#' @rdname n4m_estimator_role_constructors
#' @export
n4m_saps <- function(n_components = 5L, score_weight = 1.0, fit_intercept = TRUE, ridge = 0.0) {
  .n4m_estimator("preprocessing.baselines.saps", c("transformer"), list(n_components = n_components, score_weight = score_weight, fit_intercept = fit_intercept, ridge = ridge))
}

#' @rdname n4m_estimator_role_constructors
#' @export
n4m_snip <- function(max_half_window = 20L) {
  .n4m_estimator("preprocessing.baselines.snip", c("transformer"), list(max_half_window = max_half_window))
}

#' @rdname n4m_estimator_role_constructors
#' @export
n4m_derivate <- function(order = 1L, delta = 1.0) {
  .n4m_estimator("preprocessing.derivatives.derivate", c("transformer"), list(order = order, delta = delta))
}

#' @rdname n4m_estimator_role_constructors
#' @export
n4m_first_derivative <- function(delta = 1.0, edge_order = 2L) {
  .n4m_estimator("preprocessing.derivatives.first_derivative", c("transformer"), list(delta = delta, edge_order = edge_order))
}

#' @rdname n4m_estimator_role_constructors
#' @export
n4m_norris_williams <- function(segment = 5L, gap = 5L, derivative_order = 1L, delta = 1.0) {
  .n4m_estimator("preprocessing.derivatives.norris_williams", c("transformer"), list(segment = segment, gap = gap, derivative_order = derivative_order, delta = delta))
}

#' @rdname n4m_estimator_role_constructors
#' @export
n4m_savitzky_golay <- function(window_length = 5L, polyorder = 2L, deriv = 0L, delta = 1.0, mode = "mirror", cval = 0.0) {
  .n4m_estimator("preprocessing.derivatives.savitzky_golay", c("transformer"), list(window_length = window_length, polyorder = polyorder, deriv = deriv, delta = delta, mode = mode, cval = cval))
}

#' @rdname n4m_estimator_role_constructors
#' @export
n4m_second_derivative <- function(delta = 1.0, edge_order = 2L) {
  .n4m_estimator("preprocessing.derivatives.second_derivative", c("transformer"), list(delta = delta, edge_order = edge_order))
}

#' @rdname n4m_estimator_role_constructors
#' @export
n4m_flexible_pca <- function(n_components = 5.0) {
  .n4m_estimator("preprocessing.feature_selection.flexible_pca", c("transformer"), list(n_components = n_components))
}

#' @rdname n4m_estimator_role_constructors
#' @export
n4m_flexible_svd <- function(n_components = 5.0) {
  .n4m_estimator("preprocessing.feature_selection.flexible_svd", c("transformer"), list(n_components = n_components))
}

#' @rdname n4m_estimator_role_constructors
#' @export
n4m_osc <- function(n_components = 1L, scale = TRUE) {
  .n4m_estimator("preprocessing.orthogonalization.osc", c("transformer"), list(n_components = n_components, scale = scale))
}

#' @rdname n4m_estimator_role_constructors
#' @export
n4m_crop <- function(start = NULL, end = NULL) {
  .n4m_estimator("preprocessing.resampling.crop", c("transformer"), list(start = start, end = end))
}

#' @rdname n4m_estimator_role_constructors
#' @export
n4m_kbins_discretizer <- function(n_bins = 5L, strategy = "uniform") {
  .n4m_estimator("preprocessing.resampling.kbins_discretizer", c("transformer"), list(n_bins = n_bins, strategy = strategy))
}

#' @rdname n4m_estimator_role_constructors
#' @export
n4m_range_discretizer <- function(edges = NULL) {
  .n4m_estimator("preprocessing.resampling.range_discretizer", c("transformer"), list(edges = edges))
}

#' @rdname n4m_estimator_role_constructors
#' @export
n4m_resample_transformer <- function(num_samples = NULL) {
  .n4m_estimator("preprocessing.resampling.resample_transformer", c("transformer"), list(num_samples = num_samples))
}

#' @rdname n4m_estimator_role_constructors
#' @export
n4m_resampler <- function(target_wavelengths = c(), method = "linear", crop_min = 0.0, crop_max = 0.0, use_crop = FALSE, fill_value = 0.0, bounds_error = FALSE, extrapolate = FALSE, tgt_min = 0.0, tgt_step = 1.0, tgt_n = 0L) {
  .n4m_estimator("preprocessing.resampling.resampler", c("transformer"), list(target_wavelengths = target_wavelengths, method = method, crop_min = crop_min, crop_max = crop_max, use_crop = use_crop, fill_value = fill_value, bounds_error = bounds_error, extrapolate = extrapolate, tgt_min = tgt_min, tgt_step = tgt_step, tgt_n = tgt_n))
}

#' @rdname n4m_estimator_role_constructors
#' @export
n4m_baseline <- function() {
  .n4m_estimator("preprocessing.scaling.baseline", c("transformer"), list())
}

#' @rdname n4m_estimator_role_constructors
#' @export
n4m_log_transform <- function(base = 0.0, offset = 0.0, auto_offset = TRUE, min_value = 1e-08) {
  .n4m_estimator("preprocessing.scaling.log_transform", c("transformer"), list(base = base, offset = offset, auto_offset = auto_offset, min_value = min_value))
}

#' @rdname n4m_estimator_role_constructors
#' @export
n4m_normalize <- function(feature_min = -1.0, feature_max = 1.0) {
  .n4m_estimator("preprocessing.scaling.normalize", c("transformer"), list(feature_min = feature_min, feature_max = feature_max))
}

#' @rdname n4m_estimator_role_constructors
#' @export
n4m_simple_scale <- function() {
  .n4m_estimator("preprocessing.scaling.simple_scale", c("transformer"), list())
}

#' @rdname n4m_estimator_role_constructors
#' @export
n4m_area_normalization <- function(method = "sum") {
  .n4m_estimator("preprocessing.scatter.area_normalization", c("transformer"), list(method = method))
}

#' @rdname n4m_estimator_role_constructors
#' @export
n4m_emsc <- function(degree = 2L) {
  .n4m_estimator("preprocessing.scatter.emsc", c("transformer"), list(degree = degree))
}

#' @rdname n4m_estimator_role_constructors
#' @export
n4m_local_centering <- function() {
  .n4m_estimator("preprocessing.scatter.local_centering", c("transformer"), list())
}

#' @rdname n4m_estimator_role_constructors
#' @export
n4m_local_snv <- function(window = 11L, pad_mode = "reflect", constant_value = 0.0) {
  .n4m_estimator("preprocessing.scatter.local_snv", c("transformer"), list(window = window, pad_mode = pad_mode, constant_value = constant_value))
}

#' @rdname n4m_estimator_role_constructors
#' @export
n4m_localized_msc <- function(window_size = 32L, reference = c(), eps = 1e-12) {
  .n4m_estimator("preprocessing.scatter.localized_msc", c("transformer"), list(window_size = window_size, reference = reference, eps = eps))
}

#' @rdname n4m_estimator_role_constructors
#' @export
n4m_msc <- function() {
  .n4m_estimator("preprocessing.scatter.msc", c("transformer"), list())
}

#' @rdname n4m_estimator_role_constructors
#' @export
n4m_piecewise_msc <- function(window_size = 32L, reference = c(), eps = 1e-12) {
  .n4m_estimator("preprocessing.scatter.piecewise_msc", c("transformer"), list(window_size = window_size, reference = reference, eps = eps))
}

#' @rdname n4m_estimator_role_constructors
#' @export
n4m_piecewise_snv <- function(window_size = 32L, ddof = 0L, eps = 1e-12) {
  .n4m_estimator("preprocessing.scatter.piecewise_snv", c("transformer"), list(window_size = window_size, ddof = ddof, eps = eps))
}

#' @rdname n4m_estimator_role_constructors
#' @export
n4m_robust_snv <- function(with_center = TRUE, with_scale = TRUE, k = 1.4826) {
  .n4m_estimator("preprocessing.scatter.robust_snv", c("transformer"), list(with_center = with_center, with_scale = with_scale, k = k))
}

#' @rdname n4m_estimator_role_constructors
#' @export
n4m_snv <- function(with_mean = TRUE, with_std = TRUE, ddof = 0L) {
  .n4m_estimator("preprocessing.scatter.snv", c("transformer"), list(with_mean = with_mean, with_std = with_std, ddof = ddof))
}

#' @rdname n4m_estimator_role_constructors
#' @export
n4m_vsn <- function(eps = 1e-12) {
  .n4m_estimator("preprocessing.scatter.vsn", c("transformer"), list(eps = eps))
}

#' @rdname n4m_estimator_role_constructors
#' @export
n4m_weighted_snv <- function(weights = c(), ddof = 0L, eps = 1e-12) {
  .n4m_estimator("preprocessing.scatter.weighted_snv", c("transformer"), list(weights = weights, ddof = ddof, eps = eps))
}

#' @rdname n4m_estimator_role_constructors
#' @export
n4m_fraction_to_percent <- function() {
  .n4m_estimator("preprocessing.signal_conversion.fraction_to_percent", c("transformer"), list())
}

#' @rdname n4m_estimator_role_constructors
#' @export
n4m_from_absorbance <- function(is_percent = FALSE) {
  .n4m_estimator("preprocessing.signal_conversion.from_absorbance", c("transformer"), list(is_percent = is_percent))
}

#' @rdname n4m_estimator_role_constructors
#' @export
n4m_kubelka_munk <- function(is_percent = FALSE, epsilon = 1e-10) {
  .n4m_estimator("preprocessing.signal_conversion.kubelka_munk", c("transformer"), list(is_percent = is_percent, epsilon = epsilon))
}

#' @rdname n4m_estimator_role_constructors
#' @export
n4m_percent_to_fraction <- function() {
  .n4m_estimator("preprocessing.signal_conversion.percent_to_fraction", c("transformer"), list())
}

#' @rdname n4m_estimator_role_constructors
#' @export
n4m_to_absorbance <- function(is_percent = FALSE, epsilon = 1e-10, clip_negative = TRUE) {
  .n4m_estimator("preprocessing.signal_conversion.to_absorbance", c("transformer"), list(is_percent = is_percent, epsilon = epsilon, clip_negative = clip_negative))
}

#' @rdname n4m_estimator_role_constructors
#' @export
n4m_gaussian <- function(sigma = 1.0, order = 0L, mode = "reflect", cval = 0.0, truncate = 4.0) {
  .n4m_estimator("preprocessing.smoothing.gaussian", c("transformer"), list(sigma = sigma, order = order, mode = mode, cval = cval, truncate = truncate))
}

#' @rdname n4m_estimator_role_constructors
#' @export
n4m_fck_static <- function(kernel_size = NULL, alphas = NULL, sigmas = NULL) {
  .n4m_estimator("preprocessing.specialized.fck_static", c("transformer"), list(kernel_size = kernel_size, alphas = alphas, sigmas = sigmas))
}

#' @rdname n4m_estimator_role_constructors
#' @export
n4m_direct_standardization <- function(fit_intercept = TRUE, ridge = 0.0) {
  .n4m_estimator("preprocessing.transfer.direct_standardization", c("transformer"), list(fit_intercept = fit_intercept, ridge = ridge))
}

#' @rdname n4m_estimator_role_constructors
#' @export
n4m_piecewise_direct_standardization <- function(window_size = 5L, fit_intercept = TRUE, ridge = 0.0) {
  .n4m_estimator("preprocessing.transfer.piecewise_direct_standardization", c("transformer"), list(window_size = window_size, fit_intercept = fit_intercept, ridge = ridge))
}

#' @rdname n4m_estimator_role_constructors
#' @export
n4m_robust_direct_standardization <- function(fit_intercept = TRUE, ridge = 0.0, trim_quantile = 0.9, max_iter = 3L) {
  .n4m_estimator("preprocessing.transfer.robust_direct_standardization", c("transformer"), list(fit_intercept = fit_intercept, ridge = ridge, trim_quantile = trim_quantile, max_iter = max_iter))
}

#' @rdname n4m_estimator_role_constructors
#' @export
n4m_haar <- function() {
  .n4m_estimator("preprocessing.wavelets.haar", c("transformer"), list())
}

#' @rdname n4m_estimator_role_constructors
#' @export
n4m_wavelet <- function(family = "haar", mode = "periodization") {
  .n4m_estimator("preprocessing.wavelets.wavelet", c("transformer"), list(family = family, mode = mode))
}

#' @rdname n4m_estimator_role_constructors
#' @export
n4m_wavelet_denoise <- function(family = "db4", mode = "periodization", level = 3L, threshold_mode = "soft", noise_estimator = "median") {
  .n4m_estimator("preprocessing.wavelets.wavelet_denoise", c("transformer"), list(family = family, mode = mode, level = level, threshold_mode = threshold_mode, noise_estimator = noise_estimator))
}

#' @rdname n4m_estimator_role_constructors
#' @export
n4m_wavelet_features <- function(family = "haar", mode = "periodization", max_level = 3L, entropy = "energy") {
  .n4m_estimator("preprocessing.wavelets.wavelet_features", c("transformer"), list(family = family, mode = mode, max_level = max_level, entropy = entropy))
}

#' @rdname n4m_estimator_role_constructors
#' @export
n4m_wavelet_pca <- function(family = "haar", mode = "periodization", max_level = 2L, n_components = 5.0) {
  .n4m_estimator("preprocessing.wavelets.wavelet_pca", c("transformer"), list(family = family, mode = mode, max_level = max_level, n_components = n_components))
}

#' @rdname n4m_estimator_role_constructors
#' @export
n4m_wavelet_svd <- function(family = "haar", mode = "periodization", max_level = 2L, n_components = 5.0) {
  .n4m_estimator("preprocessing.wavelets.wavelet_svd", c("transformer"), list(family = family, mode = mode, max_level = max_level, n_components = n_components))
}

#' @rdname n4m_estimator_role_constructors
#' @export
n4m_bipls <- function(n_components = 2L, interval_width = 10L, min_intervals = 2L, cv = 3L) {
  .n4m_estimator("selection.bipls", c("selector"), list(n_components = n_components, interval_width = interval_width, min_intervals = min_intervals, cv = cv))
}

#' @rdname n4m_estimator_role_constructors
#' @export
n4m_bve <- function(n_components = 2L, n_steps = 10L, min_features = 0L, cv = 3L) {
  .n4m_estimator("selection.bve", c("selector"), list(n_components = n_components, n_steps = n_steps, min_features = min_features, cv = cv))
}

#' @rdname n4m_estimator_role_constructors
#' @export
n4m_cars <- function(n_components = 2L, n_iterations = 50L, min_features = 0L, cv = 3L) {
  .n4m_estimator("selection.cars", c("selector"), list(n_components = n_components, n_iterations = n_iterations, min_features = min_features, cv = cv))
}

#' @rdname n4m_estimator_role_constructors
#' @export
n4m_emcuve <- function(n_components = 2L, noise_features = 50L, noise_seed = 0L, n_ensembles = 10L, vote_threshold = 0.5, cv = 3L) {
  .n4m_estimator("selection.emcuve", c("selector"), list(n_components = n_components, noise_features = noise_features, noise_seed = noise_seed, n_ensembles = n_ensembles, vote_threshold = vote_threshold, cv = cv))
}

#' @rdname n4m_estimator_role_constructors
#' @export
n4m_ga <- function(n_components = 2L, n_generations = 30L, population_size = 40L, min_features = 0L, max_features = 0L, mutation_rate = 0.05, cv = 3L, seed = 0L) {
  .n4m_estimator("selection.ga", c("selector"), list(n_components = n_components, n_generations = n_generations, population_size = population_size, min_features = min_features, max_features = max_features, mutation_rate = mutation_rate, cv = cv, seed = seed))
}

#' @rdname n4m_estimator_role_constructors
#' @export
n4m_ipw <- function(top_k = NULL, n_components = 2L, n_iterations = 20L, damping = 0.5, weight_floor = 1e-06, cv = 3L) {
  .n4m_estimator("selection.ipw", c("selector"), list(top_k = top_k, n_components = n_components, n_iterations = n_iterations, damping = damping, weight_floor = weight_floor, cv = cv))
}

#' @rdname n4m_estimator_role_constructors
#' @export
n4m_irf <- function(top_k = NULL, n_components = 2L, n_iterations = 100L, window_size = 5L, initial_intervals = 5L, cv = 3L, seed = 0L) {
  .n4m_estimator("selection.irf", c("selector"), list(top_k = top_k, n_components = n_components, n_iterations = n_iterations, window_size = window_size, initial_intervals = initial_intervals, cv = cv, seed = seed))
}

#' @rdname n4m_estimator_role_constructors
#' @export
n4m_iriv <- function(n_components = 2L, max_rounds = 5L, cv = 5L, seed = 0L) {
  .n4m_estimator("selection.iriv", c("selector"), list(n_components = n_components, max_rounds = max_rounds, cv = cv, seed = seed))
}

#' @rdname n4m_estimator_role_constructors
#' @export
n4m_pso <- function(n_components = 2L, n_swarm = 30L, n_iterations = 50L, w = 0.729, c1 = 1.494, c2 = 1.494, v_max = 4.0, cv = 3L, seed = 0L) {
  .n4m_estimator("selection.pso", c("selector"), list(n_components = n_components, n_swarm = n_swarm, n_iterations = n_iterations, w = w, c1 = c1, c2 = c2, v_max = v_max, cv = cv, seed = seed))
}

#' @rdname n4m_estimator_role_constructors
#' @export
n4m_random_frog <- function(top_k = NULL, n_components = 2L, n_iterations = 100L, initial_size = 20L, min_size = 0L, max_size = 0L, cv = 3L, seed = 0L) {
  .n4m_estimator("selection.random_frog", c("selector"), list(top_k = top_k, n_components = n_components, n_iterations = n_iterations, initial_size = initial_size, min_size = min_size, max_size = max_size, cv = cv, seed = seed))
}

#' @rdname n4m_estimator_role_constructors
#' @export
n4m_randomization <- function(n_components = 2L, n_permutations = 200L, randomization_seed = 0L, alpha = 0.05) {
  .n4m_estimator("selection.randomization", c("selector"), list(n_components = n_components, n_permutations = n_permutations, randomization_seed = randomization_seed, alpha = alpha))
}

#' @rdname n4m_estimator_role_constructors
#' @export
n4m_rep <- function(n_components = 2L, n_steps = 10L, min_features = 0L, remove_count = 1L, cv = 3L) {
  .n4m_estimator("selection.rep", c("selector"), list(n_components = n_components, n_steps = n_steps, min_features = min_features, remove_count = remove_count, cv = cv))
}

#' @rdname n4m_estimator_role_constructors
#' @export
n4m_scars <- function(n_components = 2L, n_iterations = 50L, min_features = 0L, sample_fraction = 0.8, cv = 3L, seed = 0L) {
  .n4m_estimator("selection.scars", c("selector"), list(n_components = n_components, n_iterations = n_iterations, min_features = min_features, sample_fraction = sample_fraction, cv = cv, seed = seed))
}

#' @rdname n4m_estimator_role_constructors
#' @export
n4m_shaving <- function(n_components = 2L, n_steps = 10L, min_features = 0L, shave_fraction = 0.2, cv = 3L) {
  .n4m_estimator("selection.shaving", c("selector"), list(n_components = n_components, n_steps = n_steps, min_features = min_features, shave_fraction = shave_fraction, cv = cv))
}

#' @rdname n4m_estimator_role_constructors
#' @export
n4m_sipls <- function(n_components = 2L, interval_width = 10L, combination_size = 2L, cv = 3L) {
  .n4m_estimator("selection.sipls", c("selector"), list(n_components = n_components, interval_width = interval_width, combination_size = combination_size, cv = cv))
}

#' @rdname n4m_estimator_role_constructors
#' @export
n4m_spa <- function(top_k = NULL, n_components = 2L) {
  .n4m_estimator("selection.spa", c("selector"), list(top_k = top_k, n_components = n_components))
}

#' @rdname n4m_estimator_role_constructors
#' @export
n4m_st <- function(thresholds = NULL, n_components = 2L, min_selected = 0L, cv = 3L) {
  .n4m_estimator("selection.st", c("selector"), list(thresholds = thresholds, n_components = n_components, min_selected = min_selected, cv = cv))
}

#' @rdname n4m_estimator_role_constructors
#' @export
n4m_stability <- function(top_k = NULL, n_components = 2L, cv = 3L) {
  .n4m_estimator("selection.stability", c("selector"), list(top_k = top_k, n_components = n_components, cv = cv))
}

#' @rdname n4m_estimator_role_constructors
#' @export
n4m_t2 <- function(alpha_thresholds = NULL, n_components = 2L, min_selected = 0L, cv = 3L) {
  .n4m_estimator("selection.t2", c("selector"), list(alpha_thresholds = alpha_thresholds, n_components = n_components, min_selected = min_selected, cv = cv))
}

#' @rdname n4m_estimator_role_constructors
#' @export
n4m_uve <- function(n_components = 2L, noise_features = 50L, noise_seed = 0L, min_features = -1L, cv = 3L) {
  .n4m_estimator("selection.uve", c("selector"), list(n_components = n_components, noise_features = noise_features, noise_seed = noise_seed, min_features = min_features, cv = cv))
}

#' @rdname n4m_estimator_role_constructors
#' @export
n4m_variable_select <- function(top_k = NULL, n_components = 2L, rank_method = "vip") {
  .n4m_estimator("selection.variable_select", c("selector"), list(top_k = top_k, n_components = n_components, rank_method = rank_method))
}

#' @rdname n4m_estimator_role_constructors
#' @export
n4m_vip_spa <- function(top_k = NULL, n_components = 2L, vip_threshold = 0.3) {
  .n4m_estimator("selection.vip_spa", c("selector"), list(top_k = top_k, n_components = n_components, vip_threshold = vip_threshold))
}

#' @rdname n4m_estimator_role_constructors
#' @export
n4m_vissa <- function(n_components = 2L, n_iterations = 10L, n_submodels = 60L, ratio_kept = 0.1, threshold = 0.5, floor_probability = 0.05, cv = 3L, seed = 0L) {
  .n4m_estimator("selection.vissa", c("selector"), list(n_components = n_components, n_iterations = n_iterations, n_submodels = n_submodels, ratio_kept = ratio_kept, threshold = threshold, floor_probability = floor_probability, cv = cv, seed = seed))
}

#' @rdname n4m_estimator_role_constructors
#' @export
n4m_wvc <- function(top_k = NULL, n_components = 2L, normalize = TRUE) {
  .n4m_estimator("selection.wvc", c("selector"), list(top_k = top_k, n_components = n_components, normalize = normalize))
}

#' @rdname n4m_estimator_role_constructors
#' @export
n4m_wvc_threshold <- function(n_components = 2L, normalize = TRUE, score_threshold = 0.0, threshold_factor = 1.0, min_selected = 0L) {
  .n4m_estimator("selection.wvc_threshold", c("selector"), list(n_components = n_components, normalize = normalize, score_threshold = score_threshold, threshold_factor = threshold_factor, min_selected = min_selected))
}
